NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TWEAKS =
TITLE = Straight Talk Carrier String
DESCRIPTION = This patch will change the carrier string of any webOS 2.x to Straight Talk. This patch is based on the HP webOS carrier string by ShiftyAxel and Jason Robitaille.
CATEGORY = Misc
VERSIONS = 2.1.0-258 2.1.1-63 2.1.2-74 2.2.4-66
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = AwesomePalmPre127
HOMEPAGE = http://forums.webosnation.com/webos-patches/316945-patch-straight-talk-carrier-string.html