NAME = $(shell basename $(shell pwd))
PATCH = video-player/${NAME}.patch
TWEAKS =
TITLE = Edit Any Videos Metadata
DESCRIPTION = Will let you edit the metadata (title and description) of any video.
CATEGORY = Video Player
VERSIONS = 1.4.5-29 2.1.0-3 2.2.0-21
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Videoplayer.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/235050-patch-edit-any-videos-metadata.html