NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Fixed Keyboard Brightness 100
DESCRIPTION = Keeps the keyboard brightness at a fixed value of 100.
CATEGORY = Misc
VERSIONS = 1.4.5-134 2.0.0-34 2.0.1-61 2.1.0-15 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = webOSdealer, CRaiaSoftware
HOMEPAGE = http://forums.precentral.net/webos-patches/266115-fixed-keyboard-brightness-patches.html
