#!/bin/sh

APP_ID=org.webosinternals.dbus

APP_DIR=/media/cryptofs/apps/usr/palm/applications/${APP_ID}

[ -d ${APP_DIR} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

cp ${APP_DIR}/upstart/org.webosinternals.dbus /var/palm/event.d

# Check the upstart script is installed
[ -f /var/palm/event.d/org.webosinternals.dbus ] || exit 1

# Start the service
/sbin/start org.webosinternals.dbus

exit 0
