NAME = $(shell basename $(shell pwd))
PATCH = pandora/${NAME}.patch
TITLE = Headset Advance Vibrate
DESCRIPTION = Pandora broke using the headset button in newer versions.  This patch re-adds the missing headset button functionality as well as adds a long vibration (750ms) when advancing the track in Pandora via the double-press headset button.<br/><br/>This may or may not break future versions.
CATEGORY = Pandora
VERSIONS = 1.3.5-20
ICON = http://www.webos-internals.org/images/d/d1/Icon_WebOSInternals_Patches_Pandora.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = jhoff80
HOMEPAGE = http://forums.precentral.net/webos-patches/211631-musicplayer-vibrate-headset-button-track-advance.html