NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Disable LightBar
DESCRIPTION = Turns off the light in the notification area when a card is active. It still blinks on notifications.
CATEGORY = Misc
VERSIONS = 1.4.5-113 2.0.0-16 2.0.1-24
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Franz Rühmland <frause@stealthberry.org>
HOMEPAGE = http://m.forums.precentral.net/showthread.php?p=2791389