NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TWEAKS =
TITLE = Disable LightBar
DESCRIPTION = Turns off the light in the gesture area on the Pre plus, Pre 2, Pre 3 and Veer when a card is active. It still blinks on notifications and lights up on touch.
CATEGORY = Misc
VERSIONS = 1.4.5-169 2.1.0-159 2.1.1-22 2.1.2-31 2.2.4-40
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Herrie <webos-internals.org@herrie.org>
HOMEPAGE = http://m.forums.precentral.net/showthread.php?p=2791389