NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Tweet via Bad Kitty and Add to Relego
DESCRIPTION = This patch adds a 'Tweet Link' option to the Browser Menu under Page it will launch Bad Kitty and compose a tweet containing the page title and URL.<br/><br/>Please note this patch is not currently compatible with the Add to Relego and Add to Spare Time patches. Please uninstall first<br/><br/>Version of the patch that includes the Add To Relego functionality.<br/><br/>Thanks to the authors of the Add to Relego and Add to Spare Time patches for the inspiration for this patch and @germboy the Bad Kitty dev for creating a cross app API to plug into.
CATEGORY = Browser
VERSIONS = 1.4.5-72
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Ben Fysh
HOMEPAGE = http://forums.precentral.net/webos-patches/264317-patch-tweet-link-via-bad-kitty.html