NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Make it so - UK
DESCRIPTION = Changes 'Just type...' to 'Make it so...' for UK  Devices
CATEGORY = Mojo
VERSIONS = 2.2.4-35 3.0.4-60 3.0.5-4
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = DiplPhy <DiplPhy@gmail.com>
HOMEPAGE = http://forums.webosnation.com/hp-touchpad-tips-information-resources/295014-replace-just-type-custom-message-8.html