NAME = $(shell basename $(shell pwd))
PATCH = youtube/${NAME}.patch
TITLE = Video Downloads - No Truncating
DESCRIPTION = Adds a download option for videos in the YouTube app. This version does not truncate the video title to 30 characters, so may cause issues with really really long YouTube video titles.
CATEGORY = YouTube
VERSIONS = 1.3.5-23 1.4.0-12
ICON = http://www.webos-internals.org/images/8/8b/Icon_WebOSInternals_Patches_Youtube.png
SCREENSHOTS =
META_SUB_VERSION = 

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/219045-patch-youtube-download-patch-5.html#post2123881