NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Add ThumbNav Controls
DESCRIPTION = When you swipe your finger in from the right or left side of the screen, a little popup appears that lets you perform functions. It includes buttons for Back, Forward, Refresh, New Card, and Open Bookmarks panel.
CATEGORY = Browser
VERSIONS = 3.0.2-29 3.0.4-2
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Garrett92C <Garrett92C@gmail.com>, Arthur Thornton
HOMEPAGE = http://forum.webosroundup.com/index.php?threads/touchpad-thumbnav-browser-controls.907/
