NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS = browser/${NAME}.json
TITLE = Add ThumbNav Controls
DESCRIPTION = When you swipe your finger in from the left or right of the screen, a menu will popup. This menu contains all your Browser controls such as Back, Forward, Refresh, New Card, Open Bookmarks, Share Options, and Full Screen. With the Tweaks app, you can customize the layout of the menu to better fit your needs.
CATEGORY = Browser
VERSIONS = 3.0.2-29 3.0.4-2 3.0.5-8
ICON = http://www.webos-internals.org/images/3/37/Icon_WebOSInternals_Patches_Plus_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Garrett92C <Garrett92C@gmail.com>
HOMEPAGE = http://forums.webosnation.com/hp-touchpad-homebrew/309039-patch-thumbnav.html