NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TITLE = Advanced Reset Options - DE
DESCRIPTION = On power button hold, it goes straight to the reset options, with airplane mode, java restart, and luna restart added, and skips the swap-battery/shutdown prompt. German language.
CATEGORY = Notifications
VERSIONS = 1.4.5-30 2.0.1-45
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/223829-patch-advanced-reset-options-5.html#post2611264