NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TWEAKS =
TITLE = Advanced Reset Options - DE
DESCRIPTION = On power button hold, the options will be airplaine mode, luna restart, device restart, shut down, and cancel. German language. Based on the original 'Advanced Reset Options' patch by Jason Robitaille.
CATEGORY = Notifications
VERSIONS = 1.4.5-30 2.1.0-4 2.2.0-38 2.2.3-38 3.0.2-3
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = DiplPhy, Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/288393-patch-touchpad-advanced-reset-options.html