NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = GPS in Device Menu
DESCRIPTION = Adds a GPS toggle to the device menu.
CATEGORY = Top Bar
VERSIONS = 2.1.0-3 2.2.0-19 2.2.3-19
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/5/52/Top-bar-gps-in-device-menu.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/212458-patch-request-add-gps-toggle-top-bar.html