NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Facebook Chat Spoof
DESCRIPTION = Add a facebook account as if it where a gmail account, so @chat.facebook.com.<br/><br/>You must have a facebook username.<br/><br/>GTalk should still function as normal.
CATEGORY = Messaging
VERSIONS = 1.3.5-33 1.4.0-52 1.4.1-24 1.4.2-9 1.4.3-3 1.4.5-8
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille, robvanvliet, TheInvsbleMan
HOMEPAGE = http://forums.precentral.net/palm-pre/236332-very-simple-facebook-chat-patch.html#post2305008