NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Relocate Clock - Right
DESCRIPTION = This patch will move the clock to the far right side of the Top Bar.
CATEGORY = Top Bar
VERSIONS = 1.4.5-101 2.1.0-15 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/c/c1/Top-bar-relocate-clock---right-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Garrett92C <Garrett92C@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/268540-patch-move-clock-top-bar.html
