NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Annuaire inverse
DESCRIPTION = Ajoute un lien vers la recherche du numéro sur l'annuaire inversé du 118000 depuis l'historique des appels.Adapation du patch 'WhitePages Call Log Phone Lookup' pour la France.
CATEGORY = Phone
VERSIONS = 2.1.0-273 2.1.1-112 2.1.2-112
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/a/a4/Phone-annuaire-inverse-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = nova-box
HOMEPAGE =