NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = BIG Fonts for Messaging App
DESCRIPTION = <br/><br/>This patch makes the font size in messaging app bigger.
CATEGORY = Messaging
VERSIONS = 3.0.5-1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = 
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = 
