NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Date and AM-PM Indicator
DESCRIPTION = Adds the date (without year) to the left of the time display as well as an AM/PM indicator. If the time is in 24 hours format, there will just be the date without the AM/PM indicator.<br/>Date can be in DD/MM or MM/DD format, based on regional settings (see Screenshot 2).
CATEGORY = Top Bar
VERSIONS = 2.1.0-57 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/9/9e/Top-bar-date-and-am-pm-indicator-1.png\",\
\"http://www.webos-internals.org/images/1/18/Top-bar-date-and-am-pm-indicator-2.png\",\
\"http://www.webos-internals.org/images/5/58/Top-bar-date-and-am-pm-indicator-3.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = JingleX
HOMEPAGE = http://forums.precentral.net/webos-patches/279711-patch-date-am-pm-indicator-top-bar.html
