NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = Date and AM-PM Indicator
DESCRIPTION = Adds the date (without year) to the left of the time display as well as an AM/PM indicator. If the time is in 24 hours format, there will just be the date without the AM/PM indicator.Date can be in DD/MM or MM/DD format, based on regional settings (see Screenshot 2).
CATEGORY = Top Bar
VERSIONS = 2.1.0-232 2.1.1-38 2.1.2-47 2.2.0-111 2.2.3-105 2.2.4-21
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/9/9e/Top-bar-date-and-am-pm-indicator-1.png\",\
\"http://www.webos-internals.org/images/1/18/Top-bar-date-and-am-pm-indicator-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = isagar2004, JingleX
HOMEPAGE = http://forums.webosnation.com/webos-patches/308906-patch-request-date-am-pm-top-bar-pre3.html#post3268401