NAME = call-duration
PATCH = /phone/${NAME}.patch
TITLE = Call Duration in Log
DESCRIPTION = Adds call duration to the Phone call log
CATEGORY = Phone
VERSION = 0.3.0
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
