NAME = call-duration
PATCH = /phone/${NAME}.patch
TITLE = Call Duration in Call Log
DESCRIPTION = This will enable the viewing of call durations in the call log.
CATEGORY = Phone
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/c/cb/Call-duration.png\"]

include ../common.mk
include ../modifications.mk
