NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Battery Icon as Percent
DESCRIPTION = This will replace the battery icon in the top bar with a color-coded percent number. Charging = Teal. 100%-70% = Green. 69%-45% = Yellow. = 44%-20% = Orange. 19%-0% = Red.
CATEGORY = Top Bar
VERSIONS = 1.3.5-3 1.4.0-3
ICON = http://www.webos-internals.org/images/a/a2/Icon_WebOSInternals_Patches_Percent.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/7/76/Battery-percent.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = nesl247, Jason Robitaille
HOMEPAGE = http://forums.precentral.net/web-os-development/194029-battery-place-icon-working-1-1-0-color.html
