NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = Battery Percent as Icon
DESCRIPTION = This will replace the battery icon in the top bar with a color-coded percent number.Charging = Teal.100%-70% = Green.69%-45% = Yellow.44%-20% = Orange.19%-0% = Red.
CATEGORY = Top Bar
VERSIONS = 2.1.0-11 2.1.1-22 2.1.2-31 2.2.4-38
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/0/0f/Top-bar-battery-percent-as-icon-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = nesl247 <0188801@gmail.com>, Jason Robitaille, CRaiaSoftware, pcworld
HOMEPAGE = http://forums.precentral.net/web-os-development/194029-battery-place-icon-working-1-1-0-color.html