NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TWEAKS =
TITLE = Sync Fix for Google Calendar
DESCRIPTION = This patch fix sync issue for Google CalendarIssues fixed: * Upload contacts with non-ASCII characters like ChineseIssues not fixed: * all other issues. please see if calendar-google-sync-behaviors-patch can be applied on your version.
CATEGORY = Calendar
VERSIONS = 2.1.0-202 2.1.1-22 2.1.2-31 2.2.0-74 2.2.3-68 3.0.2-68 3.0.4-31
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = moo <moo.tinys@gmail.com>
HOMEPAGE =
