NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Swipe For Prev and Next Emails
DESCRIPTION = Swipe left and right in the message body to see previous and next emails. Useful for people that find it hard to use the little arrows.
CATEGORY = Email
VERSIONS = 1.4.1-49 1.4.2-35 1.4.3-29 1.4.5-37
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = egaudet
HOMEPAGE =