NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = Long Chinese Messaging Notification Patch
DESCRIPTION = Fixes the long Chinese messaging notification issue which causes a system hang or reboot.
CATEGORY = Messaging
VERSIONS = 1.4.5-186 2.1.0-220 2.1.1-26 2.1.2-34 2.2.0-96 2.2.3-89 2.2.4-2
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = 911boy <support@talign.com>
HOMEPAGE = http://www.talign.com