NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = Long Chinese Messaging Notification Patch
DESCRIPTION = Fix long Chinese messaging notification cause system hand or reboot issue.
CATEGORY = Messaging
VERSIONS = 1.4.5-183 2.1.0-215 2.2.0-89 2.2.3-83
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sz911boy <support@talign.com>
HOMEPAGE = www.talign.com