NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TITLE = Disable LED Notifications for Email
DESCRIPTION = Disables LED notifications for new emails.
CATEGORY = Screen Lock
VERSIONS = 1.3.1-36 1.3.5-20 1.4.0-9
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS =
META_SUB_VERSION = 

include ../common.mk

include ../modifications.mk

MAINTAINER = Franz Rühmland <frause@stealthberry.org>
HOMEPAGE = http://m.forums.precentral.net/showthread.php?p=2205248