NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Swap Reply2All with Move v2
DESCRIPTION = This will replace the 'Reply to All' button with the 'Move to Folder' menu option. The 'Reply to All' is moved to the menu. Add shortcut to ReplyAll, change shortcut for SetFlag to 'f', change shortcut for mark unread to 'u'. Cannot have both Reply2All patches applied at same time
CATEGORY = Email
VERSIONS = 1.3.5-12 1.4.0-3
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = mikePre <rizmail@gmail.com>
HOMEPAGE =
