NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = More Dialing Shortcuts
DESCRIPTION = Add 8 and 10 Digits to Dialing Shortcuts in Phone Preferences.
CATEGORY = Phone
VERSIONS = 2.1.0-237 2.1.1-43 2.1.2-52 2.2.4-43
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Herrie
HOMEPAGE =