#!/bin/sh

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APP_ID=org.webosinternals.pulseaudio-modules

APP_DIR=/media/cryptofs/apps/usr/palm/applications/${APP_ID}

ln -s ${APP_DIR}/librtp.so /usr/lib/pulse-0.9.22
ln -s ${APP_DIR}/libraop.so /usr/lib/pulse-0.9.22
ln -s ${APP_DIR}/libavahi-wrap.so /usr/lib/pulse-0.9.22

ln -s ${APP_DIR}/modules/module-zeroconf-*.so /usr/lib/pulse-0.9.22/modules
ln -s ${APP_DIR}/modules/module-raop-*.so /usr/lib/pulse-0.9.22/modules
ln -s ${APP_DIR}/modules/module-rtp-*.so /usr/lib/pulse-0.9.22/modules
ln -s ${APP_DIR}/modules/module-native-protocol-tcp.so /usr/lib/pulse-0.9.22/modules
ln -s ${APP_DIR}/modules/module-tunnel-sink.so /usr/lib/pulse-0.9.22/modules

ORIG_MD5SUM=$(grep -h /usr/lib/pulse-0.9.22/modules/module-palm-policy.so /usr/lib/ipkg/info/*.md5sums | cut -d ' ' -f 1)

FILE_MD5SUM=$(md5sum /usr/lib/pulse-0.9.22/modules/module-palm-policy.so | cut -d ' ' -f 1)

if [ "${ORIG_MD5SUM}" = "${FILE_MD5SUM}" ]; then
  if [ ! -f ${APP_DIR}/backup/module-palm-policy.so ]; then
    mkdir ${APP_DIR}/backup

    cp -f /usr/lib/pulse-0.9.22/modules/module-palm-policy.so ${APP_DIR}/backup/
  fi
fi

exit 0
