#!/bin/sh

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APP_ID=org.webosinternals.pulseaudio-modules

APP_DIR=/media/cryptofs/apps/usr/palm/applications/${APP_ID}

rm -f /usr/lib/pulse-0.9.22/librtp.so
rm -f /usr/lib/pulse-0.9.22/libraop.so
rm -f /usr/lib/pulse-0.9.22/libavahi-wrap.so

rm -f /usr/lib/pulse-0.9.22/modules/module-raop-*.so
rm -f /usr/lib/pulse-0.9.22/modules/module-zeroconf-*.so
rm -f /usr/lib/pulse-0.9.22/modules/module-rtp-*.so
rm -f /usr/lib/pulse-0.9.22/modules/module-native-protocol-tcp.so
rm -f /usr/lib/pulse-0.9.22/modules/module-tunnel-sink.so

ORIG_MD5SUM=$(md5sum ${APP_DIR}/modules/module-palm-policy.so | cut -d ' ' -f 1)

FILE_MD5SUM=$(md5sum /usr/lib/pulse-0.9.22/modules/module-palm-policy.so | cut -d ' ' -f 1)

if [ "${ORIG_MD5SUM}" = "${FILE_MD5SUM}" ]; then
  if [ -f ${APP_DIR}/backup/module-palm-policy.so ]; then
    cp -f ${APP_DIR}/backup/module-palm-policy.so /usr/lib/pulse-0.9.22/modules/

    rm -rf ${APP_DIR}/backup
  fi
fi

exit 0

