#!/bin/sh

PACKAGE=org.webosinternals.eom-overlord-monitoring

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
    IPKG_OFFLINE_ROOT=/media/cryptofs/apps
    mount -o remount,rw /
fi

# Stop uploading stuff to the mothership
# First off, stop uploadd and rdxd processes.
# Next, kill off contextupload
# Remove execute perms
#
chmod -x /usr/bin/uploadd
stop uploadd

chmod -x /usr/bin/rdxd
stop rdxd

rm /var/log/rdxd/pending/*
rm /var/log/rdxd/uploaded/*

chmod -x /usr/bin/contextupload
killall -9 contextupload

# FIX PRIOR VERSION OF EOM.
sed -i -e 's/^#respawn/respawn/' /etc/event.d/uploadd
sed -i -e 's/^#exec/exec/' /etc/event.d/uploadd

#ipkg -o $IPKG_OFFLINE_ROOT remove $PACKAGE
exit 0
