#!/bin/sh

PACKAGE=org.webosinternals.eom-overlord-monitoring

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
    IPKG_OFFLINE_ROOT=/media/cryptofs/apps
    mount -o remount,rw /
fi

# Set things back to the way they were
#sed -i -e 's/^#respawn/respawn/' /etc/event.d/uploadd
#sed -i -e 's/^#exec/exec/' /etc/event.d/uploadd
#start uploadd

#sed -i -e 's/^#respawn/respawn/' /etc/event.d/rdxd
#sed -i -e 's/^#exec/exec/' /etc/event.d/rdxd
#start rdxd

#if [ -f /usr/bin/contextupload.orig ]
#    mv /usr/bin/contextupload.orig /usr/bin/contextupload
#fi

#ipkg -o $IPKG_OFFLINE_ROOT remove $PACKAGE
exit 0
