NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Private Browsing
DESCRIPTION = Adds an option to the webOS browser that will prevent adding new items to the browser history.  It can be toggled with a menu item.<br/><br/>Now changes the toolbar to red so you can tell when it is on, and it will now stay on when you open a link in a new window.
CATEGORY = Browser
VERSIONS = 1.4.5-136 2.0.0-36 2.0.1-63 2.1.0-17 3.0.0-26 3.0.2-7
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = minego
HOMEPAGE =