NAME = $(shell basename $(shell pwd))
PATCH = /phone/${NAME}.patch
TITLE = Call Duration in Call Log
DESCRIPTION = This will enable the viewing of call durations in the call log.
CATEGORY = Phone
VERSION = 1.2.1-0
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/c/cb/Call-duration.png\"]
META_VERSION = 1.2.1-0

include ../common.mk
include ../modifications.mk
