NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Call Duration in Call Log
DESCRIPTION = This will enable the viewing of call durations in the call log.
CATEGORY = Phone
VERSIONS = 1.3.5-4
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/c/cb/Call-duration.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = dBsooner 
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Phone_Show_Call_Duration_in_the_Call_Log
