NAME = $(shell basename $(shell pwd))
PATCH = advanced/${NAME}.patch
TITLE = Advanced System Menus - Framework (Veer)
DESCRIPTION = Adds support for having two new system menus called status and today menus in addition to already existing application, device and power menus. Status menu is placed into left corner of top bar and the today menu in the center of top bar. Also adds support for menus to have editing option through tap-n-hold.<br/><br/>NOTE: this patch itself does not add those new menus it only layouts the groundwork to allow other patches to create these menus.
CATEGORY = Advanced
VERSIONS = 2.1.0-103
ICON = http://www.webos-internals.org/images/f/f1/Icon_WebOSInternals_Patch_Plus.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = http://forums.precentral.net/enlightened-linux-solutions/269207-patch-advanced-system-menus-2-x.html
