NAME = $(shell basename $(shell pwd))
PATCH = /app-launcher/${NAME}.patch
TITLE = Reset Scroll Position
DESCRIPTION = This will reset the scroll position back to the top of the page rather than remembering the scroll position when switching pages in the App Launcher.
CATEGORY = App Launcher
WEBOS_VERSION = 1.2.1
IPKG_VERSION = 0
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = 
META_SUB_VERSION = 1
include ../common.mk
include ../modifications.mk

MAINTAINER = Bsiegel
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Launcher_Reset_Scroll_on_Page_Change
