NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = No Auto-Answer Upon Touchstone Removal
DESCRIPTION = Prevents the phone from automatically answering an incoming call when removed from the Touchstone.
CATEGORY = Phone
VERSIONS = 1.4.0-45 1.4.1-16 1.4.2-2 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2378748#post2378748
