NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = No Auto-Answer Upon Touchstone Removal
DESCRIPTION = Prevents the phone from automatically answering an incoming call when removed from the Touchstone.
CATEGORY = Phone
VERSIONS = 2.0.0-36 2.0.1-63 2.1.0-17 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid, CRaiaSoftware
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2378748#post2378748
