NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = WiFi Fix for Pre3-224
DESCRIPTION = ONLY FOR Pre 3 2.2.4. Some people are experiencing intermittent WiFi connection problems on Pre 3 2.2.4. This patch rolls back the PmWiFiDhclient.conf file to the 2.2.3 version.
CATEGORY = System
VERSIONS = 2.2.4-24
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GuyFromNam <GuyFromNam@hotmail.com>
HOMEPAGE =