NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TWEAKS =
TITLE = Messaging Notification Private
DESCRIPTION = SMS notification bar replace the contents with 'New Message'
CATEGORY = Notifications
VERSIONS = 1.4.5-179 2.1.0-202 2.2.0-74 2.2.3-68
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = flatland <flatlandcn@gmail.com>
HOMEPAGE =