NAME = $(shell basename $(shell pwd))
PATCH = youtube/${NAME}.patch
TWEAKS =
TITLE = Upload to Youtube as Private
DESCRIPTION = Upload all videos to Youtube as Private.Reboot after applying.
CATEGORY = YouTube
VERSIONS = 3.0.5-3
ICON = http://www.webos-internals.org/images/8/8b/Icon_WebOSInternals_Patches_Youtube.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GuyFromNam <GuyFromNam@hotmail.com>
HOMEPAGE =