NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Raise Image Resolution Limit
DESCRIPTION = This re-enables the ability to view higher resolution images in the web browser.
CATEGORY = Browser
VERSIONS = 1.4.0-29 v1.4.1-1
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = edit_text
HOMEPAGE =
