NAME = $(shell basename $(shell pwd))
PATCH = universal-search/${NAME}.patch
TITLE = Command Line for O2 Palm Pre
DESCRIPTION = Special version of the Universal Search Command Line patch that *should* work on an O2 Palm Pre.<br/>I can't really test this, but you can!<br/><br/>This *may* work on other devices, too, if the original USCL patch doesn't work on your device.  Or not.
CATEGORY = Universal Search
VERSIONS = 1.4.5-70
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = dsevil <dse@webonastick.com>
HOMEPAGE = http://webonastick.com/uscl/
