NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Add Date - MM/DD
DESCRIPTION = Adds the date to the left of the time in the top bar in MM/DD format.
CATEGORY = Top Bar
WEBOS_VERSION = 1.2.1
IPKG_VERSION = 0
SCREENSHOTS = [\"http://www.webos-internals.org/images/2/29/Add_date_to_top_bar_no_year.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = tk102
HOMEPAGE = http://forums.precentral.net/web-os-development/200039-add-date-time-top.html
