NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Mojo Smooth Scrolling
DESCRIPTION = Removes the annoying 'snap' when you begin scrolling in Mojo applications. Original patch by bright2k.
CATEGORY = Mojo
VERSIONS = 2.2.0-68 2.2.3-60
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ShiftyAxel <jpalmerwatkins@me.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/305418-patch-mojo-smooth-scrolling-2-2-x.html