NAME = $(shell basename ${PWD})
PATCH = /nascar/${NAME}.patch
TITLE = Hide Nascar App
DESCRIPTION = This will hide the Nascar application in the App Launcher.
CATEGORY = App Launcher
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/b/b8/Icon_WebOSInternals_Patches_Nascar.png

include ../common.mk
include ../modifications.mk
