NAME = $(shell basename $(shell pwd))
PATCH = music-player/${NAME}.patch
TWEAKS =
TITLE = Handle non-uppercase Ogg Vorbis fields
DESCRIPTION = The music indexer only handles Ogg Vorbis fields with all uppercase names. This patch allows for the field names to be any case.
CATEGORY = Music Player
VERSIONS = 3.0.4-7
ICON = http://www.webos-internals.org/images/d/df/Icon_WebOSInternals_Patches_Musicplayer.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Nicholas Guarracino <nick@guarracino.org>
HOMEPAGE = http://forums.precentral.net/webos-patches/304520-patch-touchpad-handle-non-uppercase-ogg-vorbis-fields.html