NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Launch Mode Switcher on Luna Boot
DESCRIPTION = This will add Mode Switcher to be started when Luna starts. This is needed for Mode Switcher to work.
CATEGORY = Misc
VERSIONS = 1.4.0-55 1.4.1-27 1.4.2-12 1.4.3-6 1.4.5-11
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = http://forums.precentral.net/homebrew-apps/224544-mode-switcher.html