NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Simple Browser Gestures
DESCRIPTION = This patch adds two new 'gestures' to the stock Browser app. Swipe your finger from the left bezel to the screen to go forward. Swipe in from the right bezel to go back.
CATEGORY = Browser
VERSIONS = 3.0.2-29
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Garrett92C <Garrett92C@gmail.com>
HOMEPAGE = http://forum.webosroundup.com/index.php?threads/touchpad-simple-browser-gestures.940/
