NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = AutoSpeakerphone via Proximity Sensor Delayed
DESCRIPTION = Switches between the front and back speaker as the display is turned on & off by the proximity sensor.<br/><br/>A 2 second delay is observed before the audio route is changed from front to back while the change from back to front is immediate.
CATEGORY = Phone
VERSIONS = 1.4.1-15
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/244195-patch-auto-speakerphone-via-proximity-sensor.html#post2415544