NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = Disk Cache Mod
DESCRIPTION = This patch will modify the disk cache of linux to 1MB. This appears to have a positive effect on the lagginess of webOS (ie: there is less lag)
CATEGORY = System
VERSIONS = 1.4.5-194 2.1.0-241 2.1.1-47 2.1.2-56 2.2.0-118 2.2.3-112 2.2.4-37 3.0.2-93 3.0.4-62 3.0.5-4
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mau <robmausser@gmail.com>
HOMEPAGE =