NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = Disk Cache Mod
DESCRIPTION = This patch will modify the disk cache of linux to 1MB. This appears to have a positive effect on the lagginess of webOS (ie: there is less lag)
CATEGORY = System
VERSIONS = 1.4.5-182 2.1.0-210 2.1.1-22 2.1.2-31 2.2.0-83 2.2.3-77 3.0.2-74 3.0.4-37
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mau <robmausser@gmail.com>
HOMEPAGE =
