NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Power Button Ends Calls Except Speaker
DESCRIPTION = Press power button to end phone calls.  This patch is deactivated when the speaker phone is in use.
CATEGORY = Phone
VERSIONS = 1.3.1-36 1.3.5-19 1.4.0-8
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = KeyToss <info@keytoss.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/215031-patch-power-button-end-calls.html