NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Notification Repeat
DESCRIPTION = This patch will repeat the messaging notification every two minutes until either dismissed or viewed.<br/><br/>Changelog:<br/>11-24-2009: Create compatibility with SMS Tone Per Contact patch.
CATEGORY = Messaging
VERSIONS = 1.2.1-25 1.3.1-19 1.3.5-1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/c/c2/Messaging-notificatiion-repeat-1.jpg\"]
META_SUB_VERSION = 2

include ../common.mk
include ../modifications.mk

MAINTAINER = lclarkjr <lclarkjr@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2041590#post2041590
