NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Notification Repeat
DESCRIPTION = This patch will repeat the messaging notification every two minutes until either dismissed or viewed.
CATEGORY = Messaging
VERSIONS = 1.3.5-3 1.4.0-32 1.4.1-1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/c/c2/Messaging-notificatiion-repeat-1.jpg\" ]
META_SUB_VERSION = 2

include ../common.mk

include ../modifications.mk

MAINTAINER = lclarkjr <lclarkjr@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2041590#post2041590
