NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Notification Repeat
DESCRIPTION = This patch will repeat the messaging notification every two minutes until either dismissed or viewed.
CATEGORY = Messaging
VERSION = 1.2.1-25
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/c/c2/Messaging-notificatiion-repeat-1.jpg\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = lclarkjr <lclarkjr@gmail.com>
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Messaging_Notification_Repeat
