NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = 15 Minute Intervals Only
DESCRIPTION = Only show 15 minute intervals for start/end times while creating a new event.  This eliminates the need to scroll the list if you're like me and only use 15 min intervals.
CATEGORY = Calendar
VERSIONS = 1.4.5-84
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Chris Mann <csmann19@gmail.com>
HOMEPAGE =
