NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = GestureClick Context Menu
DESCRIPTION = Allows you to use 'gesture area+click' in addition to 'orange+click' to pull up the context menu in the browser.
CATEGORY = Browser
VERSIONS = 1.3.1-20 1.3.5-3
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = zinge, dBsooner <webos@dbsooner.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/214390-patch-gesture-click-browser-context-menu.html
