NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TWEAKS =
TITLE = Just Charge Button Label DE
DESCRIPTION = On the USB Mode popup, it'll rename the Cancel button back to the classic Just Charge button. This is a localized german version, renaming the button to 'Nur aufladen'.
CATEGORY = Notifications
VERSIONS = 3.0.0-28 3.0.2-6
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille, tklr
HOMEPAGE = http://forums.precentral.net/webos-patches/288396-patch-touchpad-just-charge-button-label.html