NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Hide Sprint Navigation App
DESCRIPTION = This patch will hide the Sprint Navigation App in the Launcher.
CATEGORY = App Launcher
VERSIONS = 1.4.0-34 1.4.1-3 1.4.2-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = v3ritas <SPM7654@optonline.net>, opacityzero
HOMEPAGE = http://forums.precentral.net/webos-patches/215737-patch-hide-sprint-navigation-app.html
