NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = No Auto Refresh After Idle
DESCRIPTION = Disables the annoying browser feature that reloads the page every time you are away from it for a while.
CATEGORY = Browser
VERSIONS = 1.3.5-18 1.4.0-7 v1.4.1-1
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/222786-patch-no-refresh-browser.html
