NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = No Auto Refresh After Idle
DESCRIPTION = Disables the annoying browser feature that reloads the page every time you are away from it for a while.
CATEGORY = Browser
VERSIONS = 2.1.0-99 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = MetaView <metaview@web.de>
HOMEPAGE = http://forums.precentral.net/webos-patches/283272-browser-no-refresh-after-idle-webos-2-1-a.html
