NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Shake to Reload
DESCRIPTION = After a shake of your Pre, the current webpage will reload.
CATEGORY = Browser
VERSIONS = 1.3.5-24 1.4.0-13
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1 

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/229809-patch-browser-shake-reload.html