NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Disable Various Phone Sounds
DESCRIPTION = This patch will disable the end call, missed call, ignored call, and dropped call sound.
CATEGORY = Phone
VERSIONS = 2.0.0-35 2.0.1-62 2.1.0-16 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =
