#!/bin/sh

rm -rf /media/internal/.local/lib/locale
mkdir -p /media/internal/.local/lib/locale

tar --no-same-owner -C /media/internal/.local/lib/locale -zxf \
	$IPKG_OFFLINE_ROOT/usr/palm/applications/org.webosinternals.locale/locales.tar.gz

if [ ! -e /usr/lib/locale ]
then
	ln -s /media/internal/.local/lib/locale /usr/lib/locale
fi

