#!/bin/sh

mkdir -p /media/internal/.local/lib/locale

tar -C /media/internal/.local/lib/locale -zxf $IPKG_OFFLINE_ROOT/usr/palm/applications/org.webosinternals.locale/locales.tar.gz

if [ ! -e /usr/lib/locale ]
then
	ln -s /media/internal/.local/lib/locale /usr/lib/locale
fi

