NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Voogle replaces Voicemail in Phone
DESCRIPTION = This patch replaces the default voicemail button action in the Phone App by launching the Voogle app instead. Dialing Voicemail from Just Type also launches Voogle.  This is based off the 'YouView from Phone' patch by Inglorious Apps.
CATEGORY = Phone
VERSIONS = 2.1.0-88 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Audemars02 <adam.marks@precentral.net>, Inglorious Apps
HOMEPAGE =
