#!/bin/sh
CHROOT_NAME=ubuntu-natty-chroot
CHROOT_PATH=/media/ext3fs/${CHROOT_NAME}
XAPP_NAME="xchat"

NAME="xapps-xchat-ubuntu-natty"

APPID="org.webosinternals.${NAME}"

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

# Stop the service if running
/sbin/stop ${APPID} || true

# Remove the upstart script
rm -f /var/palm/event.d/${APPID}

if [ ! -d /media/ext3fs ] ; then
    echo "This package requires a dedicated ext3fs partition created by the WebOS Internals Meta-Doctor"
    exit 1
fi

if ! `grep -q ext3fs /proc/mounts` ; then
    echo "You must ensure a dedicated ext3fs partition is mounted before installing this package"
    exit 1
fi

# install new app

cp /etc/resolv.conf ${CHROOT_PATH}/etc/resolv.conf

mount --bind /dev ${CHROOT_PATH}/dev
mount --bind /dev/pts ${CHROOT_PATH}/dev/pts
mount --bind /proc ${CHROOT_PATH}/proc
mount --bind /sys ${CHROOT_PATH}/sys
mount --bind /tmp ${CHROOT_PATH}/tmp

# add our application
export PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin
chroot ${CHROOT_PATH} /usr/bin/apt-get install --force-yes -y ${XAPP_NAME}

umount ${CHROOT_PATH}/tmp
umount ${CHROOT_PATH}/sys
umount ${CHROOT_PATH}/proc
umount ${CHROOT_PATH}/dev/pts
umount ${CHROOT_PATH}/dev

# Install the upstart script
mkdir -p /var/palm/event.d
cp ${APPDIR}/upstart/${APPID} /var/palm/event.d/${APPID}

exit 0
