#!/bin/sh

APPID=mobi.optware.openssh-sftp-server

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

# Symlink files into /opt
cd ${APPDIR}/opt
find libexec -type d -exec mkdir -p /opt/{} \;
find libexec -type f -exec ln -sf ${APPDIR}/opt/{} /opt/{} \;

exit 0
