NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Enable Personal Avatar
DESCRIPTION = This will enable your own avatar in the messaging application. To add your own personal avatar, name it my-avatar.png and place it in /usr/palm/applications/com.palm.app.messaging/images/
CATEGORY = Messaging
VERSIONS = 1.2.1-0 1.1.3-0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/0/00/Msg-avatar.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = optik678, Jason Robitaille <robitaille88@gmail.com>
HOMEPAGE = http://www.webos-internals.org/wiki/Myavatar_In_Messaging_App
