NAME = $(shell basename $(shell pwd))
PATCH = memos/${NAME}.patch
TWEAKS =
TITLE = Open Memos App to New Memo Page
DESCRIPTION = This will open the Memos app directly to the 'New Memo page' when first opened. To get back to the main viewing page simply back-swipe.
CATEGORY = Memos
VERSIONS = 1.4.5-155 2.1.0-96 2.1.1-22 2.1.2-31 2.2.0-22 2.2.3-22
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/3/31/Misc-open-memos-app-to-new-memo-page-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Djgardn2
HOMEPAGE = http://forums.precentral.net/webos-patches/282397-patch-open-memos-app-new-memo-page.html
