#!/bin/sh

APPID=mobi.optware.libstdc++

# Remove files from /opt
rm -f /opt/lib/libstdc++.so /opt/lib/libstdc++.so.6
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find lib -depth -type f -exec rm -f /opt/{} \;
find lib -depth -type d -exec rmdir /opt/{} \;

exit 0
