NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = 4x4 Icons v5
DESCRIPTION = This will modify the App launcher to display 4x4.  The size and spacing are just right.  This is the same as '4x4 icons v4 with extras' but without the extra features.  This should improve compatibility with other patches.
CATEGORY = App Launcher
VERSIONS = 1.4.1-14 1.4.2-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/7/71/App-launcher-4x4-icons-v5-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = cwgtex
HOMEPAGE = http://forums.precentral.net/webos-patches/244975-patch-4x4-icons-v4.html
