NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = New Card Button
DESCRIPTION = Adds a new card button in the browser that opens up new browser cards
CATEGORY = Browser
VERSIONS = 1.3.5-24 1.4.0-13 1.4.1-1 1.4.2-1 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1 

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/219794-patch-new-card-button-browser.html#post2093933
