NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = New Card Button
DESCRIPTION = Adds a new card button in the browser that opens up new browser cards. Works very nicely with the stacks feature of 2.x
CATEGORY = Browser
VERSIONS = 1.4.5-1 2.0.0-26 2.0.1-39 2.1.0-3
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/219794-patch-new-card-button-browser.html#post2093933