NAME = $(shell basename $(shell pwd))
PATCH = navigation/${NAME}.patch
TITLE = Verizon aGPS Blocker
DESCRIPTION = Attempts to block the VZW aGPS server to allow rollover to standard GPS  (MIT license)
CATEGORY = Navigation
VERSIONS = 1.4.5-104
ICON = http://www.webos-internals.org/images/c/c3/Icon_WebOSInternals_Patches_SprintNav.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Troy Miller <troy.miller@miller-technologies.com>
HOMEPAGE = http://forums.precentral.net/web-os-development/268933-patch-disable-verizon-agps-server-improved-gps.html
