NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Battery Percent As Icon White
DESCRIPTION = This is the same as the original Battery Percent as Icon patch, except the % icon will be white instead of multiple colored icons.<br/><br/>If you use one of my topbar font patches the numbers and % icon will match the font size and color.<br/><br/>This will remove and replace your current battery icons with the number and % icon.<br/><br/><b>NOTE:</b>There are no Charging notifications with this patch.<br/><br/>Thanks to nesl247 for the original!
CATEGORY = Top Bar
VERSIONS = 1.3.1-24 1.3.5-3 1.4.0-3
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/0/09/Top-bar-battery-percent-as-icon-white-1.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = 2sslow
HOMEPAGE =
