NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Add Date MM/DD Period as Delimiter
DESCRIPTION = Adds the date to the left of the time in the top bar in MM.DD format.
CATEGORY = Top Bar
VERSIONS = 1.3.5-21 1.4.0-10
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 

include ../common.mk

include ../modifications.mk

MAINTAINER = hape <hanspeter@hp-jochmann.de>, tk102
HOMEPAGE =