NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = Messenger Mega Mix
DESCRIPTION = This patch combines various useful patches for Messenger: adds Character Counter, removes Send and Attach buttons, adds a Forward Gesture in place for Send button, adds Gesture+p shortcut to attach item, adds Enter Button for New line instead of sending message, adds Date/Time into chatview of conversation dialog.
CATEGORY = Messaging
VERSIONS = 2.2.4-86
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = michel <michel7@mail.ru>
HOMEPAGE = http://forums.webosnation.com/webos-patches/320580-patch-messenger-mega-mix-webos-2-2-x.html