NAME = $(shell basename $(shell pwd))
PATCH = youtube/${NAME}.patch
TWEAKS =
TITLE = Youtube Brazilian Feed
DESCRIPTION = Change the youtube app to Brazilian feed. based on iMarck90 work.
CATEGORY = YouTube
VERSIONS = 2.1.0-251 2.1.1-56 2.1.2-66 2.2.4-52
ICON = http://www.webos-internals.org/images/8/8b/Icon_WebOSInternals_Patches_Youtube.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = padula
HOMEPAGE =