NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Prevent Scrolling When Minimizing Browser
DESCRIPTION = This patch prevents the page from scrolling when you minimize a Browser card.
CATEGORY = Browser
VERSIONS = 3.0.2-94 3.0.4-63 3.0.5-8
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Garrett92C <Garrett92C@gmail.com>
HOMEPAGE = http://forums.webosnation.com/hp-touchpad-homebrew/309219-patch-prevent-scrolling-when-minimizing-browser.html