NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Bluetooth Increased Media and In Call Volume
DESCRIPTION = The patch bluetooth-volume increases the in call and media volume while on a bluetooth headset. After applying patch REBOOT IS MANDATORY for patches to work. Luna restart won't apply change.
CATEGORY = Misc
VERSIONS = 1.4.5-96
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = jctreo <marion.mouton@gmail.com>, mamouton
HOMEPAGE =
