NAME     = tipcalculator
APP_ID   = org.jwz.${NAME}
VERSION  = 1.0.6
PLATFORM = all
HOMEPAGE = http://www.jwz.org/${NAME}/

SRC_IPKG = http://www.jwz.org/${NAME}/${APP_ID}_${VERSION}_${PLATFORM}.ipk
include ../../support/download.mk

include ../../support/application-copy.mk
