NAME = $(shell basename $(shell pwd))
PATCH = camera/${NAME}.patch
TWEAKS =
TITLE = Set Camcorder as Default
DESCRIPTION = All this actually does is restore the last capture mode of the camera app from prefs. So, if you use the camcorder a lot, the camera app will default to that mode when you start it.
CATEGORY = Camera
VERSIONS = 2.1.0-228 2.1.1-35 2.1.2-43 2.2.0-106 2.2.3-100 2.2.4-16
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GuyFromNam <GuyFromNam@hotmail.com>
HOMEPAGE =