#!/bin/sh

DISTRO=ubuntu-natty

NAME=${DISTRO}-chroot

APPID=org.webosinternals.${NAME}

if [ -d /media/ext3fs/${NAME} ] ; then
    echo "Will not overwrite existing chroot directory at /media/ext3fs/${NAME}"
    exit 1
fi

if [ -d /media/ext3fs ] ; then
    mkdir -p /media/ext3fs/${NAME} || exit 1
    tar -C /media/ext3fs/${NAME} -z -x -f /media/cryptofs/apps/usr/palm/applications/${APPID}/${NAME}.tgz || exit 1
fi

exit 0
