#!/bin/sh
PACKAGE=org.webosinternals.emergency-patch-recovery
PATCH_CONTROL_DIR=/var/usr/lib/.webosinternals.patches

if [ ! -d $PATCH_CONTROL_DIR ]
then
  echo "NOTE: No patches found!"
  ipkg -o /var remove $PACKAGE
  exit 1
fi

if [ -e $PATCH_CONTROL_DIR/packages ]
then
  for i in `cat $PATCH_CONTROL_DIR/packages`
  do
    ipkg -o /var remove $i
  done
fi

if [ -e $PATCH_CONTROL_DIR/backups ]
then
  for i in `cat $PATCH_CONTROL_DIR/backups`
  do
    echo "Recovering original file $i..."
    mv $i.webosinternals.orig $i
  done
fi

echo "DONE"
rm -rf $PATCH_CONTROL_DIR

ipkg -o /var remove $PACKAGE
exit 0
