NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TWEAKS =
TITLE = Facebook calendar timezone fix
DESCRIPTION = Fixes display of Facebook calendar events
CATEGORY = Calendar
VERSIONS = 2.1.0-252 2.1.1-57 2.1.2-67 2.2.4-53 3.0.5-24
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = frantid
HOMEPAGE = http://forums.webosnation.com/webos-patches/314083-fix-facebook-timezone-problems.html