NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Rotated 270deg Battery Icon And Percent
DESCRIPTION = Adds a 12px battery percent value to the above of the rotated battery icon, which is rotated 270 degrees.  -   Based on the Battery icon and percent patches in Preware by nesl247 and Jason Robitaille and the rotated version by Vincent Law (MIT license)
CATEGORY = Top Bar
VERSIONS = 1.4.5-133 2.0.0-34 2.0.1-61 2.1.0-15 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/5/58/Top-bar-rotated-270deg-battery-icon-and-percent-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = frause
HOMEPAGE = http://forums.precentral.net/webos-patches/242657-patch-rotated-battery-icon-percentage-2.html#post2399715
