NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = Remove Tap Ripple
DESCRIPTION = Removes the ripple effect on tap. This mitigates lag on tapping, especially in 60fps PDK applications.
CATEGORY = System
VERSIONS = 2.1.0-133 2.2.0-27 3.0.2-9
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Alan Stice <alan@associativeintelligence.org>
HOMEPAGE =