NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = Remove Tap Ripple
DESCRIPTION = Removes the ripple effect on tap. This mitigates lag on tapping, especially in 60fps PDK applications.
CATEGORY = System
VERSIONS = 2.1.0-186 2.1.1-22 2.1.2-31 2.2.0-54 2.2.3-48 2.2.4-8 3.0.2-54 3.0.4-8 3.0.5-4
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Alan Stice <alan@associativeintelligence.org>
HOMEPAGE =