NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Fix Pin Screen Background
DESCRIPTION = Fixes the ugly grey, and hardly readable pin screen Background.
CATEGORY = Misc
VERSIONS = 1.4.5-137 2.0.0-37 2.0.1-64 2.1.0-18 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/9/92/Misc-fix-pin-screen-background-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = michote <reischuck.micha@googlemail.com>
HOMEPAGE = http://m.forums.precentral.net/showthread.php?t=277738
