NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Add Audio to SMS
DESCRIPTION = Ability to add audio to text message
CATEGORY = Messaging
VERSIONS = 2.0.0-44 2.0.1-72 2.1.0-43 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/d/d1/Messaging-add-audio-to-sms-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =
