NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = No Snooze for Banner
DESCRIPTION = Eliminates the pop-up notification after you hit the snooze button on a calendar reminder that states 'Snoozed for 5 minutes'. Allowing you to move on with your work and not wait for it to clear.
CATEGORY = Calendar
VERSIONS = 1.4.5-134 2.0.0-34 2.0.1-61 2.1.0-15 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = CRaia Software
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2495887#post2495887
