NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Additional Days And Times For Syncing Email
DESCRIPTION = Additional Days For Syncing & More Sync Times
CATEGORY = Email
VERSIONS = 2.1.0-30 2.1.1-22 2.1.2-31 3.0.2-88 3.0.4-54
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =