NAME = $(shell basename $(shell pwd))
PATCH = video-player/${NAME}.patch
TITLE = No Pause of Video on Screen Change
DESCRIPTION = Don't pause the video (in Video Player and Youtube) when the app is minimized or when the screen is turned off
CATEGORY = Video Player
VERSIONS = 1.4.5-98
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Videoplayer.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = insideout
HOMEPAGE = http://forums.precentral.net/webos-patches/242614-patc-no-video-pause-dim-screen-change.html
