NAME = full-im-status
PATCH = /messaging/full-IMstatus.patch
TITLE = Full IM Status
DESCRIPTION = Shows full buddy list IM status instead of truncated.
CATEGORY = Messaging
VERSION = 0.3.2
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
