NAME = $(shell basename ${PWD})
PATCH = /messaging/${NAME}.patch
TITLE = Full IM Status
DESCRIPTION = This will show the full buddy list IM status instead of a truncated one.
CATEGORY = Messaging
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = 
META_VERSION = 1

include ../common.mk
include ../modifications.mk
