NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Hide Quick Launch Bar in Launcher Remix
DESCRIPTION = Hides quick launcher in app launcher and adds a menu item to edit the quick launcher. Selecting edit from menu makes quick launcher visible for editing. This patch also adds the add/remove pages into the app launchers menu.
CATEGORY = App Launcher
VERSIONS = 1.4.0-38 1.4.1-7
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = http://forums.precentral.net/homebrew-apps/224544-mode-switcher.html