NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Change number of bookmarks to 99
DESCRIPTION = Changes the maximum number of bookmarks on browser start page to 99
CATEGORY = Browser
VERSIONS = 2.1.0-18 2.1.1-22 2.1.2-31 2.2.4-45
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = pastorrich1, Herrie
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2805799#post2805799