NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Notification Repeat
DESCRIPTION = This patch will repeat the missed call notification every 2 minutes until dismissed or viewed.
CATEGORY = Phone
VERSIONS = 1.3.5-3 1.4.0-3 1.4.1-1 1.4.2-1
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/9/97/Phone-phone-notification-repeat-1.jpg\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = lclarkjr <lclarkjr@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2041604#post2041604
