NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Notification Repeat
DESCRIPTION = This patch will repeat the missed call notification every 2 minutes until dismissed or viewed.
CATEGORY = Phone
VERSIONS = 1.2.1-25 1.3.1-8
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/9/97/Phone-phone-notification-repeat-1.jpg\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = lclarkjr <lclarkjr@gmail.com>
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Phone_Notification_Repeat
