NAME = $(shell basename $(shell pwd))
PATCH = camera/${NAME}.patch
TWEAKS =
TITLE = Short Date in Video File Name
DESCRIPTION = Cosmetic. This patch saves new videos as '12-05-2012 [time]' instead of '12 May 2012 [time]'. 'This is not America.' ;)
CATEGORY = Camera
VERSIONS = 2.1.2-72 2.2.4-64
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GuyFromNam <GuyFromNam@hotmail.com>
HOMEPAGE =