NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Delete From Notification
DESCRIPTION = This patch lets you delete the email displayed in the notification bar. Once deleted the sync should send an update to your Pre to either remove the notification or update the notification with the next new email.
CATEGORY = Email
VERSIONS = 1.2.1-25 1.3.1-13
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/b/b4/Email-delete-from-notification-1.jpg\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = lclarkjr <lclarkjr@gmail.com>
HOMEPAGE = http://forums.precentral.net/web-os-development/210407-delete-email-notification-bar.html
