NAME     = pretris
APP_ID   = com.danielfarina.${NAME}
VERSION  = 0.2.5
PLATFORM = all
HOMEPAGE = http://forums.precentral.net/homebrew-apps/192053-pretris-pre-tetris-v2-0-v1-8-nrr.html

SRC_IPKG = http://forums.precentral.net/attachments/homebrew-apps/22531d1247958957-pretris-pre-tetris-v2-0-v1-8-nrr-${APP_ID}_${VERSION}_${PLATFORM}.ipk
include ../../support/download.mk

include ../../support/application-copy.mk
