NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Auto BCC - Verizon Wireless only
DESCRIPTION = Allows input bcc email address in email account profile. The bcc address will be automatically added to outgoing email.Should now work for *all* languages.Note: The bcc address is only filled in of the account you start the e-mail from. If you change the account in header of the compose e-mail scene, the bcc address won't be changed.
CATEGORY = Email
VERSIONS = 2.1.0-159
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = pcworld <0188801@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/260848-patch-email-auto-bcc.html