NAME = $(shell basename $(shell pwd))
PATCH = contacts/${NAME}.patch
TWEAKS =
TITLE = Enhanced Contacts VCard Export
DESCRIPTION = Fixes and enhances the VCard(.vcf)-Fileexport so more fields of a contact get exported into the file, making it suitable for complete backup of contacts or switching to new contacts account.- URL: fixed for 2.2.4 - was exported with wrong marker- Spouse (Partner: added newly as X-SPOUSE:- Children: added newly as X-CHILD:Use forumthread for feedback.(only for 2.2.4 for now, need betatesters for 2.1 , 3.0.5)
CATEGORY = Contacts
VERSIONS = 2.2.4-80
ICON = http://www.webos-internals.org/images/c/ca/Icon_WebOSInternals_Patches_Contacts.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = gizmo21
HOMEPAGE = http://forums.webosnation.com/webos-patches/319213-patch-fixing-enhancing-vcard-vcf-export.html