NAME = $(shell basename $(shell pwd))
PATCH = contacts/${NAME}.patch
TWEAKS =
TITLE = Enhanced Contacts VCard Export
DESCRIPTION = Fixes and enhances the VCard(.vcf)-Fileexport so more fields of a contact get exported into the file, making it suitable for complete backup of contacts or switching to new contacts account.- URL: fixed - was exported with wrong marker     - Spouse(Partner): added newly as X-SPOUSE:      - Children: added newly as X-CHILD:             Use forum thread for feedback. Initial for 2.2.4.                      Update: added support for 2.1.0, 2.1.1, 2.1.2, 3.0.5 (credits to John Steffes)
CATEGORY = Contacts
VERSIONS = 2.1.0-270 2.1.1-106 2.1.2-108 2.2.4-80 3.0.5-45
ICON = http://www.webos-internals.org/images/c/ca/Icon_WebOSInternals_Patches_Contacts.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = gizmo21
HOMEPAGE = http://forums.webosnation.com/webos-patches/319213-patch-fixing-enhancing-vcard-vcf-export.html