NAME = $(shell basename $(shell pwd))
PATCH = advanced/${NAME}.patch
TITLE = Advanced System Prefs - Framework
DESCRIPTION = NOTE: This is for most versions of WebOS 2.1.0, some older WebOS 2.1.0 versions need the LEGACY version of this patch.<br/><br/>Adds support for per contact and unknown contacts notification settings. This patch is required by all of the system prefs patches.
CATEGORY = Advanced
VERSIONS = 2.1.0-98
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/9/9f/AdvancedSystemPrefsFramework_1.jpg\", \"http://www.webos-internals.org/images/5/5b/AdvancedSystemPrefsFramework_2.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = http://forums.precentral.net/enlightened-linux-solutions/269550-patch-advanced-system-prefs-2-x.html
