NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Media Volume in Device Menu
DESCRIPTION = Adds a media volume slider control to the device menu.
CATEGORY = Top Bar
VERSIONS = 1.4.0-34 1.4.1-3
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/d/d3/Top-bar-media-volume-in-device-menu-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/237644-patch-media-volume-control-device-menu.html