NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Replies Forwards Multi Mod
DESCRIPTION = This patch modifies the formatting of email replies and forwards sent from your phone. Changes include: <br/><br/>1) change reply font size to 11 pt. Calibri, light blue<br/>2) replaces the 'John Smith wrote:' text with the 'From', 'Sent', 'To', and 'Subject' language used in Outlook<br/>3) uses the long form for dates in 'Sent' field (e.g., Wednesday, January 06, 2010 9:26 pm).<br/><br/>This patch is currently not compatible with Replies/Forwards in Black Font. Must remove before you try to apply this patch.
CATEGORY = Email
VERSIONS = 1.4.5-1
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/2/22/Email-replies-forwards-multi-mod-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mikePre, Jonolee
HOMEPAGE =
