NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Replies Forwards Multi Mod
DESCRIPTION = This will change the reply to a smaller, black Calibri font. Also changes the Reply to remove the 'John Smith wrote' text and replace it with the typical 'From: ... To: ...' language that Outlook displays.<br /><br />This patch is currently not compatible with Replies/Forwards in Black Font. Must remove before you try to apply this patch.
CATEGORY = Email
VERSIONS = 1.3.1-27 1.3.5-11
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/2/22/Email-replies-forwards-multi-mod-1.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = mikePre <rizmail@gmail.com>, Jonolee
HOMEPAGE =
