NAME = $(shell basename $(shell pwd))
PATCH = universal-search/${NAME}.patch
TITLE = Add Bing and Yahoo and Remove Twitter
DESCRIPTION = Enables Bing and Yahoo in Universal Search and removes Twitter
CATEGORY = Universal Search
VERSIONS = 1.4.1-11 1.4.2-1 1.4.5-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/7/70/Universal-search-add-bing-and-yahoo-and-remove-twitter-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Thomas Coe <thomascoe1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/240226-patch-yahoo-bing-universal-search.html
