NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Repeat Reminder Notifys
DESCRIPTION = This patch will repeat the reminder notification every 2 minutes until you either dismiss or snooze the reminder.
CATEGORY = Calendar
VERSION = 1.2.1-2
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/a/ab/CalendarRepeatNotification.png\"]
META_SUB_VERSION = 2
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk

MAINTAINER = Lclarkjr
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Calendar_Notification_Repeat
