NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Repeat Reminder Notifys
DESCRIPTION = This patch will repeat the reminder notification every 2 minutes until you either dismiss or snooze the reminder.
CATEGORY = Calendar
VERSIONS = 1.3.5-3
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/a/ab/CalendarRepeatNotification.png\"]
META_SUB_VERSION = 3

include ../common.mk
include ../modifications.mk

MAINTAINER = Lclarkjr
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2041448#post2041448
