NAME = message-tone-sounds-and-alerts
PATCH = /soundsandalerts/${NAME}.patch
TITLE = Message Tone Options
DESCRIPTION = This will give you the ability to change the Alert tone and Notification tone in the Sounds & Alerts application.  NOTE that the SMS Tone per Contact patch includes this exact functionality so this is not needed and will not install if that patch is installed.
CATEGORY = Sounds and Alerts
VERSION = 0.4.3
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Soundsandalerts.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/d/d3/Message-tone-sounds-and-alerts.png\"]
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
