NAME = message-tone-sounds-and-alerts
PATCH = /soundsandalerts/${NAME}.patch
TITLE = message tone sounds and alerts patch
DESCRIPTION = ???
CATEGORY = Sounds and Alerts
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
