NAME = message-tone-sounds-and-alerts
PATCH = /soundsandalerts/${NAME}.patch
TITLE = message tone sounds and alerts patch
DESCRIPTION = ???
CATEGORY = Sounds and Alerts
VERSION = 0.2.1
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Soundsandalerts.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
