NAME = $(shell basename $(shell pwd))
TITLE = Stock Kernel (Palm Pre)
DESCRIPTION = An unmodified stock kernel package.<br>\
Useful for restoring the operation of your device back to factory specifications.<br>${KERNEL_DISCLAIMER}
CATEGORY = Hardware-Related
VERSIONS = 1.4.1-1
ICON = http://www.webos-internals.org/images/8/8d/Icon_WebOSInternals_WebOSInternals.png
SCREENSHOTS = 
META_SUB_VERSION = 1

PACKAGES = ipkgs/${APP_ID}_${VERSION}_arm.ipk

include ../common.mk

HOMEPAGE = http://opensource.palm.com
KERNEL_PATCHES =

include ../kernel.mk
