NAME = $(shell basename $(shell pwd))
TITLE = Stock Kernel (Palm Pre)
DESCRIPTION = An unmodified stock kernel package.<br>\
Useful for restoring the operation of your device back to factory specifications.<br>${KERNEL_DISCLAIMER}
CATEGORY = Stable
# VERSIONS = 1.4.1-1
VERSION = 1.4.1-1
SCREENSHOTS = 

HOMEPAGE = http://opensource.palm.com
SRC_GIT = git://git.webos-internals.org/kernels/patches.git
KERNEL_PATCHES =

include ../../support/kernel.mk
