NAME = $(shell basename ${PWD})
PATCH = /browser/${NAME}.patch
TITLE = Swipe Delete History in Browser
DESCRIPTION = This will add the ability to swipe delete items in the browser history with a confirmation dialog.
CATEGORY = Browser
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
