NAME = swipe-delete-history
PATCH = /browser/${NAME}.patch
TITLE = Swipe Delete History in Browser
DESCRIPTION = Adds ability to swipe delete items in the browser history WITH confirmation dialog
CATEGORY = Browser
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
