NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Increase Speaker Headset Volume
DESCRIPTION = Increase Back Speaker and Headset for Media and calls.  Requires a full reboot of the phone after installation.
CATEGORY = Misc
VERSIONS = 1.4.5-92
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = jctreo <marion.mouton@gmail.com>, mamouton, joetemp75, fixxer
HOMEPAGE =