NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = GSM 3G GPS and Brightness in Device Menu
DESCRIPTION = Toggles GSM 3G/2G, Data, GPS and adjust brightness in device menu (language independend)
CATEGORY = Top Bar
VERSIONS = 1.4.5-123 2.0.1-44 2.1.0-2 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/6/65/Top-bar-gsm-3g-gps-and-brightness-in-device-menu-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = MetaView <metaview@web.de>
HOMEPAGE =
