NAME = music-player-book-resume
PATCH = music-player/music-player-book-resume.patch
TITLE = Resume Play for Books
DESCRIPTION = Adds resume play support for the "Books" and "Books & Spoken" genres.
CATEGORY = Music Player
VERSION = 1.2.1-8
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Sivan
HOMEPAGE =
