NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = CN Number List upgrade
DESCRIPTION = Update number list for China (CN). recognize 12520 from fetion, and 179XX so message sent from fetion can match your mobile number in your contact list.
CATEGORY = Phone
VERSIONS = 2.1.0-210 2.1.1-22 2.1.2-31 2.2.4-4 3.0.2-74 3.0.4-73 3.0.5-37
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = moo <moo.tinys@gmail.com>
HOMEPAGE = http://www.treo8.com/bbs/thread-275013-1-1.html