NAME = compose-email
PATCH = /messaging/${NAME}.patch
TITLE = Message Compose to Email
DESCRIPTION = Adds email addresses of contacts to the list of available destinations in the Messaging Application.
CATEGORY = Messaging
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
