NAME = compose-email
PATCH = /messaging/${NAME}.patch
TITLE = Messaging Compose Email
DESCRIPTION = Adds ability to messaging app to compse email
CATEGORY = Messaging
VERSION = 0.3.3
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
