NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Scrim Messaging
DESCRIPTION = This patch adds the ability to add a background scrim image to the messaging app. When you install this patch it will first change the messaging app to almost the Palm-Dark scheme (dark gray back ground with black fonts) if you like it you can stop there. For the user that wants to add their own background, there are many 320x480 png images to choose from. Choose an image, name it messaging-scrim.png and save it in the wallpapers folder (/media/internal/wallpapers/) on your Pre. There are some great scrim images and ideas here: <a href="http://forums.precentral.net/webos-patches/214624-patch-add-background-scrim-contacts-app.html">http://forums.precentral.net/webos-patches/214624-patch-add-background-scrim-contacts-app.html</a>
CATEGORY = Messaging
VERSIONS = 1.3.5-3 1.4.0-3
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/a/aa/Messaging-scrim-messaging-1.jpg\",\
\"http://www.webos-internals.org/images/b/b0/Messaging-scrim-messaging-2.jpg\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = mracer29 <mracer29@yahoo.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/214891-patch-add-background-scrim-email-app.html?highlight=scrim
