NAME = $(shell basename $(shell pwd))
PATCH = sounds-and-alerts/${NAME}.patch
TITLE = Disable Charging Alert Sound
DESCRIPTION = This will prevent the alert sound from being played when the device starts to charge.
CATEGORY = Sounds and Alerts
VERSIONS = 1.2.1-0 1.1.3-0
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Soundsandalerts.png
SCREENSHOTS =
META_SUB_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk

MAINTAINER = a2ny <A2NY.Sinister@gmail.com>
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_webOS_Disable_Charging_Event_Sounds
