NAME = $(shell basename $(shell pwd))
PATCH = /sounds-and-alerts/${NAME}.patch
TITLE = Disable Charging Alert Sound
DESCRIPTION = This will prevent the alert sound from being played when the device starts to charge.
CATEGORY = Sounds and Alerts
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Soundsandalerts.png
SCREENSHOTS =
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
