#!/bin/sh

APPID=mobi.optware.dropbear

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=$APPS/usr/palm/applications/$APPID

# Remove any legacy upstart script
rm -f /etc/event.d/${APPID}

# Symlink files into /opt
cd $APPDIR/opt
find bin etc sbin -type d -exec mkdir -p /opt/{} \;
find bin etc sbin -type f -exec ln -sf $APPDIR/opt/{} /opt/{} \;
ln -sf /opt/sbin/dropbearmulti /opt/bin/dbclient
ln -sf /opt/sbin/dropbearmulti /opt/sbin/dropbear
ln -sf /opt/sbin/dropbearmulti /opt/sbin/dropbearconvert
ln -sf /opt/sbin/dropbearmulti /opt/sbin/dropbearkey

/opt/bin/update-alternatives --install /opt/bin/scp scp /opt/sbin/dropbearmulti 50
/opt/bin/update-alternatives --install /opt/bin/ssh ssh /opt/sbin/dropbearmulti 50

mkdir -p /opt/etc/dropbear

if [ ! -f /opt/etc/dropbear/dropbear_rsa_host_key ]; then
    echo Generating RSA Key...
    /opt/sbin/dropbearkey -t rsa -f /opt/etc/dropbear/dropbear_rsa_host_key
fi

if [ ! -f /opt/etc/dropbear/dropbear_dss_host_key ]; then
    echo Generating DSS Key...
    /opt/sbin/dropbearkey -t dss -f /opt/etc/dropbear/dropbear_dss_host_key
fi

# The emulator already has an ssh server running, so no need to start another.
if [ "`uname -m`" != "i686" ]; then
    rm -f /var/palm/event.d/$APPID
    mkdir -p /var/palm/event.d/
    cp $APPDIR/upstart/$APPID /var/palm/event.d/$APPID
    /sbin/start $APPID
fi

exit 0
