#!/bin/sh

APPID=mobi.optware.dropbear

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=$APPS/usr/palm/applications/$APPID

# The emulator already has an ssh server running, so no need to start another.
if [ "`uname -m`" != "i686" ]; then
    /sbin/stop $APPID
fi

rm -f /etc/event.d/$APPID /var/palm/event.d/$APPID

/opt/bin/update-alternatives --remove scp /opt/sbin/dropbearmulti
/opt/bin/update-alternatives --remove ssh /opt/sbin/dropbearmulti

# Remove files from /opt
rm -f /opt/bin/dbclient /opt/sbin/dropbear /opt/sbin/dropbearconvert /opt/sbin/dropbearkey
cd $APPDIR/opt
find bin etc sbin -depth -type f -exec rm -f /opt/{} \;
find bin etc sbin -depth -type d -exec rmdir /opt/{} \;

# We intentionally do not remove the host keys.

exit 0
