NAME = $(shell basename $(shell pwd))
PATCH = sounds-and-alerts/${NAME}.patch
TITLE = Disable Low Battery Warning Sound 10 Percent
DESCRIPTION = Disable 10% Battery low warning sound
CATEGORY = Sounds and Alerts
VERSIONS = 1.4.0-23 1.4.1-1
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Soundsandalerts.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =
