NAME = $(shell basename $(shell pwd))
PATCH = universal-search/${NAME}.patch
TITLE = SMS Icon for Mobile Tagged Numbers Only
DESCRIPTION = Displays the SMS icon only on numbers tagged 'Mobile' in universal search
CATEGORY = Universal Search
VERSIONS = 1.3.5-24 1.4.0-13 1.4.1-1 1.4.2-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/4/43/Universal-search-sms-icon-for-mobile-tagged-numbers-only-1.png\" ]
META_SUB_VERSION = 1 

include ../common.mk

include ../modifications.mk

MAINTAINER = xenoph0be
HOMEPAGE = http://forums.precentral.net/webos-patches/231090-universal-search-display-sms-icon-mobile-tagged-numbers-only.html
