NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Replies/Forwards Black Font
DESCRIPTION = This will change the font color for replies and forwards to black instead of navy blue.
CATEGORY = Email
VERSIONS = 1.2.1-0 1.3.1-10 1.3.5-8 1.4.0-1
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/0/06/Replies-forwards-black.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = jdoelger, dBsooner <webos@dbsooner.com>
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Email_Change_Default_Font_for_Replies-Forwards_from_Navy_to_Black
