NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Add Priority Discard Btns
DESCRIPTION = This will place a high priority icon and a discard message icon at the bottom of your email you are composing.
CATEGORY = Email
VERSIONS = 1.2.1-19 1.3.1-0
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/6/60/Email-add-priority-discard-btns-1.jpg\",\
\"http://www.webos-internals.org/images/5/57/Email-add-priority-discard-btns-2.jpg\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =
