NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Add Priority Discard Btns
DESCRIPTION = This will place a high priority icon and a discard message icon at the bottom of the email you are composing. This update includes a send message confirmation. This update incorporates Tibfib's discard confirmation as well as removing the options from the menu. Special thanks to Tibfib for his work in adding the discard confirmation option.
CATEGORY = Email
VERSIONS = 1.3.5-31 1.4.0-24
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/c/ca/Email-add-priority-discard-btns-1.png\",\
\"http://www.webos-internals.org/images/5/57/Email-add-priority-discard-btns-2.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =