NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Bookmark Browser Fix
DESCRIPTION = Patch to fix bug that causes bookmarks not to be displayed in browser preferences. That scene enables deletion or reordering of bookmarks. by Dick99999....I just submitted it.
CATEGORY = Browser
VERSIONS = 2.2.4-53
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Hernie
HOMEPAGE = http://forums.webosnation.com/webos-patches/276011-patch-browser-fix-no-bookmarks-displayed-bug-2-0-1-a.html