NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TITLE = Enable LED Notifications
DESCRIPTION = This will uncomment the code necessary for the gesture area to light up for notifications. You must still make sure LED Notifications is enabled in the Screen & Lock application.
CATEGORY = Screen Lock
WEBOS_VERSION = 1.2.1
IPKG_VERSION = 0
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/8/86/Enable-led-notifications.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Jhoff80
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Enable_LED_Notifications
