NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TWEAKS =
TITLE = Advanced Options in Launcher
DESCRIPTION = Adds additional options to the launcher's menu: turn on/off DevMode, rescan fileindexer, and rescan applications
CATEGORY = App Launcher
VERSIONS = 2.1.0-3 2.1.1-22 2.1.2-31 2.2.0-19 2.2.3-19 2.2.4-14
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/223806-patch-advanced-options-launcher.html