NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Decrease Font Size
DESCRIPTION = Reduce font size by several pts (21 ->10) on some webpages. Please restart phone to clear font cache for this patch to take effect.Works on m.ft.com, mobile.nytimes.com, m.guardian.co.uk, m.cricinfo.com.It does nothing on e.g.,  mobile.bloomberg.com, the mobile Google reader page, m.theregister.co.uk, m.espn.go.com/wireless, news.google.com, groups.google.com/forum/m. Any input on why this patch does nothing on these pages will be greatly appreciated.Acknowledgements: Beknatok (for finding these settings in browser-app.conf)
CATEGORY = Browser
VERSIONS = 1.4.5-122 2.2.0-79 2.2.3-108 2.2.4-25
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = veerar
HOMEPAGE = http://forums.precentral.net/webos-patches/273212-patch-reduce-browser-font-size-unreliably.html#post3245681