NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Decrease Font Size
DESCRIPTION = Reduce font size by 2pts (14 ->12) on some webpages. <br/><br/>Please restart phone to clear font cache for this patch to take effect.<br/><br/>Works on m.ft.com, mobile.nytimes.com, m.guardian.co.uk, m.cricinfo.com.<br/><br/>It does nothing on e.g.,  mobile.bloomberg.com, the mobile Google reader page, <br/>m.theregister.co.uk, m.espn.go.com/wireless, news.google.com, <br/>groups.google.com/forum/m. Any input on why this patch does nothing on <br/>these pages will be greatly appreciated.<br/><br/>Acknowledgements: Beknatok (for finding these settings in browser-app.conf)
CATEGORY = Browser
VERSIONS = 1.4.5-122
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = veerar
HOMEPAGE = http://forums.precentral.net/webos-patches/273212-patch-reduce-browser-font-size-unreliably.html#post2833507