#!/bin/sh

PACKAGE=org.webosinternals.eom-overlord-monitoring

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
    IPKG_OFFLINE_ROOT=/media/cryptofs/apps
    mount -o remount,rw /
fi

# Stop uploading stuff to the mothership
# First off, stop uploadd and rdxd processes.
# Next, kill off contextupload
#
stop uploadd
sed -i -e 's/^respawn/#respawn/' /etc/event.d/uploadd
sed -i -e 's/^exec/#exec/' /etc/event.d/uploadd

stop rdxd
sed -i -e 's/^respawn/#respawn/' /etc/event.d/rdxd
sed -i -e 's/^exec/#exec/' /etc/event.d/rdxd

#killall contextupload
#mv /usr/bin/contextupload /usr/bin/contextupload.orig

#ipkg -o $IPKG_OFFLINE_ROOT remove $PACKAGE
exit 0
