NAME = capture-with-volume-keys
PATCH = /camera/capture_with_volume_keys.patch
TITLE = Camera Capture with Volume Keys
DESCRIPTION = Use volume keys to capture pictures in camera app
CATEGORY = Camera
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
