NAME = capture-with-volume-keys
PATCH = /camera/capture_with_volume_keys.patch
VERSION = 0.1.0
TITLE = Camera Capture with Volume Keys
DESCRIPTION = Use volume keys to capture pictures in camera app
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
