NAME = capture-with-volume-keys
PATCH = /camera/capture_with_volume_keys.patch
TITLE = Camera Capture with Volume Keys
DESCRIPTION = This will add the ability to capture images with the volume keys in the camera applications.
CATEGORY = Camera
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
