NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = iPhone Style No Avatar
DESCRIPTION = This patch formats the messenger to be like the iphones, without any avatars.
CATEGORY = Messaging
VERSIONS = 1.3.5-36 1.4.0-37
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/6/6d/Messaging-iphone-style-no-avatar-1.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Elryon <elryon@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/213063-patch-request-messaging-app-like-iphones-11.html#post2037734