NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = SMS Prepend Fwd When Forwarding
DESCRIPTION = Adds a 'Fwd: ' to the beginning of a SMS Message when forwarding.
CATEGORY = Messaging
VERSIONS = 1.4.0-35 1.4.1-4
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/7/79/Messaging-sms-prepend-fwd-when-forwarding-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = opacityzero
HOMEPAGE = http://forums.precentral.net/webos-patches/239089-patch-pretends-fwd-when-forwarding-sms-message.html