NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Neato that URL
DESCRIPTION = Adds a 'Neato! it' option in the browser page menu to send the URL to your PC.Probably not compatible with a lot of other browser patches, I will be combining some just wanted to get this out there.You will need version 0.9.0 or higher of Neato!Make sure Neato! is already running before trying to Neato! a URL.Lastly thanks to @zhephree for providing a cross app api.
CATEGORY = Browser
VERSIONS = 1.4.5-131 2.1.0-4 2.1.1-22 2.1.2-31 2.2.0-116 2.2.3-110 2.2.4-27
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/7/74/Browser-neato-that-url-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Ben Fysh
HOMEPAGE = http://forums.precentral.net/webos-patches/268551-patch-neato-url.html