NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Reverse Lookup - Israel
DESCRIPTION = This patch enables the call-log to reverse lookup the number using 441il.com. based on James Harris White Pages reverse lookup patch and Marcel Meissel & johncc
CATEGORY = Phone
VERSIONS = 2.0.0-51 2.0.1-81 2.1.0-105 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Avner Arbel / palmpreacher <preacher@palmpreacher.com>
HOMEPAGE = www.palmpreacher.com
