NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Display UMTS and HSDPA Icons
DESCRIPTION = This patch will make your phone display a UMTS or HSDPA icon in place of the generic '3G' icon.
CATEGORY = Top Bar
VERSIONS = 1.4.5-101
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/b/b4/Top-bar-display-umts-and-hsdpa-icons-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Garrett92C <Garrett92C@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/268529-patch-display-umts-hsdpa-icons-top-bar.html
