NAME = $(shell basename ${PWD})
PATCH = /messaging/${NAME}.patch
TITLE = Force Send Offline
DESCRIPTION = This will enable the force sending while offline in the Messaging application.
CATEGORY = Messaging
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
