NAME = forcesendoffline
PATCH = /messaging/${NAME}.patch
TITLE = Force Send Offline
DESCRIPTION = Force send offline in messaging app
CATEGORY = Messaging
VERSION = 0.3.2
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
