NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TWEAKS =
TITLE = Disable Light Sensitive Dimming
DESCRIPTION = This patch prevents the screen brightness from increasing or decreasing based on how bright the environment is. If you choose maximum brightness, your screen will stay at maximum brightness.
CATEGORY = Screen Lock
VERSIONS = 2.1.0-203 2.2.0-75 2.2.3-69
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = errade, nightburn
HOMEPAGE =