NAME = $(shell basename $(shell pwd))
PATCH = camera/${NAME}.patch
TWEAKS =
TITLE = Volume Button Camera Trigger
DESCRIPTION = Use the volume buttons to take photos and videos in the Camera app. Vol+ for photos, Vol- for video. Vol- toggles video capture, so you don't have to hold the button down.
CATEGORY = Camera
VERSIONS = 3.0.5-47
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GMMan <yukaili.geek@gmail.com>
HOMEPAGE = http://forums.webosnation.com/webos-patches/319983-patch-volume-button-camera-trigger.html