#!/bin/sh

APPID=mobi.optware.screen

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

# Remove any legacy upstart script
if [ -f /etc/event.d/${APPID} ] ; then
  mount -o remount,rw /
  rm -f /etc/event.d/${APPID}
fi

# Symlink files into /opt
cd ${APPDIR}/opt
find bin etc libexec sbin var -type d -exec mkdir -p /opt/{} \;
find bin etc libexec sbin var -type f -exec ln -sf ${APPDIR}/opt/{} /opt/{} \;

/opt/bin/update-alternatives --install /opt/bin/screen screen /opt/bin/screen 80

mkdir -p /opt/etc/screen

exit 0
