#!/bin/sh

APPID=mobi.optware.screen

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

# Remove files from /opt
cd ${APPDIR}/opt
find bin share info  -depth -type f -exec rm -f /opt/{} \;
find bin share info  -depth -type d -exec rmdir /opt/{} \;

exit 0
