#!/bin/sh

PACKAGE=org.webosinternals.rmsslcerts

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
    IPKG_OFFLINE_ROOT=/media/cryptofs/apps
    mount -o remount,rw /
fi

# Move bad certs to a different directory
mkdir -p /etc/ssl/UNTRUSTED
mv /etc/ssl/certs/trustedcerts/DigiNotarRootCA_NL.pem /etc/ssl/UNTRUSTED
mv /etc/ssl/certs/trustedcerts/c0cafbd2.0 /etc/ssl/UNTRUSTED
chmod 000 /etc/ssl/UNTRUSTED/DigiNotarRootCA_NL.pem

#ipkg -o $IPKG_OFFLINE_ROOT remove $PACKAGE
exit 0
