NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Show Actual Battery Percent
DESCRIPTION = Shows the actual battery percent in the top bar rather than the gui percent mapping. Now compatible with other Battery Icon patches.
CATEGORY = Top Bar
VERSIONS = 1.2.1-17 1.3.1-1 1.3.5-1
ICON = http://www.webos-internals.org/images/3/35/Icon_WebOSInternals_Patches_Actualpercent.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/9/9a/Show-actual-battery-percent.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = a2ny <A2NY.Sinister@gmail.com>
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_webOS_Show_Actual_Battery_Percentage
