NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = Date As Carrier String No Year
DESCRIPTION = Replace the carrier string with the date (without the year).
CATEGORY = Top Bar
VERSIONS = 1.4.5-30 2.1.0-3 2.1.1-22 2.1.2-31 2.2.0-19 2.2.3-19 2.2.4-14
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/217215-patch-date-carrier-string-5.html#post2611293