NAME = readalldelall
PATCH = /email/${NAME}.patch
VERSION = 0.1.1
TITLE = read all del all patch
DESCRIPTION = ???
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
