NAME = readalldelall
PATCH = /email/${NAME}.patch
VERSION = 0.1.5
TITLE = read all del all patch
DESCRIPTION = ???
CATEGORY = Email
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
