NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = SMS Vibrate to Five Seconds
DESCRIPTION = Extends the vibrate time to Five seconds whenever you alerted for a SMS message.
CATEGORY = Messaging
VERSIONS = 1.4.0-36 1.4.1-5 1.4.2-1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = thenyboy
HOMEPAGE =
