NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = SMS Vibrate to Five Seconds
DESCRIPTION = Extends the vibrate time to Five seconds whenever you alerted for a SMS message.
CATEGORY = Messaging
VERSIONS = 1.4.5-176 2.1.0-30
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = thenyboy
HOMEPAGE =