#!/bin/sh

# Stop org.webosinternals.pdk
if [ -f /etc/event.d/org.webosinternals.pdk ]; then
    /sbin/stop org.webosinternals.pdk
fi

# Install the upstart script
rm -f /etc/event.d/org.webosinternals.pdk
mkdir -p /etc/event.d/
cp $IPKG_OFFLINE_ROOT/etc/event.d/org.webosinternals.pdk /etc/event.d/org.webosinternals.pdk

# Start org.webosinternals.pdk
/sbin/start org.webosinternals.pdk

exit 0
