NAME = min-brightness
PATCH = /screenlock/${NAME}.patch
TITLE = Reduce Minimum Brightness
DESCRIPTION = Reduces the minimum brightness to bare minimum
CATEGORY = Screen Lock
VERSION = 0.3.0
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
