NAME = min-brightness
PATCH = /screenlock/${NAME}.patch
TITLE = Reduce Minimum Brightness
DESCRIPTION = This will give the ability to lower the brightness of the backlight to the bare minimum. Changes minimum for "10" to "0". Maximum is still "100". Your current setting is not changed. You have to adjust it manually in the Screen & Lock application.
CATEGORY = Screen Lock
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS = 
META_VERSIOn = 1

include ../common.mk
include ../modifications.mk
