NAME = $(shell basename $(shell pwd))
PATCH = app-catalog/${NAME}.patch
TITLE = Show App Details
DESCRIPTION = Shows the version, release date, & file size in the app catalog which is normally hidden by default.
CATEGORY = App Catalog
VERSIONS = 1.4.5-139 2.0.0-39 2.0.1-66
ICON = http://www.webos-internals.org/images/0/03/Icon_WebOSInternals_Patches_Findapps.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/e/e0/App-catalog-show-app-details-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/226292-patch-show-app-details.html
