NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Open to Favorites
DESCRIPTION = This patch causes the phone app to always open up to the Favorites scene. It makes the Favorites scene the default back view for the Dialpad and CallLog scenes. It also makes it so that if you swipe back on the Favorites scene, the app will go into card view.
CATEGORY = Phone
VERSIONS = 2.1.0-30 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha <dropdeadbabies@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2905658#post2905658
