NAME = $(shell basename $(shell pwd))
PATCH = music-player/${NAME}.patch
TITLE = Banshee Linux Compat
DESCRIPTION = This will cause the Pre to be recognized as a media player when connected to a linux desktop running Banshee, Rythmbox, or any HAL-aware media player.
CATEGORY = Music Player
VERSIONS = 1.2.1-21 1.3.1-1
ICON = http://www.webos-internals.org/images/d/df/Icon_WebOSInternals_Patches_Musicplayer.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = VeeDubb65 <mail@stevecoonsphoto.com>
HOMEPAGE = http://forums.precentral.net/palm-pre/211284-make-pre-mp3-device-while-usb-mode-ubuntu.html
