NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = History Chat Balloon Color
DESCRIPTION = Change messaging app history view to show conversation balloon to be green if last message is from phone owner (outgoing) and to blue for others (incoming) to match chat view.
CATEGORY = Messaging
VERSIONS = 1.4.5-129 2.0.0-29 2.0.1-51 2.1.0-2 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/a/a8/Messaging-history-chat-balloon-color-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = blake0, CRaiaSoftware
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2373510
