NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Add to Paper Mache
DESCRIPTION = Adds a link to the 'Share' menu to save the current page to Paper Mache, an Instapaper client.  Also adds an entry to the hold menu for links to do the same, without opening the page first.
CATEGORY = Browser
VERSIONS = 3.0.2-56 3.0.4-12
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Ryan Watkins
HOMEPAGE = http://www.ryanwatkins.net/software/papermache/
