NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = No Battery Level
DESCRIPTION = Remove battery level from device menu.
CATEGORY = Top Bar
VERSIONS = 1.3.5-3 1.4.0-3 1.4.1-1 1.4.2-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = 
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = zhzyg <emailtodonald@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2050566#post2050566
