NAME = $(shell basename $(shell pwd))
PATCH = universal-search/${NAME}.patch
TITLE = No Fax Numbers In Search
DESCRIPTION = Stops Fax numbers from appearing in the universal search for a contact. Fax numbers will still appear in the main contacts application. This will work with Google synched contacts if you use 'Work Fax' or 'Home Fax', but no if you use a custom label with the word fax.
CATEGORY = Universal Search
VERSIONS = 1.4.5-122
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/2/2c/Universal-search-no-fax-numbers-in-search-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = CRaiaSoftware
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2830247#post2830247
