NAME = $(shell basename $(shell pwd))
PATCH = contacts/${NAME}.patch
TITLE = GSM-display-phone-numbers-as-synced
DESCRIPTION = This patch displays phone numbers in Contacts as they are synced, including spaces, dashes. comments etc. North American phone numbers are carefully formatted by a CDMA Pre, GSM model phone numbers are not.
CATEGORY = Contacts
VERSIONS = 1.4.5-1
ICON = http://www.webos-internals.org/images/c/ca/Icon_WebOSInternals_Patches_Contacts.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = DIck99999
HOMEPAGE = http://forums.precentral.net/webos-patches/222968-patch-gsm-display-phone-numbers-synced.html#post2132224
