NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Gesture Click Open In New Card
DESCRIPTION = Gesture-click a link to open it in a new card. Like middle-clicking a link in your browser :)
CATEGORY = Browser
VERSIONS = 1.4.1-28 1.4.2-13 1.4.5-26
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = bsiegel <brandon@smartercode.net>
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Browser_Gesture_Click_Open_in_New_Card