NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TITLE = Limited Emergency Button
DESCRIPTION = This will reduce the chance of accidentally calling 911. It removes the prepopulated number that appears in the dialpad once you select the Emergency Call button on the PIN screen, forcing the user to manually input the emergency number.
CATEGORY = Screen Lock
VERSIONS = 1.3.5-3 1.4.0-8 1.4.1-1 1.4.2-1
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/0/02/Screen-lock-limited-emergency-button-1.png\"]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Abyssul <Time4swim@gmail.com>, dBsooner
HOMEPAGE = http://forums.precentral.net/showthread.php?p=1982599
