NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Actual Words Instead Of Icons
DESCRIPTION = This replaces the icons with the actual words plus adds some extra shortcuts.<br/><br/>Gesture+(key)<br/>r: reply<br/>e: reply All<br/>f: forward<br/>d: delete
CATEGORY = Email
VERSIONS = 1.4.5-130 2.0.0-29 2.0.1-51 2.1.0-2 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/6/6c/Email-actual-words-instead-of-icons-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>, CRaiaSoftware
HOMEPAGE = http://forums.precentral.net/webos-patches/219517-patch-email-replace-icons-actual-words.html
