NAME = jump-one-word-at-a-time
PATCH = /messaging/${NAME}.patch
TITLE = Jump one word at a time
DESCRIPTION = Modifies messaging app to use jump backwards one word with sym+f, and jump forwards one word with sym+g
CATEGORY = Messaging
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png

include ../common.mk
include ../modifications.mk
