NAME = jump-one-word-at-a-time
PATCH = /messaging/${NAME}.patch
TITLE = Messaging Jump One Word
DESCRIPTION = This will modify the messaging app to use sym+f to jump backward one word and sym+g to jump forward one word. WebOS 1.2.0 enable OrangeKey(Option)+Swipe to move forward or backward in messaging, email, memos and other apps.
CATEGORY = Messaging
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png

include ../common.mk
include ../modifications.mk
