NAME = $(shell basename ${PWD})
PATCH = /messaging/${NAME}.patch
TITLE = Jump One Word at a Time
DESCRIPTION = This will modify the messaging app to use sym+f to jump backward one word and sym+g to jump forward one word. WebOS 1.2.0 enable OrangeKey(Option)+Swipe to move forward or backward in messaging, email, memos and other apps.
CATEGORY = Messaging
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_VERSION = 1

include ../common.mk
include ../modifications.mk
