NAME = $(shell basename $(shell pwd))
PATCH = video-player/${NAME}.patch
TITLE = Remove video pause on minimize
DESCRIPTION = This patch allows video content to continue playing when the screen is minimized, dimmed or off in WebOS 2.1
CATEGORY = Video Player
VERSIONS = 2.1.0-39 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Videoplayer.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = peterlemonjello
HOMEPAGE =
