NAME = $(shell basename $(shell pwd))
PATCH = camera/${NAME}.patch
TWEAKS =
TITLE = Improved CIMG Video Naming
DESCRIPTION = Will output videos from the camera in the format: CIMG_YYYY-MM-DD-hhmmss.mp4
CATEGORY = Camera
VERSIONS = 2.1.0-3 2.2.0-19
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE =