NAME = message-forwarding
PATCH = /messaging/${NAME}.patch
VERSION = 0.1.1
TITLE = Message Forwarding
DESCRIPTION = Adds forwarding capabilities to messaging app
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
