NAME = message-forwarding
PATCH = /messaging/${NAME}.patch
TITLE = Message Forwarding
DESCRIPTION = This will add the ability to forward messages in the Messaging application. Touch a message to use this feature.
CATEGORY = Messaging
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
