NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Mojo FPS Booster
DESCRIPTION = Increases Mojo's FPS to 60 in order to increase UI smoothness.
CATEGORY = Mojo
VERSIONS = 3.0.5-4
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ShiftyAxel <jpalmerwatkins@me.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/306180-patch-smartphone-touchpad-mojo-fps-booster-2-x-3-x.html