NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Default to Month View
DESCRIPTION = This will set the default view of the Calendar application to Month view.
CATEGORY = Calendar
VERSIONS = 1.2.1-0 1.1.3-0
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/b/b2/Default-to-month-view.png\"]
META_SUB_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk

MAINTAINER = matthewn <matthewn@alum.berkeley.edu>
