NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TWEAKS =
TITLE = Default to Month View
DESCRIPTION = This will set the default view of the Calendar application to Month view.
CATEGORY = Calendar
VERSIONS = 2.1.0-18 2.1.1-22 2.1.2-31 3.0.2-16 3.0.4-3 3.0.5-10
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 2

include ../common.mk

include ../modifications.mk

MAINTAINER = djgardn2, matthewn, NightHammer
HOMEPAGE = http://forums.precentral.net/webos-patches/291356-patch-touchpad-open-calendar-month-view.html