NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Default to Month View
DESCRIPTION = This will set the default view of the Calendar application to Month view.
CATEGORY = Calendar
VERSIONS = 1.3.5-3 1.4.0-3 1.4.1-1 1.4.2-1 1.4.5-1
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/b/b2/Default-to-month-view.png\"]
META_SUB_VERSION = 2

include ../common.mk
include ../modifications.mk

MAINTAINER = matthewn <webospatches@mahnamahna.net>
