#!/bin/sh

APPID=mobi.optware.openssl

# Remove files from /opt
rm -f /opt/lib/libcrypto.so /opt/lib/libcrypto.so.0
rm -f /opt/lib/libssl.so /opt/lib/libssl.so.0
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find bin lib share -depth -type f -exec rm -f /opt/{} \;
find bin lib share -depth -type d -exec rmdir /opt/{} \;

exit 0
