NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TWEAKS =
TITLE = Enyo Smooth Scrolling
DESCRIPTION = Eliminate the snap when first dragging Sliding Views, Toasts and Swipe-to-Delete items in Enyo apps. Does not effect WebView, because it is a compiled Mojo browser.
CATEGORY = Misc
VERSIONS = 3.0.5-17
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ShiftyAxel <jpalmerwatkins@me.com>
HOMEPAGE = http://forums.webosnation.com/webos-patches/311581-patch-touchpad-enyo-smooth-scrolling.html#post3296626