NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TWEAKS =
TITLE = Enyo Smooth Scrolling
DESCRIPTION = Work-in-progress patch to eliminate drag snapping throughout Enyo. Currently only affects multi-layer Sliding Panes (Email, Music). Single layer Panes (Browser Bookmarks, Maps popouts) are actually Toasts.
CATEGORY = Misc
VERSIONS = 3.0.5-16
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ShiftyAxel <jpalmerwatkins@me.com>
HOMEPAGE = http://forums.webosnation.com/webos-patches/311581-patch-touchpad-enyo-smooth-scrolling.html#post3296626