NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Call Vibration And 50sec Vibration
DESCRIPTION = When Call Connected The Phone Will vibration & When 50 second will vibration
CATEGORY = Phone
VERSIONS = 3.0.5-3
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = flatland <flatlandcn@gmail.com>
HOMEPAGE = http://bbs.zoopda.com/thread-97865-1-1.html
