NAME = $(shell basename $(shell pwd))
PATCH = camera/${NAME}.patch
TITLE = Improved Photo Naming PRE
DESCRIPTION = Will output images from the camera in the format: PRE_YYYY-MM-DD-hhmmss.jpg
CATEGORY = Camera
VERSIONS = 1.4.5-1 2.0.1-48 2.1.0-3
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/232987-3-patches-improved-camera-photo-filenames.html