NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Faster Card Animations HYPER Version
DESCRIPTION = Speeds up various timings related to how app cards and the launcher are animated.<br/><br/>Hyper version: The loading glow is 4x faster than normal speed.
CATEGORY = Mojo
VERSIONS = 2.0.0-29 2.0.1-51 2.1.0-2 3.0.0-1 3.0.2-5
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid, CRaiaSoftware
HOMEPAGE = http://forums.precentral.net/webos-patches/241665-patch-faster-card-animations.html