NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Faster Card Animations HYPER Version
DESCRIPTION = Speeds up various timings related to how app cards and the launcher are animated.<br/><br/>Hyper version: The loading glow is 4x faster than normal speed.
CATEGORY = Mojo
VERSIONS = 1.4.5-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/241665-patch-faster-card-animations.html
