NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TWEAKS =
TITLE = Agenda Exhibition Mode Background Image
DESCRIPTION = Enables you to change the Background for the Agenda Exhibition Mode App.After Patching the Agenda Exhibition App uses the following Picture as BG: Wallpapers/AgendaBG.png You need to restart Luna-Manager after changeing the Image File!Be sure the Image as 1024x768 Pixels
CATEGORY = Calendar
VERSIONS = 2.1.0-219 2.1.1-20 2.1.2-29 2.2.0-94 2.2.3-87 3.0.2-83 3.0.4-47
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Taurec <webos@hendrichs.de>
HOMEPAGE = http://webos.hendrichs.com