NAME = $(shell basename $(shell pwd))
PATCH = camera/${NAME}.patch
TWEAKS =
TITLE = Capture with Volume Keys
DESCRIPTION = This will add the ability to capture images with the volume keys in the camera applications.
CATEGORY = Camera
VERSIONS = 1.4.5-131 2.1.0-4 2.1.1-22 2.1.2-31 2.2.0-116 2.2.3-110 2.2.4-27
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = tk102
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Camera_Using_Volume_Buttons_to_Take_a_Picture