NAME = $(shell basename $(shell pwd))
PATCH = camera/${NAME}.patch
TITLE = Capture with Volume Keys
DESCRIPTION = This will add the ability to capture images with the volume keys in the camera applications.
CATEGORY = Camera
VERSIONS = 1.4.5-1
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = tk102 <zxcvbnm6012@yahoo.com>
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Camera_Using_Volume_Buttons_to_Take_a_Picture
