#!/bin/sh
# Copyright (c) 2009 Rod Whitby <rod@whitby.id.au>
# Copyright (c) 2009 Carl E. Thompson <devel-webos@carlthompson.net>
# Licensed GPLv2

PARENT=$(ps -o comm --no-heading -p $PPID)

#echo >> /tmp/ipkg-called
#echo "CMDLINE: $*" >> /tmp/ipkg-called
#echo "PARENT: $PARENT[$PPID]" >> /tmp/ipkg-called

if [ "$PARENT" = "LunaSysMgr" -a "$*" = "-o /var list" ] ; then
  exec /usr/bin/ipkg -o /var list_installed
else
  exec /usr/bin/ipkg "$@"
fi
