NAME = $(shell basename $(shell pwd))
PATCH = sounds-and-alerts/${NAME}.patch
TITLE = Increase volume back speaker media playback
DESCRIPTION = This will increase the volume of everything played through the back speaker other than phone calls. Requires a full power cycle or COMPLETE reboot after install.
CATEGORY = Sounds and Alerts
VERSIONS = 2.1.0-30 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Soundsandalerts.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = jc-Treo <jspamc@gmx.net>
HOMEPAGE =
