NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Disable Compressed View
DESCRIPTION = Disables the compressed view in the Calendar. (Compatible with Uber)
CATEGORY = Calendar
VERSIONS = 1.4.5-134 2.1.1-22 2.1.2-31 2.0.0-34 2.0.1-61 2.1.0-15
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = CRaiaSoftware
HOMEPAGE = http://forums.precentral.net/webos-patches/262971-patch-disable-compressed-view-calendar.html
