NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Notification Repeat
DESCRIPTION = This patch will repeat the email notification every two minutes until either dismissed or viewed.
CATEGORY = Email
VERSIONS = 1.2.1-26 1.3.1-14 1.3.5-11 1.4.0-2
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/d/df/Email-notification-repeat-1.jpg\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = lclarkjr <lclarkjr@gmail.com>, dBsooner <webos@dbsooner.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2024041#post2024041
