NAME = $(shell basename $(shell pwd))
PATCH = photos/${NAME}.patch
TWEAKS =
TITLE = 3rd party Photos synergy enabler
DESCRIPTION = This patch allows to utilize synergy photo service in TouchPad for 3rd party services.For developers. If you set serviceName property in your account template for PHOTO.UPLOAD capability then, with this patch webOS will read it and use that service for photo syncing process. For more info visit http://forums.precentral.net/hp-touchpad-homebrew/305758-patch-3rd-party-photo-synergy-enabler.html
CATEGORY = Photos
VERSIONS = 3.0.2-95 3.0.4-64 3.0.5-9
ICON = http://www.webos-internals.org/images/7/7d/Icon_WebOSInternals_Patches_Photos.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Dmitry V. Silaev aka Compvir <compvir@compvir.com>
HOMEPAGE = http://forums.precentral.net/hp-touchpad-homebrew/305758-patch-3rd-party-photo-synergy-enabler.html