#!/bin/sh

rm -f /etc/event.d/mobi.optware.openvpn
mkdir -p /etc/event.d/
cp $IPKG_OFFLINE_ROOT/etc/event.d/mobi.optware.openvpn /etc/event.d/mobi.optware.openvpn
/sbin/start mobi.optware.openvpn

exit 0
