#!/bin/sh

PACKAGE=org.webosinternals.ausmt-system-verify

if [ -z ${IPKG_OFFLINE_ROOT} ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
fi

/media/cryptofs/apps/usr/bin/ausmt-verify

ipkg -o ${IPKG_OFFLINE_ROOT} remove ${PACKAGE}

exit 0
