NAME = $(shell basename $(shell pwd))
PATCH = google-maps/${NAME}.patch
TITLE = Hebrew Google Maps
DESCRIPTION = Changes Google Maps defaults to Hebrew
CATEGORY = Google Maps
VERSIONS = 1.4.5-105 2.0.0-7 2.0.1-9
ICON = http://www.webos-internals.org/images/c/c3/Icon_WebOSInternals_Patches_SprintNav.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/4/4a/Google-maps-hebrew-google-maps-1.jpg\",\
\"http://www.webos-internals.org/images/f/ff/Google-maps-hebrew-google-maps-2.jpg\",\
\"http://www.webos-internals.org/images/8/8d/Google-maps-hebrew-google-maps-3.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Avner Arbel / palmpreacher <preacher@palmpreacher.com>
HOMEPAGE = www.palmpreacher.com