NAME = $(shell basename $(shell pwd))
PATCH = google-maps/${NAME}.patch
TITLE = Hebrew Google Maps
DESCRIPTION = Changes Google Maps defaults to hebrew
CATEGORY = Google Maps
VERSIONS = 1.4.5-12
ICON = http://www.webos-internals.org/images/c/c3/Icon_WebOSInternals_Patches_SprintNav.png
SCREENSHOTS = [ ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = palmpreacher <preacher@palmpreacher.com>
HOMEPAGE = www.palmpreacher.com
