NAME = $(shell basename $(shell pwd))
PATCH = google-maps/${NAME}.patch
TITLE = Hebrew Google Maps
DESCRIPTION = Changes Google Maps defaults to hebrew
CATEGORY = Google Maps
VERSIONS = 1.4.0-56 1.4.1-28 1.4.2-13 1.4.3-7 1.4.5-12
ICON = http://www.webos-internals.org/images/c/c3/Icon_WebOSInternals_Patches_SprintNav.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = palmpreacher <preacher@palmpreacher.com>
HOMEPAGE = www.palmpreacher.com