NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Hebrew support for physical keyboard PIXI
DESCRIPTION = Hebrew support for physical keyboard. double tap the Sym button to switch between English/Hebrew
CATEGORY = Mojo
VERSIONS = 1.4.5-167
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = @avnerarbel <preacher@palmpreacher.com>
HOMEPAGE = www.palmpreacher.com