NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = 4x4 Icons v1
DESCRIPTION = This will modify the App launcher to display 4x4 icons rather than 3x4. Does not word wrap.
CATEGORY = App Launcher
VERSIONS = 1.2.1-1 1.3.1-1 1.3.5-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/a/a8/Launcher-icons-4x4-jason.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Jason Robitaille
