NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Hide Amazon MP3 App
DESCRIPTION = This patch will hide the Amazon MP3 icon in the launcher.
CATEGORY = App Launcher
VERSIONS = 1.3.1-13 1.3.5-0
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = v3ritas (Sean McAdam) <CoiretFirinne@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2045728#post2045728