NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TWEAKS =
TITLE = Show Agenda from Exhibition
DESCRIPTION = Install this if your language is set to English.  Other languages selected this patch won't work.  This will bring out the Agenda mode from Exhibition to the launcher to be opened at will.  Opening this way also frees up landscape mode for Agenda.  This will not override Exhibition mode so Exhibition mode will come up normally if device is on the touchstone.
CATEGORY = App Launcher
VERSIONS = 2.1.0-78 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/c/c8/Other-show-agenda-from-exhibition-in-launcher-1.png\",\
\"http://www.webos-internals.org/images/8/8c/Other-show-agenda-from-exhibition-in-launcher-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = addiarmadar <addiarmadar@yahoo.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2943474#post2943474
