NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Enter Key for New Line
DESCRIPTION = This will cause the enter button to insert a newline instead of sending the message in the Messaging application.
CATEGORY = Messaging
VERSIONS = 2.0.0-29 2.0.1-51 2.1.0-33
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha <zxcvbnm6012@yahoo.com>, tk102, CRaiaSoftware
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2912866#post2912866