NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Enter Key for New Line
DESCRIPTION = This will cause the enter button to insert a newline instead of sending the message in the Messaging application.
CATEGORY = Messaging
VERSIONS = 2.0.0-29 2.0.1-51
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = tk102 <zxcvbnm6012@yahoo.com>, CRaiaSoftware
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Messaging_Change_%22Enter_Key%22_To_Create_Newline