NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Enter Key for New Line
DESCRIPTION = This will cause the enter button to insert a newline instead of sending the message in the Messaging application.
CATEGORY = Messaging
WEBOS_VERSION = 1.2.1
IPKG_VERSION = 0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk

MAINTAINER = jjvcuyler <jack@unixgeeks.biz>
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Messaging_Change_%22Enter_Key%22_To_Create_Newline
