NAME = $(shell basename $(shell pwd))
PATCH = sprintnav/${NAME}.patch
TITLE = Black Background Dark Blue Font
DESCRIPTION = This Patch will change the generic Background to Black and the font to Dark Blue.
CATEGORY = SprintNav
VERSIONS = 1.3.5-3 1.4.0-24 v1.4.1-1
ICON = http://www.webos-internals.org/images/c/c3/Icon_WebOSInternals_Patches_SprintNav.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/e/ef/Sprintnav-black-background-dark-blue-font-1.png\",\
\"http://www.webos-internals.org/images/9/94/Sprintnav-black-background-dark-blue-font-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = 2sslow <2sslow@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/216361-patch-black-background-sprintnav.html
