NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = No Arrows or Fade Bar
DESCRIPTION = This patch removes the arrow and fade bar behind it in the launcher.  Compatible with 4x4 and 5x4 patches.
CATEGORY = App Launcher
VERSIONS = 1.3.5-26 1.4.0-14 1.4.1-1 1.4.2-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/5/50/App-launcher-no-arrows-or-fade-bar-1.png\" ]
META_SUB_VERSION = 1 

include ../common.mk

include ../modifications.mk

MAINTAINER = cwgtex
HOMEPAGE = http://forums.precentral.net/webos-patches/230979-patch-no-arrows-fade-bar-launcher.html
