NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Disable Search Engine Browser Notifications
DESCRIPTION = Disables the notification and still adds the search engine to your just type history.
CATEGORY = Browser
VERSIONS = 3.0.2-56 3.0.4-12 3.0.5-4
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Abyssul <Time4swim@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/304935-patch-disable-type-add-search-engine-browser-notification.html#post3222834
