NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = smiley faces in symbol box
DESCRIPTION = Use the sym key and letter K (words) or Z (symbols) to bring up the built-in emoticons list.
CATEGORY = Messaging
VERSIONS = 1.4.5-42
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid warlord9159
HOMEPAGE = http://forums.precentral.net/showpost.php?p=2623043&postcount=82