NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = 15px Font with Bold Italics
DESCRIPTION = Decreases the font size to 15px and adds bold with italics in the chat balloons.
CATEGORY = Messaging
VERSIONS = 1.3.1-22 1.3.5-1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/1/1d/Messaging-15px-font-bold-italics-1.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/216337-patch-smaller-font-size-messaging-app.html
