NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = 15px Font with Bold Italics
DESCRIPTION = Decreases the font size to 15px and adds italics in the chat balloons. [Does not really add bold anymore ;)]
CATEGORY = Messaging
VERSIONS = 2.0.0-43 2.0.1-71 2.1.0-40 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/1/1d/Messaging-15px-font-bold-italics-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = fritos1406 <dse@webonastick.com>, dsevil
HOMEPAGE = http://forums.precentral.net/webos-patches/216337-patch-smaller-font-size-messaging-app.html
