NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TWEAKS =
TITLE = Move Pin Entry Done Button
DESCRIPTION = Move the 'Done' button from the bottom of the pin entry scene (where fingers can easily miss the button and hit the emergency call banner, instead) to the empty space next to the '0' button.
CATEGORY = Screen Lock
VERSIONS = 1.4.5-158
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mobusby
HOMEPAGE =