NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = No Draft Text
DESCRIPTION = Starting a reply message and then abandoning it (swipe back or exit) WebOS saves this message as a draft to remain when you go back to reply to the same contact to start where you left off. If this is anything but convenient, then this is the patch you're looking for.
CATEGORY = Messaging
VERSIONS = 1.4.0-35 1.4.1-4 1.4.2-1 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = opacityzero, xanthinealkaloid
HOMEPAGE =
