NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Wrap Pages
DESCRIPTION = Enables page wrapping for the launcher pages. Works for both switching between pages and moving apps from one page to another.
CATEGORY = App Launcher
VERSIONS = 1.2.1-25 1.3.1-13
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/6/69/App-launcher-wrap-pages-1.jpg\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = lclarkjr <lclarkjr@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2041630#post2041630
