NAME = $(shell basename $(shell pwd))
PATCH = google-maps/${NAME}.patch
TITLE = Latitude Workaround
DESCRIPTION = Allows you to use Latitude when in Google Maps via the app menu or gesture area + 'L'...Also, you can reload Google Maps to normal functionality by using the app menu or gesture area + 'R'...If you close Gmaps on Latitude, the patch will automatically clear the map the next time you open it to restore normal functionality.
CATEGORY = Google Maps
VERSIONS = 1.3.5-24
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/3/37/Google-maps-latitude-workaround-1.png\",\
\"http://www.webos-internals.org/images/7/79/Google-maps-latitude-workaround-2.png\",\
\"http://www.webos-internals.org/images/2/23/Google-maps-latitude-workaround-3.png\" ]
META_SUB_VERSION = 

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/229741-patch-google-latitude-workaround.html