NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Scrim Chat Balloon
DESCRIPTION = I have created this to help the people that don't feel comfortable using command line.<br/><br/>Here's how it works!<br/><br/>1)Create a folder in usb mode called 'scrims' without the quotes<br/>2)Place the chat balloons pics you want in the newly created scrims folder.<br/>3) make sure they are named:<br/>chat-balloon-left.png<br/>chat-balloon-right.png<br/><br/>Enjoy!
CATEGORY = Messaging
VERSIONS = 1.3.5-14 1.4.0-3 v1.4.1-1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = 2sslow
HOMEPAGE = http://forums.precentral.net/webos-patches/220840-patch-messaging-balloon-scrim.html
