NAME = $(shell basename $(shell pwd))
PATCH = music-player/${NAME}.patch
TITLE = Headset Track Advance Vibrate
DESCRIPTION = If your headset has a button, you can use a quick double-press to advance the track in the music player. This patch gives a long vibration (750ms) as feedback when you advance the track this way.
CATEGORY = Music Player
VERSIONS = 1.2.1-16 1.3.1-11 1.3.5-2 1.4.0-2
ICON = http://www.webos-internals.org/images/d/df/Icon_WebOSInternals_Patches_Musicplayer.png
SCREENSHOTS =
META_SUB_VERSION = 4

include ../common.mk
include ../modifications.mk

MAINTAINER = jhoff80, dBsooner <webos@dbsooner.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/211631-musicplayer-vibrate-headset-button-track-advance.html
