NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Gesture Tap for Info and Delete
DESCRIPTION = Gives the ability to use Gesture+tap on an icon in the launcher which will bring up a menu of info/delete
CATEGORY = App Launcher
VERSIONS = 1.3.5-9 1.4.0-3 v1.4.1-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/a/aa/App-launcher-gesture-tap-for-info-and-delete-1.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/218675-patch-gesture-tap-launcher.html
