NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Cycling Email Notifications
DESCRIPTION = This patch allows new mail notifications to automatically cycle to the next one so you can see the entire stack before dismissing the ones you don't care about.
CATEGORY = Email
VERSIONS = 3.0.5-50
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GMMan <yukaili.geek@gmail.com>
HOMEPAGE = http://forums.webosnation.com/touchpad-patches/320979-patch-cycling-email-notifications.html