NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Screen Lock
DESCRIPTION = You can lock browser screen via item 'lock screen' in context menu by the patch
CATEGORY = Browser
VERSIONS = 2.1.0-210 2.1.1-22 2.1.2-31 2.2.0-83 2.2.3-77
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Cloud.Qi <qz5747@yahoo.com.cn>
HOMEPAGE =
