NAME = $(shell basename $(shell pwd))
PATCH = photos/${NAME}.patch
TWEAKS =
TITLE = Immediately load high resolution
DESCRIPTION = Normally, it takes a few seconds until the app loads the high resolution version of a photo.<br/>This patch makes the app loading the high resolution version of a photo immediately.<br/><br/>A disadvantage is the high memory usage when viewing many pictures. (With a bit more patching there would be a way around this.)<br/><br/>Changelog:<br/>2011-08-23: Initial submission
CATEGORY = Photos
VERSIONS = 2.1.0-142
ICON = http://www.webos-internals.org/images/7/7d/Icon_WebOSInternals_Patches_Photos.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = pcworld <0188801@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/291520-patch-v0-0-1-immediately-load-high-resolution-webos-2-photos-app.html