NAME = $(shell basename $(shell pwd))
PATCH = photos/${NAME}.patch
TWEAKS =
TITLE = Immediately load high resolution
DESCRIPTION = Normally, it takes a few seconds until the app loads the high resolution version of a photo.This patch makes the app loading the high resolution version of a photo immediately.A disadvantage is the high memory usage when viewing many pictures. (With a bit more patching there would be a way around this.)Changelog:2011-08-23: Initial submission2012-01-04: Updated for webOS 2.2
CATEGORY = Photos
VERSIONS = 2.1.0-142 2.1.1-22 2.1.2-31 2.2.0-116 2.2.3-110 2.2.4-27
ICON = http://www.webos-internals.org/images/7/7d/Icon_WebOSInternals_Patches_Photos.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = pcworld <0188801@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/291520-patch-v0-0-1-immediately-load-high-resolution-webos-2-photos-app.html