NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Remove Engadget Nonsense Text
DESCRIPTION = Removes the nonsense text that flashes during scene transitions.
CATEGORY = Misc
VERSIONS =
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/234146-patch-remove-engadget-nonsense-text.html
