NAME = messaging-personal-avatar-left-side-v2
PATCH = messaging/messaging-personal-avatar-left-side-v2.patch
TITLE = Personal Avatar Left Side - V2
DESCRIPTION = This will enable a personal avatar centered on the left side of the conversation. This is to be used if you have 'Messaging in Landscape' patch installed. This also changes the location for the my-avatar.png to '/media/internal/my-avatar.png'. This allows you to change your avatar in USB mode. 
CATEGORY = Messaging
VERSION = 1.2.1-8
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/3/39/Messaging-personal-avatar-left-side-v2-1.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Elryon <elryon@hotmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/211028-personal-avatar-left-patch.html
