NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Fixed Keyboard Brightness 25
DESCRIPTION = Keeps the keyboard brightness at a fixed value of 25.
CATEGORY = Misc
VERSIONS = 1.4.5-140 2.0.0-40 2.0.1-67 2.1.0-30 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = webOSdealer
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2718111
