NAME = messaging-personal-avatar-left-side
PATCH = messaging/messaging-personal-avatar-left-side.patch
TITLE = Personal Avatar Left Side
DESCRIPTION = This will enable a personal avatar centered on the left side of the conversation. This also changes the location for the my-avatar.png to "/media/internal/my-avatar.png". This allows you to change your avatar in USB mode.
CATEGORY = Messaging
VERSIONS = 1.2.1-6
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/d/d0/Messaging-left-side-personal-avatar-1.png\"]
META_SUB_VERSION = 2

include ../common.mk
include ../modifications.mk

MAINTAINER = Elryon <elryon@hotmail.com>
HOMEPAGE =
