NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Personal Avatar Left Side
DESCRIPTION = This will enable a personal avatar centered on the left side of the conversation. This also changes the location for the my-avatar.png to '/media/internal/my-avatar.png'. This allows you to change your avatar in USB mode. This is also compatible for with messaging-enable-landscape patch.
CATEGORY = Messaging
VERSIONS = 1.4.5-1 2.1.0-11 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 2

include ../common.mk

include ../modifications.mk

MAINTAINER = Elryon <elryon@gmail.com>, dBsooner, Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/211028-personal-avatar-left-patch.html
