NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TWEAKS =
TITLE = UberCalendar Multilingual Localization
DESCRIPTION = Makes UberCalendar  patch display in your native language.<br/>Supported languages: Fr, De, Es.<br/><br/>Version 4-8: compatible with v4-8 of UberCalendar for WebOS v2.1.0.<br/>Thanks to the contributors:<br/>CptOx (Es), Pulp(De).<br/><br/>Be aware that the original UberCalendar  patch is required and must be installed.<br/>Credits for UberCalendar go to metaview, frantid, frause, xanthinealkaloid, lexb, Lclarkjr.
CATEGORY = Calendar
VERSIONS = 1.4.5-146 2.0.1-73 2.1.0-130
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Kratus
HOMEPAGE = http://forums.precentral.net/webos-patches/245177-ubercalendar-enhanced-calendar-patch.html