NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = UberCalendar Multilingual Localization
DESCRIPTION = Makes  UberCalendar  patch display in your native language.Version 34-6. Fully compatible with version 34-6 of UberCalendar. Supported languages:  Fr,De.Be aware that the original   UberCalendar   patch is required and must be installed.Credits for  UberCalendar  go to metaview, frause, xanthinealkaloid, lexb, Lclarkjr.
CATEGORY = Calendar
VERSIONS = 1.4.5-101
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/8/84/Calendar-ubercalendar-multilingual-localization-1.jpg\",\
\"http://www.webos-internals.org/images/6/6b/Calendar-ubercalendar-multilingual-localization-2.jpg\",\
\"http://www.webos-internals.org/images/c/c5/Calendar-ubercalendar-multilingual-localization-3.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Kratus
HOMEPAGE = http://forums.precentral.net/webos-patches/245177-ubercalendar-enhanced-calendar-patch.html