NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TWEAKS =
TITLE = UberCalendar Multilingual Localization
DESCRIPTION = Makes UberCalendar HD  patch display in your native language.Supported languages: Fr,De,Es,.Version 2-8: compatible with v2-8 of UberCalendar HD for WebOS v3.0.2.Thanks to the contributors:CptOx (Es), Pulp(De).Be aware that the original UberCalendar HD  patch is required and must be installed.Credits for UberCalendar HD go to metaview, frantid, frause, xanthinealkaloid, lexb, Lclarkjr.
CATEGORY = Calendar
VERSIONS = 1.4.5-146 2.1.0-130 3.0.2-47
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Kratus
HOMEPAGE = http://forums.precentral.net/webos-patches/245177-ubercalendar-enhanced-calendar-patch.html