NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = Add Select All
DESCRIPTION = Adds the 'Select All' option and gesture shortcut to the Messaging app.
CATEGORY = Messaging
VERSIONS = 1.4.5-188 2.1.0-227 2.1.1-34 2.1.2-42 2.2.0-104 2.2.3-98 2.2.4-13
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ProParkour, isagar2004
HOMEPAGE = http://forums.webosnation.com/webos-patches/308993-patch-messaging-add-select-all.html#post3268409