NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = Add Select All
DESCRIPTION = Add the Select All option to the menu and gesture shortcut to Messaging app.Tested on 2.1.0, may work on other versions.
CATEGORY = Messaging
VERSIONS = 1.4.5-187 2.1.0-226 2.1.1-33 2.1.2-41 2.2.0-103 2.2.3-97 2.2.4-12
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ProParkour
HOMEPAGE = http://forums.webosnation.com/webos-patches/308993-patch-messaging-add-select-all.html#post3268409