NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Fixed Keyboard Brightness 35
DESCRIPTION = Sets keyboard brightness to a fixed value of 35%.
CATEGORY = Misc
VERSIONS = 2.0.0-36 2.0.1-63 2.1.0-17 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <schlk21@gmail.com>, zinge
HOMEPAGE =
