NAME = $(shell basename $(shell pwd))
PATCH = /phone/${NAME}.patch
TITLE = No Alert During Call
DESCRIPTION = This will disable alerts during a call and re-enable them when you hang up.
CATEGORY = Phone
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
