NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = No Alert During Call
DESCRIPTION = This will disable alerts during a call and re-enable them when you hang up.
CATEGORY = Phone
VERSIONS = 1.2.1-2 1.3.1-20 1.3.5-3 1.4.0-3
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Ikyo <jody.r.owens@sprint.com>
