NAME = $(shell basename $(shell pwd))
PATCH = /phone/${NAME}.patch
TITLE = No Alert During Call
DESCRIPTION = This will disable alerts during a call and re-enable them when you hang up.
CATEGORY = Phone
WEBOS_VERSION = 1.2.1
IPKG_VERSION = 0
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk

MAINTAINER = Ikyo <jody.r.owens@sprint.com>
