NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Remove Send and Attach Buttons
DESCRIPTION = Removes The Send & Attach Buttons. Adds A Forward Gesture In Place For Send Button. Adds Gesture+p Shortcut To Attach Item.
CATEGORY = Messaging
VERSIONS = 1.3.5-26 1.4.0-26 1.4.1-6
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/e/ed/Messaging-remove-send-and-attach-buttons-1.png\",\
\"http://www.webos-internals.org/images/0/05/Messaging-remove-send-and-attach-buttons-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/231175-patch-remove-send-attach-button-messaging-app-requested.html