NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TWEAKS =
TITLE = Increase Touch Sensitivity - Legacy Devices
DESCRIPTION = This is a modified version of the Touch Sensitivity patch that has been modified for low RAM devices, ie: any device with 256mb of RAM. This includes the Pixi, Pixi Plus and the Pre Minus.
CATEGORY = Misc
VERSIONS = 1.4.5-180
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mau
HOMEPAGE =