NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Launch Calendar from invite email
DESCRIPTION = Click on the calendar icon in an invite email to launch Calendar, opened to the time of the meetings.
CATEGORY = Email
VERSIONS = 1.4.5-77
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/9/93/Email-launch-calendar-from-invite-email-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ahub <ahub@ahub-dev.com>
HOMEPAGE = www.ahub-dev.com
