NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TWEAKS =
TITLE = Add Music Player to Exhibition Mode German
DESCRIPTION = This patch adds the Standart Music Player App to Exhibition Mode to listen to music, if in Exhibition Mode. Other languages see Precentral Forum.!!!<br/><br/>It is only tested on German Device.<br/><br/>NO GUARANTEE FOR DAMAGES OR DATA LOOSES. YOU TAKE YOUR OWN RISK!!<br/><br/>For any wishes or infos, contact me
CATEGORY = App Launcher
VERSIONS = 2.1.0-81 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/6/6d/App-launcher-add-music-player-to-exhibition-mode-german-1.png\",\
\"http://www.webos-internals.org/images/3/3c/App-launcher-add-music-player-to-exhibition-mode-german-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = y2kadir <y2kadir@gmx.net>
HOMEPAGE = http://forums.precentral.net/webos-patches/281267-patch-add-music-player-exhibition-mode.html
