NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Disable Landscape Gesture Scroll
DESCRIPTION = Disable the scroll feature using the gesture area in landscape
CATEGORY = Browser
VERSIONS = 1.3.5-16 1.4.0-5
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/225090-patch-enable-disable-gesture-scroll-browser.html