NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Disable Landscape Gesture Scroll
DESCRIPTION = Disable the scroll feature using the gesture area in landscape
CATEGORY = Browser
VERSIONS = 1.4.5-131 2.1.0-224 2.1.1-31 2.1.2-39 2.2.0-101 2.2.3-95 2.2.4-9
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha, fritos1406
HOMEPAGE = http://forums.precentral.net/webos-patches/225090-patch-enable-disable-gesture-scroll-browser.html