NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Hide Quick Launch Bar in Launcher Only
DESCRIPTION = Hides the quick launch bar in the launcher only. The quick launch bar will still be displayed over the wallpaper 'home' screen.
CATEGORY = App Launcher
VERSIONS = 1.3.5-24 1.4.0-13 v1.4.1-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1 

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/216722-patch-hide-quick-launch-bar-launcher.html#post2059675
