NAME = messaging-sounds
PATCH = /messaging/${NAME}.patch
TITLE = messaging sounds patch
DESCRIPTION = ???
CATEGORY = Messaging
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
