NAME = $(shell basename ${PWD})
PATCH = /messaging/${NAME}.patch
TITLE = Message Tone Notifications
DESCRIPTION = Deprecated. Uninstall this and use SMS Tone per Contact. -- This will play a specified message tone for notifications.
CATEGORY = Messaging
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
