NAME = messaging-sounds
PATCH = /messaging/${NAME}.patch
VERSION = 0.1.0
TITLE = messaging sounds patch
DESCRIPTION = ???
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
