NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Adds 30 sec 1min to ExhibitionMode  Photo App
DESCRIPTION = Adds 30 seconds-1 minute to ExhibitionMode Photo App (Dock-Slideshow).
CATEGORY = Misc
VERSIONS = 2.1.0-35 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Warlord9159
HOMEPAGE = http://m.forums.precentral.net/webos-patches/278696-patch-adds-30-seconds-1-minute-exhibition-mode-photo-app.html
