NAME = $(shell basename $(shell pwd))
PATCH = /app-launcher/${NAME}.patch
TITLE = Hide Musicplayer App
DESCRIPTION = This will hide the Musicplayer application in the App Launcher.
CATEGORY = App Launcher
VERSION = 1.2.1-0
ICON = http://www.webos-internals.org/images/d/df/Icon_WebOSInternals_Patches_Musicplayer.png
SCREENSHOTS = 
META_VERSION = 1

include ../common.mk
include ../modifications.mk
