NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Hide Musicplayer App
DESCRIPTION = This will hide the Musicplayer application in the App Launcher.
CATEGORY = App Launcher
VERSIONS = 1.3.5-3 1.4.0-15 1.4.1-1 1.4.2-1 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = dBsooner, noir
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Launcher_Hide-Delete_The_NASCAR_App
