NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = No VPN
DESCRIPTION = Removes the VPN menu entry from the device menu.<br/><br/>(original code by Jason Robitaille)
CATEGORY = Top Bar
VERSIONS = 2.0.0-35 2.0.1-62 2.1.0-16 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = michote <reischuck.micha@googlemail.com>
HOMEPAGE =
