NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Toggle 3G in Device Menu
DESCRIPTION = Displays a submenu in device menu to switch network type between 2G, 3G or Auto
CATEGORY = Top Bar
VERSIONS = 1.3.5-21
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/3/31/Phone-toggle-3g-in-device-menu-1.png\" ]
META_SUB_VERSION = 1 

include ../common.mk

include ../modifications.mk

MAINTAINER = MetaView <metaview@web.de>
HOMEPAGE = http://forums.precentral.net/webos-patches/225494-switch-between-2g-3g-auto-device-menu.html