NAME = $(shell basename $(shell pwd))
PATCH = sounds-and-alerts/${NAME}.patch
TWEAKS =
TITLE = Charging Alert Sound Preference
DESCRIPTION = This patch adds a new preference to the Sounds & Ringtones application. The preference controls whether a sound should be played when a charger is connected to the device. The options available are 'Sound', 'Vibrate' & 'Mute'
CATEGORY = Sounds and Alerts
VERSIONS = 2.1.0-191 2.1.1-22 2.1.2-31 2.2.0-60 2.2.3-44
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Soundsandalerts.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sara.ramli
HOMEPAGE = http://forums.precentral.net/webos-patches/302772-patch-charging-alert-sound-preference.html
