NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = 4x4 icons v4 No Arrows Plus More
DESCRIPTION = This is my app launcher patch. I tinkered with the spacing and size to get it just how I like it, which is 4x4 with NO ARROWS AT THE BOTTOM. Only time arrows appear is if luna restarts with a notification (new text, charging, etc) or if there are more than 16 icons on a page.<br/><br/>I also added in the 'add/delete pages' patch and 'gesture tap for info/delete' patch, since they touch the same files.<br/><br/>I created this using Jason Robitaille's wonderful application UnifiedDiffCreator. All credit for patches goes to Rod Whitby, fritos1406, and whoever else helped figure everything out. Thanks again Jason for the UnifiedDiffCreator.
CATEGORY = App Launcher
VERSIONS = 1.3.5-21 1.4.0-10
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/d/d3/App-launcher-4x4-icons-v4-no-arrows-plus-more-1.png\",\
\"http://www.webos-internals.org/images/f/fb/App-launcher-4x4-icons-v4-no-arrows-plus-more-2.png\",\
\"http://www.webos-internals.org/images/0/0e/App-launcher-4x4-icons-v4-no-arrows-plus-more-3.png\" ]
META_SUB_VERSION = 

include ../common.mk

include ../modifications.mk

MAINTAINER = cwgtex
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2198138