NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TWEAKS =
TITLE = 4x4 icons v4 No Arrows Plus More
DESCRIPTION = This will modify the App launcher to display 4x4.  The size and spacing are just right, and there are no scroll arrows.  I also added in the 'add/delete pages' patch and 'gesture tap for info/delete' patch, since they touch the same files.
CATEGORY = App Launcher
VERSIONS = 1.4.5-166 2.1.0-141
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/d/d3/App-launcher-4x4-icons-v4-no-arrows-plus-more-1.png\",\
\"http://www.webos-internals.org/images/f/fb/App-launcher-4x4-icons-v4-no-arrows-plus-more-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = cwgtex
HOMEPAGE = http://forums.precentral.net/webos-patches/228607-patch-4x4-icons-no-arrows-extras.html