NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = 4x4 icons v4 No Arrows Plus More
DESCRIPTION = This is my app launcher patch. I tinkered with the spacing and size to get it just how I like it, which is 4x4 with NO ARROWS AT THE BOTTOM (for real this time). I also added in the 'add/delete pages' patch and 'gesture tap for info/delete' patch, since they touch the same files.
CATEGORY = App Launcher
VERSIONS = 1.3.5-23 1.4.0-12
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/d/d3/App-launcher-4x4-icons-v4-no-arrows-plus-more-1.png\",\
\"http://www.webos-internals.org/images/f/fb/App-launcher-4x4-icons-v4-no-arrows-plus-more-2.png\",\
\"http://www.webos-internals.org/images/0/0e/App-launcher-4x4-icons-v4-no-arrows-plus-more-3.png\" ]
META_SUB_VERSION = 

include ../common.mk

include ../modifications.mk

MAINTAINER = cwgtex
HOMEPAGE = http://forums.precentral.net/webos-patches/228607-patch-4x4-icons-no-arrows-extras.html