NAME = $(shell basename $(shell pwd))
PATCH = navigation/${NAME}.patch
TITLE = GPS Fix for VZ Navigator
DESCRIPTION = ** VERIZON USERS ONLY! ** REQUIRES VZ NAVIGATOR APP **<br/><br/>This patch allows VZ Navigator to be launched and then automatically closed forcing GPS functions to wake up. It is designed to be used in conjunction with the GPS Fix app that is currently in the Beta Channel (search PreCentral forums or tap on Homepage link).<br/><br/>Please refer to the forum thread and application itself for usage instructions.<br/><br/>Subscription to VZ Navigator is *NOT* required.<br/><br/>** Currently this is a Beta. Please help make this solution better by posting in the forum thread with your experiences.
CATEGORY = Navigation
VERSIONS = 1.4.0-66 1.4.1-38 1.4.2-23 1.4.3-17
ICON = http://www.webos-internals.org/images/c/c3/Icon_WebOSInternals_Patches_SprintNav.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/e/e1/Sprintnav-gps-fix-for-vz-navigator-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = spdsktr <erupnu@gmail.com>
HOMEPAGE = http://forums.precentral.net/web-os-development/255632-mini-app-request-periodically-pinging-vzw-gps-background.html