NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = GSM iDialPlan Pre Dialer Integration
DESCRIPTION = Integrates a dialplan created by iDialPlan in the Pre standard dialer. Numbers to be dialed are adapted on the fly depending on being abroad or at home. Needs the iDialPlan App for setup.
CATEGORY = Phone
VERSIONS = 1.3.5-37 1.4.0-38 1.4.1-7
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Itura
HOMEPAGE = http://forums.precentral.net/homebrew-apps/226937-idialplan-automatic-number-adjustment-international-calling-travelers.html#post2178249