#!/bin/sh

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

# Install the executable symlink
rm -f /usr/bin/opkg
ln -s $APPS/usr/bin/opkg /usr/bin/opkg

exit 0
