NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Enable Profile Creation - Activation Bypassed
DESCRIPTION = This patch will enable you to create/log in to a Palm Profile on an Activation Bypassed device.<br/><br/>This requires that you use the Palm Activation Bypass tool and then install this patch (as well as the 'Show First Use App' patch). Then open up the First Use app and you'll be able to create your profile or sign in to an existing profile.<br/><br/>Based on code from the webOS Internals website from the very, very early webOS days (1.1.0 and before).
CATEGORY = Other
VERSIONS = 1.4.5-110
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Arthur Thornton (arthurthornton on P|C)
HOMEPAGE = http://forums.precentral.net/webos-patches/269972-patch-enable-profile-creation-activation-bypassed-device-1-4-5-a.html
