NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = E-mail Portrait Only
DESCRIPTION = Gets rid of landscape orientation in the E-mail app.
CATEGORY = Email
VERSIONS = 2.1.0-229 2.1.1-36 2.1.2-44 2.2.0-107 2.2.3-101 2.2.4-17
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GuyFromNam <GuyFromNam@hotmail.com>
HOMEPAGE =