NAME = more-icons-per-row-4x4-1.2
PATCH = /luna/more_icons_per_row_4x4-1.2.patch
TITLE = 4x4 App Launcher
DESCRIPTION = Modify app launcher to display 4x4 icons rather than 3x4
CATEGORY = Luna

include ../common.mk
include ../modifications.mk
