NAME = more-icons-per-row-4x4-1.2
PATCH = /luna/more_icons_per_row_4x4-1.2.patch
TITLE = App Launcher 4x4
DESCRIPTION = This will modify the App launcher to display 4x4 icons rather than 3x4.
CATEGORY = App Launcher
VERSION = 0.4.1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png

include ../common.mk
include ../modifications.mk
