NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = Send Memo to Text Message
DESCRIPTION = This adds the option to Text Message the memo that you have open.
CATEGORY = Messaging
VERSIONS = 1.4.5-153 2.0.0-46 2.0.1-76 2.1.0-88 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/0/01/Other-send-memo-to-text-message-1.png\",\
\"http://www.webos-internals.org/images/a/aa/Other-send-memo-to-text-message-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Djgardn2
HOMEPAGE = http://forums.precentral.net/webos-patches/282152-patch-text-message-memo.html
