NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Toggle Keyboard Button
DESCRIPTION = This patch will add a button to the address bar (next to the bookmark button) that allows the keyboard to be toggled at will.
CATEGORY = Browser
VERSIONS = 3.0.2-92 3.0.4-61 3.0.5-4
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = knownboyofno <knownboyofno@gmail.com>, isagar2004
HOMEPAGE = http://forums.precentral.net/hp-touchpad-homebrew/307942-patch-toggle-keyboard-button-browser.html#post3255998