NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = SMS Vibrate to One and a Half Seconds
DESCRIPTION = Extends the vibrate time to one and a half seconds whenever you alerted for a SMS message.
CATEGORY = Messaging
VERSIONS = 1.4.5-176 2.1.0-30 2.1.1-22 2.1.2-31 2.2.0-62 2.2.3-56
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Abyssul <Time4swim@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2164165#post2164165
