NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = 15px fonts
DESCRIPTION = Decrease text font in the messaging app from 18px to 15px
CATEGORY = Messaging
VERSIONS = 2.2.0-70 2.2.3-62
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Alexis Toyane <alexistoyane@gmail.com>
HOMEPAGE =