NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = 15px fonts
DESCRIPTION = Decrease font size from 18px to 15px in the messaging app
CATEGORY = Messaging
VERSIONS = 1.4.5-178 2.1.1-22 2.1.2-31 2.1.0-201 2.2.0-73 2.2.3-65
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Alexis Toyane <alexistoyane@gmail.com>
HOMEPAGE =
