NAME = shutter-sound-on-off-button
PATCH = /camera/${NAME}.patch
TITLE = Add shutter sound on/off button
DESCRIPTION = Adds shutter sound on/off button to camera app
CATEGORY = Camera

include ../common.mk
include ../modifications.mk
