NAME = shutter-sound-on-off-button
PATCH = /camera/${NAME}.patch
TITLE = Add shutter sound on/off button
DESCRIPTION = Adds shutter sound on/off button to camera app
CATEGORY = Camera
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png

include ../common.mk
include ../modifications.mk
