NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Default to Show Bookmarks in Browser
DESCRIPTION = This will make the Bookmarks show by default instead of being closed.
CATEGORY = Browser
VERSIONS = 3.0.2-31 3.0.4-3
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Djgardn2
HOMEPAGE = http://forums.precentral.net/webos-patches/299292-patch-touchpad-default-show-bookmarks-browser.html
