NAME = $(shell basename $(shell pwd))
PATCH = sounds-and-alerts/${NAME}.patch
TITLE = Really Silent Ringer Switch Mute
DESCRIPTION = Flicking the ringer switch to off will mute every aspect of the webOS, music and games included.
CATEGORY = Sounds and Alerts
VERSIONS = 1.3.1-28 1.3.5-11
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Soundsandalerts.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/224587-patch-really-silent-ringer-switch.html