NAME = $(shell basename $(shell pwd))
PATCH = sounds-and-alerts/${NAME}.patch
TITLE = Really Silent Ringer Switch Mute
DESCRIPTION = Flicking the ringer switch to off will mute every aspect of the webOS, music and games included. Will not mute alarms nor the phone speaker (though will mute ringtone). If a wired or wireless headset/headphones are connected, mute will be canceled for music/games.
CATEGORY = Sounds and Alerts
VERSIONS = 1.3.5-14 1.4.0-69 1.4.1-42 1.4.2-28 1.4.3-22 1.4.5-28
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Soundsandalerts.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/224587-patch-really-silent-ringer-switch.html