NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TWEAKS =
TITLE = Buttah
DESCRIPTION = Formerly known as the Increase Touch Sensitivity And Smoothness 10 patch.This patch will increase the touch sensitivity and smooth the scrolling of WebOS. What this means is that scrolls and other behaviours will be more precise and smoother (which has been a critique of WebOS for a long time), giving the smooth visual appearance of some 'other' smartphone OSes out there. Basically it attempts to fix the jitteriness that WebOS sometimes displays when scrolling or loading elements/apps.This is intended to be a compromise between the 8px and 15px versions. Furthermore, this is the middle setting for the old 'Reduce Drag Radius' patches from webOS 1.4.5
CATEGORY = Misc
VERSIONS = 2.1.0-190 2.2.0-59 2.2.3-54 3.0.2-57 3.0.4-15
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = WebOS Internals
HOMEPAGE = http://forums.precentral.net/hp-touchpad/287848-my-hp-touchpad-seems-running-so-fast.html