NAME = contact-multitone
PATCH = /messaging/${NAME}.patch
VERSION = 0.1.4
TITLE = contact multitone patch
DESCRIPTION = ???
CATEGORY = Messaging
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
