NAME = contact-multitone
PATCH = /messaging/${NAME}.patch
VERSION = 0.1.2
TITLE = contact multitone patch
DESCRIPTION = ???
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
