NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Close Slider to End Calls
DESCRIPTION = This will allow you to end your phone calls by closing the slider on your Pre. Developed by KeyToss.com.
CATEGORY = Phone
VERSIONS = 1.2.1-6 1.3.1-12 1.3.5-3 1.4.0-3
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = 
META_SUB_VERSION = 2

include ../common.mk
include ../modifications.mk

MAINTAINER = KeyToss <info@keytoss.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/209950-phone-slider-patch.html
