NAME = $(shell basename $(shell pwd))
PATCH = advanced/${NAME}.patch
TITLE = Advanced System Prefs - Email Prefs (Veer)
DESCRIPTION = * Requires Advanced System Prefs Framework patch to function properly!<br/><br/>Adds per account notification configuration for email app. Also adds support for notification settings for emails received from unknown contacts.
CATEGORY = Advanced
VERSIONS = 2.1.0-150
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/e/e8/AdvancedSystemPrefsEmail_1.jpg\",\"http://www.webos-internals.org/images/c/cd/AdvancedSystemPrefsEmail_2.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = http://forums.precentral.net/enlightened-linux-solutions/269550-patch-advanced-system-prefs-2-x.html
