NAME = misc-powersave-smartreflex-600mhz
PATCH = misc/${NAME}.patch
TITLE = Powersave Smartreflex 600MHz
DESCRIPTION = This patch enables SmartReflex powersaving. It sets the max CPU speed to 600Mhz. If you want to change this, edit /etc/event.d/powersave-smartreflex. Make sure you reboot after applying this patch for it to take effect. WARNING: Do not apply the CPU Scaling patch if you use this patch. It will cause your webOS device to crash.
CATEGORY = Misc
VERSION = 1.3.1-17
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = 
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = jauderho
HOMEPAGE = http://forums.precentral.net/web-os-development/192181-stable-cpu-frequency-scaling-app-here.html
