NAME = $(shell basename $(shell pwd))
PATCH = /messaging/${NAME}.patch
TITLE = Compose to Email
DESCRIPTION = Adds email addresses of contacts to the list of available destinations in the Messaging application.
CATEGORY = Messaging
VERSION = 1.2.1-0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/5/5a/Compose-email.png\"]
META_VERSION = 1.2.1-0

include ../common.mk
include ../modifications.mk
