NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Compose to Email
DESCRIPTION = Adds email addresses of contacts to the list of available destinations in the Messaging application.
CATEGORY = Messaging
VERSIONS = 1.3.5-3 1.4.0-3 1.4.1-1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/5/5a/Compose-email.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = fritos1406
