NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TWEAKS =
TITLE = Screenlock Scrim
DESCRIPTION = This patch lets you choose a scrim for the Screenlock (pin or pswd). Save the image to /media/internal/.scrims/Screenlock-scrim.jpg
CATEGORY = Screen Lock
VERSIONS = 1.4.5-203
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = palmuse
HOMEPAGE = http://forums.webosnation.com/webos-patches/315839-patch-screenlock-wallpaper-1-4-5-a.html#post3331778