NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Allow Browser in Low Mem
DESCRIPTION = This patch will allow the web browser to startup in situations when you'd normally get the too many cards error.
CATEGORY = Browser
VERSIONS = 1.3.1-15 1.3.5-5 1.4.0-3
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = diomark <diomark@sbcglobal.net>, dBsooner 
HOMEPAGE =
