NAME = all-day-events-in-month-view
PATCH = /calendar/${NAME}.patch
TITLE = All-Day Events Month View
DESCRIPTION = Show all-day events in the calendar month view
CATEGORY = Calendar
VERSION = 0.1.16
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png

include ../common.mk
include ../modifications.mk
