NAME = all-day-events-in-month-view
PATCH = /calendar/${NAME}.patch
TITLE = All-Day Events Month View
DESCRIPTION = Show all-day events in the calendar month view
CATEGORY = Calendar

include ../common.mk
include ../modifications.mk
