NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Make It So
DESCRIPTION = Instead of Just type..., we Make it so...
CATEGORY = Mojo
VERSIONS = 2.1.0-110 2.1.1-22 2.1.2-31 2.2.0-10 2.2.3-10 2.2.4-5 3.0.2-15 3.0.4-14 3.0.5-4
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = webosinternals
HOMEPAGE =