NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Make It So
DESCRIPTION = Instead of Just type..., we get Make it so...
CATEGORY = Mojo
VERSIONS = 2.0.0-52 2.0.1-82 2.1.0-108 3.0.0-
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = webosinternals
HOMEPAGE =