NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Make It So
DESCRIPTION = Instead of Just type..., we get Make it so...
CATEGORY = Mojo
VERSIONS = 2.0.0-14 2.0.1-20
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = webosinternals
HOMEPAGE =