NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TWEAKS =
TITLE = Disable Captive Portal Notifications
DESCRIPTION = This patch disables the Captive Portal notifications while you roam from network to network with webOS 2.1., 2.2.4 It can become very frustrating. This patch simply disables the annoying alert.
CATEGORY = Notifications
VERSIONS = 2.1.0-30 2.1.1-22 2.1.2-31 2.2.4-46
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = thfcme <eric.hk.tsang@gmail.com>, tsangh
HOMEPAGE = http://forums.precentral.net/webos-patches/277304-patch-request-disable-captive-portal-detected-wifi-webos-2-1-a.html