NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TITLE = Disable Captive Portal Notifications
DESCRIPTION = This patch disables the Captive Portal notifications while you roam from network to network with webOS 2.1. It can become very frustrating. This patch simply disables the annoying alert.
CATEGORY = Notifications
VERSIONS = 2.0.0-40 2.0.1-67 2.1.0-30 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = thfcme <thfcme@hotmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/277304-patch-request-disable-captive-portal-detected-wifi-webos-2-1-a.html
