NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Email Save Confirmation
DESCRIPTION = Confirmation message to save an email.
CATEGORY = Email
VERSIONS = 1.4.1-5 1.4.2-1 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/9/9a/Email-email-save-confirmation-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =
