NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Show UMTS and HSDPA Icon
DESCRIPTION = This patch shows the UMTS and HSDPA Icon instead of 3G.
CATEGORY = Top Bar
VERSIONS = 2.0.1-45
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ART-ifact
HOMEPAGE =