NAME = $(shell basename $(shell pwd))
PATCH = other/${NAME}.patch
TITLE = Tweed Dark
DESCRIPTION = This patch allows the user to select the dark theme in the the preference section.
CATEGORY = Other
VERSIONS = 1.4.5-70
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/d/d1/Other-tweed-dark-1.png\",\
\"http://www.webos-internals.org/images/c/c5/Other-tweed-dark-2.png\",\
\"http://www.webos-internals.org/images/1/1c/Other-tweed-dark-3.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =
