NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Battery Icon and Vertical Percent
DESCRIPTION = This patch adds a clean vertical percentage to the right of the battery.
CATEGORY = Top Bar
VERSIONS = 1.4.5-13 2.0.0-21 2.0.1-30
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Vibol Hou <vibol@hou.cc>, webOS-Internals
HOMEPAGE =
