NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Hide Date While Screen Locked
DESCRIPTION = This patch will hide the date in the Top Bar while the screen is locked.
CATEGORY = Top Bar
VERSIONS = 1.4.5-101
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Garrett92C <Garrett92C@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/268541-patch-change-clock-display-when-phone-locked.html
