NAME = messagelandscape
PATCH = /messaging/${NAME}.patch
VERSION = 0.1.0
TITLE = Messaging Landscape
DESCRIPTION = Adds landscape mode for messaging app
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
