NAME = messagelandscape
PATCH = /messaging/${NAME}.patch
VERSION = 0.1.4
TITLE = obsolete Messaging Landscape
DESCRIPTION = ERROR not working for me, use message-orientation patch
CATEGORY = Messaging
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
