NAME = $(shell basename $(shell pwd))
PATCH = contacts/${NAME}.patch
TITLE = Per-Contact Call Rejection
DESCRIPTION = This patch will add the option to automatically reject calls on a per-contact basis. Calls can be rejected either by sending the call directly to voicemail, or with a quick answer and hangup.
CATEGORY = Contacts
VERSIONS = 1.4.1-16 1.4.5-1
ICON = http://www.webos-internals.org/images/c/ca/Icon_WebOSInternals_Patches_Contacts.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/8/86/Contacts-per-contact-call-rejection-1.png\",\
\"http://www.webos-internals.org/images/1/1d/Contacts-per-contact-call-rejection-2.png\",\
\"http://www.webos-internals.org/images/1/13/Contacts-per-contact-call-rejection-3.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = JackieRipper <jack@unixgeeks.biz>
HOMEPAGE =
