NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Enable Dialpad Vibration
DESCRIPTION = This will enable haptic feedback and silence the dialpad in the phone application.
CATEGORY = Phone
VERSIONS = 1.3.5-3 1.4.0-3 1.4.1-1 1.4.2-1 1.4.5-1
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = 
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = icederror
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_webOS_Turning_Off_Dialpad_Noise
