NAME = $(shell basename $(shell pwd))
PATCH = /phone/${NAME}.patch
TITLE = Enable Dialpad Vibration
DESCRIPTION = This will enable haptic feedback and silence the dialpad in the phone application.
CATEGORY = Phone
WEBOS_VERSION = 1.2.1
IPKG_VERSION = 0
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = 
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = icederror
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_webOS_Turning_Off_Dialpad_Noise
