NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Snooze Duration Selection
DESCRIPTION = Adds a snooze duration selection to the reminder notification.
CATEGORY = Calendar
VERSIONS = 1.3.5-4 1.4.0-52 1.4.1-24 1.4.2-9 1.4.3-3 1.4.5-8
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/2/2e/CalendarSnoozeDurationSelecton_1.png\",\
\"http://www.webos-internals.org/images/6/67/CalendarSnoozeDurationSelecton_2.png\" ]
META_SUB_VERSION = 3

include ../common.mk

include ../modifications.mk

MAINTAINER = lclarkjr
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2041492#post2041492