NAME = $(shell basename $(shell pwd))
PATCH = /phone/${NAME}.patch
TITLE = Call History During Call
DESCRIPTION = Adds ability to go into app menu and show the call history while you are on a call.
CATEGORY = Phone
VERSION = 1.2.1-0
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/2/20/Call-history-during-call.png\"]
META_VERSION = 1.2.1-0

include ../common.mk
include ../modifications.mk
