NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TITLE = Device Profile Service Override
DESCRIPTION = Allows the Impostah application to override the values returned by the com.palm.deviceprofile service.
CATEGORY = System
VERSIONS = 2.1.0-73 2.1.1-22 2.1.2-31 2.2.0-1 2.2.3-1 2.2.4-1 3.0.2-1 3.0.4-1 3.0.5-4
ICON = http://www.webos-internals.org/images/a/aa/Tux_Imposter.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = WebOS Internals
HOMEPAGE =
