NAME = $(shell basename $(shell pwd))
PATCH = clock/${NAME}.patch
TITLE = Clock Landscape Only
DESCRIPTION = This puts the clock in your stock clock app in landscape only, and hides the buttons on the clock scene. Now, tap-and-hold the screen to get to your alarms (which is still in free orientation) or get to preferences.
CATEGORY = Clock
VERSIONS = 1.4.5-120
ICON = http://www.webos-internals.org/images/8/8d/Icon_WebOSInternals_Patches_Clock.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/7/7e/Clock-clock-landscape-only-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = helidos, patricksmangan
HOMEPAGE = http://forums.precentral.net/webos-patches/268088-patch-clock-landscape-only.html
