NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Full Day View Calendar ALTERNATE
DESCRIPTION = Shrinks the day view and week view on the webos calendar so that (depending on the number of all day events) you can see most or all of the day on the calendar screen.
CATEGORY = Calendar
VERSIONS = 2.0.0-29 2.0.1-51 2.1.0-2 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/3/34/Calendar-full-day-view-calendar-alternate-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Lawren Quigley-Jones, CRaiaSoftware
HOMEPAGE = http://forums.precentral.net/webos-patches/275560-patch-webos-2-0-bucket-o-patches.html
