NAME = $(shell basename $(shell pwd))
PATCH = /browser/${NAME}.patch
TITLE = Swipe Delete History in Browser
DESCRIPTION = This will add the ability to swipe delete items in the browser history WITHOUT a confirmation dialog.
CATEGORY = Browser
VERSION = 1.2.1-0
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
