NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Unlimited Recipients
DESCRIPTION = This patch allows you to break the carrier messaging recipients limit. With this patch installed you'll be able to send messages to all the recipients you desire. Redone from original Mamouton's work.
CATEGORY = Messaging
VERSIONS = 1.4.0-27
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = deCorvett
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2288737