NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Ctrl and Enter for New Line
DESCRIPTION = Modifies the Messaging app so that pressing Ctrl+Enter produces a new line. The Ctrl button is the white or orange square button on the left side of the keyboard.<br/><br/>Just pressing enter will still send the message.
CATEGORY = Messaging
VERSIONS = 2.1.0-43
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha <dropdeadbabies@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/234990-request-enter-key-new-line-messaging-5.html#post2916778