NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = ImageView Hi-Res Zoom
DESCRIPTION = Lets you more fully zoom into large-size photos in any application that uses the Mojo ImageView widget, like slideshow apps Slide RSS and Slide Master.
CATEGORY = System
VERSIONS = 3.0.5-4
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = appsotutely <patches@appsotutely.com>
HOMEPAGE = http://forums.webosnation.com/webos-patches/309833-patch-mojo-imageview-hi-res-zoom-see-all-pixels-your-original-photo.html