NAME = $(shell basename $(shell pwd))
PATCH = contacts/${NAME}.patch
TITLE = Additional Contact Labels
DESCRIPTION = Added addtional contact labels to choose from when saving contacts.
CATEGORY = Contacts
VERSIONS = 1.4.0-35 1.4.1-4
ICON = http://www.webos-internals.org/images/c/ca/Icon_WebOSInternals_Patches_Contacts.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/b/ba/Contacts-additional-contact-labels-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =