NAME = $(shell basename $(shell pwd))
PATCH = sprintnav/${NAME}.patch
TITLE = Black Background Grey Font
DESCRIPTION = This Patch will change the background to black and the font to grey.
CATEGORY = SprintNav
VERSIONS = 1.3.1-22 1.3.5-1
ICON = http://www.webos-internals.org/images/c/c3/Icon_WebOSInternals_Patches_SprintNav.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/2/22/Sprintnav-black-background-grey-font-1.png\",\
\"http://www.webos-internals.org/images/9/9e/Sprintnav-black-background-grey-font-2.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = 2sslow
HOMEPAGE = http://forums.precentral.net/webos-patches/216361-patch-black-background-sprintnav.html
