NAME = $(shell basename $(shell pwd))
PATCH = clock/${NAME}.patch
TITLE = More Default Snooze Times
DESCRIPTION = Adds more snooze times to the Preferences page for the Clock app. (based on code by Palm Engineer Matt Hornyak)
CATEGORY = Clock
VERSIONS = 1.3.1-37 1.3.5-21 1.4.0-10
ICON = http://www.webos-internals.org/images/8/8d/Icon_WebOSInternals_Patches_Clock.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/4/4d/Clock-more-default-snooze-times-1.png\" ]
META_SUB_VERSION = 

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2207910#post2207910