NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Add to ReadOnTouch
DESCRIPTION = Adds an option to the 'Share' menu to send the current page to ReadOnTouch, a ReadItLater client. Also adds an entry to the hold menu for links to do the same.
CATEGORY = Browser
VERSIONS = 3.0.2-61 3.0.4-22 3.0.5-4
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Sven Ziegler <readontouch@sven-ziegler.com>
HOMEPAGE = http://sven-ziegler.com/wordpress/?page_id=17
