NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Call Reject
DESCRIPTION = This will auto reject any call from a number listed for the contact name: 'Do Not Answer' (no quotes though). The call will still show up in the call history, but no notification will happen.
CATEGORY = Phone
VERSIONS = 2.1.0-11
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 2

include ../common.mk

include ../modifications.mk

MAINTAINER = Elryon <elryon@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/211255-call-rejecter-patch.html
