#!/bin/sh

DISTRO=ubuntu-natty

NAME=xapp-xchat

APPID=org.webosinternals.${NAME}

APPS=/media/cryptofs/apps

CHROOT_NAME=ubuntu-natty-chroot

CHROOT_PATH=/media/ext3fs/${CHROOT_NAME}

XAPP_NAME=xchat

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

# Stop the service if running
/sbin/stop ${APPID} || true

# Remove the upstart script
rm -f /var/palm/event.d/${APPID}

# verify our shim is installed

if ! [ -e  ${CHROOT_PATH}/usr/sbin/xapps.sh ]

then
    echo 'xapps.sh not present'
    exit 1
fi

# remove our application
chroot ${CHROOT_PATH}/usr/sbin/xapps.sh remove ${XAPP_NAME}

if 'wc -l ${CHROOT_PATH}/var/log/xapps_error.log > 0'

then
    echo < ${CHROOT_PATH}/var/log/xapps_error.log
   exit 1
fi


# We intentionally do not remove the chroot contents.

exit 0
