NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Reduce Drag Radius 8px
DESCRIPTION = Sets Luna touch radius to 8px instead of 25px for dragging to be more responsive.
CATEGORY = Mojo
VERSIONS = 1.4.0-48 1.4.1-20 1.4.2-5 1.4.5-2
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Ryhor Burakou <ahsirg@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/249025-patch-reduce-drag-radius-10px.html