NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = Character Counter
DESCRIPTION = This will add a small dot in the top left corner of the text entry field in the Messaging application. It will keep track of how many characters have been entered. When nothing has been entered, the dot will not be visible.<br/><br/>Now includes support for all languages.
CATEGORY = Messaging
VERSIONS = 1.4.5-166 2.0.0-35 2.0.1-62 2.1.0-17
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/c/c4/Messaging_CharacterCounter.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha <dropdeadbabies@gmail.com>, HattCzech
HOMEPAGE = http://forums.precentral.net/webos-patches/221456-patch-messaging-character-counter.html