NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Character Counter
DESCRIPTION = This will add a small dot in the top left corner of the text entry field in the Messaging application. It will keep track of how many characters have been entered. When nothing has been entered, the dot will not be visible.
CATEGORY = Messaging
VERSIONS = 1.2.1-1 1.3.1-34 1.3.5-16 1.4.0-5
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/c/c4/Messaging_CharacterCounter.jpg\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = HattCzech
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Messaging_Character_Counter
