NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Show FirstUse App
DESCRIPTION = This patch will make the FirstUse App visible so you can run from the launcher. Comes in handy when you are switching phones back and forth and can't get the data service back on your WebOS phone that is already activated. Running first use should resolve the issue.
CATEGORY = App Launcher
VERSION = 1.3.1-20
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = jack87 <akop87@gmail.com>
HOMEPAGE = webos-internals.org
