NAME = $(shell basename $(shell pwd))
PATCH = pandora/${NAME}.patch
TITLE = Pandora Ad Fix
DESCRIPTION = Fixes empty advertisement box issue. This patch is not intended to disable ads! It will only keep Pandora from displaying the ad box in cases where the ads would not normally display properly (the 'empty ad box' issue).
CATEGORY = Pandora
VERSIONS = 1.3.5-24 v1.4.1-1
ICON = http://www.webos-internals.org/images/d/d1/Icon_WebOSInternals_Patches_Pandora.png
SCREENSHOTS =
META_SUB_VERSION = 1 

include ../common.mk

include ../modifications.mk

MAINTAINER = Vincent Law <patches@sorrowind.net>
HOMEPAGE = http://forums.precentral.net/webos-patches/228692-patch-pandora-ad-fix.html
