NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Enable Add/Delete Pages
DESCRIPTION = Adds the ability to add and remove launcher pages. Access these from the App Menu of the App Launcher.
CATEGORY = App Launcher
VERSIONS = 1.3.5-3 1.4.0-3 1.4.1-1 1.4.2-1 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/d/dc/Add_delete_pages_app_launcher.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Rod Whitby <rod@whitby.id.au>
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Launcher_Add_or_Delete_Pages
