NAME = phone-close-on-hangup
PATCH = phone/phone-close-on-hangup.patch
TITLE = Close on hangup
DESCRIPTION = This patch causes the Phone app to close automatically when all calls end, regardless of whether the last call was incoming or outgoing.
CATEGORY = Phone
VERSION = 1.2.1-10
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png	
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = dallashigh <karl@webosnerd.com>
HOMEPAGE =webosnerd.com
