NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Close on hangup
DESCRIPTION = This patch causes the Phone app to close automatically when all calls end, regardless of whether the last call was incoming or outgoing.
CATEGORY = Phone
VERSIONS = 1.2.1-10 1.3.1-10 1.3.5-1 1.4.0-1
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png	
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = dallashigh <karl@webosnerd.com>
HOMEPAGE =webosnerd.com
