NAME = $(shell basename $(shell pwd))
PATCH = universal-search/${NAME}.patch
TWEAKS =
TITLE = Change Just Type to launch Universe
DESCRIPTION = This patch changes Just Type to launch Universe when you click 'Open URL', 'Google', or any other Just Type thing. and should make Just Type only ever launch Universe.<br/>If you experience problems, please report in the forum.
CATEGORY = Universal Search
VERSIONS = 2.0.1-75 2.1.0-82 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = PatrickC <patrickappcreator@gmail.com>, NuttyBunny
HOMEPAGE = http://forums.precentral.net/webos-patches/281434-patch-change-just-type-launch-universe.html
