NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Add To Spare Time
DESCRIPTION = This patch will allow you to add the current URL in your browser to Spare Time (an Instapaper Client).
CATEGORY = Browser
VERSIONS = 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/4/4b/Browser-add-to-spare-time-1.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha <dropdeadbabies@gmail.com>, Darrin Holst
HOMEPAGE = http://semicolonapps.com
