NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Radio Always Off
DESCRIPTION = Keeps the phone radio always off. Handy for developers that use their devices without cellular connection.
CATEGORY = Phone
VERSIONS = 1.4.5-1 2.0.1-45 2.1.0-3
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/217213-patch-phone-always-offline.html