NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TWEAKS =
TITLE = More AppLauncher and QuickLaunch Bar Icons
DESCRIPTION = For TouchPad only! Enables Landscape/Portrait to have 9x6/7x8+ (56/54+) icons per App Launcher screen & up to 8/6 QuickLaunch Bar icons. Reduces App Launcher horizontal & vertical icon spacing and vertical icon-to-icon label. Lowers QuickLaunch Bar vertical height & icon positions. Raises QuickLaunch Launcher Button above QuickLaunch Bar so 8th/6th icon won't overlap it. Retains original icon dimensions displayed & App Launcher icon label font size. WARNING: BEFORE UNINSTALLING, HAVE 5 OR LESS QuickLaunch Bar icons!!! IF uninstalled with 6 or more icons... reinstall patch, remove extra icons & uninstall.
CATEGORY = App Launcher
VERSIONS = 3.0.5-30
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = WknThDg
HOMEPAGE = http://forums.webosnation.com/webos-patches/316679-patch-more-applauncher-quicklaunch-bar-icons-tp.html