NAME = $(shell basename $(shell pwd))
PATCH = /messaging/${NAME}.patch
TITLE = Timestamps - Clean
DESCRIPTION =  This will add timestamps to messages in the Messaging application. The format of the timestamps are MM/DD/YY 00:00 AM and are black with no spacing between them and the message.
CATEGORY = Messaging
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/8/88/Clean-timestamp.png\"]
META_VERSION = 0.5.0

include ../common.mk
include ../modifications.mk
