NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Hide Media Sync
DESCRIPTION = This will hide the 'Media Sync' option when you connect to a computer via USB.
CATEGORY = Mojo
VERSIONS = 1.2.1-8 1.3.1-1 1.3.5-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/c/c7/Mojo-hide-media-sync-1.png\"]
META_SUB_VERSION = 2

include ../common.mk
include ../modifications.mk

MAINTAINER = sottey, jhoff80
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Launcher_Hide_Media_Sync_Option
