NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS = browser/${NAME}.json
TITLE = Sharing Super Mix
DESCRIPTION = This patch is a combined version of various patches which allow you to share webpages through apps. It is based on work by Thomas Coe, fritos1406, @benyfish, and @semicolonapps.<br/><br/>Supports: Neato, Spare Time, Relego, ReKindleIt!, Facebook (Catalog/Beta), Bad Kitty, Spaz SpEd/Beta/Free, Twee, Tweed, Carbon (official), Quick Post, Tachyon<br/><br/>Adds gesture commands and separates Share Page into Share Via Email/SMS (SMS share auto-shortens URL).<br/><br/>Options shown are configured via the Tweaks application.<br/><br/>For more info on the various options, see the corresponding help in the Tweaks app.<br/><br/>Update: Fixed the stuff I broke the last update re:some options not working. Added Tachyon to supported apps.
CATEGORY = Browser
VERSIONS = 2.1.0-130
ICON = http://www.webos-internals.org/images/3/37/Icon_WebOSInternals_Patches_Plus_Browser.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/f/f1/Browser-sharing-super-mix-1.png\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha <dropdeadbabies@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/279817-patch-browser-sharing-super-mix-patch-2-1-0-a.html