NAME = $(shell basename $(shell pwd))
PATCH = /luna/${NAME}.patch
TITLE = Quiet powerd Messages
DESCRIPTION = This will silence the powerd messages. The powerd messages are the sleep/wake messages sent to ssh/terminal when the device sleeps or wakes.
CATEGORY = Luna
VERSION = 0.5.0
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
