NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Call Vibration
DESCRIPTION = When Call Connected The Phone Will vibration
CATEGORY = Phone
VERSIONS = 2.2.0-73 2.2.3-65 3.0.2-67 3.0.4-30
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = flatland <flatlandcn@gmail.com>
HOMEPAGE =
