NAME = $(shell basename $(shell pwd))
TITLE = Kernel (Opal)
DEVICE = opal
CATEGORY = Stable
VERSIONS = 3.0.3-1
APPINFO_DESCRIPTION = Stock webOS kernel, rebuilt from source.
DESCRIPTION = ${APPINFO_DESCRIPTION}<br>${KERNEL_DISCLAIMER}
APPINFO_CHANGELOG = [ \
{ "version" : "${WEBOS_VERSION}-1", "log" : [ "Initial public release" ] }, \
]
CHANGELOG = \
${WEBOS_VERSION}-1: Initial public release

TYPE = Kernel

include ../../support/kernel.mk
