NAME = contacttone
PATCH = /contacts/${NAME}.patch
VERSION = 0.1.1
TITLE = contact tone patch
DESCRIPTION = ???
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
