NAME = contacttone
PATCH = /contacts/${NAME}.patch
TITLE = Message Tone per Contact
DESCRIPTION = This will allow you to set a message tone for individual contacts. You will see the new option while adding or editing a contact.
CATEGORY = Contacts
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/c/ca/Icon_WebOSInternals_Patches_Contacts.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
