NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TWEAKS =
TITLE = Reminder Times Patch v2
DESCRIPTION = Adds additional reminder time options to calendar events.
CATEGORY = Calendar
VERSIONS = 1.4.5-18 2.1.0-179 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = 4wheels
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2533251#post2533251
