NAME = calendar-wrap-location-field
PATCH = calendar/calendar-wrap-location-field.patch
TITLE = Wrap Location Field
DESCRIPTION = This will let the Location field wrap onto multiple lines.
CATEGORY = Calendar
VERSION = 1.2.1-6
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS =
META_SUB_VERSION = 2

include ../common.mk
include ../modifications.mk

MAINTAINER = lordbah 
HOMEPAGE =
