NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Wrap Location Field
DESCRIPTION = This will let the Location field wrap onto multiple lines.
CATEGORY = Calendar
VERSIONS = 1.3.5-3 1.4.0-28
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS =
META_SUB_VERSION = 2

include ../common.mk

include ../modifications.mk

MAINTAINER = lordbah
HOMEPAGE =