NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Movable Voice Dial
DESCRIPTION = The name is misleading. This actually hides the voice dial icon. Hold down volume up/down to activate voice dial.
CATEGORY = Phone
VERSIONS = 2.1.0-23 2.2.0-17
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = codecrumb
HOMEPAGE =