NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Movable Voice Dial
DESCRIPTION = Make it so that you can move Voice Dial to a different launcher page
CATEGORY = Phone
VERSIONS = 2.1.0-22
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = codecrumb
HOMEPAGE =