NAME = bookmark
PATCH = /musicplayer/${NAME}.patch
VERSION = 0.1.3
TITLE = musicplayer patch
DESCRIPTION = ???
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
