NAME = bookmark
PATCH = /musicplayer/${NAME}.patch
TITLE = musicplayer patch
DESCRIPTION = ???
CATEGORY = Music Player
VERSION = 0.1.16
ICON = http://www.webos-internals.org/images/d/df/Icon_WebOSInternals_Patches_Musicplayer.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
