NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Additional Days for Syncing Mail
DESCRIPTION = Additional period of days/months to get email adds 2, 3, 6, 9 months and one year back.
CATEGORY = Email
VERSIONS = 1.3.1-27 1.3.5-10
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/e/e7/Email-additional-days-for-syncing-mail-1.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =
