NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Advanced Phone Menu
DESCRIPTION = A combination of the following patches: <br/>* Phone Radio Toggle <br/>* Data in Device Menu <br/>* Roam Only in Device Menu <br/><br/>With the following modifications: <br/>* All three patches are grouped under the Phone menu. <br/>* Roaming cycles: Auto -> Never -> Always -> Auto
CATEGORY = Top Bar
VERSIONS = 1.4.5-9
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/f/f6/Top-bar-advanced-phone-menu-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = asedeno
HOMEPAGE =
