NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TITLE = Enable LED Notifications German
DESCRIPTION = This will uncomment the code necessary for the gesture area to light up for notifications. You must still make sure LED Notifications is enabled in the Screen & Lock application.<br/><br/>This is for GERMAN devices only!
CATEGORY = Screen Lock
VERSIONS =
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS =
META_SUB_VERSION = 1 

include ../common.mk

include ../modifications.mk

MAINTAINER = hape <hanspeter@hp-jochmann.de>, jhoff80
HOMEPAGE =
