NAME = $(shell basename $(shell pwd))
PATCH = other/${NAME}.patch
TITLE = Fahrenheit Temperature in Device Info
DESCRIPTION = Adds the current battery temperature (in Fahrenheit) to the Device Info application.
CATEGORY = Other
VERSIONS = 1.4.0-33 1.4.1-2
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/238427-patch-temperature-device-info-2.html