NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = Add Skype Invisible Messaging Status
DESCRIPTION = Adds Skype Invisible Messaging Status. Does not work with GTalk. Other accounts; no clue.
CATEGORY = Messaging
VERSIONS = 2.2.4-54 3.0.5-25
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GuyFromNam <GuyFromNam@hotmail.com>
HOMEPAGE =