NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Better Finnish Support
DESCRIPTION = Modifies symbols table for faster Finnish typing and does couple other modifications to better support Finnish language/formats.
CATEGORY = Mojo
VERSIONS = 2.1.0-163 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = 
