NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TITLE = Standby Times Deluxe
DESCRIPTION = Adds 5, 10, 15, and 45 seconds; and 4, 5, 10, 15, 20, 25, and 30 minutes times to the screen turn off after setting in screen and lock.
CATEGORY = Screen Lock
VERSIONS = 1.3.5-39 1.4.0-42 1.4.1-12 1.4.2-1 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = StoneRyno
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2392024#post2392024
