NAME = vibrate-charging-alert-sound
PATCH = /luna/${NAME}.patch
TITLE = Charging Alert Vibrate Only
DESCRIPTION = This will change the charging alert sound to vibrate only.
CATEGORY = Sounds and Alerts
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Soundsandalerts.png

include ../common.mk
include ../modifications.mk
