NAME = vibrate-charging-alert-sound
PATCH = /luna/${NAME}.patch
TITLE = Vibrate only on charging alert
DESCRIPTION = Change the charging alert to vibrate only
CATEGORY = Luna

include ../common.mk
include ../modifications.mk
