NAME = vibrate-charging-alert-sound
PATCH = /luna/${NAME}.patch
TITLE = Vibrate only on charging alert
DESCRIPTION = Change the charging alert to vibrate only
CATEGORY = Luna
VERSION = 0.1.16

include ../common.mk
include ../modifications.mk
