NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = Media Indexer No-Index Locations
DESCRIPTION = This patch will allow you to set custom locations to exclude Media Indexer from searching. Once applied, any new files that match the paths you specify will not be added to the index. Please see webOS Nation thread for instructions to configure the patch.
CATEGORY = System
VERSIONS = 3.0.5-48
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GMMan <yukaili.geek@gmail.com>
HOMEPAGE = http://forums.webosnation.com/webos-patches/320657-patch-media-indexer-no-index-locations.html