NAME = swipe-delete-history-auto-confirm
PATCH = /browser/${NAME}.patch
TITLE = Swipe Delete History in Browser
DESCRIPTION = Adds ability to swipe delete items in the browser history WITHOUT confirmation dialog
CATEGORY = Browser
VERSION = 0.1.16
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
