NAME = swipe-delete-history-auto-confirm
PATCH = /browser/${NAME}.patch
TITLE = Swipe Delete History in Browser
DESCRIPTION = Adds ability to swipe delete items in the browser history WITHOUT confirmation dialog
CATEGORY = Browser
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
