NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Roam Only in Device Menu
DESCRIPTION = This will add a roam-only toggle to the device menu.
CATEGORY = Top Bar
VERSIONS = 1.4.5-1 2.0.1-45 2.1.0-3
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/0/04/Top-bar-roam-only-in-device-menu.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/212652-patch-request-roam-only-toggle-topbar.html