NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Multi Mod
DESCRIPTION = This will give the option to download or stream streamable files. It will also enable the display of the URL bar in landscape mode. Finally, it adds hotkeys for in-page navigation as shown below and adjusts them for right orientation, i.e the phone is on it's side with the keyboard out to the left.Keyboard navigation:Top of page = backspaceBottom of page = enter keyLine Up = sym keyPage Up = periodPage Down = space barLine Down = '@' keyAdjusted for right orientation:Line Up = '@' keyPage Up = space barPage Down = periodLine Down = sym key
CATEGORY = Browser
VERSIONS = 1.4.5-36 2.1.0-3 2.2.0-21 2.2.3-21
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/0/0d/Enable-browser-downloads-1.png\",\
\"http://www.webos-internals.org/images/0/02/Enable-browser-downloads-2.png\" ]
META_SUB_VERSION = 3

include ../common.mk

include ../modifications.mk

MAINTAINER = fritos1406, daventx, Mark Klein, drnull, Jason R.
HOMEPAGE = http://forums.precentral.net/web-os-development/206908-autopatch-browser-multi-patch.html