NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Multi Mod
DESCRIPTION = This will gives the option to download or stream streamable files. It will also enable the display of the URL bar in landscape mode. Finally, it adds hotkey for page up and page down.
CATEGORY = Browser
VERSION = 1.2.1-0
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/0/0d/Enable-browser-downloads-1.png\",\
\"http://www.webos-internals.org/images/0/02/Enable-browser-downloads-2.png\"]
META_VERSION = 1

#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk

MAINTAINER = Mark Klein <mdklein@gmail.com>, drnull <jdhatfield@gmail.com>, fritos1406, Jason Robitaille <robitaille88@gmail.com>
