NAME = $(shell basename $(shell pwd))
PATCH = advanced/${NAME}.patch
FILES = advanced/${NAME}.tar.gz
TITLE = Advanced System Menus - App Menu
DESCRIPTION = * Requires Advanced System Menus Framework patch to be installed to function properly!<br/><br/>Modifies app menu to be full width. This way it covers whole top bar preventing top bar menus pressed while app is in foreground. The background of the app menu is transparent so you can still see the top bar but can access the app menu by pressing anywhere on the top bar which makes it accessible more easily when using phone with one hand.<br/><br/>Depends: org.webosinternals.patches.top-bar-system-menu-initial-framework
CATEGORY = Advanced
VERSIONS = 2.1.0-59 2.1.1-22 2.1.2-31 2.2.0-2
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/5/57/AdvancedSystemMenusAppMenu.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = http://forums.precentral.net/enlightened-linux-solutions/269207-patch-advanced-system-menus-2-x.html
