NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Increase Font Size 17
DESCRIPTION = Increases the font of the top bar to size 17 for the carrier string, date/time, battery icon percent, and to size 16 for the app name when an app is open. It makes the clock much easier to read and uses up more of the available space.<br/><br/>NOTE: To display properly, this patch can be used with either the Battery Icon AS Percent or Battery Icon AND Percent patch.
CATEGORY = Top Bar
VERSIONS = 1.3.5-3 1.4.0-3 1.4.1-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/1/15/Top-bar-increase-top-bar-font-size---17-1.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = jmartino2011 <jmartino2011@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/216350-patch-increase-top-bar-font-size.html
