NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Save Attachments To Downloads Folder
DESCRIPTION = Will save email attachments to /media/internal/downloads/ for easier access
CATEGORY = Email
VERSIONS = 1.4.5-142
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/275782-patch-save-email-attachment-download-folder.html