#!/bin/sh

# Stop org.webosinternals.widk
if [ -f /etc/event.d/org.webosinternals.widk ]; then
    /sbin/stop org.webosinternals.widk
fi

# Remove the upstart script
rm -f /etc/event.d/org.webosinternals.widk

# Unmount /usr/local
umount /usr/local

exit 0
