NAME = $(shell basename $(shell pwd))
PATCH = youtube/${NAME}.patch
TITLE = Hyperlinks in Descripts
DESCRIPTION = Creates hyperlinks for text URLs in YouTube video descriptions.
CATEGORY = YouTube
VERSIONS = 1.4.5-1 2.0.1-45 2.1.0-3 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/8/8b/Icon_WebOSInternals_Patches_Youtube.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/212138-patch-hyperlinks-youtube-descriptions.html
