NAME = launcher-icons-4x4-jason
PATCH = /luna/${NAME}.patch
TITLE = App Launcher 4x4 Ver2
DESCRIPTION = This will modify the App launcher to display 4x4 icons rather than 3x4. Does not word wrap.
CATEGORY = App Launcher
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
