NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = Temperature for Device Menu Megamix
DESCRIPTION = Will add a temperature value on the right side of the phone row of the Device Menu Megamix.
CATEGORY = Top Bar
VERSIONS = 1.4.5-126 2.1.0-3 2.2.0-19 2.2.3-19
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/245717-temperature-device-menu-megamix.html