NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Scrim Translucent
DESCRIPTION = Well I finally got it figured out!<br/><br/>1) install my updated statusbar-scrim.patch (thanks mracer29)<br/>2) create a folder on the usb portion of your pre called scrims (if you already have this folder skip this step)<br/>3) put a copy of your wallpaper in the scrims folder and rename it to statusbar-scrim.png (full size 320x480)<br/><br/>Thats it!
CATEGORY = Top Bar
VERSIONS = 1.3.1-35 1.3.5-18 1.4.0-7
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/a/a9/Top-bar-scrim-translucent-1.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = 2sslow
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2173810#post2173810