NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TWEAKS =
TITLE = Unhide Dev Mode Icon
DESCRIPTION = This will show the Developer Mode Icon in the App Launcher.
CATEGORY = App Launcher
VERSIONS = 3.0.5-3
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/0/09/Enable-dev-mode-icon.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = codecrumb
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Launcher_Unhide_the_DeveloperMode_App