NAME = $(shell basename $(shell pwd))
PATCH = tasks/${NAME}.patch
TWEAKS =
TITLE = Disable Tasks Notifications
DESCRIPTION = This just kills any notification of tasks.
CATEGORY = Tasks
VERSIONS = 2.2.4-63
ICON = http://www.webos-internals.org/images/8/83/Icon_WebOSInternals_Patches_Tasks.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GuyFromNam <GuyFromNam@hotmail.com>
HOMEPAGE = http://twitter.com/GuyFromNam