NAME = add-delete-pages-in-the-launcher
PATCH = applauncher/${NAME}.patch
TITLE = Add/Delete Pages in Launcher
DESCRIPTION = Adds the ability to add and remove launcher pages. Access these from the App Menu of the App Launcher.
CATEGORY = App Launcher
VERSION = 0.4.1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/d/dc/Add_delete_pages_app_launcher.png\"]
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
