NAME = add-delete-pages-in-the-launcher
PATCH = applauncher/${NAME}.patch
TITLE = Add/Delete Pages in App Launcher
DESCRIPTION = Add and Remove pages from the app menu in the App Launcher
CATEGORY = App Launcher
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
