NAME = add-delete-pages-in-the-launcher
PATCH = applauncher/${NAME}.patch
TITLE = Add/Delete Pages in App Launcher
DESCRIPTION = Add and Remove pages from the app menu in the App Launcher
CATEGORY = App Launcher
VERSION = 0.1.16
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
