NAME = $(shell basename ${PWD})
PATCH = /email/${NAME}.patch
TITLE = Replies/Forwards Black Font
DESCRIPTION = This will change the font color for replies and forwards to black instead of navy blue.
CATEGORY = Email
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/0/06/Replies-forwards-black.png\"]
META_VERSION = 1

include ../common.mk
include ../modifications.mk
