NAME = replies-forwards-black
PATCH = /email/${NAME}.patch
TITLE = Replies/Forwards black font
DESCRIPTION = Changes font for replies/forwards to black instead of navy blue
CATEGORY = Email

include ../common.mk
include ../modifications.mk
