NAME = $(shell basename $(shell pwd))
PATCH = /luna/${NAME}.patch
TITLE = Battery Icon as Percent
DESCRIPTION = This will replace the battery icon in the top bar with a color-coded percent number. Charging = Teal. 100%-70% = Green. 69%-45% = Yellow. = 44%-20% = Orange. 19%-0% = Red.
CATEGORY = Luna
VERSION = 0.5.0
ICON = 
SCREENSHOTS = [\"http://www.webos-internals.org/images/7/76/Battery-percent.png\"]
META_VERSION = 1

include ../common.mk
include ../modifications.mk
