NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = Binary Bluetooth Patch
DESCRIPTION = This is a Bluetooth patch to enable the binary encoding format for communications. It was created for a Lego Mindstorms project and is backward compatible.
CATEGORY = System
VERSIONS = 3.0.2-73 3.0.4-36 3.0.5-17
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = bluetoothPatch <bluetoothpatch@googlemail.com>
HOMEPAGE =