#!/bin/sh

APPID=mobi.optware.readline

# Remove files from /opt
rm -f /opt/lib/libhistory.so /opt/lib/libhistory.so.6 /opt/lib/libreadline.so /opt/lib/libreadline.so.6
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find lib -depth -type f -exec rm -f /opt/{} \;
find lib -depth -type d -exec rmdir /opt/{} \;

exit 0
