NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Hold CHat To Launch New Card
DESCRIPTION = This adds the feature to hold on a chat and will launch in a new card, will launch a new only if u hold. while still keeping the tap to view in same card as well. (Buggy since 1.3.5, Will Need to Use Advance Gesture For The 1st Card Not To Move To The Chat)
CATEGORY = Messaging
VERSIONS = 1.3.5-12 1.4.0-3 1.4.1-1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/220092-patch-hold-chat-launch-new-card.html
