NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TWEAKS = notifications/${NAME}.json
TITLE = Bluetooth watch - SE MBW-150
DESCRIPTION = This patch uses MetaViews App 'MW150' to report Calls, Mail, Messaging and MP3 Tags (build in player) to the SonyEricsson bluetooth watch MBW-150 or MBW-200 and display it in its Display. Features can be en-/disabled via tweaks. MP3 tag patch by HaPe!
CATEGORY = Notifications
VERSIONS = 2.2.0-96 2.2.3-89 2.2.4-
ICON = http://www.webos-internals.org/images/f/f1/Icon_WebOSInternals_Patch_Plus.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mgmft <marcel@meissel.com>
HOMEPAGE = http://forums.webosnation.com/webos-homebrew-apps/308451-mw150-connect-your-sonyericsson-mbw150-bluetooth-watch.html