NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = 26px font
DESCRIPTION = Increase font size for messaging compose and chat to 26px
CATEGORY = Messaging
VERSIONS = 1.4.5-200 2.1.0-253 2.1.1-59 2.1.2-68 2.2.4-56
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = johncc
HOMEPAGE = http://forums.webosnation.com/palm-pixi-pixi-plus/314265-need-enlarge-fonts-text-messages.html