NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Change number of bookmarks to 24
DESCRIPTION = Changes the maximum number of bookmark tiles in the browser start page from 12 to 24
CATEGORY = Browser
VERSIONS = 2.0.0-24 2.0.1-37
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Pastorrich1
HOMEPAGE =
