NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Mobilize page with instapaper
DESCRIPTION = This patch add a new option in Menu -> Page->Mobilize to send the current page to instapaper mobilizer.
CATEGORY = Browser
VERSIONS = 2.1.0-255 2.1.1-60 2.1.2-70 2.2.4-61
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = gimco <gimcoo@gmail.com>
HOMEPAGE =