NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Smaller Bookmarks Icons
DESCRIPTION = Changes the Browser Bookmarks Icons to 61x60 In size.<br/>Old Icons size was 90x120.<br/>With this patch, the icons fit in the page and<br/>you can see 9 web bookmarks.
CATEGORY = Browser
VERSIONS = 1.4.5-113
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/b/b5/Browser-smaller-bookmarks-icons-1.png\",\
\"http://www.webos-internals.org/images/a/a9/Browser-smaller-bookmarks-icons-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Warlord9159
HOMEPAGE = http://m.forums.precentral.net/webos-patches/270501-patch-smaller-size-bookmark-icons.html
