NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Add additional default event length times
DESCRIPTION = adds zero (0), 15 minutes, four (4) hour, and eight (8) hour options in the default event length preference
CATEGORY = Calendar
VERSIONS = 1.4.0-66 1.4.1-38 1.4.2-23 1.4.3-17 1.4.5-22
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/1/11/Calendar-add-additional-default-event-length-times-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = aric <aaakins@gmail.com>
HOMEPAGE =