NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = System Menu Initial Framework
DESCRIPTION = Adds support for having two new system menus called status and today menus in addition to already existing application and device menus. Status menu is placed into left corner of top bar and the today menu in the center of top bar.<br/><br/>NOTE: this patch itself don't add those new menus it only layouts the groundwork to allow other patches to create these menus.
CATEGORY = Top Bar
VERSIONS = 1.4.0-39
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = http://forums.precentral.net/homebrew-apps/224544-mode-switcher.html