NAME = default-to-month-view
PATCH = calendar/${NAME}.patch
VERSION = 0.1.3
TITLE = Month View as default
DESCRIPTION = Set the calendar to default to month view
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
