NAME = default-to-month-view
PATCH = calendar/${NAME}.patch
TITLE = Month View as default
DESCRIPTION = Set the calendar to default to month view
CATEGORY = Calendar
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
