NAME = default-to-month-view
PATCH = calendar/${NAME}.patch
TITLE = Calendar Month View Default
DESCRIPTION = This will set the default view of the Calendar application to Month view.
CATEGORY = Calendar
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/b/b2/Default-to-month-view.png\"]
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
