NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Auto Show Dialpad for Outgoing Calls Only
DESCRIPTION = Automatically shows the dialpad only when an outgoing call is connected rather than the contact pic, except when the dialing string has a pause or wait after which the dialpad will be shown.
CATEGORY = Phone
VERSIONS = 1.4.1-13 1.4.2-1 1.4.5-1
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2378780#post2378780
