NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Swipe For Prev And Next Emails Reversed
DESCRIPTION = Swipe left and right in the message body to see previous and next emails. Useful for people that find it hard to use the little arrows.<br/><br/>This swipes right to left for next email and left to right for previous email.
CATEGORY = Email
VERSIONS = 1.4.5-41
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = egaudet
HOMEPAGE =
