NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = Neato My Messages
DESCRIPTION = if you have Neato installed, when you receive text messages, they'll be neato'd to your PC. You also have an option of toggling this on/off by setting the Yes/No.
CATEGORY = Messaging
VERSIONS = 1.4.5-162 2.1.0-99
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/5/52/Messaging-neato-my-messages-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Inglorious Apps <0188801@gmail.com>
HOMEPAGE = www.IngloriousApps.com