#!/bin/sh

APPID=org.webosinternals.fonts.liberation-mono

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

cd /usr/share/fonts; ln -s ${APPDIR}/* .

exit 0
