NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Poor Mans Twitter Client for Bad Kitty
DESCRIPTION = Modified version of Poor Mans Twitter Client. Opens Twitter profiles in Bad Kitty. You must have Bad Kitty 1.2 or higher installed for this patch to work correctly.
CATEGORY = Messaging
VERSIONS = 1.4.5-97
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Thomas Coe <thomascoe1@gmail.com>
HOMEPAGE =
