NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Week Numbers
DESCRIPTION = Adds ISO 8601 week numbers in the header of day, week and month view of the calendar.
CATEGORY = Calendar
VERSIONS = 2.0.0-23 2.0.1-35
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/7/7d/Calendar-week-numbers-1.png\",\
\"http://www.webos-internals.org/images/9/93/Calendar-week-numbers-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Franz Rühmland <frause@stealthberry.org>
HOMEPAGE = http://m.forums.precentral.net/webos-patches/269163-patch-week-numbers-calendar.html
