NAME = hide-musicplayer-app
PATCH = /musicplayer/${NAME}.patch
TITLE = Hide musicplayer app
DESCRIPTION = Hides the musicplayer app from the launcher
CATEGORY = Music Player
VERSION = 0.2.9
ICON = http://www.webos-internals.org/images/d/df/Icon_WebOSInternals_Patches_Musicplayer.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
