NAME = hide-musicplayer-app
PATCH = /musicplayer/${NAME}.patch
TITLE = Hide musicplayer app
DESCRIPTION = Hides the musicplayer app from the launcher
CATEGORY = Musicplayer
VERSION = 0.2.8
ICON = 
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
