NAME = hide-musicplayer-app
PATCH = /musicplayer/${NAME}.patch
TITLE = Hide Musicplayer App
DESCRIPTION = This will hide the Musicplayer application in the App Launcher.
CATEGORY = App Launcher
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/d/df/Icon_WebOSInternals_Patches_Musicplayer.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
