NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Date As Carrier String With Time While Locked
DESCRIPTION = Thanks to Jason Robitaille for Date As Carrier String - great patch!  This patch just has the minor change of showing the time in the top bar while the screen is locked. This is useful when a call is incoming and you want to know to answer or not based on what time it is (which isn't normally shown while an incoming call is ringing with the screen locked.)
CATEGORY = Top Bar
VERSIONS = 1.4.1-16
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Chris Mann <csmann19@gmail.com>, Jason Robitaille
HOMEPAGE =