NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Make Isis Web the default web browser
DESCRIPTION = Based on the Advanced Browser patch. Sets Isis Web as the default web browser instead of the stock web browser.
CATEGORY = Browser
VERSIONS = 3.0.2-105 3.0.4-79 3.0.5-51
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Heimen Stoffels / Vistaus <vistausss@gmail.com>
HOMEPAGE = http://forums.webosnation.com/open-webos-general-discussion/320759-release-isis-web.html