NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS = browser/${NAME}.json
TITLE = Browser Power Swipe
DESCRIPTION = Adds left/right power swipe support for going back/forward. Swipe direction can be inverted in Tweaks.
CATEGORY = Browser
VERSIONS = 3.0.2-24
ICON = http://www.webos-internals.org/images/3/37/Icon_WebOSInternals_Patches_Plus_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GyroJoe
HOMEPAGE = http://forums.precentral.net/webos-patches/291466-patch-request-two-finger-multitouch-swipe-back.html