NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Pin to HuaBan
DESCRIPTION = Add Pin This to HuaBan choice to context menu on browser (based on Pinterest Patch)
CATEGORY = Browser
VERSIONS = 3.0.4-69 3.0.5-20
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = 911boy <support@talign.com>
HOMEPAGE =