NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = Click Duration
DESCRIPTION = Quicker clicks in web browser. (Reduces DoubleClickDuration from 300 to 100ms in luna.conf, probably collides with many other patches)
CATEGORY = System
VERSIONS = 1.4.5-204
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = wiwa
HOMEPAGE =