NAME = music-player-ignore-a-an-the
PATCH = music-player/music-player-ignore-a-an-the.patch
TITLE = Ignore A, An, The
DESCRIPTION = "Removes \"A\", \"An\" and \"The\" from the beginning of Artists and Albums so everything sorts properly."
CATEGORY = Music Player
VERSION = 1.2.1-8
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/d/d9/Music-player-ignore-a-an-the-1.png\",\
\"http://www.webos-internals.org/images/1/11/Music-player-ignore-a-an-the-2.png\",\
\"http://www.webos-internals.org/images/9/97/Music-player-ignore-a-an-the-3.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = jhoff80, hopspitfire
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_MediaPlayer_Ignore_%27A%27%2C_%27An%27%2C_and_%27The%27_In_Artist_and_Album_names
