NAME = $(shell basename $(shell pwd))
PATCH = music-player/${NAME}.patch
TITLE = Ignore A, An, The
DESCRIPTION = Removes 'A', 'An' and 'The' from the beginning of Artists and Albums so everything sorts properly.
CATEGORY = Music Player
VERSIONS = 1.3.5-3 1.4.0-3 v1.4.1-1
ICON = http://www.webos-internals.org/images/d/df/Icon_WebOSInternals_Patches_Musicplayer.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/d/d9/Music-player-ignore-a-an-the-1.png\",\
\"http://www.webos-internals.org/images/1/11/Music-player-ignore-a-an-the-2.png\",\
\"http://www.webos-internals.org/images/9/97/Music-player-ignore-a-an-the-3.png\"]
META_SUB_VERSION = 3

include ../common.mk
include ../modifications.mk

MAINTAINER = jhoff80, hopspitfire
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_MediaPlayer_Ignore_%27A%27%2C_%27An%27%2C_and_%27The%27_In_Artist_and_Album_names
