NAME = $(shell basename $(shell pwd))
PATCH = contacts/${NAME}.patch
TWEAKS =
TITLE = Search Contacts in PinYin - Veer
DESCRIPTION = You can now search contacts in PinYin initial of each Chinese character. non-chinese is not affected and still searchable as it used to be. PinYin framework patch is required for this patch to work. A device restart is required. Remove or disable your account and add it back again to re-index pinyin after first installation.
CATEGORY = Contacts
VERSIONS = 2.1.0-213
ICON = http://www.webos-internals.org/images/c/ca/Icon_WebOSInternals_Patches_Contacts.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = moo <moo.tinys@gmail.com>
HOMEPAGE = http://www.treo8.com/bbs/thread-275013-1-1.html