NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Message Signature
DESCRIPTION = Adds customizable signature to outgoing text messages which can be changed in the Preferences & Accounts page.
CATEGORY = Messaging
VERSIONS = 1.4.1-5
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/a/ac/Messaging-message-signature-1.png\",\
\"http://www.webos-internals.org/images/f/f9/Messaging-message-signature-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/238919-patch-text-message-signature.html#post2342128