NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Message Signature
DESCRIPTION = Adds customizable greeting and/or signature to outgoing text messages which can be changed via the Preferences & Accounts page.<br/><br/><br/>Note: The greeting could be used to enter a delivery confirmation string for those who have carriers which support that sort of thing.
CATEGORY = Messaging
VERSIONS = 1.4.1-8
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/a/ac/Messaging-message-signature-1.png\",\
\"http://www.webos-internals.org/images/f/f9/Messaging-message-signature-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/238919-patch-text-message-signature.html#post2342128