NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = User Agent Override - iPad
DESCRIPTION = This patch changes your Touchpad's user agent to make it look like an iPad.
CATEGORY = Browser
VERSIONS = 3.0.2-104 3.0.4-78 3.0.5-49
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Choorp Studios <Choorp@gmail.com>
HOMEPAGE = http://forums.webosnation.com/webos-patches/317911-patch-user-agent-override.html