NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Big CallerID Yellow Size 30
DESCRIPTION = Display a BIG callerID readable without glaces. Also enlarges info in case of unlisted numbers, names and locations. Displayed on top of the photo area.
CATEGORY = Phone
VERSIONS = 1.4.5-172 2.1.0-30 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/9/96/Phone-big-callerid-yellow-size-30-1.png\",\
\"http://www.webos-internals.org/images/6/61/Phone-big-callerid-yellow-size-30-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Dick99999
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2349029#post2349029
