NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Big CallerID Yellow Size 30
DESCRIPTION = Big callerID readable without glaces. V  0.904 enlarges unlisted numbers too. Big callerID or unlisted number are now positioned at the bottom of the photo area.
CATEGORY = Phone
VERSIONS = 1.4.0-39 1.4.1-8
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/2/2d/Phone-big-callerid-yellow-size-30-1.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Dick99999
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2349029#post2349029