NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Big CallerID Yellow Size 30
DESCRIPTION = Large font size CallerID readable without glaces. At some expense of the photo, which shifts a little downwards.
CATEGORY = Phone
VERSIONS = 1.4.0-38 1.4.1-7
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/2/2d/Phone-big-callerid-yellow-size-30-1.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Dick99999
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2349029#post2349029