NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Add Open URL Menu Option
DESCRIPTION = Gives the option of 'Open URL' in the context menu.
CATEGORY = Browser
VERSIONS = 1.3.5-12 1.4.0-3 v1.4.1-1
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/8/8e/Browser-add-open-url-menu-option-1.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/220867-patch-option-open-url-context-menu.html
