#!/bin/sh

APPID=mobi.optware.openssh-sftp-server

# Remove files from /opt
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find libexec -depth -type f -exec rm -f /opt/{} \;
find libexec -depth -type d -exec rmdir /opt/{} \;
