#!/bin/sh

APPID=mobi.optware.nginx

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

/sbin/stop ${APPID}

rm -f /var/palm/event.d/${APPID}

# Remove files from /opt
cd ${APPDIR}/opt
find etc lib sbin var -depth -type f -exec rm -f /opt/{} \;
find etc lib sbin var -depth -type d -exec rmdir /opt/{} \;

# We intentionally do not remove the /media/internal/www/ content.

exit 0
