NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Hide NFL App
DESCRIPTION = This will hide the NFL application in the App Launcher.
CATEGORY = App Launcher
VERSIONS = 1.2.1-0 1.3.1-10 1.3.5-0
ICON = http://www.webos-internals.org/images/8/80/Icon_WebOSInternals_Patches_Nfl.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = noir
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Launcher_Hide-Delete_The_NASCAR_App
