#!/bin/sh

APPID=mobi.optware.openssh

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

# Remove any legacy upstart script
if [ -f /etc/event.d/${APPID} ] ; then
  mount -o remount,rw /
  rm -f /etc/event.d/${APPID}
fi

# Symlink files into /opt
cd ${APPDIR}/opt
find bin etc libexec sbin var -type d -exec mkdir -p /opt/{} \;
find bin etc libexec sbin var -type f -exec ln -sf ${APPDIR}/opt/{} /opt/{} \;

/opt/bin/update-alternatives --install /opt/bin/scp scp /opt/bin/openssh-scp 80
/opt/bin/update-alternatives --install /opt/bin/ssh ssh /opt/bin/openssh-ssh 80

mkdir -p /opt/etc/openssh

# Check for the SSH1 RSA key
if [ ! -f /opt/etc/openssh/ssh_host_key ]; then
    echo Generating RSA Key...
    /opt/bin/ssh-keygen -t rsa1 -f /opt/etc/openssh/ssh_host_key -C '' -N ''
fi

# Check for the SSH2 RSA key
if [ ! -f /opt/etc/openssh/ssh_host_rsa_key ]; then
    echo Generating RSA Key...
    /opt/bin/ssh-keygen -t rsa -f /opt/etc/openssh/ssh_host_rsa_key -C '' -N ''
fi

# Check for the SSH2 DSA key
if [ ! -f /opt/etc/openssh/ssh_host_dsa_key ]; then
    echo Generating DSA Key...
    /opt/bin/ssh-keygen -t dsa -f /opt/etc/openssh/ssh_host_dsa_key -C '' -N ''
fi

# The emulator already has an ssh server running, so no need to start another.
if [ "`uname -m`" != "i686" ]; then
    rm -f /var/palm/event.d/${APPID}
    mkdir -p /var/palm/event.d/
    cp ${APPDIR}/upstart/${APPID} /var/palm/event.d/${APPID}
    /sbin/start ${APPID}
fi

exit 0
