NAME = $(shell basename $(shell pwd))
PATCH = video-player/${NAME}.patch
TWEAKS =
TITLE = No video pause when minimized
DESCRIPTION = This patch disables the video pause when minimized or screen dimmed/off.
CATEGORY = Video Player
VERSIONS = 2.2.0-103 2.2.3-97 2.2.4-12
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Videoplayer.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = pastorrich1, isagar2004
HOMEPAGE = http://forums.webosnation.com/webos-patches/308890-patch-disable-video-pause-when-minimized-webos-2-2-x.html