NAME = $(shell basename $(shell pwd))
PATCH = video-player/${NAME}.patch
TITLE = No video pause when minimized
DESCRIPTION = This patch allows video content to continue playing when the screen is minimized, dimmed or off in WebOS 2.0.1
CATEGORY = Video Player
VERSIONS = 2.0.0-24 2.0.1-37
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Videoplayer.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = pastorrich1
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2805889#post2805889
