NAME = $(shell basename $(shell pwd))
PATCH = app-catalog/${NAME}.patch
TITLE = Show Download Count
DESCRIPTION = This will enable the viewing of the download count of packages in the 'Palm App Catalog'.
CATEGORY = App Catalog
VERSIONS = 1.4.5-139 2.0.0-39 2.0.1-66
ICON = http://www.webos-internals.org/images/0/03/Icon_WebOSInternals_Patches_Findapps.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = dBsooner, PreGame
HOMEPAGE =
