NAME = app-catalog-show-download-count
PATCH = app-catalog/app-catalog-show-download-count.patch
TITLE = Show Download Count
DESCRIPTION = "This will enable the viewing of the download count of packages in the \"Palm App Catalog\"."
CATEGORY = App Catalog
VERSION = 1.2.1-8
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png	
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = PreGame
HOMEPAGE =
