NAME = $(shell basename $(shell pwd))
PATCH = app-catalog/${NAME}.patch
TITLE = Show Download Count
DESCRIPTION = This will enable the viewing of the download count of packages in the 'Palm App Catalog'.
CATEGORY = App Catalog
VERSIONS = 1.3.5-4 1.4.0-20 1.4.1-1
ICON = http://www.webos-internals.org/images/0/03/Icon_WebOSInternals_Patches_Findapps.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = dBsooner, PreGame
HOMEPAGE =
