NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Add Shortcut Keys
DESCRIPTION = This will create the following shortcut keys: New Card: Gesture+nAdd Bookmark: Gesture+mAdd To Launcher: Gesture+lBookmarks: Gesture+bHistory: Gesture+hShare Page: Gesture+sRefresh: Gesture+rMay conflict with other patches that alter the browser menu.
CATEGORY = Browser
VERSIONS = 2.1.1-22 2.1.2-31 2.2.4-45
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha, fritos1406, Herrie
HOMEPAGE = http://forums.precentral.net/webos-patches/219788-patch-shortcut-browser-keys.html