NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Add Shortcut Keys
DESCRIPTION = This will create the following shortcut keys: <br/><br/>New Card: Gesture+n<br/>Add Bookmark: Gesture+m<br/>Add To Launcher: Gesture+l<br/>Bookmarks: Gesture+b<br/>History: Gesture+h<br/>Share Page: Gesture+s<br/>Refresh: Gesture+r<br/><br/>May conflict with other patches that alter the browser menu.
CATEGORY = Browser
VERSIONS = 2.1.0-56 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha, fritos1406
HOMEPAGE = http://forums.precentral.net/webos-patches/219788-patch-shortcut-browser-keys.html
