NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = New Event Icons and Shortcuts
DESCRIPTION = Here's how it works:<br/><br/>   1. The left button is for a new timed event, and the right button is for a new all day event, also showing in each view, i.e. day, week, and month.<br/>   2. The commands are also available in the menu of each view.<br/>   3. The commands are also available via shortcuts, gesture+n for a new timed event & gesture+d for an all day event.<br/>   4. A new event pushed from the week or month view will be created to whatever day you were in last, like a back gesture would take you back to the last day viewed.
CATEGORY = Calendar
VERSIONS = 1.4.0-35 1.4.1-4
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/b/b7/Calendar-new-event-icons-and-shortcuts-1.png\",\
\"http://www.webos-internals.org/images/9/9c/Calendar-new-event-icons-and-shortcuts-2.png\",\
\"http://www.webos-internals.org/images/b/bf/Calendar-new-event-icons-and-shortcuts-3.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2346207#post2346207