NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Replace EVDO Icon with 4G Icon
DESCRIPTION = As with all my scrim patches you will need to place some files in a folder named scrims on your usb drive of your Pre:<br/><br/>You can put whatever image you want here as long as its 17x18 and named correctly:<br/><br/>network-evdo-active.png<br/>network-evdo-dormant.png<br/><br/>Go to the official post url to download a zip of premade images or you can use your own creation.
CATEGORY = Top Bar
VERSIONS = 1.3.1-32 1.3.5-15 1.4.0-4
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/b/b3/Top-bar-replace-evdo-icon-with-4g-icon-1.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = 2sslow
HOMEPAGE = http://forums.precentral.net/webos-patches/225629-patch-evdo-4g.html