NAME = disable-charging-alert-sound
PATCH = /luna/${NAME}.patch
VERSION = 0.1.4
TITLE = Disable Charging Alert Sound
DESCRIPTION = Disables the charging alert sound
CATEGORY = Luna
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
