NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = URL Shorten in Browser
DESCRIPTION = Adds a URL Shorten option to the browser's app menu under 'Page'. An is.gd link for the page you are on will be copied to the clipboard.
CATEGORY = Browser
VERSIONS = 1.4.5-97
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/b/b9/Browser-url-shorten-in-browser-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Thomas Coe <thomascoe1@gmail.com>, Jeremy Thomas
HOMEPAGE =
