NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Mojo Smooth Scrolling
DESCRIPTION = Patches the Mojo scroller widget to eliminate jittery drag scrolling and remove the 'snap' when you begin scrolling.
CATEGORY = Mojo
VERSIONS = 3.0.5-3
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ShiftyAxel <jpalmerwatkins@me.com>, bright2k
HOMEPAGE = http://forums.precentral.net/webos-patches/305418-patch-mojo-smooth-scrolling-2-2-x.html