NAME = add-date-to-top-bar
PATCH = /luna/${NAME}.patch
TITLE = Add Date to Top Bar
DESCRIPTION = Add the date to the left of the time in the top bar in MM/DD/YY format.
CATEGORY = Luna
VERSION = 0.4.1
ICON =
SCREENSHOTS = [\"http://www.webos-internals.org/images/6/61/Add_date_to_top_bar.png\"]
META_VERSION = 1

include ../common.mk
include ../modifications.mk
