NAME = add-date-to-top-bar
PATCH = /luna/${NAME}.patch
TITLE = Add Date to Top Bar
DESCRIPTION = Add the date to the left of the time in the top bar in MM/DD/YY format.
CATEGORY = Luna
VERSION = 0.4.0

include ../common.mk
include ../modifications.mk
