NAME = add-date-to-top-bar
PATCH = /luna/${NAME}.patch
TITLE = Add Date to Top Bar
DESCRIPTION = Adds date string next to time in the top bar
CATEGORY = Luna

include ../common.mk
include ../modifications.mk
