NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Battery Percent and Icon White Red Teal
DESCRIPTION = This is the same as 'battery percent and icon white', with two exceptions.  First, when your battery icon turns red, the percentage will turn red also (12% and less).  Second, when the phone is charging the percentage will turn teal.
CATEGORY = Top Bar
VERSIONS = 1.3.5-27 1.4.0-15 1.4.1-1 1.4.2-1 1.4.5-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/f/f7/Top-bar-battery-percent-and-icon-white-red-teal-1.png\",\
\"http://www.webos-internals.org/images/6/6e/Top-bar-battery-percent-and-icon-white-red-teal-2.png\",\
\"http://www.webos-internals.org/images/d/d4/Top-bar-battery-percent-and-icon-white-red-teal-3.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = cwgtex
HOMEPAGE = http://forums.precentral.net/webos-patches/231550-patch-battery-percent-icon-white-red-teal.html
