NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Smiley Faces in Symbol Box Reversed
DESCRIPTION = Use the sym key and letter K (words) or Z (symbols) to bring up the built-in emoticons list. <br/>(All locales & KB layouts supported.)
CATEGORY = Mojo
VERSIONS = 2.1.0-5 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/8/8e/Mojo-smiley-faces-in-symbol-box-reversed-1.png\",\
\"http://www.webos-internals.org/images/7/70/Mojo-smiley-faces-in-symbol-box-reversed-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha, xanthinealkaloid
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2134396#post2134396
