NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Smiley Faces in Symbol Box Reversed
DESCRIPTION = Use the sym key and letter K (words) or Z (symbols) to bring up the built-in emoticons list. <br/>(Now has added language support.)
CATEGORY = Mojo
VERSIONS = 1.3.5-14 1.4.0-25 1.4.1-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/8/8e/Mojo-smiley-faces-in-symbol-box-reversed-1.png\",\
\"http://www.webos-internals.org/images/7/70/Mojo-smiley-faces-in-symbol-box-reversed-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>, Sarah Peterman
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2134396#post2134396
