NAME = $(shell basename $(shell pwd))
PATCH = app-catalog/${NAME}.patch
TWEAKS = app-catalog/${NAME}.json
TITLE = Homebrew Pivot
DESCRIPTION = This patch will change your Pivot feed in App Catalog to the new Homebrew Pivot feed. This new feed will be updated frequently (once we get the people we need) so you can read frequent new issues of community created Pivot issues. You can also enable/disable Homebrew Pivot and switch to other feeds in Tweaks. Note: This patch has been designed so that your device information is not sent to non-HP servers. The only info that is sent is your locale, for multilingual purposes in the future. Please see the forum thread at webOS Nation for more information: http://forums.webosnation.com/hp-touchpad/313719-webos-nation-pivot.html
CATEGORY = App Catalog
VERSIONS = 3.0.5-29
ICON = http://www.webos-internals.org/images/4/45/Icon_WebOSInternals_Patches_Plus_Findapps.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GMMan
HOMEPAGE = http://forums.webosnation.com/hp-touchpad/313719-webos-nation-pivot.html