NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Create Birthday Events
DESCRIPTION = Create Birthday events in the calendar from your contacts.
CATEGORY = Calendar
VERSIONS = 1.4.1-15
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/a/a3/Contacts-create-birthday-events-1.png\",\
\"http://www.webos-internals.org/images/a/aa/Contacts-create-birthday-events-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = MetaView <metaview@web.de>
HOMEPAGE = http://forums.precentral.net/webos-patches/245617-patch-create-birthday-events-your-contacts.html