#!/bin/sh

APP_DIR=$IPKG_OFFLINE_ROOT/usr/palm/applications/org.webosinternals.vkb-default-themes-config

tar --no-same-owner --strip-components=2 -xvzf ${APP_DIR}/additional_files.tar.gz -C /media/internal

for t in `ls /media/internal/virtual-keyboard/.themes`; do
  if [ "$t" != "LPC_Dark_Rounded_2e" ]; then
    sed -i -e '/\[/a \      {"label":"'${t}'","value":"'${t}'"},' /media/internal/virtual-keyboard/kb_config.json
  fi
done
