NAME = enable-dev-mode-icon
PATCH = /luna/${NAME}.patch
TITLE = Enable Dev Mode Icon
DESCRIPTION = Enable Dev Mode Icon
CATEGORY = Luna
ICON = http://www.webos-internals.org/images/e/ec/Icon_WebOSInternals_Patches_Devmodelauncher.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
