NAME = enable-dev-mode-icon
PATCH = /luna/${NAME}.patch
VERSION = 0.1.0
TITLE = Enable Dev Mode Icon
DESCRIPTION = Enable Dev Mode Icon
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
