NAME = enable-dev-mode-icon
PATCH = /luna/${NAME}.patch
TITLE = Enable Dev Mode Icon
DESCRIPTION = Enable Dev Mode Icon
CATEGORY = Luna
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
