NAME = $(shell basename ${PWD})
PATCH = /sprinttv/${NAME}.patch
TITLE = Hide SprintTV App
DESCRIPTION = This will hide the SprintTV app in the App Launcher.
CATEGORY = App Launcher
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/4/48/Icon_WebOSInternals_Patches_Sprinttv.png
SCREENSHOTS =
META_VERSION = 1

include ../common.mk
include ../modifications.mk
