NAME = hide-sprinttv-app
PATCH = /sprinttv/${NAME}.patch
TITLE = Hide SprintTV App
DESCRIPTION = Hides the SprintTV App in the Launcher
CATEGORY = SprintTV
ICON = http://www.webos-internals.org/images/4/48/Icon_WebOSInternals_Patches_Sprinttv.png

include ../common.mk
include ../modifications.mk
