NAME = hide-sprinttv-app
PATCH = /sprinttv/${NAME}.patch
TITLE = Hide SprintTV App
DESCRIPTION = Hides the SprintTV App in the Launcher
CATEGORY = SprintTV

include ../common.mk
include ../modifications.mk
