NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = TopBar Full Screen Wallpaper
DESCRIPTION = This patch will let you pick a wallpaper from the 'photo' app<br/>and it will let you set it as the top-bar image.<br/>now you will have a full screen background.<br/><br/>No need to put a copy of your image in any folder. <br/>just pick an image from the photo app.<br/>Do a Luna restart or restart your phone and that's it.
CATEGORY = Top Bar
VERSIONS = 1.4.5-82 2.0.0-29 2.0.1-51 2.1.0-2 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Warlord9159
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2688620#post2688620
