NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = TopBar Full Screen Wallpaper
DESCRIPTION = This patch will let you pick a wallpaper from the 'photo' app<br/>and it will let you set it as the top-bar image.<br/>now you will have a full screen background.<br/><br/>No need to put a copy of your image in any folder. <br/>just pick an image from the photo app.<br/>Do a Luna restart or restart your phone and that's it. <br/><br/>This patch took me three days to develop and it is just one <br/>line of code to the systemui.css text file <br/><br/>When you pick a wallpaper from the photo app, it makes a temp copy of it<br/>and the patch pulls that image for the top-bar background.
CATEGORY = Top Bar
VERSIONS = 1.4.1-67 1.4.2-54 1.4.3-49 1.4.5-72
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Warlord9159
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2688620#post2688620