NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Just Type - DE
DESCRIPTION = Changes 'Einfach lostippen...' to 'Just type...' for german TouchPad
CATEGORY = Mojo
VERSIONS = 2.2.0-33 3.0.2-40
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = DiplPhy
HOMEPAGE =