NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Just Type - DE
DESCRIPTION = Changes 'Einfach lostippen...' to 'Just type...' for german TouchPad
CATEGORY = Mojo
VERSIONS = 2.2.0-33 2.2.3-33 3.0.2-40 3.0.4-3
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = DiplPhy
HOMEPAGE = http://forums.precentral.net/hp-touchpad-tips-information-resources/295014-replace-just-type-custom-message-6.html#post3176394