NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Brightness in Device Menu
DESCRIPTION = Adds screen brightness control to the device menu.
CATEGORY = Top Bar
VERSIONS = 1.4.5-1 2.0.1-45 2.1.0-3
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/c/cc/Top-bar-brightness-in-device-menu.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/212385-patch-request-add-brightness-control-top-bar.html