NAME = $(shell basename $(shell pwd))
PATCH = memos/${NAME}.patch
TWEAKS =
TITLE = TimeStamp in Memo
DESCRIPTION = This adds a TimeStamp option, located in the top left pull down menu for the memo that is open.
CATEGORY = Memos
VERSIONS = 1.4.5-168 2.1.0-159 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = djgardn2
HOMEPAGE = http://forums.precentral.net/webos-patches/289233-patch-timestamp-memos-app.html
