NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TITLE = Move PIN Pad to Top
DESCRIPTION = Ever accidentally placed an emergency call while trying to unlock your phone? This patch moves the PIN pad away from the 'Emergency Call' button.
CATEGORY = Screen Lock
VERSIONS = 1.2.1-9 1.3.1-12
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/c/cc/Screen-lock-move-pin-pad-to-top-1.png\"]
META_SUB_VERSION = 2

include ../common.mk
include ../modifications.mk

MAINTAINER = Eric Salo <salo@cs.stanford.edu>, dBsooner 
HOMEPAGE =
