NAME = $(shell basename $(shell pwd))
PATCH = advanced/${NAME}.patch
TITLE = Advanced System Behavior (Veer)
DESCRIPTION = The Advanced System Behavior patch has been designed to try and give webOS a more consistent and standardized feel. In addition, the Advanced Systems Behavior patch adds some unique / custom functionality to webOS that you may find useful. For more information see the homepage link and wiki for this patch.
CATEGORY = Advanced
VERSIONS = 2.1.0-119
ICON = http://www.webos-internals.org/images/f/f1/Icon_WebOSInternals_Patch_Plus.png
SCREENSHOTS = 
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = http://forums.precentral.net/enlightened-linux-solutions/279467-patch-advanced-system-behavior-2-x.html
