NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TWEAKS =
TITLE = Screenlock Wallpaper
DESCRIPTION = This patch makes your current wallpaper the background for the Screenlock (pin or pswd). **NOTE** The wallpaper *MUST* be set by the Palm Photos app for this to work and will require a Luna Reset each time you change your wallpaper for it to show on the Screenlock. Will *NOT* pick up wallpaper-changing-app wallpapers. Hopefully that is clear enough.Wallpaper is pulled from /media/internal/.wallpapers/wallpaper-temp.jpgAnyway, enjoy!Big thanks to warlord9159 for providing the groundwork for this patch.
CATEGORY = Screen Lock
VERSIONS = 1.4.5-202
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = palmuse
HOMEPAGE = http://forums.webosnation.com/webos-patches/315839-patch-screenlock-wallpaper-1-4-5-a.html#post3331778