NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Use Ev icon for Ev connections
DESCRIPTION = Under the right conditions, webOS decides to show the '3G' icon for your data connection even if you have 'EVDO.'  This patch makes it show the 'Ev' icon instead.
CATEGORY = Top Bar
VERSIONS = 2.0.0-35 2.0.1-62 2.1.0-16 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = EdCates <edcates@gmail.com>
HOMEPAGE =
