NAME = $(shell basename $(shell pwd))
PATCH = video-player/${NAME}.patch
TWEAKS =
TITLE = YouTube Video Title in Mail Subject
DESCRIPTION = Inserts the video title in the Subject line when sending a YouTube video link by e-mail. Does not remove the title from the e-mail body. If you want additional info on the Subject line, let me know.
CATEGORY = Video Player
VERSIONS = 2.2.4-60
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Videoplayer.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GuyFromNam <GuyFromNam@hotmail.com>
HOMEPAGE =