#!/bin/sh

APPID=org.webosinternals.hulu-fix

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

mount -o remount,rw /
sed -i 's/WEB 10/LNX 10/' /usr/lib/BrowserServerPlugins/libflashplayer.so

exit 0
