#!/bin/sh

APPID=org.webosinternals.fonts.dejavu-mono

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

cp ${APPDIR}/* /usr/share/fonts/

exit 0
