NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Email Body Dismissible
DESCRIPTION = Make the body pane in the Touchpad email app dismissible by swiping it to the right. Selecting an email restores the body pane.
CATEGORY = Email
VERSIONS = 3.0.0-5
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Ryan Hope (PuffTheMagic) <rmh3093@gmail.com>
HOMEPAGE =