NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TITLE = No Charging Banner On AC or Touchstone
DESCRIPTION = Disables the charging banner notification when plugged into an AC wall charger OR placed on Touchstone.
CATEGORY = Notifications
VERSIONS = 1.4.5-98 2.0.0-34 2.0.1-61 2.1.0-15 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha, Speebs
HOMEPAGE = http://forums.precentral.net/webos-patches/266774-patch-no-charging-banner-touchstone.html#post2727981
