NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Thinner Email Accounts Column
DESCRIPTION = This patch will make the Accounts column thinner. It adjusts the size from 320px to 200px.
CATEGORY = Email
VERSIONS = 3.0.5-8
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Garrett92C <Garrett92C@gmail.com>
HOMEPAGE = http://forums.webosnation.com/webos-patches/291132-patch-request-resize-email-column-size-accounts.html