NAME = phone-enable-roam-only
PATCH = /phone/${NAME}.patch
TITLE = Roam Only Patch
DESCRIPTION = ???
CATEGORY = Phone
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
