NAME = phone-enable-roam-only
PATCH = /phone/${NAME}.patch
VERSION = 0.1.1
TITLE = Roam Only Patch
DESCRIPTION = ???
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
