NAME = phone-enable-roam-only
PATCH = /phone/${NAME}.patch
TITLE = Roam Only Patch
DESCRIPTION = ???
CATEGORY = Phone
VERSION = 0.1.16
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
