NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TWEAKS =
TITLE = Show Agenda from Exhibition German
DESCRIPTION = Installieren Sie dieses, wenn Ihre Sprache auf Deutsch eingestellt ist. Andere Sprachen ausgewählt diesem Patch wird nicht funktionieren. Dadurch wird die Agenda-Modus aus Ausstellung, um das Startprogramm an geöffnet. Das Öffnen dieser Art gibt's auch im Querformat für die Agenda. Dies wird nicht überschreiben Ausstellung Modus so Ausstellung Modus wird kommen normalerweise, wenn das Gerät auf dem Prüfstein.
CATEGORY = App Launcher
VERSIONS = 2.1.0-78 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = addiarmadar <addiarmadar@yahoo.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/280962-patch-show-agenda-exhibtion-launcher.html
