#!/bin/sh

APPID=org.webosinternals.fonts.xfonts-base
FONTDIR=misc

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

mkdir -p /usr/share/fonts/X11
cd /usr/share/fonts/X11; ln -s ${APPDIR}/${FONTDIR}

exit 0
