NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Add Date - MM/DD/YY
DESCRIPTION = Add the date to the left of the time in the top bar in MM/DD/YY format.
CATEGORY = Top Bar
VERSION = 1.2.1-0
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/6/61/Add_date_to_top_bar.png\"]
META_SUB_VERSION = 2

include ../common.mk
include ../modifications.mk

MAINTAINER = dirtygreek
HOMEPAGE = http://forums.precentral.net/web-os-development/200039-add-date-time-top.html
