NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Mojo Tap Responsiveness
DESCRIPTION = Makes the UI more responsive by eliminating the 0.15s delay between tapping on something and it being selected (Buttons, for instance.) Tap-and-hold time is also reduced from 0.5s to 0.25s.
CATEGORY = Mojo
VERSIONS = 1.4.5-185 2.1.0-229 2.1.1-20 2.1.2-44 2.2.0-107 2.2.3-101 2.2.4-37 3.0.2-85 3.0.4-51 3.0.5-4
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ShiftyAxel <jpalmerwatkins@me.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/307783-patch-mojo-tap-responsiveness.html