#!/bin/sh

APPID=mobi.optware.termcap

# Remove files from /opt
rm -f /opt/lib/libtermcap.a 
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find lib -depth -type f -exec rm -f /opt/{} \;
find lib -depth -type d -exec rmdir /opt/{} \;

exit 0
