NAME = radiopower
PATCH = /phone/${NAME}.patch
VERSION = 0.1.5
TITLE = phone radio power patch
DESCRIPTION = ???
CATEGORY = Phone
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
