NAME = radiopower
PATCH = /phone/${NAME}.patch
TITLE = Phone Radio Power
DESCRIPTION = This will add the ability to turn the Phone Radio On and Off in the Device Info application. This will only turn off the Phone Radio.
CATEGORY = Phone
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
