NAME = $(shell basename ${PWD})
PATCH = /phone/${NAME}.patch
TITLE = Phone Radio Toggle
DESCRIPTION = This will add the ability to turn the Phone Radio On and Off in the Device Menu. This will only turn off the Phone Radio.
CATEGORY = Phone
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
