NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Slider Blocks Orientation Change
DESCRIPTION = Open the phone slider to prevent the browser from switching from portrait to landscape, or vice versa.  Close the slider to re-enable auto-orientation.
CATEGORY = Browser
VERSION = 1.3.1-22
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = KeyToss <info@keytoss.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/217421-patch-slider-disables-browser-orientation-change.html
