NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Add date dd-MMM-yy
DESCRIPTION = Adds date to the top bar next to the time in format dd-MMM-yy. Unlike others the month displays as a 3 letter nemonic e.g Jan.
CATEGORY = Top Bar
VERSIONS = 1.3.5-13 1.4.0-2
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = AnthonyK
HOMEPAGE =