#!/bin/sh

if [ ! -d "/etc/profile.d" ]; then
  mkdir /etc/profile.d
fi

cat > /etc/profile.d/mobi.webosinternals.bash << "EOF"
if [ "`id -u`" -eq 0 ]; then
  PS1='\[\033[01;31m\]\h\[\033[01;34m\] \W \$\[\033[00m\] '
else
  PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w \$\[\033[00m\] '
fi
EOF

if [ ! -f "/etc/shells" ]; then
  touch /etc/shells
fi

if grep -q /bin/sh /etc/shells; then
  echo /bin/sh >> /etc/shells
fi

if grep -q /opt/bin/bash /etc/shells; then
  echo /opt/bin/bash >> /etc/shells
fi

exit 0
