#!/bin/sh

APPID=mobi.optware.bash

# Remove files from /opt
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find bin -depth -type f -exec rm -f /opt/{} \;
find bin -depth -type d -exec rmdir /opt/{} \;

sed -e '/\/opt\/bin\/bash/d' -i /etc/shells

rm -f /etc/profile.d/mobi.webosinternals.bash
rm -f /etc/profile.d/$APPID

exit 0
