NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Enable Call Forwarding
DESCRIPTION = This patch enables a hidden feature in phone preferences and allows you to add the call forwarding feature.
CATEGORY = Phone
VERSIONS = 1.4.0-80 1.4.1-65 1.4.2-52 1.4.3-47 1.4.5-63
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/f/f9/Phone-enable-call-forwarding-1.png\",\
\"http://www.webos-internals.org/images/d/dc/Phone-enable-call-forwarding-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =