NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TITLE = No Charging Banner On Touchstone
DESCRIPTION = Disables the charging banner notification when placed on the Touchstone.
CATEGORY = Notifications
VERSIONS = 1.4.5-96
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Speebs
HOMEPAGE =
