NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Enable Virtual Keyboard
DESCRIPTION = This patch enables the virtual keyboard on webOS 2.0.1.
CATEGORY = Mojo
VERSIONS = 2.0.1-64
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Arthur Thornton (arthurthornton on PreCentral)
HOMEPAGE =
