NAME = battery-percent
PATCH = /luna/${NAME}.patch
TITLE = Battery % in Header
DESCRIPTION = Replaces battery icon with colour-coded percent number
CATEGORY = Luna
VERSION = 0.3.1
ICON = 
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
