NAME = battery-percent
PATCH = /luna/${NAME}.patch
TITLE = Battery Icon as Percent
DESCRIPTION = This will replace the battery icon in the top bar with a color-coded percent number. Charging = Teal. 100%-70% = Green. 69%-45% = Yellow. = 44%-20% = Orange. 19%-0% = Red.
CATEGORY = Luna
VERSION = 0.4.0
ICON = 
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
