NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = SMS Vibrate to Half Second
DESCRIPTION = Extends the vibrate of the SMS notification by half a second.
CATEGORY = Messaging
VERSIONS = 2.1.0-193 2.1.1-22 2.1.2-31 2.2.0-62 2.2.3-56
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Abyssul <Time4swim@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/225334-patch-sms-im-vibrate-extension.html
