NAME     = saverestore
TITLE    = Save/Restore
APP_ID   = org.webosinternals.${NAME}
SIGNER   = org.webosinternals
BLDFLAGS = -p
VERSION  = 1.5.9
DEPENDS  = org.webosinternals.unzip, org.webosinternals.zip
TYPE	 = Application
CATEGORY = System Utilities
HOMEPAGE = http://www.webos-internals.org/wiki/Application:SaveRestore
ICON	 = http://www.webos-internals.org/images/f/f0/Icon_WebOSInternals_Saver.png
DESCRIPTION = Save/Restore enables saving and restoring application data to and from the /media/internal/saverestore/ directory on a webOS device.<br>It is in a general beta testing phase, but you should not trust it as your sole backup of data.<br>\
WebOS Internals provides Save/Retore as is without warranty of any kind, either expressed or implied, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose.  The entire risk as to the quality and performance of Save/Restore is with you.  Should Save/Restore prove defective, you assume the cost of all necessary servicing, repair or correction.<br>\
In no event will WebOS Internals or any other party be liable to you for damages, including any general, special, incidental or consequential damages arising out of the use or inability to use Save/Restore (including but not limited to loss of data or data being rendered inaccurate or losses sustained by you or third parties or a failure of Save/Restore to operate with any other programs).
CHANGELOG = \
1.5.9: Applications: Aftermath XHD, Totemo HD (both courtesy of Audemars02), Pink Pad (both courtesy of marysm), Market Pulse HD, SportsLive HD (both courtesy of MoreSolutions), Data Manager, Data Manager Demo (both courtesy of sidamos), Quell, Quell Reflect (updates courtesy of stickb0y).<br>\
1.5.8: Applications: Quell Reflect HD, No Gravity, Asphalt6, Bubble Birds 2.0, Bubble Birds 2.0 Premium, Glyder 2 HD.<br>\
1.5.7: Application: Bug Village.<br>\
1.5.6: Application: podFrenzy (courtesy of Audemars02).<br>\
1.5.5: Application: Angry Birds Seasons HD (courtesy of Audemars02).<br>\
1.5.4: Applications: Launcher (3.0 update), Beyond Ynth, Sparkle HD, Quell HD (all courtesy of Audemars02), Blocked (courtesy of stickb0y).<br>\
1.5.3: Added AppNote for Robotek HD script to indicate restore only works with the same device.<br>\
1.5.2: Applications: intervalGym, Jamwam Jog, Power Nap, ZenSearch (all courtesy of irateb), Need For Speed Hot Pursuit (TouchPad) (courtesy of A.Stice), FlightView, Gowalla, Open Table, Robotek HD, Slice It HD, Spare Time, Wall Switch (all courtesy of Audemars02).<br>\
1.5.1: Applications: Trip Traq - HBLR, Trip Traq - BART, Pane Free, Multi Pane (all courtesy of appsotutely), Clock In, Clock In Trial, Gizmo, BeamOut, Days Gone By, Days To Come (all courtesy of djgardn2), DORK 1 (courtesy of lordbah), FitTrack Trial, MiniSquadron (both courtesy of malpha), Super Ads (courtesy of Audemars02).<br>\
1.5.0: Applications: SecuStore 2, SecuStore 2 (Trial).<br>\
1.4.8: Added back buttons for devices with no back gesture.<br>\
1.4.7: Applications: Angry Birds HD, Angry Birds Rio HD (courtesy of Audemars02).<br>\
1.4.6: Added support for saving Text Assist entries.<br>\
1.4.5: Added support for devices with no back gesture.<br>\
1.4.4: Applications: Add Pad, Convertor, GPS Fix, Grooveshark, Hopper, phnx, Touchnote, Universe Browser, Voice Memos, Voices, WhitePages (all courtesy of Audemars02).<br>\
1.4.3: Change scrim to Mojo spinner on Main during load.<br>\
1.4.2: Fixed auto-save and sorting of apps in the save and installed scenes.<br>\
1.4.0: Now incrementally loads the set of application scripts.<br>\
1.3.9: Applications: Safe Wallet (courtesy of Audemars02), Koto Player (courtesy of fxspec06), CryptoNotes (courtesy of hboisvert), ToDo Classic (courtesy of hboisvert), FitTrack, Headlines, Slice It (all courtesy of malpha), Kookaroo, LumenCalc, SiteStatusPro (all courtesy of pcimino), Bills Vs Income, Blox, Chemistry Encyclopedia, Click Trainer, Dashboard Utilities, GeoStrings, Marquees ROCK, Music (Remix), Quick Post, Todays Tasks, WikiXplorer, ZIP Code Tools (all courtesy of djgardn2).<br>\
1.3.8: Applications: Angry Birds Rio, Supersonic. Updated Device Info and Backup scripts in Contrib directory for webOS 2.0 changes.  Added Max webOS 1.4.5 version to Advanced Patches scripts (all courtesy of Audemars02).<br>\
1.3.6: Applications: Airplanes, Beat Box, BibleZ (pro), BibleZ, Bubbles (free), Buka, Buka (Lite), gpsDashboard Free, gpsDashboard, Helicopter 3D, Hit the dots, Hyperspace Tournament, Labyrinth Lite, Metronome, Navit, Puzzle Paint (Lite), Puzzle Paint, Radiant, Radiant (Lite), Relego, Rhythm News, Solitaire, SuperNES, Wetter.com, World Time (Lite), World Time (Pro), zcorder (all courtesy of pcworld), Brothers In Arms 2 (updated), InterfaceLift, Worms (all courtesy of djgardn2), Go To Demo, Go To Lite, Go To tool (all courtesy of markpowers), Azkend, Heroes of Kalevala, Just Draw (all courtesy of sunmorgus), SiteStatus (courtesy of pcimino).<br>\
1.3.5: Applications: Done, Count Down Clock, Geocaching for Webos, Astraware Mahjong, ICE - In Case of Emergency, Fling, Amigo, Bahnfahren, Dict.cc Translator, Forums, Free Klondike Solitaire, Glow Hockey, Glow Hockey FREE, Leo Dictionary, Nodoze, Plasma Cannon, Precentral News (unofficial), Premote , Raging Thunder 2, Rockus Racer Expansion Pack, Snake, Space Sheep, Space Sheep Lite, SWR3-Elchradio, Telmap O2 Germany, Znax.<br>\
1.3.4: Applications: Clipboard for webOS (UPDATED), A+ Student Organizer Trial (both courtesy of Audemars02), Poker Session Tracker (courtesy of iamthedood), ColorHarmony (courtesy of rretsiem), Backgammon, Bible Reader, Blink, Blink (free), Chess for webOS, chess.com, ColorJunction, DasTelefonbuch, Galcon, Labyrinth, Mazer, Palm Developer Day 2010 Schedule, Pandablast, Plumbers Nightmare (Lite), PreJvm, Simple Bible, Tile Breaker, Tile Breaker (Lite), Titan Stopwatch, TuneIn by RadioTime, Virus Defense, Virus Defense (Lite), VLC Remote, VLC Remote (free), webOS Blog, webOS roundup, YouTube Mini, YouTube Mini (Free) (all courtesy of pcworld).<br>\
1.3.3: Keep the device awake during scheduled auto-save (courtesy of MetaView). Applications: Clipboard for webOS, Carbon Beta (courtesy of Audemars02).<br>\
1.3.1: Applications: Backup (Contrib), Device Info (Contrib), Launcher (Updated for 2.0), Need for Speed (Spanish), Carbon, Foursquare (beta), Ace Casino, Definitive Saved by the Bell Quiz Full, freeTether (all courtesy of Audemars02), Baseball Live, Basketball Live, Women's College Basketball Live, Women's Basketball Live, US Soccer Live, UK Football Live, Sports Live, International Soccer Live, Hockey Live, Football Live, Euro Football Live, College Football Live, College Basketball Live (all courtesy of MoreSolutions), TapNote (courtesy of One Crayon).<br>\
1.3.0: Rolled up all the beta release features for a public release.<br>\
1.2.9: Added dashboard for auto-save and fixed scheduling (courtesy of ryanjduffy).<br>\
1.2.8: Added scheduled backups (courtesy of ryanjduffy).<br>\
1.2.7: Applications: InContact Plus, InContact (both courtesy of ryanjduffy), EVAC, Dough (both courtesy of Carl Spakler), EZ Shop List (courtesy of crabbz), Dead Runner (courtesy of Audemars02), Feeder, Reboxed, Word Whirl, Gamer Friends for PSN, Tangram, Tilt Origami, Wobble Words, ExZeus arcade, Scrabble, Quell, Tradewinds 2 (all courtesy of malpha).<br>\
1.2.6: Applications: Angry Birds Seasons.<br>\
1.2.5: Applications: DigiPay, Woodenigma, Ancient Frog.<br>\
1.2.4: Now distinguishes internal and external databases with the same name. Affects My WebOS Apps and perhaps other scripts - please do a backup to ensure you have both databases saved correctly.<br>\
1.2.3: Application: Pronto Dial (courtesy of malpha).<br>\
1.2.2: Applications: Ground Effect, TileStorm, TileStorm Eire, Rock Band.<br>\
1.2.0: Added support for scripts that are dependent upon the webOS version.<br>\
1.1.0: Rolled up all the beta release features for a public release.<br>\
1.0.19: Applications: What's for dinner? Premium (courtesy of rksand), NesEm (Updated), Dungeon Hunter (Updated), WOG O.S.K. (all courtesy of djgardn2).<br>\
1.0.18: No longer saves file attachments from MMS messages. You will need to manually back up those files from /attachments directory on the USB drive.<br>\
1.0.17: Added a Changelog button to the Help scene.<br>\
1.0.16: Patch: Advanced Config Sys Pref-World script. Applications: Astraware Boardgames, Angry Birds (Pixi) (both courtesy of Audemars02), Crosswords (courtesy of tobias funke). Added executable for ACSP-World in the contrib directory. Updated Photos script and Readme.txt file in contrib directory.<br>\
1.0.15: Added support for saving Tasks.<br>\
1.0.14: Added support for saving MMS messages.<br>\
1.0.13: Application: Application: FitTrack Beta (courtesy of troymiller). Updated: Advanced Config for System Preferences patch (courtesy of tobias funke).  Robustify file-saving script when creating the source directory if it does not already exist.<br>\
1.0.12: Application: NesEm. Patch: Advanced Config for System Preferences. Added executable to run Advanced Config for System Preferences to /contrib directory (see Readme.txt file in that directory for details).<br>\
1.0.11: Robustify the Directory script.  Added a photos/videos backup script and an executable for App Launcher Advanced Config script in the /contrib (see Readme.txt file in that directory for details).<br>\
1.0.10: Robustify postinst script. Added french translation support. Added support for saving a single directory. Robustify file-saving script to create the source directory if it does not already exist. Applications: Jacksonville, New York Times, TodoTracker (all courtesy of djgardn2), Slide RSS (courtesy of appsotutely), Scratch Word Processor (courtesy of Chakat Silverstreak), Astraware Casino (courtesy of Audemars02), Putki, SuperJump (both courtesy of pcworld), VisualBoy Advance (courtesy of rwhitby), College Football Live, International Soccer Live, UK Football Live, Womens Basketball Live (all courtesy of MoreSolutions), Angry Birds Lite, BFG Maps, BFG Maps Beta, Bluetooth Profiles, Crimson Fields, Frootrees, Lumberjack, Sparkle Lite (all courtesy of StoneRyno).<br>\
1.0.9: Robustify the installation scripts.  Applications: Music (Remix), Music Wave Lite, Fuzzies (all courtesy of mamouton), Brain Challenge HD, TangramPuzzle Lite, TangramPuzzle (all courtesy of Audemars02).<br>\
1.0.8: Applications: EasyList, Cosmic Nitro, TechTray, GPS Trip Panel, Raging Thunder, What's for dinner? Lite (all courtesy of djgardn2), Crusade Of Destiny, Rednecks Vs Aliens (both courtesy of mamouton), TrackMyWork Full (courtesy of kr_ke), Sparkle (courtesy of pip smith).<br>\
1.0.6: Applications: TouchConnect+, Mobile Hotspot (both courtesy of Audemars02), SmartRunner (courtesy of djgardn2).<br>\
1.0.5: Fixed case insensitive unzip overwrite query bug. Applications: Angry Birds.<br>\
1.0.4: Fixed issue created when allowing filenames that include spaces. Fixed application names for a few scripts.<br>\
1.0.3: Allows for filenames that include spaces.  Applications: wIRC (updated), AutoReplace Dictionary Backup, pReader, Photo Safe, YouTube (all courtsey of Audemars02); Fliq Tasks, Sorting Thoughts, bit.ly (all courtesy of djgardn2), SiDiary Exporter (courtesy of Taurec), My Pets (courtesy of rgisraelsen)<br>\
1.0.1: Added support for Preferences-type backups, including support for Mode Switcher. Applications: Quit Smoking Tracker (courtesy of Chakat Silverstreak); NaNPlayer  (courtesy of mamouton); TealSpeed, Brothers In Arms 2, YP Mobile (all courtesy of djgardn2); My DataBank Unlimited, Movie Diary (courtesy of pip smith); Wifi Profiles, YouView, Facebook, Facebook Beta, Cronk, Internalz, ZumoDrive, Switcharoo Free, Wallpaper Switcharoo, Brightness Unlinked, WiFi Media Sync, Quick Event, LaunchPoint Speed Dial (courtesy of Audemars02); Spades, DZ.Tanks, foursquare, Geocaching for webOS BETA, Speed Brain, Pandora, Card Ace, Card Ace: Blackjack, Word Ace, WHERE, Bible (Youversion), Solitaire Collection (minego), Solitaire Collection Beta (minego), LED torch, AccuRadio, Flixster, Convert, Unit Wizard, Slacker Radio, Trapster, Weather Channel, Units, MyQ for Netflix, Terminal (all courtesy of StoneRyno)
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/b/b5/Saverestore_ss1.png\", \
\"http://www.webos-internals.org/images/7/76/Saverestore_ss2.png\", \
\"http://www.webos-internals.org/images/4/47/Saverestore_ss3.png\", \
\"http://www.webos-internals.org/images/3/36/Saverestore_ss4.png\" \
 ]
LICENSE  = GPL v2 Open Source

SRC_GIT = git://git.webos-internals.org/applications/saverestore.git

.PHONY: package
package: ipkgs/${APP_ID}_${VERSION}_arm.ipk ipkgs/${APP_ID}_${VERSION}_i686.ipk
include ../../support/package.mk

include ../../support/download.mk

.PHONY: unpack
unpack: build/.unpacked-${VERSION}

build/.unpacked-${VERSION}: ${DL_DIR}/${NAME}-${VERSION}.tar.gz
	rm -rf build
	mkdir -p build/src
	tar -C build/src -xf ${DL_DIR}/${NAME}-${VERSION}.tar.gz
	rm -rf build/src/bin build/src/*.script
	chmod ugo+x build/src/scripts/*
	chmod ugo+x build/src/contrib/*
	tar -C build/src/scripts -zcf build/src/scripts.tgz .
	rm -rf build/src/scripts
	touch $@

.PHONY: build
build: build/.built-${VERSION}

build/.built-${VERSION}: build/arm.built-${VERSION} build/i686.built-${VERSION}
	touch $@

include ../../support/cross-compile.mk

build/%.built-${VERSION}: build/.unpacked-${VERSION}
	rm -rf build/$*
	( cd build/src/src ; \
	  ${MAKE} STAGING_DIR=${STAGING_DIR_$*} CC=${CROSS_COMPILE_$*}gcc \
	  clobber ${NAME} \
	)
	mkdir -p build/$*/usr/palm/applications/${APP_ID}
	cp -r build/src/* build/$*/usr/palm/applications/${APP_ID}/
	rm -rf build/$*/usr/palm/applications/${APP_ID}/src
	mkdir -p build/$*/usr/palm/applications/${APP_ID}/bin
	install -m 755 build/src/src/${NAME} build/$*/usr/palm/applications/${APP_ID}/bin/${APP_ID}
	touch $@

build/%/CONTROL/postinst:
	rm -f $@
	mkdir -p build/$*/CONTROL
	install -m 0775 build/src/control/postinst build/$*/CONTROL
	chmod ugo+x $@

build/%/CONTROL/prerm:
	rm -f $@
	mkdir -p build/$*/CONTROL
	install -m 0775 build/src/control/prerm build/$*/CONTROL
	chmod ugo+x $@

clobber::
	rm -rf build
