NAME = $(shell basename $(shell pwd))
TITLE = Stock Kernel (Palm Pre/Pre+)
DESCRIPTION = An unmodified kernel, recompiled from source.<br>\
Useful for testing the kernel packaging and upgrade processes.<br>${KERNEL_DISCLAIMER}
CATEGORY = Stable
VERSIONS = 1.4.1-1

HOMEPAGE = http://opensource.palm.com
SRC_GIT = git://git.webos-internals.org/kernels/patches.git
KERNEL_PATCHES =

include ../../support/kernel.mk
