NAME     = fcoaster
APP_ID   = com.palm.net.precoder.${NAME}
VERSION  = 1.0.1
PLATFORM = all
HOMEPAGE = http://forums.precentral.net/homebrew-apps/194825-filecoaster-first-pre-gui-downloader-installer.html
SECTION = misc
MAINTAINER = Brian Jost <http://precoder.net>

SRC_IPKG = http://forums.precentral.net/spe_attachment/download-23873-com.palm.net.precoder.fcoaster_1.0.1_all.ipk
include ../../support/download.mk

include ../../support/application-copy.mk
