NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Increase Font Size 18 Aqua
DESCRIPTION = This will increase the font size to 17px and the color of the carrier string, AppMenu Wrapper, Date/Time and the clock to aqua. This is not recommended if you are using the Top Bar: Add Date mm-dd-yy and/or the Top Bar: Battery AND Percent patch.
CATEGORY = Top Bar
VERSIONS = 1.3.1-20 1.3.5-1 1.4.0-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/a/af/Top-bar-increase-font-size-18-aqua-1.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = 2sslow
HOMEPAGE =
