NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TWEAKS =
TITLE = Advanced Reset Options - FR
DESCRIPTION = On power button hold, the options will be airplaine mode, luna restart, device restart, shut down, and cancel. French language. Based on the original 'Advanced Reset Options' patch by Jason Robitaille.
CATEGORY = Notifications
VERSIONS = 3.0.5-14
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = DiplPhy <diplphy@gmail.com>
HOMEPAGE = http://forums.webosnation.com/webos-patches/288393-patch-touchpad-advanced-reset-options-4.html