NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Twee Super Mix
DESCRIPTION = Adds Shorten URL, Tweet via Twee, Add to Relego, Add to Spare Time, and Send via Neato! options in the app menu. Disables auto-refresh in the browser. <br/><br/>Adds shortcut keys for the following:<br/>New Card: Gesture+N;<br/>Add Bookmark: Gesture+M;<br/>Add To Launcher: Gesture+L;<br/>Bookmarks: Gesture+B;<br/>History: Gesture+H;<br/>Share Page: Gesture+S;<br/><br/>Based off patches by benuk, mamouton, and fritos1406.<br/><br/>*Send via Neato! requires Neato! version 1.0.0 or higher
CATEGORY = Browser
VERSIONS = 1.4.5-121
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/7/7a/Browser-twee-super-mix-1.png\",\
\"http://www.webos-internals.org/images/4/40/Browser-twee-super-mix-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ThomasCoe <thomascoe1@gmail.com>
HOMEPAGE =
