NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS = browser/${NAME}.json
TITLE = Custom Browser Gestures
DESCRIPTION = This patch enables 4 configurable gesture areas. You can reconfigure the action for each gesture in Tweaks. The gestures activate by swiping in from the top and bottom halfs of the screen edges. Current supported actions: Back, Forward, Bookmarks, Refresh, Disable
CATEGORY = Browser
VERSIONS = 3.0.2-34
ICON = http://www.webos-internals.org/images/3/37/Icon_WebOSInternals_Patches_Plus_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = nightburn <nightburn@gmail.com>, Garrett92C
HOMEPAGE = http://forums.precentral.net/webos-patches/300661-patch-custom-browser-gestures-touchpad.html