NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Haptic Feedback Manager
DESCRIPTION = Enables Vibrate feature to any Tap on an object/icon..etc.<br/>*Remove any other vibrate tap patches or it would just add onto the vibrate atop of that patch<br/>*Also currently only working on stock apps
CATEGORY = Mojo
VERSIONS = 1.3.5-16 1.4.0-21 1.4.1-8
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/225480-patch-haptic-feedback-manager.html