NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Dialpad Tones Off
DESCRIPTION = This will turn off the DTMF tones when dialing a phone number.  Note that tones are still played correctly on the other end of the call.
CATEGORY = Phone
VERSIONS = 1.2.1-12 1.3.1-1 1.3.5-1
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png	
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = icederror, jblebrun, jhoff80
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_webOS_Turning_Off_Dialpad_Noise
