NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = Remove Send-Attach buttons in compose view
DESCRIPTION = Removes Send and Attach buttons in the Messaging app. when composing a new text message (the 'attach file' option is in the menu now and forward swipe send the message).
CATEGORY = Messaging
VERSIONS = 2.1.0-194 2.2.0-65 2.2.3-57
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = kbywal
HOMEPAGE =