NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Menu Fade Scrim
DESCRIPTION = If you just want to get rid of the fade, just install the patch, if you want a custom scrim just place it in the scrims folder used for my other patches.<br/>This will also remove the top fade in the messaging app!<br/><br/>If you are not using one of my scrims patches (shame on you lol)then just create a folder on the usb drive of your Pre called scrims and put the .pngs in there.<br/><br/>The affected files are:<br/>command-menu-gradient.png   Fade at the bottom of mast apps.<br/>view-menu-gradient.png   Fade at the top of the messaging app.<br/><br/>If you use the Launcher-scrim-menu-fade patch<br/>The file is called<br/>launcher-scrim.png
CATEGORY = App Launcher
VERSIONS = 1.3.5-16
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/e/e4/App-launcher-menu-fade-scrim-1.jpg\",\
\"http://www.webos-internals.org/images/1/14/App-launcher-menu-fade-scrim-2.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = 2sslow
HOMEPAGE = http://forums.precentral.net/webos-patches/225366-patch-launcher-scrim-menu-fade.html