NAME = $(shell basename $(shell pwd))
PATCH = contacts/${NAME}.patch
TITLE = Additional Speed Dial Keys
DESCRIPTION = Adds back the 'Z/*' and 'B/Pound' speed dial keys as well as adds the '@/0', '.', and ',/_' keys.
CATEGORY = Contacts
VERSIONS = 1.4.5-22 2.0.0-24 2.0.1-37
ICON = http://www.webos-internals.org/images/c/ca/Icon_WebOSInternals_Patches_Contacts.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/4/44/Contacts-additional-speed-dial-keys-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = CraiaSoftware
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2494994#post2494994