#!/bin/sh

APPID=mobi.optware.nano

# Remove files from /opt
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find bin etc share -depth -type f -exec rm -f /opt/{} \;
find bin etc share -depth -type d -exec rmdir /opt/{} \;

exit 0
