#!/bin/sh

PACKAGE=org.webosinternals.eom-overlord-monitoring

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
    IPKG_OFFLINE_ROOT=/media/cryptofs/apps
    mount -o remount,rw /
fi

# Stop uploading stuff to Palm
stop uploadd
sed -i -e 's/^spawn/#spawn/' /etc/event.d/uploadd
sed -i -e 's/^exec/#exec/' /etc/event.d/uploadd

ipkg -o $IPKG_OFFLINE_ROOT remove $PACKAGE
exit 0
