NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Auto Hide All Icons After Page Load
DESCRIPTION = Hides all icons except the loading icon when the browser app is loading/refreshing page.<br/><br/>For those with Flash:<br/>Once you click on Flash Content, the X to close out of it will appear. After you click the X, it icon will go away.
CATEGORY = Browser
VERSIONS = 2.1.0-11 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/b/bd/Browser-auto-hide-all-icons-after-page-load-1.png\",\
\"http://www.webos-internals.org/images/1/14/Browser-auto-hide-all-icons-after-page-load-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha, fritos1406
HOMEPAGE = http://forums.precentral.net/webos-patches/223477-patch-no-icons-browser-2.html
