NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Auto Hide All Icons After Page Load
DESCRIPTION = Hides all icons except the loading icon when the browser app is loading/refreshing page.
CATEGORY = Browser
VERSIONS = 1.3.1-33 1.3.5-16 1.4.0-5
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/223477-patch-no-icons-browser-2.html