NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = UberCalendar MINI
DESCRIPTION = Adds more reminder times, the agenda icon, new event icon and allday event icon
CATEGORY = Calendar
VERSIONS = 2.0.0-29 2.0.1-51 2.1.0-2 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = MetaView & CRaiaSoftware
HOMEPAGE = http://forums.precentral.net/webos-patches/275560-patch-webos-2-0-bucket-o-patches.html
