NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = Chinese PinYin Framework
DESCRIPTION = Provide Chinese character to PinYin lookup. This is a framework require by other patch or modules, you don't get anything directly. Please restart your device after installation instead of just restarting Luna
CATEGORY = System
VERSIONS = 2.1.0-213 2.1.1-22 2.1.2-31 2.2.0-100 2.2.3-93 2.2.4-4 3.0.2-84 3.0.4-43
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = moo <moo.tinys@gmail.com>
HOMEPAGE =