NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Jump One Word at a Time
DESCRIPTION = This will modify the messaging app to use sym+f to jump backward one word and sym+g to jump forward one word. WebOS 1.2.0 enable OrangeKey(Option)+Swipe to move forward or backward in messaging, email, memos and other apps.
CATEGORY = Messaging
VERSIONS = 1.2.1-0 1.3.1-0 1.3.5-0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = hmagoo
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Messaging_Jump_Forward%2C_Backward_One_Word_at_a_Time
