NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TWEAKS =
TITLE = Quiet powerd Messages
DESCRIPTION = This will silence the powerd messages. The powerd messages are the sleep/wake messages sent to ssh/terminal when the device sleeps or wakes.
CATEGORY = Misc
VERSIONS = 2.1.0-19 2.1.1-22 2.1.2-31 2.2.4-5 3.0.2-3 3.0.4-13
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 2

include ../common.mk

include ../modifications.mk

MAINTAINER = Leslie Michael Orchard <l.m.orchard@pobox.com>
HOMEPAGE =