NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Quiet powerd Messages
DESCRIPTION = This will silence the powerd messages. The powerd messages are the sleep/wake messages sent to ssh/terminal when the device sleeps or wakes.
CATEGORY = Misc
VERSIONS = 1.2.1-0 1.1.3-0
META_SUB_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk

MAINTAINER = Leslie Michael Orchard <l.m.orchard@pobox.com>
