NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Set Avatar in Messaging Left Side
DESCRIPTION = This adds a menu option to dynamically set avatar whenever you want. Avatar positioned on left side. Requires FileMgr service.
CATEGORY = Messaging
VERSIONS = 1.4.5-30 2.0.1-48
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/257309-patch-set-avatar-messaging.html#post2611333