NAME = $(shell basename $(shell pwd))
PATCH = universal-search/${NAME}.patch
TITLE = Command Line
DESCRIPTION = "This will add commands to Universal Search. Type \".calc 2 + 5\" to calculate something.  Type \".dict affluent\" or \".thes wealthy\" to look up a word.  Type \".memo I like pie.\" to create a new memo.  And more! Type \".help\" for a list of commands. NOTE: To make certain commands such as \".memo\" work, you must install separate packages such as the \"USCL Memos Patch\" which patches the Memos application.  If you get an error message such as \"The application %s is not configured for the Universal Search Command Line\" or a command such as \".memo\" is missing when you type \".help\", that\'s your cue to do so."
CATEGORY = Universal Search
VERSION = 1.2.1-18
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/b/b6/Universal-search-command-line-%28USCL%29-1.png\",\
\"http://www.webos-internals.org/images/f/fe/Universal-search-command-line-%28USCL%29-2.png\",\
\"http://www.webos-internals.org/images/1/13/Universal-search-command-line-%28USCL%29-3.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = dsevil <dse@webonastick.com>
HOMEPAGE = http://webonastick.com/webos/patches/
