NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Scrim System Screens
DESCRIPTION = allows you to change the white background of the system screens to an image file.' .png ' file.<br/><br/>apps are ' backup, bluetooth, dateandtime, deviceinfo, location, screenlock, soundsandalerts, updates and wifi '<br/><br/>image size 320x450. if your image is 320x480 it will not fit but will display.<br/><br/>send your image to scrims folder.<br/><br/>or make a folder called ' scrims ' in the internal memory card of your pre.<br/><br/>name the file ' backup-scrim '<br/><br/>remember that the text color in the apps are black, blue and gray.<br/>try not to make the background picture black, blue or gray or this will hide your text.<br/><br/>install patch
CATEGORY = App Launcher
VERSIONS = 1.4.5-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/9/95/App-launcher-scrim-system-screens-1.png\",\
\"http://www.webos-internals.org/images/f/f0/App-launcher-scrim-system-screens-2.png\",\
\"http://www.webos-internals.org/images/0/09/App-launcher-scrim-system-screens-3.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Warlord9159
HOMEPAGE = http://forums.precentral.net/webos-patches/245916-patch-change-palm-back-ground-color-png.html
