NAME = enable-browser-downloads
PATCH = browser/${NAME}.patch
VERSION = 0.1.4
TITLE = Enable Browser Downloads
DESCRIPTION = Enable downloads in browser and more
CATEGORY = Browser
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
