NAME = $(shell basename $(shell pwd))
PATCH = other/${NAME}.patch
TWEAKS =
TITLE = Test Patch
DESCRIPTION = This is a test patch, please do not install it.
CATEGORY = Other
VERSIONS = 1.4.5-148 2.0.0-59 2.0.1-89 2.1.0-132 2.1.1-22 2.1.2-31 3.0.0-31 3.0.2-3
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/d/da/Other-test-patch-1.png\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = rwhitby
HOMEPAGE = http://www.webos-internals.org
