NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Reverse number lookup multi-country
DESCRIPTION = This patch adds an option to the call log to do a reverse lookup of a phone number using various websites. Currently supports AT, BE, CH, DE, FR and NL. Supports local and international phone number formats. Should also work properly while roaming :)
CATEGORY = Phone
VERSIONS = 2.2.4-47
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Herrie <webos-internals.org@herrie.org>
HOMEPAGE = http://forums.webosnation.com/webos-patches/312190-patch-2-2-x-reverse-number-lookup-multi-country.html