NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TITLE = More Standby Times - DE
DESCRIPTION = *DE only*<br/>This will add more standby times to the Screen & Lock application. New settings will be 15 seconds, 3 minutes, 5 minutes and never. This will not change your standby time automatically. You will have to select the length you desire in the Screen & Lock application.
CATEGORY = Screen Lock
VERSIONS = 1.4.5-132 2.0.0-31 2.0.1-53 2.1.0-5 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/d/dd/Screen-lock-more-standby-times---de-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = michote <reischuck.micha@googlemail.com>
HOMEPAGE =
