NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = WhitePages Call Log Phone Lookup
DESCRIPTION = Lookup any number from your call log in the WhitePages for webOS App. Get the name, address, and more.
CATEGORY = Phone
VERSIONS = 1.4.5-153 2.0.0-46 2.0.1-76 2.1.0-88 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/b/b5/Phone-whitepages-call-log-phone-lookup-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = spdsktr <erupnu@gmail.com>
HOMEPAGE = http://www.whitepages.com
