NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Multi Patch
DESCRIPTION = Combines confirm delete, enable landscape, and swap reply2all with move patches.  I give all credit to jhoff80, SirWill, dBsooner, and Jason Robitaille for the original patches.  Thanks Jason Robitaille again for the UnifiedDiffCreator program.
CATEGORY = Email
VERSIONS = 1.3.5-13 1.4.1-1
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/f/f9/Email-multi-patch-1.png\",\
\"http://www.webos-internals.org/images/d/d5/Email-multi-patch-2.png\",\
\"http://www.webos-internals.org/images/d/dd/Email-multi-patch-3.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = cwgtex
HOMEPAGE = http://forums.precentral.net/webos-patches/224596-my-email-multi-patch.html
