NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Export Call History
DESCRIPTION = Adds a menu item to the Phone app to export your call history to /media/internal/calllog.csv
CATEGORY = Phone
VERSIONS = 2.2.4-49
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = MetaView <metaview@web.de>
HOMEPAGE = http://forums.webosnation.com/webos-patches/313011-export-call-history.html