NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = 5x4 Icons v2
DESCRIPTION = This will modify the App launcher to display 5x4 icons rather than 3x4. This is an alternate version made by flare576. It has different spacing and properly word wraps.
CATEGORY = App Launcher
VERSIONS = 1.3.5-5 1.4.0-3 1.4.1-1 1.4.2-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/9/93/5x4-icons.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = flare576, dBsooner 
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Launcher_To_Allow_More_Icons_Per_Row
