#!/bin/sh

APPID=mobi.optware.zlib

# Symlink files into /opt
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find lib -type d -exec mkdir -p /opt/{} \;
find lib -type f -exec ln -sf $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt/{} /opt/{} \;
ln -sf libz.so.1.2.3 /opt/lib/libz.so
ln -sf libz.so.1.2.3 /opt/lib/libz.so.1

exit 0
