NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = 3000 Autoreplace Words
DESCRIPTION = This will make the autoreplace contain 3000 words based on the top 3000 google words. This will not cause any lag.
CATEGORY = Mojo
VERSIONS = 1.3.5-5 1.4.0-3 v1.4.1-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = 
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = diomark, dBsooner 
HOMEPAGE = 
