#!/bin/sh

PID="org.webosinternals.preware"

# Handle execution as pmPreRemove.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Stop the service
/sbin/stop ${PID} || true
umount /opt || true

# Remove the upstart script
rm -f /etc/event.d/${PID} /var/palm/event.d/${PID}

# Remove the profile script
rm -f /etc/profile.d/${PID}

exit 0
