#!/bin/sh

APPID=org.webosinternals.optware

# Handle execution as pmPreRemove.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Stop the service
/sbin/stop ${APPID} || true
umount /opt || true

# Remove the upstart script
rm -f /etc/event.d/${APPID} /var/palm/event.d/${APPID}

# Remove the profile script
rm -f /etc/profile.d/${APPID}

exit 0
