NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Reset to First Page
DESCRIPTION = This patch resets the Launcher to the first page, rather than re-opening at the last page used. It also scrolls each page back to the top.
CATEGORY = App Launcher
VERSIONS = 1.3.5-12 1.4.0-21
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = IMGrant <ian@iangrant.me>
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Launcher_Reset_to_First_Page