NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Add Move to Folder Button
DESCRIPTION = Adds a 'Move to Folder' button in email messages.
CATEGORY = Email
VERSION = 1.2.1-19
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Jason Robitaille <robitaille88@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/212150-patch-altered-email-message-button-layout.html
