NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Bookmarks Tile Button
DESCRIPTION = Adds a bookmarks button that brings up the start page with the tiled bookmarks
CATEGORY = Browser
VERSIONS = 1.4.5-1 2.0.0-26 2.0.1-39 2.1.0-3
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/219787-patch-bookmarks-button-browser.html#post2093883