NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Hide YouTube App
DESCRIPTION = This patch will hide the YouTube Application (as per request).
CATEGORY = App Launcher
VERSIONS = 1.3.5-21
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1 

include ../common.mk

include ../modifications.mk

MAINTAINER = veritas06 (Sean McAdam) <SPM7654@optonline.net>
HOMEPAGE = http://forums.precentral.net/web-os-development/226837-patch-requests-youtube-browser.html#post2201710