NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TITLE = Device Menu Maxed Out
DESCRIPTION = Adds date and battery level to Bright<br/>Screen brightness & media volume control<br/>Phone submenu (radio data roaming) toggles<br/>GPS toggle<br/>Flashlight led toggle<br/>To the Devicemenu
CATEGORY = System
VERSIONS = 1.4.5-63
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/e/ea/System-devicemenu-maxed-out-1.png\",\
\"http://www.webos-internals.org/images/0/04/System-devicemenu-maxed-out-2.png\",\
\"http://www.webos-internals.org/images/d/da/System-devicemenu-maxed-out-3.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Warlord9159
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2649380#post2649380
