#!/bin/sh

if [ "`readlink /usr/local/bin/du`" = "/var/usr/palm/applications/org.webosinternals.fairdinkum/du" ] ; then
  rm -f /usr/local/bin/du
fi

if [ "`readlink /usr/local/bin/ipkg`" = "/var/usr/palm/applications/org.webosinternals.fairdinkum/ipkg" ] ; then
  rm -f /usr/local/bin/ipkg
fi

exit 0
