NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = German - Change top bar to Just Type
DESCRIPTION = This patch will change the text of the Just Type bar from 'Einfach lostippen...' to 'Just Type'.
CATEGORY = Top Bar
VERSIONS = 2.1.0-2 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/d/db/Top-bar-german---change-top-bar-to-just-type-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = pcworld <0188801@gmail.com>
HOMEPAGE =
