#!/bin/sh

APPID=mobi.optware.lzo

# Remove files from /opt
rm -f /opt/lib/liblzo2.so /opt/lib/liblzo2.so.2
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find lib -depth -type f -exec rm -f /opt/{} \;
find lib -depth -type d -exec rmdir /opt/{} \;

exit 0
