NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Replies Forwards Multi Mod 10pt Arial Black
DESCRIPTION = This will change the reply to a 10 pt, black Arial font. Also changes the Reply to remove the 'John Smith wrote' text and replace it with the typical 'From: ... To: ...' language that Outlook displays.<br/><br/>This patch is currently not compatible with Replies/Forwards in Black Font. Must remove before you try to apply this patch.
CATEGORY = Email
VERSIONS = 1.3.5-21
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/2/2d/Email-replies-forwards-multi-mod-10pt-arial-black-1.png\" ]
META_SUB_VERSION = 1 

include ../common.mk

include ../modifications.mk

MAINTAINER = bpdamas, mikePre, Jonolee
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2195132&posted=1#post2190051