NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TWEAKS =
TITLE = No skip limit for Pandora Tablet
DESCRIPTION = This patch disables the skip limit service on Pandora Tablet, allowing for unlimited skips. Make sure to remove before updating. The patch can be applied again afterwards.To download Pandora Tablet, go to http://developer.palm.com/appredirect/?packageid=com.drewksparks.pandora-tablet in the default Touchpad browser.
CATEGORY = Misc
VERSIONS = 3.0.5-15
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = drewksparks <drewksparks@gmail.com>
HOMEPAGE = http://twitter.com/drewksparks