NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Add Select All and New Message
DESCRIPTION = Adds the missing 'Select All' feature plus a 'Compose New' option in the context menu.
CATEGORY = Messaging
VERSIONS = 1.3.5-12 1.4.0-21 1.4.1-1 1.4.2-1 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/f/f4/Messaging-add-select-all-and-new-message-1.png\",\
\"http://www.webos-internals.org/images/4/47/Messaging-add-select-all-and-new-message-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/219658-patch-added-shortcut-messaging.html
