NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Unthrottle Download Manager
DESCRIPTION = This patch significantly speeds up downloads, especially over wifi. The Pre comes stock limited to 64kb/sec downloads (noticible especially in DrPodder/etc) - this patch unthrottles it.
CATEGORY = Misc
VERSIONS = 1.3.5-21 1.4.0-10 1.4.1-1 1.4.2-1 1.4.5-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = diomark
HOMEPAGE = http://forums.precentral.net/webos-patches/210774-patch-unthrottle-download-manager.html
