NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Total Message Count
DESCRIPTION = Adds the total number of messages to chatview header of each conversation which will update as messages are sent, received, or deleted.
CATEGORY = Messaging
VERSIONS = 1.4.0-37 1.4.1-6
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/3/3c/Messaging-total-message-count-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/238268-patch-total-message-count.html