NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = Cycle Wi-Fi in Device Menu
DESCRIPTION = Pre 2.2.4 has daddy issues. I mean Wi-Fi issues. Sometimes, turning Wi-Fi off and on again is the quickest fix. This patch adds a Cycle Wi-Fi option to the Device Menu. If Wi-Fi is ON, it will turn it OFF and ON again. If  Wi-Fi is OFF already, it will simply turn it ON. YMMV. Feedback appreciated.
CATEGORY = Top Bar
VERSIONS = 2.2.4-58
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GuyFromNam <GuyFromNam@hotmail.com>
HOMEPAGE =