NAME = confirm-delete
PATCH = /email/${NAME}.patch
TITLE = Confirm Delete Email
DESCRIPTION = Adds confirmation when swipe deleting emails
CATEGORY = Email
VERSION = 0.1.16
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png

include ../common.mk
include ../modifications.mk
