NAME = confirm-delete
PATCH = /email/${NAME}.patch
TITLE = Confirm Delete Email
DESCRIPTION = Adds a confirmation prompt after swipe-to-deleting an email.
CATEGORY = Email
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/0/01/Confirm-delete.png\"]
META_VERSION = 1

include ../common.mk
include ../modifications.mk
