NAME = confirm-delete
PATCH = /email/${NAME}.patch
TITLE = Confirm Delete Email
DESCRIPTION = Adds confirmation when swipe deleting emails
CATEGORY = Email

include ../common.mk
include ../modifications.mk
