NAME = $(shell basename $(shell pwd))
PATCH = clock/${NAME}.patch
TITLE = Lock Alarm and Clock to portrait
DESCRIPTION = When opening the clock application, this patch locks Alarm and Clock in portrait view.
CATEGORY = Clock
VERSIONS = 1.4.5-90
ICON = http://www.webos-internals.org/images/8/8d/Icon_WebOSInternals_Patches_Clock.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Warlord9159
HOMEPAGE = http://forums.precentral.net/webos-patches/265609-request-alarm-clock-portrait-mode.html#post2715134
