NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = Add Date dd-MM-yy  Period as Delimiter
DESCRIPTION = Adds the date to the top bar next to the time in format dd.MM.yy (e.g. 19.06.11).<br/>Based on patches by tk102 and dirtygeek.
CATEGORY = Top Bar
VERSIONS = 1.4.5-159
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Olodin
HOMEPAGE =
