NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TWEAKS =
TITLE = Bridge Call Dialer Launcher
DESCRIPTION = Create an item in the Calendar Event application menu that launches the 'Bridge Call Dialer' App.
CATEGORY = Calendar
VERSIONS = 1.4.5-141 2.1.0-33 2.2.0-46 2.2.3-39
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ahub <ahub@ahub-dev.com>
HOMEPAGE = www.ahub-dev.com