NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Slider answers to speaker
DESCRIPTION = Modifies the phone app to answer a call in speaker phone mode when answered via the slider.  Much safer and easier when driving.
CATEGORY = Phone
VERSIONS = 1.2.1-21 1.3.1-20 1.3.5-1 1.4.0-1
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = wtgreen <wt.green@bigfoot.com>
HOMEPAGE = http://forums.precentral.net/web-os-development/210466-app-tweak-request-speaker-phone-answer.html
