#!/bin/sh

APPID=mobi.optware.ipkg-opt

# Symlink files into /opt
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find bin lib share -type d -exec mkdir -p /opt/{} \;
find bin lib share -type f -exec ln -sf $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt/{} /opt/{} \;
ln -sf ipkg /opt/bin/ipkg-opt
ln -sf libipkg.so.0.0.0 /opt/lib/libipkg.so
ln -sf libipkg.so.0.0.0 /opt/lib/libipkg.so.0

mkdir -p /opt/etc/ipkg

# Install optware feeds
echo "src/gz cross  http://ipkg.nslu2-linux.org/feeds/optware/`/bin/uname -m`/cross/unstable" > /opt/etc/ipkg/optware.conf
echo "src/gz native  http://ipkg.nslu2-linux.org/feeds/optware/`/bin/uname -m`/native/unstable" >> /opt/etc/ipkg/optware.conf
echo "src/gz kernel http://ipkg.nslu2-linux.org/feeds/optware/device-`/bin/uname -m`/cross/unstable" >> /opt/etc/ipkg/optware.conf
sed -i -e 's|device-armv7l|pre|g' /opt/etc/ipkg/optware.conf
sed -i -e 's|device-armv6l|pixi|g' /opt/etc/ipkg/optware.conf
sed -i -e 's|device-i686|pre-emulator|g' /opt/etc/ipkg/optware.conf
sed -i -e 's|armv7l|cs08q1armel|g' /opt/etc/ipkg/optware.conf
sed -i -e 's|armv6l|cs08q1armel|g' /opt/etc/ipkg/optware.conf
sed -i -e 's|i686|i686g25|g'       /opt/etc/ipkg/optware.conf

exit 0
