NAME = $(shell basename $(shell pwd))
PATCH = camera/${NAME}.patch
TWEAKS =
TITLE = Veer Photo Video Naming
DESCRIPTION = Jason's Pre naming patches for photo and video (all credit to him) combined and adapted for Veer. This no be no Pre. GFN says HI.
CATEGORY = Camera
VERSIONS = 2.1.2-103
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GuyFromNam <GuyFromNam@hotmail.com>
HOMEPAGE =