NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TWEAKS =
TITLE = Disable Lock Screen
DESCRIPTION = Disables lock screen (swipe to unlock) on touchpad. Does not disable pin/password screens.
CATEGORY = Screen Lock
VERSIONS = 3.0.5-3
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = kyle3om <kyle3om@yahoo.com>
HOMEPAGE = http://forums.precentral.net/hp-touchpad-homebrew/301645-new-patch-disable-screen-lock-touchpad.html#post3185113
