NAME = $(shell basename $(shell pwd))
PATCH = music-player/${NAME}.patch
TWEAKS =
TITLE = Save Playlist in Stock Music Player
DESCRIPTION = For those who want to experience why Palm didn't include this crappy feature in the stock music player.
CATEGORY = Music Player
VERSIONS = 2.2.4-56
ICON = http://www.webos-internals.org/images/d/df/Icon_WebOSInternals_Patches_Musicplayer.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GuyFromNam <GuyFromNam@hotmail.com>
HOMEPAGE =