NAME = hidden-clock
PATCH = /clock/${NAME}.patch
TITLE = hidden clock patch
DESCRIPTION = ???
CATEGORY = Clock
VERSION = 0.1.16
ICON = http://www.webos-internals.org/images/8/8d/Icon_WebOSInternals_Patches_Clock.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
