NAME = hidden-clock
PATCH = /clock/${NAME}.patch
VERSION = 0.1.2
TITLE = hidden clock patch
DESCRIPTION = ???
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
