NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Move Popup in Emails
DESCRIPTION = Adds a move-to-folder button with popup in email messages
CATEGORY = Email
VERSIONS = 1.4.5-17
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [ ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = drnull <jdhatfield@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/247490-patch-move-popup-emails-email.html
