NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Mojo FPS Booster
DESCRIPTION = Increases Mojo's FPS to 60 and increases the poll rate for scrolling in order to increase the smoothness of transitions, and drag scrolling. Works best with rmausser's Increase Touch Sensitivity and Smoothness patch.
CATEGORY = Mojo
VERSIONS = 2.1.0-206 2.2.0-75 2.2.3-69 3.0.2-69 3.0.4-32
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ShiftyAxel <jpalmerwatkins@me.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/306180-patch-smartphone-touchpad-mojo-fps-booster-2-x-3-x.html