NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = No Missed Call Callback
DESCRIPTION = Tapping the missed call notification will open the missed call list rather than calling the number.
CATEGORY = Phone
VERSIONS = 2.1.0-22 2.1.1-22 2.1.2-31 2.2.4-40
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Herrie <webos-internals.org@herrie.org>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2207874