NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = No Missed Call Callback
DESCRIPTION = Tapping the missed call notification will open the missed call list rather than calling the number.
CATEGORY = Phone
VERSIONS = 1.3.5-21 1.4.0-10
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2207874#post2207874