NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Swap Reply2All with Move
DESCRIPTION = This will replace the 'Reply to All' button with the 'Move to Folder' menu option. The 'Reply to All' is moved to the menu.
CATEGORY = Email
VERSIONS = 2.1.0-3 2.1.1-22 2.1.2-31 2.2.0-19 2.2.3-19
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = dBsooner, Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/212150-patch-altered-email-message-button-layout.html
