NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS = email/${NAME}.json
TITLE = Mimic Outlook Formatting on Email Reply/Forward
DESCRIPTION = <br/><br/>This patch modifies the formatting of email replies/forwards so that they mimic the formatting of Outlook. The wanted formatting needs to be selected in Tweaks.
CATEGORY = Email
VERSIONS = 2.1.0-240 2.1.1-46 2.1.2-55 2.2.0-117 2.2.3-111 2.2.4-28 3.0.4-59
ICON = http://www.webos-internals.org/images/e/ee/Icon_WebOSInternals_Patches_Plus_Email.png
SCREENSHOTS = 
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = http://forums.precentral.net/enlightened-linux-solutions/291210-patch-mimic-outlook-formatting.html
