NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Mega Mix
DESCRIPTION = This combines multiple broswer patches of fritos1406 and the suggestions of chrislo. This patch will hide icons in browser, icons show while loading a web page , fullscreen browser,no refresh when not active. Includes enable/disable gesture landscape  options in the app menu for the scroll feature using the gesture area in landscape, also adds shortcut keys to the launcher<br/>Enable Gesture Scroll: Gesture+e<br/>Disable Gesture Scroll: Gesture+d<br/>New Card: Gesture+n<br/>Add Bookmark: Gesture+m<br/>Add To Launcher: Gesture+l<br/>Bookmarks: Gesture+b<br/>History: Gesture+h<br/>Share Page: Gesture+s
CATEGORY = Browser
VERSIONS = 1.4.5-103 2.0.0-35 2.0.1-62 2.1.0-16 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/7/7e/Browser-mega-mix-1.png\",\
\"http://www.webos-internals.org/images/8/86/Browser-mega-mix-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =
