NAME = $(shell basename $(shell pwd))
PATCH = video-player/${NAME}.patch
TWEAKS =
TITLE = MP4 Video Downloader
DESCRIPTION = Adds a button to the video player to save any currently playing online mp4 video to /media/internal/downloads/
CATEGORY = Video Player
VERSIONS = 2.1.0-161 2.2.0-21 2.2.3-21
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Videoplayer.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/298388-patch-mp4-video-downloader.html