NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TWEAKS =
TITLE = Bigger Active Screen when minimized
DESCRIPTION = This patch gives the touchpad a bigger active screen when the app is minimized. Check the pictures. It's easier to see than describe. It also makes the apps closer together to fit more on the screen.
CATEGORY = Misc
VERSIONS = 3.0.2-43
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = kyle3om <kyle3om@yahoo.com>
HOMEPAGE =