NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TWEAKS =
TITLE = Bigger Active Screen when minimized
DESCRIPTION = This patch gives the Touchpad a bigger active card size when apps are minimized. It also makes the cards closer together to fit more on the screen.
CATEGORY = Misc
VERSIONS = 3.0.2-55 3.0.4-9
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = kyle3om <kyle3om@yahoo.com>
HOMEPAGE =
