NAME = $(shell basename $(shell pwd))
PATCH = video-player/${NAME}.patch
TWEAKS =
TITLE = Tap on the right half to pause
DESCRIPTION = This patch allows you to pause a video by tapping on the right half of the screen. The menu will not pop up. You can still use the left half of the screen to bring the menu up.
CATEGORY = Video Player
VERSIONS = 2.1.0-164 2.1.1-22 2.1.2-31 2.2.0-29 2.2.3-29
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Videoplayer.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = pcworld <0188801@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/298653-patch-videos-tap-right-half-pause.html
