NAME = $(shell basename $(shell pwd))
PATCH = advanced/${NAME}.patch
FILES = advanced/${NAME}.tar.gz
TITLE = Advanced System Prefs - Messaging Prefs (ATT/VZW)
DESCRIPTION = * Requires Advanced System Prefs Framework patch to function properly!<br/><br/>Adds per account notification configuration for messaging app. Also adds support for notification settings for SMS received from unknown contacts and per contact notification configuration.
CATEGORY = Advanced
VERSIONS = 2.1.0-165 2.2.3-38
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/4/4d/AdvancedSystemPrefsMessaging_1.jpg\",\"http://www.webos-internals.org/images/3/35/AdvancedSystemPrefsMessaging_2.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = http://forums.precentral.net/enlightened-linux-solutions/269550-patch-advanced-system-prefs-2-x.html
