NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Reverse number lookup GERMAN
DESCRIPTION = This patch adds an option to the call log to do a reverse lookup of a phone number using dasoertliche.de. This patch is based in James Harris White Pages reverse lookup patch! Thanks James!
CATEGORY = Phone
VERSIONS = 1.4.5-157 2.1.0-100 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/6/6b/Phone-reverse-number-lookup-german-1.png\",\
\"http://www.webos-internals.org/images/5/5a/Phone-reverse-number-lookup-german-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Marcel Meissel
HOMEPAGE = http://webos.r11gs.de/
