NAME = $(shell basename $(shell pwd))
PATCH = video-player/${NAME}.patch
TITLE = Edit and Share Any Video
DESCRIPTION = Allows you to edit (trim) any and share videos besides those that have been captured by the pre. Such as downloaded/uploaded videos.
CATEGORY = Video Player
VERSIONS =
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Videoplayer.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/3/37/Video-player-edit-and-share-any-video-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/242611-patch-edit-share-videos-besides-those-video-roll.html
