NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = Dim Screen After 1 Hour
DESCRIPTION = Adds a 1 Hour timer value to the list: Nevah. Just sick of tapping the screen to keep it from dimming.
CATEGORY = System
VERSIONS = 2.2.4-55
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GuyFromNam <GuyFromNam@hotmail.com>
HOMEPAGE =