NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Email Read All Delete All
DESCRIPTION = Patch to mark emails read all or delete all.
CATEGORY = Email
VERSIONS = 2.0.0-44 2.0.1-72 2.1.0-43 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =
