NAME     = daliclock
APP_ID   = org.jwz.${NAME}
VERSION  = 2.29.0
HOMEPAGE = http://www.jwz.org/${NAME}/
SECTION  = Clocks and Timers

SRC_IPKG = http://www.jwz.org/xdaliclock/${NAME}-229.ipk
include ../../support/download.mk

include ../../support/application-copy.mk
