NAME = $(shell basename $(shell pwd))
PATCH = universal-search/${NAME}.patch
TWEAKS =
TITLE = Secure Universal Search
DESCRIPTION = This patches things so that searches to Google, Wikipedia, Twitter, Amazon & Youtube are done over HTTPS.On the TouchPad, only Google, Wikipedia & Twitter are supported.
CATEGORY = Universal Search
VERSIONS = 2.2.0-113 2.2.4-23 3.0.4-55
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = codecrumb
HOMEPAGE = twitter.com/warthogkernel