NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Stop ability to delete text and call history
DESCRIPTION = Remove ability to delete text messages and phone call history. <br/><br/>To help with the monitoring of your child's conversations.<br/><br/>If they know how to install Preware, they can remove this patch.<br/>I give it a name that has no reference to what this patch changes.<br/><br/>NOTE: This patch modifies many different Palm packages, so it will likely not work for OTA updates. Users may need to EPR to remove it and update it.
CATEGORY = Misc
VERSIONS = 1.4.5-121
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Warlord9159
HOMEPAGE = http://m.forums.precentral.net/webos-patches/272012-patch-remove-ability-delete-text-messages-phone-call-history.html
