NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TWEAKS =
TITLE = Increase Touch Sensitivity and Smoothness
DESCRIPTION = This patch will increase the touch sensitivity and smooth the scrolling of WebOS. What this means is that scrolls and other behaviours will be more precise and smoother (which has been a critique of WebOS for a long time), giving the smooth visual appearance of some 'other' smartphone OSes out there. Basically it attempts to fix the jitteriness that WebOS sometimes displays when scrolling or loading elements/apps.
CATEGORY = Misc
VERSIONS = 1.4.5-180 2.1.0-208 2.2.0-79 2.2.3-73 3.0.2-72 3.0.4-35
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mau
HOMEPAGE =