NAME = $(shell basename $(shell pwd))
PATCH = app-catalog/${NAME}.patch
TITLE = Hide App Vendors
DESCRIPTION = Makes it easier to hide applications from vendors you don't like, be it because of spam or other reasons. By 'hide' I mean 'dim to make it easier to ignore' because due to certain aspects of how the App Catalog application is implemented, I can't find a way to hide them without breaking the app.<br/><br/>Oh and there's an easter egg.
CATEGORY = App Catalog
VERSIONS = 1.3.5-25 1.4.0-29 1.4.1-1 1.4.2-1 1.4.5-28
ICON = http://www.webos-internals.org/images/0/03/Icon_WebOSInternals_Patches_Findapps.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/7/7b/App-catalog-hide-app-vendors-1.png\",\
\"http://www.webos-internals.org/images/a/a3/App-catalog-hide-app-vendors-2.png\",\
\"http://www.webos-internals.org/images/3/3a/App-catalog-hide-app-vendors-3.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = dsevil <dse@webonastick.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/220335-patch-hide-app-vendors.html