NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Smooth Scrolling
DESCRIPTION = Patch for the scroll bar widget. This Eliminates the flicker at the beginning of scrolling, makes it more smooth.
CATEGORY = Mojo
VERSIONS = 1.4.5-118
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = bright2k <bright2k@gmail.com>
HOMEPAGE =