NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Smooth Scrolling
DESCRIPTION = Patch for the scroll widget. This Eliminates the flicker at the beginning of scrolling, makes it more smooth.
CATEGORY = Mojo
VERSIONS = 1.4.5-158 2.1.0-105 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = bright2k <bright2k@gmail.com>
HOMEPAGE =
