NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Confirm Delete
DESCRIPTION = Adds a confirmation prompt after swipe-to-deleting an email.
CATEGORY = Email
VERSIONS = 1.2.1-1 1.1.3-1 1.3.1-1 1.3.5-1
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/0/01/Confirm-delete.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = jhoff80
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Email_Confirm_Deletion
