NAME = $(shell basename $(shell pwd))
PATCH = /email/${NAME}.patch
TITLE = Confirm Delete
DESCRIPTION = Adds a confirmation prompt after swipe-to-deleting an email.
CATEGORY = Email
VERSION = 1.2.1-0
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/0/01/Confirm-delete.png\"]
META_VERSION = 1.2.1-0

include ../common.mk
include ../modifications.mk
