#!/bin/sh

APPID=mobi.optware.readline

# Symlink files into /opt
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find lib -type d -exec mkdir -p /opt/{} \;
find lib -type f -exec ln -sf $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt/{} /opt/{} \;
ln -sf libhistory.so.6.0 /opt/lib/libhistory.so
ln -sf libhistory.so.6.0 /opt/lib/libhistory.so.6
ln -sf libreadline.so.6.0 /opt/lib/libreadline.so
ln -sf libreadline.so.6.0 /opt/lib/libreadline.so.6

exit 0
