NAME = $(shell basename $(shell pwd))
PATCH = photos/${NAME}.patch
TITLE = Preload More Thumbnail Photos
DESCRIPTION = Increases the number of thumbnail photos the Photos app preloads from 30 to 999. Scrolling in the thumbnail view will now show less empty thumbnails and more of your photos. Also preloads the first 24 photos (up from 15) before entering the selected Album.
CATEGORY = Photos
VERSIONS = 1.4.5-17
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = opacityzero
HOMEPAGE = http://forums.precentral.net/webos-patches/256455-patch-preload-more-photos-photos.html
