NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Rotated Battery Icon and Percentage White
DESCRIPTION = This patch implements the 'Battery Icon and Percent' white text patch, but rotates the battery icon to place it directly above the percentage, resulting in a cleaner, more space-efficient display. Not recommended for those with poor eyesight. Remember to uninstall all other Battery icon patches!
CATEGORY = Top Bar
VERSIONS = 1.4.0-41 1.4.1-11 1.4.2-1 1.4.5-1
ICON = http://www.webos-internals.org/images/a/a2/Icon_WebOSInternals_Patches_Percent.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Vincent Law <webmaster@sorrowind.net>, nesl247, Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/242657-patch-rotated-battery-icon-percentage.html
