NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Disable flash pause when browser minimized
DESCRIPTION = This patch disables flash player pause when stock browser minimized.
CATEGORY = Browser
VERSIONS = 2.1.1-62
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = nova_ck
HOMEPAGE =