NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Glass Effect
DESCRIPTION = This is my first patch. It gives the launcher a sexy glass effect rather than the rather ugly default gray. I am hoping to update the patch so that the glass effect persists across WebOS in menus and splash screens etc. This work was inspired by discolightning's Lite Launcher Patch.
CATEGORY = App Launcher
VERSIONS = 1.4.1-12 1.4.2-1 1.4.5-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/6/63/App-launcher-glass-effect-1.png\",\
\"http://www.webos-internals.org/images/2/20/App-launcher-glass-effect-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = SqyArc
HOMEPAGE = http://forums.precentral.net/webos-patches/243026-patch-glass-effect-launcher.html
