NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Add Date MM DD - DE
DESCRIPTION = *DE - only*<br/>Adds the date to the left of the time in the top bar in DD.MM. format.
CATEGORY = Top Bar
VERSIONS = 2.1.0-6 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/d/dd/Top-bar-add-date-mm-dd---de-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = michote <reischuck.micha@googlemail.com>
HOMEPAGE =
