NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Hide MobileHotspot
DESCRIPTION = Hides Mobile Hotspot icon.
CATEGORY = App Launcher
VERSIONS = 1.4.0-30 1.4.1-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mhous33
HOMEPAGE = http://forums.precentral.net/webos-patches/235614-hide-mobile-hotspot-per-request.html
