NAME = $(shell basename $(shell pwd))
PATCH = contacts/${NAME}.patch
TITLE = Swipe to Delete
DESCRIPTION = This patch adds the ability to swipe to delete in the contacts list view, rather than having to tap the contact to view its details and then choose delete from the app menu.
CATEGORY = Contacts
VERSIONS = 1.3.5-9 1.4.0-3 v1.4.1-1
ICON = http://www.webos-internals.org/images/c/ca/Icon_WebOSInternals_Patches_Contacts.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/d/d9/Contacts-swipe-to-delete-1.png\",\
\"http://www.webos-internals.org/images/c/c6/Contacts-swipe-to-delete-2.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = IMGrant <ian@iangrant.me>
HOMEPAGE = http://m.forums.precentral.net/webos-patches/218740-patch-swipe-delete-contacts.html
