NAME = $(shell basename $(shell pwd))
PATCH = camera/${NAME}.patch
TWEAKS =
TITLE = Veer Photo Video Naming-Short Date in Video
DESCRIPTION = Jason's Pre naming patches for photo and video (all credit to him) combined and adapted for Veer. This no be no Pre. This version combines it with Short Date in Video File Name since they seem to conflict. GFN says HI.
CATEGORY = Camera
VERSIONS = 2.1.2-103
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GuyFromNam <GuyFromNam@hotmail.com>
HOMEPAGE =