NAME = $(shell basename $(shell pwd))
PATCH = universal-search/${NAME}.patch
TITLE = Add IMDB
DESCRIPTION = Add IMDB to universal search
CATEGORY = Universal Search
VERSIONS = 1.4.5-36
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/e/e0/Universal-search-add-imdb-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = lexb <lex.brugman@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/260492-patch-add-imdb-one-preware.html
