NAME = $(shell basename $(shell pwd))
PATCH = sounds-and-alerts/${NAME}.patch
TITLE = Increase volume in-call front speaker-a
DESCRIPTION = This should increase the volume of the front speaker.  Install this and/or the b version (seems to be carrier based).  Requires a full power cycle after install.
CATEGORY = Sounds and Alerts
VERSIONS = 2.1.0-30 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Soundsandalerts.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = jc-Treo <jspamc@gmx.net>
HOMEPAGE =
