NAME = $(shell basename $(shell pwd))
PATCH = contacts/${NAME}.patch
TITLE = Block Low Res Contact Photos From Gmail
DESCRIPTION = This patch blocks the contacts app from overwiting your hi resolution contact photos with Googles 100x100 photos. Photos from the phone still sync to Gmail, but not from it.<br/><br/>Use this post to set hi res contact photos: http://forums.precentral.net/showthread.php?p=2913968#post2913968
CATEGORY = Contacts
VERSIONS = 2.0.0-41 2.0.1-68 2.1.0-33 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/c/ca/Icon_WebOSInternals_Patches_Contacts.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = EmC350
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2913981#post2913981
