#!/bin/sh

APPID=mobi.optware.openssl

# Symlink files into /opt
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find * -type d -exec mkdir -p /opt/{} \;
find * -type f -exec ln -sf $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt/{} /opt/{} \;
ln -sf libcrypto.so.0.9.8 /opt/lib/libcrypto.so
ln -sf libcrypto.so.0.9.8 /opt/lib/libcrypto.so.0
ln -sf libssl.so.0.9.8 /opt/lib/libssl.so
ln -sf libssl.so.0.9.8 /opt/lib/libssl.so.0

exit 0
