NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = Muffle System Logging
DESCRIPTION = By default, webOS tends to log pretty much everything. This patch turns logging down so that it only logs errors or worse.
CATEGORY = System
VERSIONS = 3.0.5-3
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = WebOS Internals, Canuck Software
HOMEPAGE =