NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = iPhone Style
DESCRIPTION = This is a patch that will format your messenger to be very similar to the iphones.  Best when used with solid balloons...
CATEGORY = Messaging
VERSIONS = 1.3.1-13 1.3.5-3 1.4.0-1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/e/e0/Messaging-iphone-style-1.jpg\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Elryon <elryon@gmail.com>, dBsooner <webos@dbsooner.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/213063-patch-request-messaging-app-like-iphones-11.html#post2037734
