NAME = $(shell basename $(shell pwd))
PATCH = youtube/${NAME}.patch
TITLE = Enable Landscape
DESCRIPTION = This will enable landscape mode. It uses accelerometer to detect orientation. You also need a 400x400 background or it looks odd.
CATEGORY = YouTube
VERSIONS = 1.4.5-131 2.0.0-30 2.0.1-52 2.1.0-4 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/8/8b/Icon_WebOSInternals_Patches_Youtube.png
SCREENSHOTS =
META_SUB_VERSION = 3

include ../common.mk

include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/208473-landcape-orientation-patches.html
