NAME = youtube-enable-landscape
PATCH = youtube/youtube-enable-landscape.patch
TITLE = Enable Landscape YouTube
DESCRIPTION = This will enable landscape mode. It uses accelerometer to detect orientation. You also need a 400x400 background or it looks odd.
CATEGORY = YouTube
VERSION = 1.2.1-8
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 2

include ../common.mk
include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/208473-landcape-orientation-patches.html
