NAME = $(shell basename $(shell pwd))
PATCH = google-maps/${NAME}.patch
TWEAKS = google-maps/${NAME}.json
TITLE = Multilingual Google Maps
DESCRIPTION = Changes Google Maps defaults to selected language. make sure you load the app twice for the changes to take effect
CATEGORY = Google Maps
VERSIONS = 2.1.0-65
ICON = http://www.webos-internals.org/images/f/f1/Icon_WebOSInternals_Patch_Plus.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Avner Arbel / palmpreacher <preacher@palmpreacher.com>
HOMEPAGE = www.palmpreacher.com