NAME = $(shell basename $(shell pwd))
PATCH = google-maps/${NAME}.patch
TWEAKS = google-maps/${NAME}.json
TITLE = Multilingual Google Maps
DESCRIPTION = Changes Google Maps defaults to selected language. make sure you load the app twice for the changes to take effect
CATEGORY = Google Maps
VERSIONS = 2.1.0-65 2.1.1-24 2.1.2-32
ICON = http://www.webos-internals.org/images/f/f1/Icon_WebOSInternals_Patch_Plus.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/b/b9/Google-maps-multilingual-google-maps-1.png\",\
\"http://www.webos-internals.org/images/e/e4/Google-maps-multilingual-google-maps-2.png\",\
\"http://www.webos-internals.org/images/d/d4/Google-maps-multilingual-google-maps-3.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Avner Arbel / palmpreacher <preacher@palmpreacher.com>
HOMEPAGE = www.palmpreacher.com
