NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Hold Tap Context  Menu
DESCRIPTION = Hold tap on a link or picture to pull up the context menu
CATEGORY = Email
VERSIONS = 1.4.5-96 2.0.0-30 2.0.1-52 2.1.0-4 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = n1ce, pcworld
HOMEPAGE = http://forums.precentral.net/webos-patches/265126-patch-email-hold-tap-context-menu.html
