NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Enable Landscape Email
DESCRIPTION = This will enable landscape mode in the Email application. It uses accelerometer to detect orientation.
CATEGORY = Email
VERSIONS = 1.3.5-10 1.4.0-20 1.4.1-1 1.4.2-1
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/5/5a/Enable-landscape-email.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = user <andrewboudreau@gmail.com>, SirWill, dBsooner
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Email_Enable_Landscape_Viewing
