NAME = $(shell basename $(shell pwd))
PATCH = memos/${NAME}.patch
TWEAKS =
TITLE = Export Notes
DESCRIPTION = Grants the Export Notes app permission to read the notes database so it can wirte all notes into a text file on the usb partition.
CATEGORY = Memos
VERSIONS = 2.1.0-280 2.1.1-120 2.1.2-120 2.2.4-97
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Garfonso
HOMEPAGE = http://webos.mobo.info