NAME = $(shell basename $(shell pwd))
PATCH = google-maps/${NAME}.patch
TITLE = Auto Enable and Disable GPS for Maps
DESCRIPTION = This will turn on GPS when launching Maps and then turn it off, when exiting Maps. If GPS already on, when launching Maps, it will not turn GPS off, when exiting Maps.
CATEGORY = Google Maps
VERSIONS = 1.4.1-15 1.4.2-1
ICON = http://www.webos-internals.org/images/c/c3/Icon_WebOSInternals_Patches_SprintNav.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Ryhor Burakou <ahsirg@gmail.com>
HOMEPAGE =
