NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Bookmarks List Button
DESCRIPTION = Adds a bookmarks-list button that brings up the list view of bookmarks.
CATEGORY = Browser
VERSIONS = 2.1.0-3 2.1.1-22 2.1.2-31 2.2.0-19 2.2.3-19 2.2.4-14
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/219793-bookmarks-list-button-browser.html#post2093927