NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Bookmarks List Button
DESCRIPTION = Adds a bookmarks-list button that brings up the list view of bookmarks.
CATEGORY = Browser
VERSIONS = 1.4.5-1 2.0.1-45 2.1.0-3
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/219793-bookmarks-list-button-browser.html#post2093927