NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = Show UMTS and HSDAP icon instead of 3G
DESCRIPTION = This patch modifies to 3G icon to show either the UMTS or HSDAP icon.
CATEGORY = Top Bar
VERSIONS = 2.2.0-34 2.2.3-34
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = lexb <lex.brugman@gmail.com>
HOMEPAGE =
