NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TITLE = Move Emergency Call
DESCRIPTION = Moves the 'Emergency Call' button horizontally to the middle of the lock screen, where it is less likely to accidentally be hit by fingers wrapping around the edges of the phone. The previously unused button to the left of the zero is now the 'Cancel' button.
CATEGORY = Screen Lock
VERSIONS = 1.2.1-22 1.3.1-11
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/8/89/Screen-lock-move-emergency-call-1.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Eric Salo <salo@cs.stanford.edu>, dBsooner 
HOMEPAGE = http://forums.precentral.net/webos-patches/212795-patch-move-emergency-call-middle-lock-screen.html
