NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Character Counter With Text Counter
DESCRIPTION = Thanks to HattCzech for Character Counter - great patch!  This patch just displays the current number of multiple text segments before the character counter with a period in between.  This is useful with the Remove Send and Attach Buttons patch.
CATEGORY = Messaging
VERSIONS = 1.4.0-72 1.4.1-45 1.4.2-31 1.4.3-25 1.4.5-46
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Chris Mann <csmann19@gmail.com>
HOMEPAGE =