NAME = $(shell basename $(shell pwd))
PATCH = sounds-and-alerts/${NAME}.patch
TITLE = Charging Alert Vibrate Only
DESCRIPTION = This will change the charging alert sound to vibrate only.
CATEGORY = Sounds and Alerts
VERSIONS = 1.3.5-5 1.4.0-3 v1.4.1-1
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Soundsandalerts.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = a2ny <A2NY.Sinister@gmail.com>, dBsooner 
HOMEPAGE =
