NAME = $(shell basename $(shell pwd))
PATCH = sounds-and-alerts/${NAME}.patch
TITLE = Charging Alert Vibrate Only
DESCRIPTION = This will change the charging alert sound to vibrate only.
CATEGORY = Sounds and Alerts
VERSIONS = 2.0.1-45
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Soundsandalerts.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ART-ifact
HOMEPAGE =