NAME = app-launcher-remove-icon-titles
PATCH = app-launcher/app-launcher-remove-icon-titles.patch
TITLE = Remove Icon Titles
DESCRIPTION = This will remove the titles from under the icons. Recommended: The 4x4-Icons-v3 for the larger icons.
CATEGORY = App Launcher
VERSION = 1.2.1-7
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/2/22/App-launcher-remove-launcher-icon-titles-1.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Abyssul <Time4swim@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=1993916
