NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Remove Icon Titles
DESCRIPTION = This will remove the titles from under the icons. Recommended: The 4x4-Icons-v3 for the larger icons.
CATEGORY = App Launcher
VERSIONS = 1.3.5-3 1.4.0-3 1.4.1-1 1.4.2-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/2/22/App-launcher-remove-launcher-icon-titles-1.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Abyssul <Time4swim@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=1993916
