NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Black Font in Launcher
DESCRIPTION = This changes the White font when in launcher to Black
CATEGORY = App Launcher
VERSIONS = 1.3.1-36 1.3.5-19 1.4.0-8
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/b/bf/App-launcher-black-font-in-launcher-1.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = 2sslow
HOMEPAGE = http://forums.precentral.net/webos-patches/226174-patch-launcher-black-font.html