NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Advanced Configuration for App Launcher
DESCRIPTION = This patch adds the following advanced functionality in the app launcher:<br/><br/>- Edit mode for adding/deleting/renaming and moving launcher pages.<br/><br/>- Configuration option for showing/hiding page names with jump to page ability.<br/><br/>- Secondary moving option for moving apps from page to page (orange+tap to a app and select move).<br/><br/>- Configuration for setting default page (page that is opened as a default when launcher is started).<br/><br/>- Configuration option for resetting page position.<br/><br/>- Configuration option for wrapping the launcher pages.<br/><br/>- Configuration for setting quick launch to be visible or hidden all the time or only in the launcher.<br/><br/>This patch conflicts with the patches that provide some of these functionalities.
CATEGORY = App Launcher
VERSIONS = 1.4.0-55 1.4.1-27 1.4.2-12 1.4.3-6 1.4.5-11
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = http://forums.precentral.net/webos-patches/245440-patch-top-bar-system-menus-status-today-device-menus.html