NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = 5x5 Icons v1
DESCRIPTION = This patch is based on the 5x4 icon launcher. It reduces the padding maximizing the screen real estate getting 5 rows of 5 icons not counting the quick launch bar. I recommend also using the no arrow and fade launcher patch. If using one of the hide quick launch patches this is perfect for 5x6 icons.
CATEGORY = App Launcher
VERSIONS = 1.4.5-14
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/9/9f/App-launcher-5x5-icons-v1-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = StoneRyno
HOMEPAGE = http://forums.precentral.net/webos-patches/234279-patch-5x5-icons-app-launcher.html
