NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = 5x5 Icons v1
DESCRIPTION = This patch is based on the 5x4 icon launcher. It reduces the padding maximizing the screen real estate getting 5 rows of 5 icons not counting the quick launch bar.
CATEGORY = App Launcher
VERSIONS = 1.3.5-30 1.4.0-21 1.4.1-1 1.4.2-1 1.4.5-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/9/9f/App-launcher-5x5-icons-v1-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = StoneRyno
HOMEPAGE =
