NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Add Move and Mark Unread Buttons
DESCRIPTION = Adds Move and Mark Unread buttons while viewing emails (removing Reply-To-All and Forward buttons and putting them in the menu instead).  Also, the buttons are re-ordered and Mark Unread returns you back to the list of emails.
CATEGORY = Email
VERSIONS = 2.2.0-49 2.2.3-44
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Chris Mann <sara.ramli@gmail.com>, sara.ramli
HOMEPAGE = http://forums.precentral.net/webos-patches/302391-patch-add-move-mark-unread-buttons.html