NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Add Move and Mark Unread Buttons
DESCRIPTION = Adds Move and Mark Unread buttons while viewing emails (removing Reply-To-All and Forward buttons and putting them in the menu instead).  Also, the buttons are re-ordered and Mark Unread returns you back to the list of emails.
CATEGORY = Email
VERSIONS = 1.4.0-45 1.4.1-16 1.4.2-2 1.4.5-1
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Chris Mann <csmann19@gmail.com>
HOMEPAGE =
