NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Smiley Faces in Symbol Box
DESCRIPTION = Use the sym key and letter K (symbols) or Z (words) to bring up the built-in emoticons list. <br/>(Now has increased language support.)
CATEGORY = Mojo
VERSIONS = 1.3.5-14 1.4.0-24
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/a/a4/Mojo-smiley-faces-in-symbol-box-1.png\",\
\"http://www.webos-internals.org/images/e/eb/Mojo-smiley-faces-in-symbol-box-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam4@gmail.com>, Sarah Peterman
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2134396#post2134396