NAME = $(shell basename $(shell pwd))
PATCH = /mojo/${NAME}.patch
TITLE = Smiley Faces in Symbol Box
CATEGORY = Mojo
VERSION = 0.5.0
DESCRIPTION = This will add smiley faces to symbol box popup.  Sym+k and sym+z offer different smiley faces.
SCREENSHOTS = [\"http://www.webos-internals.org/images/0/0e/Smile-face-sym-box.png\"]
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
