NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Smiley Faces in Symbol Box
DESCRIPTION = This will add smiley faces to symbol box popup.  Sym+k and sym+z offer different smiley faces.
CATEGORY = Mojo
VERSIONS = 1.2.1-1 1.3.5-12
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/a/a4/Mojo-smiley-faces-in-symbol-box-1.png\",\
\"http://www.webos-internals.org/images/e/eb/Mojo-smiley-faces-in-symbol-box-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam4@gmail.com>, Sarah Peterman
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2134396#post2134396
