NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = 5x4 Icons v1
DESCRIPTION = This will modify the App launcher to display 5x4 icons rather than 3x4.
CATEGORY = App Launcher
VERSIONS = 1.3.5-5 1.4.0-3
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/b/b0/More-icons-per-row.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Mitchell <hax-da-hax0rz@hotmail.com>, dBsooner 
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Launcher_To_Allow_More_Icons_Per_Row
