NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Auto Show Dialpad on Call
DESCRIPTION = Automatically shows the dialpad when a call is connected rather than the contact pic.
CATEGORY = Phone
VERSIONS = 1.4.1-7
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2378780#post2378780