NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = Palm Carrier String
DESCRIPTION = Custom carrier string of 'Palm' for the launcher.  Note: also replaces 'phone offline' message.
CATEGORY = Top Bar
VERSIONS = 1.4.5-28 2.1.0-3 2.2.0-19
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/217214-patch-palm-carrier-string.html