NAME = $(shell basename $(shell pwd))
PATCH = camera/${NAME}.patch
TITLE = Improved Filename Format
DESCRIPTION = This will change the filename formate for images taken to be 'PRE_YYYY-MM-DD-hhmmss.jpg'. Where YYYY is the year, MM is the month, DD is the day, hh is the hour in 24-hour format, mm is the minute and ss is the second the picture was taken.
CATEGORY = Camera
VERSION = 1.2.1-13
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
SCREENSHOTS =
META_SUB_VERSION = 2

include ../common.mk
include ../modifications.mk

MAINTAINER = Jason Robitaille <robitaille88@gmail.com>
HOMEPAGE = http://forums.precentral.net/web-os-development/210711-camera-image-filenames.html
