NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Remove Email Trash Can
DESCRIPTION = Remove icon from compose email
CATEGORY = Email
VERSIONS = 2.0.0-40 2.0.1-67 2.1.0-30 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =
