NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Uber Cycling Email Dashboard
DESCRIPTION = Adding timestamp, cycling and delete from the dashboard. Tapping on the email icon pauses/plays the cycling. Also screen off/on does that. Time stamp is system dependent so if you use 12hr format it'll use the correct local but it'll be wider. I find using military or 24hr much more aesthetic and economic screen wise.
CATEGORY = Email
VERSIONS = 2.1.0-278 2.1.1-117 2.1.2-117 2.2.4-94
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = 60RH
HOMEPAGE = http://forums.webosnation.com/webos-patches/324334-patch-cycling-email-notifications-time-stamp-delete-button.html#post3386903