NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TWEAKS =
TITLE = Max Blocker
DESCRIPTION = This is a superset to Ad Blocker. It blocks ads, tracking etc.<br/><br/>If you find that this breaks an app for you, try uninstalling it and using Ad Blocker instead. <br/><br/>WARNING: Only install Max Blocker OR Ad Blocker, not both. Failure to heed this will result in Santa putting you on the naughty list.
CATEGORY = Misc
VERSIONS = 1.4.5-161 2.0.0-53 2.0.1-83 2.1.0-120 3.0.0-22
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = webosinternals
HOMEPAGE =