NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Email Mega Mix
DESCRIPTION = his patch combines the following patches into one outlook formatting with a black font, move and mark emails unread. Incorporated innkeepers deluxe delete next patch<br/>read & delete all, swipe for previous and next email, confirm delete, add priority and discard buttons, send, save, and discard confirmation popup,<br/>and additional sync times and additional sync days/months, adds delete all and read buttons to email folders, and delete from notification.
CATEGORY = Email
VERSIONS = 1.4.5-100 2.0.0-40 2.0.1-67 2.1.0-30
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =