NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Email Mega Mix
DESCRIPTION = This patch combines the following patches into one black font, move to folder, add priority and discard buttons, send, save, and discard confirmation popup, additional sync times and additional sync days/months, adds delete all and read buttons to email folders.
CATEGORY = Email
VERSIONS = 1.4.5-100 2.0.0-41 2.0.1-68 2.1.0-33 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>
HOMEPAGE =
