NAME = reset-scroll
PATCH = /luna/${NAME}.patch
TITLE = Reset Scroll Applauncher
DESCRIPTION = Resets the scroll position back to the top of the page when a page is changed rather than remembering the scroll position
CATEGORY = Luna
VERSION = 0.1.16

include ../common.mk
include ../modifications.mk
