#!/bin/sh

#
# These are expected to be set at packaging time
#

APP_DIR=

PATCH_NAME=

TWEAKS_NAME=

BSPATCH_FILE=

FILES_DIR=additional_files

PACKAGES_FILE=package_list

#
# Here starts the part where all the magic happens
#

VERSION=aupt-5

IPKG_INFO_DIR=/usr/lib/ipkg/info

if [ -z "${IPKG_OFFLINE_ROOT}" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
fi

APP_DIR=${IPKG_OFFLINE_ROOT}${APP_DIR#${IPKG_OFFLINE_ROOT}}

PATCH_LOG_FILE=/media/internal/webos-patches.log
PATCH_CONTROL_DIR=/var/usr/lib/.webosinternals.patches
PATCH_PACKAGES_LIST=/media/internal/.webosinternals.patches.packages

TWEAKS_PREFERENCES_DIR=/media/cryptofs/apps/usr/palm/services/org.webosinternals.tweaks.prefs/preferences

#
# Required applications and their full execute paths
#

PATCH_EXEC=/var/usr/bin/patch
LSDIFF_EXEC=/var/usr/bin/lsdiff
BSPATCH_EXEC=/usr/bin/bspatch

if [ -f /media/cryptofs/apps/usr/bin/patch ]; then
  PATCH_EXEC=/media/cryptofs/apps/usr/bin/patch
fi

if [ -f /media/cryptofs/apps/usr/bin/lsdiff ]; then
  LSDIFF_EXEC=/media/cryptofs/apps/usr/bin/lsdiff
fi

if [ ! -z "${BSPATCH_FILE}" ]; then
  BSPATCH_NAME=`basename ${BSPATCH_FILE}`.bspatch
fi

#
# Helper functions that do all the needed heavy work
#

remount_rw() {
  mount -o rw,remount /
}

do_remove_failure() {
  echo | tee -a ${PATCH_LOG_FILE}
  echo "*** FAILED ***" | tee -a ${PATCH_LOG_FILE}
  echo | tee -a ${PATCH_LOG_FILE}

  rm -f /var/webosinternals.md5sums >/dev/null 2>&1

  exit 1
}

do_remove_success() {
  echo | tee -a ${PATCH_LOG_FILE}
  echo "*** SUCCESS ***" | tee -a ${PATCH_LOG_FILE}
  echo | tee -a ${PATCH_LOG_FILE}

  rm -f /var/webosinternals.md5sums >/dev/null 2>&1

  exit 0
}

uninstallation_failed() {
  echo >> ${PATCH_LOG_FILE}
  echo "----------------------------------" >> ${PATCH_LOG_FILE}
  echo "Patch removal FAILED!" >> ${PATCH_LOG_FILE}
  echo "----------------------------------" >> ${PATCH_LOG_FILE}
  echo >> ${PATCH_LOG_FILE}

  if [ -f ${APP_DIR}/${PATCH_NAME} ]; then
    ${PATCH_EXEC} -s -R -p 1 -d / --dry-run < ${APP_DIR}/${PATCH_NAME} | tee -a ${PATCH_LOG_FILE} 1>&2
  fi

  do_remove_failure
}

get_bck_file() {
  bck_file=`dirname ${file}`"/.webosinternals.orig."`basename ${file}`

	if [ ! -f ${bck_file} ]; then
		bck_file="${file}.webosinternals.orig"
	fi
}

get_palm_md5sum() {
  cur_version=""
  palm_md5sum=""

  check_cache_file

  if [ ! -z "${md5sums_line}" ]; then
    palm_md5sum=`echo ${md5sums_line} | awk '{print $1}'`

    echo "Found md5sum from the cache file" >> ${PATCH_LOG_FILE}
    echo "  md5sum: ${palm_md5sum}" >> ${PATCH_LOG_FILE}
  else
    echo "File not found from cache file, checking packages file" >> ${PATCH_LOG_FILE}

    check_packages_file

    if [ ! -z "${md5sums_line}" ]; then
      palm_md5sum=`echo ${md5sums_line} | awk '{print $1}'`

      echo "Found md5sum via the packages file" >> ${PATCH_LOG_FILE}
      echo "  md5sum: ${palm_md5sum}" >> ${PATCH_LOG_FILE}

      echo ${md5sums_line} >>/var/webosinternals.md5sums
    else
      echo "File not found via packages file, checking cryptofs lists" >> ${PATCH_LOG_FILE}

      check_cryptofs_lists

      if [ ! -z "${md5sums_line}" ]; then
        palm_md5sum=`echo ${md5sums_line} | awk '{print $1}'`

        echo "Found md5sum from the cryptofs lists" >> ${PATCH_LOG_FILE}
        echo "  md5sum: ${palm_md5sum}" >> ${PATCH_LOG_FILE}

        echo ${md5sums_line} >>/var/webosinternals.md5sums
      else
        echo "File not found in cryptofs lists, checking system md5sum files" >> ${PATCH_LOG_FILE}

        md5sums_line=`grep -h "*.${file}$" ${IPKG_INFO_DIR}/*.md5sums`

        if [ ! -z "${md5sums_line}" ]; then
          palm_md5sum=`echo ${md5sums_line} | awk '{print $1}'`

          echo "Found md5sum from md5sums files" >> ${PATCH_LOG_FILE}
          echo "  md5sum: ${palm_md5sum}" >> ${PATCH_LOG_FILE}

          echo ${md5sums_line} >>/var/webosinternals.md5sums
        fi
      fi
    fi
  fi
}

check_cache_file() {
  md5sums_line=""

  if [ -f "/var/webosinternals.md5sums" ]; then
    md5sums_line=`grep ${file} /var/webosinternals.md5sums`
  fi
}

check_packages_file() {
  if [ -f ${APP_DIR}/${PACKAGES_FILE} ]; then
    for p in `cat ${APP_DIR}/${PACKAGES_FILE}` ; do
      md5sums_line=`grep ${file} ${IPKG_INFO_DIR}/${p}.md5sums`

      if [ ! -z "${md5sums_line}" ]; then
        break;
      fi
    done
  fi
}

check_cryptofs_lists() {
  file_line=`grep "^${file#${IPKG_OFFLINE_ROOT}}$" ${IPKG_OFFLINE_ROOT}/${IPKG_INFO_DIR}/*.list`

  if [ ! -z "${file_line}" ]; then
    get_bck_file

    list_file=`echo "${file_line}" | cut -d ':' -f 1`

    package=`basename ${list_file} .list`

    control_file=`dirname ${list_file}`/${package}.control

    cur_version=`grep "^Version: " ${control_file} | awk '{print $2}'`

    control_line=`grep "^${package} ${file} " ${PATCH_CONTROL_DIR}/file_control`

    ctl_version=`echo ${control_line} | awk '{print $3}'`

    if [ ! -f ${bck_file} ] || [ "${cur_version}" != "${ctl_version}" ]; then
      md5sums_line=`md5sum ${file} | awk '{print $1}'`" *.${file}"
    else
      md5sums_line=`md5sum ${bck_file} | awk '{print $1}'`" *.${file}"
    fi
  fi
}

verify_text_patch() {
  if [ -f ${APP_DIR}/${PATCH_NAME} ]; then
    FILE_LIST=" "`${LSDIFF_EXEC} ${APP_DIR}/${PATCH_NAME}`

    echo >> ${PATCH_LOG_FILE}
    echo "----------------------------------" >> ${PATCH_LOG_FILE}
    echo "Dry running patch" >> ${PATCH_LOG_FILE}
    echo "----------------------------------" >> ${PATCH_LOG_FILE}
    echo >> ${PATCH_LOG_FILE}

    ${PATCH_EXEC} -f -R -p 1 -d / --dry-run < ${APP_DIR}/${PATCH_NAME} 2>&1 >> ${PATCH_LOG_FILE}

    if [ ${?} -ne 0 ]; then
      echo >> ${PATCH_LOG_FILE}
      echo "----------------------------------" >> ${PATCH_LOG_FILE}
      echo "Dry run failed, trying without -R" >> ${PATCH_LOG_FILE}
      echo "----------------------------------" >> ${PATCH_LOG_FILE}
      echo >> ${PATCH_LOG_FILE}

      ${PATCH_EXEC} -f -p 1 -d / --dry-run < ${APP_DIR}/${PATCH_NAME} 2>&1 >> ${PATCH_LOG_FILE}

      if [ ${?} -eq 0 ]; then
        echo | tee -a ${PATCH_LOG_FILE}
        echo "Interestingly, the patch seems to be already unapplied" | tee -a ${PATCH_LOG_FILE}
        echo | tee -a ${PATCH_LOG_FILE}

        patch_already_unapplied="yes"
      else
        FAIL_LIST=" "`${PATCH_EXEC} -s -f -R -p 1 -d / --dry-run < ${APP_DIR}/${PATCH_NAME} 2>&1 | \
          awk '{print "/"$12}' | sed s:".rej$":"":`

        if [ "${FAIL_LIST}" = "${FILE_LIST}" ]; then
          patch_already_unapplied="yes"
        fi
      fi
    fi
  fi
}

verify_binary_patch() {
  if [ -f ${APP_DIR}/${BSPATCH_NAME} ]; then
    FILE_LIST="${FILE_LIST} ${BSPATCH_FILE}"

    echo >> ${PATCH_LOG_FILE}
    echo "----------------------------------" >> ${PATCH_LOG_FILE}
    echo "Checking binary patch" >> ${PATCH_LOG_FILE}
    echo "----------------------------------" >> ${PATCH_LOG_FILE}
    echo >> ${PATCH_LOG_FILE}

    file=${BSPATCH_FILE}

    if [ -f ${file} ]; then
      get_palm_md5sum

      file_md5sum=`md5sum ${file} | awk '{print $1}'`

      if [ -z "${palm_md5sum}" ]; then
        FAIL_LIST="${FAIL_LIST} ${file}"

        bspatch_already_unapplied="yes"
      elif [ "${file_md5sum}" = "${palm_md5sum}" ]; then
        echo | tee -a ${PATCH_LOG_FILE}
        echo "Interestingly, the binary file is already unpatched" | tee -a ${PATCH_LOG_FILE}
        echo | tee -a ${PATCH_LOG_FILE}

        bspatch_already_unapplied="yes"
      else
        get_bck_file

        if [ -f ${bck_file} ]; then
          rm -f /var/webosinternals-*

          cp ${bck_file} /var/webosinternals-orig

          ${BSPATCH_EXEC} /var/webosinternals-orig /var/webosinternals-patched ${APP_DIR}/${BSPATCH_NAME} 2>&1

          tmp_md5sum=`md5sum /var/webosinternals-patched | awk '{print $1}'`

          rm -f /var/webosinternals-*
        fi

        if [ "${file_md5sum}" != "${tmp_md5sum}" ]; then
          FAIL_LIST="${FAIL_LIST} ${file}"

          bspatch_already_unapplied="yes"
        fi
      fi
    fi
  fi
}

verify_additional_files() {
  if [ -d ${APP_DIR}/${FILES_DIR} ]; then
    echo >> ${PATCH_LOG_FILE}
    echo "----------------------------------" >> ${PATCH_LOG_FILE}
    echo "Checking additional files" >> ${PATCH_LOG_FILE}
    echo "----------------------------------" >> ${PATCH_LOG_FILE}
    echo >> ${PATCH_LOG_FILE}

    for i in `find ${APP_DIR}/${FILES_DIR} -type f` ; do
      file=${i#${APP_DIR}/${FILES_DIR}}

      FILE_LIST="${FILE_LIST} ${file}"

      get_palm_md5sum

      if [ "${FILES_DIR}" != "files" ] && [ ! -z "${palm_md5sum}" ]; then
        FAIL_LIST="${FAIL_LIST} ${file}"
      fi

      if [ ! -f ${file} ]; then
        echo | tee -a ${PATCH_LOG_FILE}
        echo "Interestingly, the additional file is already removed" | tee -a ${PATCH_LOG_FILE}
        echo "  file: ${file}" | tee -a ${PATCH_LOG_FILE}
        echo | tee -a ${PATCH_LOG_FILE}
      fi
    done
  fi
}

remove_text_patch() {
  if [ -f ${APP_DIR}/${PATCH_NAME} ]; then
    rm -f ${PATCH_CONTROL_DIR}/backup/${PATCH_NAME} >/dev/null 2>&1

    if [ "${patch_already_unapplied}" != "yes" ]; then
      echo | tee -a ${PATCH_LOG_FILE}
      echo "----------------------------------" | tee -a ${PATCH_LOG_FILE}
      echo "Unapplying text patch" | tee -a ${PATCH_LOG_FILE}
      echo "----------------------------------" | tee -a ${PATCH_LOG_FILE}
      echo | tee -a ${PATCH_LOG_FILE}

      ${PATCH_EXEC} -R -p 1 -d / --no-backup-if-mismatch < ${APP_DIR}/${PATCH_NAME} 2>&1 | tee -a ${PATCH_LOG_FILE}
    fi
  fi
}

remove_binary_patch() {
  if [ -f ${APP_DIR}/${BSPATCH_NAME} ]; then
    if [ "${bspatch_already_unapplied}" != "yes" ]; then
      echo | tee -a ${PATCH_LOG_FILE}
      echo "----------------------------------" | tee -a ${PATCH_LOG_FILE}
      echo "Unapplying binary patch" | tee -a ${PATCH_LOG_FILE}
      echo "----------------------------------" | tee -a ${PATCH_LOG_FILE}
      echo | tee -a ${PATCH_LOG_FILE}

      file=${BSPATCH_FILE}

      echo "restoring file ${file#/}" | tee -a ${PATCH_LOG_FILE}

      get_bck_file

      if [ -f ${bck_file} ]; then
        cp -f ${bck_file} ${file} 2>&1 | tee -a ${PATCH_LOG_FILE}

        if [ "${?}" = "1" ]; then
          stop `basename ${file}` >/dev/null 2>&1
          sleep 5

          cp -f ${bck_file} ${file}

          start `basename ${file}` >/dev/null 2>&1
        fi
      fi
    fi
  fi
}

remove_additional_files() {
  if [ -d ${APP_DIR}/${FILES_DIR} ]; then
    echo | tee -a ${PATCH_LOG_FILE}
    echo "----------------------------------" | tee -a ${PATCH_LOG_FILE}
    echo "Removing additional files" | tee -a ${PATCH_LOG_FILE}
    echo "----------------------------------" | tee -a ${PATCH_LOG_FILE}
    echo | tee -a ${PATCH_LOG_FILE}

    for i in `find ${APP_DIR}/${FILES_DIR} -type f` ; do
      file=${i#${APP_DIR}/${FILES_DIR}}

      get_bck_file

      if [ -f ${bck_file} ]; then
        if [ ! -s ${bck_file} ]; then
          echo "removing file ${file#/}" | tee -a ${PATCH_LOG_FILE}

          rm -f ${file} 2>&1 | tee -a ${PATCH_LOG_FILE}
        elif [ "${FILES_DIR}" = "files" ]; then
          echo "reverting file ${file#/}" | tee -a ${PATCH_LOG_FILE}

          cp -f ${bck_file} ${file} 2>&1 | tee -a ${PATCH_LOG_FILE}
        fi
      fi
    done
  fi
}

remove_tweaks_preferences() {
  if [ -f ${APP_DIR}/${TWEAKS_NAME} ]; then
    echo | tee -a ${PATCH_LOG_FILE}
    echo "----------------------------------" | tee -a ${PATCH_LOG_FILE}
    echo "Removing tweaks json file" | tee -a ${PATCH_LOG_FILE}
    echo "----------------------------------" | tee -a ${PATCH_LOG_FILE}
    echo | tee -a ${PATCH_LOG_FILE}

    rm -f ${TWEAKS_PREFERENCES_DIR}/`basename ${APP_DIR}`.json 2>&1 | tee -a ${PATCH_LOG_FILE}
  fi
}

check_ota_update() {
  echo >> ${PATCH_LOG_FILE}
  echo "----------------------------------" >> ${PATCH_LOG_FILE}
  echo "Checking md5sums for ota" >> ${PATCH_LOG_FILE}
  echo "----------------------------------" >> ${PATCH_LOG_FILE}
  echo >> ${PATCH_LOG_FILE}

  for file in ${FILE_LIST} ; do
    if [ -f ${file} ]; then
      get_bck_file

      if [ -f ${bck_file} ]; then
        get_palm_md5sum

        file_md5sum=`md5sum ${file} | awk '{print $1}'`

        orig_md5sum=`grep -h " ${file} " ${PATCH_CONTROL_DIR}/file_md5sums | awk '{print $3}'`

        if [ -z "${palm_md5sum}" ]; then
          CREATED_LIST="${CREATED_LIST} ${file}"
        elif [ "${palm_md5sum}" = "${file_md5sum}" ]; then
          echo "File matches current md5sum, assuming OTA" >> ${PATCH_LOG_FILE}
          echo "  file: ${file}" >> ${PATCH_LOG_FILE}

          cp -f ${file} ${bck_file}

          FAIL_LIST="${FAIL_LIST# ${file}}"

          RESTORE_LIST="${RESTORE_LIST} ${file}"
        elif [ "${palm_md5sum}" != "${orig_md5sum}" ]; then
          echo "The md5sum of file has changed, assuming OTA" >> ${PATCH_LOG_FILE}
          echo "  palm_md5sum: ${palm_md5sum}" >> ${PATCH_LOG_FILE}
          echo "  orig_md5sum: ${orig_md5sum}" >> ${PATCH_LOG_FILE}

          cp -f ${file} ${bck_file}

          FAIL_LIST="${FAIL_LIST# ${file}}"

          RESTORE_LIST="${RESTORE_LIST} ${file}"
        fi
      else
        echo "File has been completely removed, assuming OTA" >> ${PATCH_LOG_FILE}
        echo "  file: ${file}" >> ${PATCH_LOG_FILE}

        FAIL_LIST="${FAIL_LIST# ${file}}"
      fi
    fi
  done

  if [ ! -z "${FAIL_LIST}" ]; then
    uninstallation_failed
  fi
}

clean_backup_files() {
  echo >> ${PATCH_LOG_FILE}
  echo "----------------------------------" >> ${PATCH_LOG_FILE}
  echo "Cleaning up backup files" >> ${PATCH_LOG_FILE}
  echo "----------------------------------" >> ${PATCH_LOG_FILE}
  echo >> ${PATCH_LOG_FILE}

  for file in ${CREATED_LIST} ; do
    get_bck_file

    if [ -f ${file} ]; then
      echo "Removing created file or old system file" >> ${PATCH_LOG_FILE}
      echo "  file: ${file}" >>${PATCH_LOG_FILE}

      rm -f ${file}
    fi
  done

  for file in ${RESTORE_LIST} ; do
    get_bck_file

    if [ -f ${bck_file} ]; then
      echo "Restoring unmodified or updated system file" >> ${PATCH_LOG_FILE}
      echo "  file: ${file}" >>${PATCH_LOG_FILE}

      mv -f ${bck_file} ${file}
    fi
  done

  for file in ${FILE_LIST} ; do
    if [ -f ${file}.rej ]; then
      rm -f ${file}.rej
    fi

    get_bck_file

    get_palm_md5sum

    if [ ! -f ${file} ]; then
      file_md5sum=""
    else
      file_md5sum=`md5sum $file | awk '{print $1}'`
    fi

    if [ ! -f ${bck_file} ]; then
      orig_md5sum=""
    else
      orig_md5sum=`md5sum ${bck_file} | awk '{print $1}'`
    fi

    if [ ! -f ${file} ] && [ ! -s ${bck_file} ] || \
       [ "${file_md5sum}" = "${orig_md5sum}" ] || \
       [ "${file_md5sum}" = "${palm_md5sum}" ]
    then
      if [ -f ${bck_file} ]; then
        if [ ! -s ${bck_file} ]; then
          echo "Removing unneeded generated backup file" >>${PATCH_LOG_FILE}
          echo "  file: ${bck_file}" >>${PATCH_LOG_FILE}
        else
          echo "Removing unneeded backup of system file" >>${PATCH_LOG_FILE}
          echo "  file: ${bck_file}" >>${PATCH_LOG_FILE}
        fi

        rm -f ${bck_file}
      fi

      tmpvar=`echo "${file}" | tr '/' '.'`

      sed -i -e /"^${tmpvar} "/d ${PATCH_CONTROL_DIR}/file_list
    fi

    if [ ! -z "${cur_version}" ]; then
      tmpvar=`echo "${package} ${file}" | tr '/' '.'`

      sed -i -e /"^${tmpvar} "/d ${PATCH_CONTROL_DIR}/file_control
    fi

    if [ ! -z "${palm_md5sum}" ]; then
      appid=`basename ${APP_DIR}`

      tmpvar=`echo "${appid} ${file}" | tr '/' '.'`

      sed -i -e /"^${tmpvar} "/d ${PATCH_CONTROL_DIR}/file_md5sums
    fi
  done

  sed -i -e /\^'`basename ${APP_DIR}` ${VERSION}'\$/d ${PATCH_PACKAGES_LIST}
}

#
# Bunch of safety checks and required initializations
#

if [ ! -f ${PATCH_LOG_FILE} ]; then
  echo "*** Patch Log Created by prerm $(date) ***" > ${PATCH_LOG_FILE}
fi

remount_rw | tee -a ${PATCH_LOG_FILE} 1>&2

echo  >> ${PATCH_LOG_FILE}
echo "------------------------------------------------------" >> ${PATCH_LOG_FILE}
echo "PATCH REMOVAL $(date)" >> ${PATCH_LOG_FILE}
echo "------------------------------------------------------" >> ${PATCH_LOG_FILE}
echo  >> ${PATCH_LOG_FILE}

if [ -f ${APP_DIR}/${PATCH_NAME} ]; then
  echo "Contains text patch: ${PATCH_NAME}" >> ${PATCH_LOG_FILE}
fi

if [ -f ${APP_DIR}/${BSPATCH_NAME} ]; then
  echo "Contains binary patch: ${BSPATCH_NAME}" >> ${PATCH_LOG_FILE}
  echo "  ${BSPATCH_FILE}" >> ${PATCH_LOG_FILE}
fi

if [ -d ${APP_DIR}/${FILES_DIR} ]; then
  echo "Contains additional files" >> ${PATCH_LOG_FILE}
fi

if [ -f ${APP_DIR}/${TWEAKS_NAME} ]; then
  echo "Contains tweaks preferences: ${TWEAKS_NAME}" >> ${PATCH_LOG_FILE}
fi

if [ ! -x ${PATCH_EXEC} ]; then
  echo "ERROR: Cannot find ${PATCH_EXEC}" | tee -a ${PATCH_LOG_FILE} 1>&2
  do_install_failure
fi

if [ ! -x ${LSDIFF_EXEC} ]; then
  echo "ERROR: Cannot find ${LSDIFF_EXEC}" | tee -a ${PATCH_LOG_FILE} 1>&2
  do_install_failure
fi

if [ ! -x ${BSPATCH_EXEC} ]; then
  echo "ERROR: Cannot find ${BSPATCH_EXEC}" | tee -a ${PATCH_LOG_FILE} 1>&2
  do_install_failure
fi

if [ -z ${APP_DIR} ]; then
  echo "ERROR: APP_DIR must be set in postinst" | tee -a ${PATCH_LOG_FILE} 1>&2
  do_install_failure
fi

if [ ! -d ${APP_DIR} ]; then
  echo "ERROR: ${APP_DIR} is not a directory or does not exist!" | tee -a ${PATCH_LOG_FILE} 1>&2
  do_install_failure
fi

if [ ! -f ${APP_DIR}/${PATCH_NAME} ] && [ ! -f ${APP_DIR}/${BSPATCH_NAME} ] && [ ! -d ${APP_DIR}/${FILES_DIR} ]; then
  echo "ERROR: Cannot find patch file, bspatch file or files directory!" | tee -a ${PATCH_LOG_FILE} 1>&2
  do_install_failure
fi

rm -f /var/webosinternals.md5sums >/dev/null 2>&1

#
# The main function that controls all the magic stuff
#

verify_text_patch

verify_binary_patch

verify_additional_files

check_ota_update

remove_text_patch

remove_binary_patch

remove_additional_files

remove_tweaks_preferences

clean_backup_files

do_remove_success

exit 0

