NAME = amazon-evdo
PATCH = amazonstore/amazon_evdo.patch
VERSION = 0.1.3
TITLE = Amazon Store EVDO
DESCRIPTION = Allow the Amazon Store to be used over EVDO
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
