NAME = amazon-evdo
PATCH = amazonstore/amazon_evdo.patch
TITLE = Amazon Store EVDO
DESCRIPTION = Allow the Amazon Store to be used over EVDO
CATEGORY = Amazon Store
ICON = http://www.webos-internals.org/images/5/5c/Icon_WebOSInternals_Patches_Amazonstore.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/8/83/Modify-stock-app.jpg\",\"http://www.webos-internals.org/images/9/91/Modify-stock-app2.jpg\"]
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
