NAME = add-date-to-top-bar-no-year
PATCH = /luna/${NAME}.patch
TITLE = Add Date to Top Bar without year
DESCRIPTION = Adds month and day date string next to time in the top bar
CATEGORY = Luna
VERSION = 0.1.16

include ../common.mk
include ../modifications.mk
