NAME = $(shell basename ${PWD})
PATCH = /luna/${NAME}.patch
TITLE = Add Date to Top Bar No Year
DESCRIPTION = Adds the date to the left of the time in the top bar in MM/DD format.
CATEGORY = Luna
VERSION = 0.5.0
SCREENSHOTS = [\"http://www.webos-internals.org/images/2/29/Add_date_to_top_bar_no_year.png\"]
META_VERSION = 1

include ../common.mk
include ../modifications.mk
