NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TITLE = WAN DNS Uses Google
DESCRIPTION = Causes the WAN connection to always use the Google 8.8.8.8 and 8.8.4.4 DNS servers.
CATEGORY = System
VERSIONS = 2.2.0-32
ICON = http://www.webos-internals.org/images/a/aa/Tux_Imposter.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = WebOS Internals
HOMEPAGE =