NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = Korean IME
DESCRIPTION = Korean IME for webOS 2.2.4
CATEGORY = System
VERSIONS = 2.1.0-259 2.1.1-64 2.1.2-75 2.2.4-67
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sirasoni
HOMEPAGE =