NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Add to Spare Time in Context Menu
DESCRIPTION = Adds an option in the context menu to send a link to the Spare Time app.<br/><br/>Spare Time is an Instapaper client by SemicolonApps that allows you to save webpages to read offline in a mobile-friendly format.
CATEGORY = Browser
VERSIONS = 2.1.0-57 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/9/92/Browser-add-to-spare-time-in-context-menu-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha <dropdeadbabies@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/270937-patch-add-spare-time-browser-context-menu.html
