NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Close Slider to End Calls Except Headset
DESCRIPTION = Same as Close Slider to End Calls patch, except it ignores slider when a headset (wired or bluetooth) is connected.
CATEGORY = Phone
VERSIONS = 1.3.1-13 1.3.5-0
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = KeyToss <info@keytoss.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/209950-phone-slider-patch.html
