NAME = $(shell basename $(shell pwd))
PATCH = video-player/${NAME}.patch
TITLE = Share Larger Videos Via Email
DESCRIPTION = Increases video size limit that users can 'share via email' from the Videos app from 7MB to 25MB (gmail's attachment cap). Currently, videos over 7MB will force users to edit/shorten the video.
CATEGORY = Video Player
VERSIONS = 1.4.1-4 1.4.2-1 1.4.5-1
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Videoplayer.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/4/46/Video-player-share-larger-videos-via-email-1.png\",\
\"http://www.webos-internals.org/images/c/c2/Video-player-share-larger-videos-via-email-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = opacityzero
HOMEPAGE = http://forums.precentral.net/webos-patches/239605-patch-share-larger-videos-via-email-videos.html
