NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = 4G Icon Instead of H Plus
DESCRIPTION = Replaces the H+ icon with a 4G one. Purely cosmetic and will affect nothing else.
CATEGORY = Top Bar
VERSIONS = 2.2.0-105 2.2.3-99 2.2.4-14
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.webosnation.com/webos-patches/307039-patches-pre3-4g-h-h-icon-instead-3g.html#post3269180