NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Reverse Lookup - Browser - Australia
DESCRIPTION = This patch adds an option to the call log to do a reverse lookup of a phone number using reverseaustralia.com. Australian localised
CATEGORY = Phone
VERSIONS = 1.4.5-158
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = johncc <johncc@internode.on.net>
HOMEPAGE = http://forums.precentral.net/webos-patches/283782-reverse-number-lookup-australia.html
