NAME = $(shell basename $(shell pwd))
PATCH = /app-launcher/${NAME}.patch
TITLE = 4x4 Icons v2
DESCRIPTION = This will modify the App launcher to display 4x4 icons rather than 3x4.
CATEGORY = App Launcher
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/9/94/More_icons_per_row_4x4_1.2.png\"]
META_VERSION = 1

include ../common.mk
include ../modifications.mk
