NAME = $(shell basename ${PWD})
PATCH = /frameworks/${NAME}.patch
TITLE = Smiley Faces in Symbol Box
CATEGORY = Frameworks
VERSION = 0.5.0
DESCRIPTION = This will add smiley faces to symbol box popup.  Sym+k and sym+z offer different smiley faces.
SCREENSHOTS = [\"http://forums.precentral.net/attachments/web-os-development/23836d1248648685-how-get-smilies-symbol-box-messaging_2009-26-07_182417.jpg\", \"http://forums.precentral.net/attachments/web-os-development/23837d1248648820-how-get-smilies-symbol-box-messaging_2009-26-07_185203.jpg\"]
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
