NAME = smiley-face-sym-box
PATCH = /frameworks/${NAME}.patch
TITLE = Smiley Faces in Symbol Box
CATEGORY = Frameworks
VERSION = 0.4.0
DESCRIPTION = This will add smiley faces to symbol box popup.  Sym+k and sym+z offer different smiley faces.
SCREENSHOTS = [\"http://www.webos-internals.org/images/0/0e/Smile-face-sym-box.png\"]
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
