NAME = $(shell basename $(shell pwd))
PATCH = universal-search/${NAME}.patch
TITLE = Remove Google Country Redirect
DESCRIPTION = Removes Google auto-redirect based on country from Universal Search. Will stop Google from mistakenly changing your language when searching Google with Universal Search.
CATEGORY = Universal Search
VERSIONS = 1.4.0-59 1.4.1-31 1.4.2-16 1.4.3-10 1.4.5-15
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jauder Ho <thomascoe1@gmail.com>, Thomas Coe
HOMEPAGE =