NAME = $(shell basename $(shell pwd))
PATCH = universal-search/${NAME}.patch
TITLE = Remove Google Country Redirect
DESCRIPTION = Removes Google auto-redirect based on country from Universal Search. Will stop Google from mistakenly changing your language when searching Google with Universal Search.
CATEGORY = Universal Search
VERSIONS = 1.4.0-66 1.4.1-38 1.4.2-19 1.4.3-17 1.4.5-22
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jauder Ho, Thomas Coe <thomascoe1@gmail.com>
HOMEPAGE =