NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = eMail-Compose-AskToSend
DESCRIPTION = By tapping the Send-Button the eMail is send immediately. This Patch pops up adialog and asks, if the eMail shall be sent or not. English and German Version.
CATEGORY = Email
VERSIONS = 1.4.0-78 1.4.1-61 1.4.5-58
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/2/25/Email-email-compose-asktosend-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Fritz Amtmann <Fritz@Do-Ri.com>
HOMEPAGE = http://www.nexave.de/forum/p384596-patch-gegen-versehentlich-abgeschickte-sms-e-mail/.html?highlight=email+papierflieger#post384596