NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = AutoSpeakerphone via Proximity Sensor Instant
DESCRIPTION = Immediately changes the audio route between the front and back speaker as the display is turned on & off by the proximity sensor.<br/><br/>(BT/headset/aux audio compatible)
CATEGORY = Phone
VERSIONS = 1.4.0-45 1.4.1-16 1.4.2-2
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/244195-patch-auto-speakerphone-via-proximity-sensor.html#post2415544