#!/bin/sh

# Disable any legacy dropbear server that was installed manually
if [ -f /etc/event.d/optware-dropbear ]; then
    /sbin/stop optware-dropbear
    rm -f /etc/event.d/optware-dropbear
fi

update-alternatives --install /opt/bin/scp scp /opt/sbin/dropbearmulti 50
update-alternatives --install /opt/bin/ssh ssh /opt/sbin/dropbearmulti 50

mkdir -p /opt/etc/dropbear

if [ ! -f /opt/etc/dropbear/dropbear_rsa_host_key ]; then
    echo Generating RSA Key...
    /opt/sbin/dropbearkey -t rsa -f /opt/etc/dropbear/dropbear_rsa_host_key
fi

if [ ! -f /opt/etc/dropbear/dropbear_dss_host_key ]; then
    echo Generating DSS Key...
    /opt/sbin/dropbearkey -t dss -f /opt/etc/dropbear/dropbear_dss_host_key
fi

# The emulator already has an ssh server running, so no need to start another.
if [ "`uname -m`" != "i686" ]; then
    rm -f /etc/event.d/mobi.optware.dropbear
    mkdir -p /etc/event.d/
    cp /var/etc/event.d/mobi.optware.dropbear /etc/event.d/mobi.optware.dropbear
    /sbin/start mobi.optware.dropbear
fi

exit 0
