#!/bin/sh

# The emulator already has an ssh server running, so no need to start another.
if [ "`uname -m`" != "i686" ]; then
    /sbin/stop org.webosinternals.dropbear
    rm -f /etc/event.d/org.webosinternals.dropbear
fi

update-alternatives --remove scp /opt/sbin/dropbearmulti
update-alternatives --remove ssh /opt/sbin/dropbearmulti

# We intentionally do not remove the host keys.

exit 0
