NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Make Advanced Browser the default browser
DESCRIPTION = Modifies the stock browser code so that all launches are redirected to Advanced Browser.Note: Currently this launches a blank window additional to the AB window. We're looking for a way to fix that.
CATEGORY = Browser
VERSIONS = 3.0.2-79 3.0.4-43
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = MaKleSoft <contact@maklesoft.com>
HOMEPAGE = http://maklesoft.com