NAME = $(shell basename $(shell pwd))
PATCH = clock/${NAME}.patch
TWEAKS =
TITLE = Optimize Clock for Exhibition
DESCRIPTION = Optimizes the Clock app for when used in exhibition mode.NOTE: If you install this patch, be sure to also install the Add Clock to Exhibition patch.
CATEGORY = Clock
VERSIONS = 2.1.0-104 2.2.0-21
ICON = http://www.webos-internals.org/images/8/8d/Icon_WebOSInternals_Patches_Clock.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/282428-patches-clock-app-exhibition-mode.html