NAME = $(shell basename $(shell pwd))
PATCH = youtube/${NAME}.patch
TWEAKS =
TITLE = Youtube Italian Feed
DESCRIPTION = Change the default feed to italian feed.
CATEGORY = YouTube
VERSIONS = 2.1.0-250 2.1.1-55 2.1.2-65 2.2.4-48
ICON = http://www.webos-internals.org/images/8/8b/Icon_WebOSInternals_Patches_Youtube.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = iMarck90
HOMEPAGE = https://github.com/iMarck/Youtube-Italian-Feed--Patch-webOS-2.x-