NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Open to call log
DESCRIPTION = Opens the Phone app to the call log and makes it switch back to the call log after each call.
CATEGORY = Phone
VERSIONS = 1.2.1-10 1.3.1-12 1.3.5-23
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = dallashigh <hardfam1@gmail.com>, dBsooner, xanthinealkaloid
HOMEPAGE = http://forums.precentral.net/webos-patches/229559-patch-default-call-log.html