NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Open to call log
DESCRIPTION = This will cause the Phone app to open directly to the call log. Useful if you often find yourself initiating calls from the log.
CATEGORY = Phone
VERSIONS = 1.2.1-10 1.3.1-12
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = dallashigh <karl@webosnerd.com>, dBsooner 
HOMEPAGE = http://www.webosnerd.com
