NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Send to Relego
DESCRIPTION = This patch allows you to send a URL to the app Relego. Relego is a Read It Later app that let's you store webpages to read them later.
CATEGORY = Browser
VERSIONS = 1.4.0-73 1.4.1-47 1.4.2-33 1.4.3-27 1.4.5-35
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/f/f5/Browser-send-to-relego-1.png\",\
\"http://www.webos-internals.org/images/f/f8/Browser-send-to-relego-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = spdsktr <erupnu@gmail.com>
HOMEPAGE = http://www.webosroundup.com