NAME = $(shell basename $(shell pwd))
PATCH = sounds-and-alerts/${NAME}.patch
TWEAKS =
TITLE = Increase Bluetooth Headset Volume
DESCRIPTION = This patch will increase the volume of your bluetooth headset.
CATEGORY = Sounds and Alerts
VERSIONS = 2.0.0-63 2.0.1-92 2.1.0-142
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Soundsandalerts.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mau
HOMEPAGE =