#!/bin/sh

APPID=mobi.optware.nano

# Symlink files into /opt
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find bin etc share -type d -exec mkdir -p /opt/{} \;
find bin etc share -type f -exec ln -sf $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt/{} /opt/{} \;

exit 0
