NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Close Phone App on Hangup
DESCRIPTION = Automatically closes the phone app after hanging up an active call. It doesn't matter which side has terminated the conversation first. Its for Enyo phone app only and should work with all 2.2.x devices.
CATEGORY = Phone
VERSIONS = 2.2.4-85
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = michel <michel7@mail.ru>
HOMEPAGE = http://forums.webosnation.com/webos-patches/320574-patch-close-phone-app-hangup-webos-2-2-x.html