NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Add Download Link option
DESCRIPTION = Adds a new 'Download Link' item in the context menu of any link in the browser. Hold your finger on the link and select 'Download Link' in the upcoming menu to download the target of this link.
CATEGORY = Browser
VERSIONS = 3.0.5-4
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ahleksb
HOMEPAGE =
