NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS = browser/${NAME}.json
TITLE = Behavior and Options Tweaks
DESCRIPTION = It is a Tweaks version of the MegaMix patch. It is compatible with the Sharing Super Mix patch.<br/><br/>This patch includes the ability to:<br/><br/>-  Go fullscreen<br/>- Auto Hide Page Icons<br/>- Disable Landscape Gesture Scroll<br/>- View Source<br/>- Enable Private Browsing<br/><br/>For more info on these options, please see the help for each in the Tweaks app.<br/><br/>This combines multiple broswer patches of fritos1406 and the suggestions of chrislo, as well as the work of mamouton, Micah N Gorrell, and Jason Robitaille.
CATEGORY = Browser
VERSIONS = 2.1.0-84 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/3/37/Icon_WebOSInternals_Patches_Plus_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/7/7b/Browser-behavior-and-options-tweaks-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha <dropdeadbabies@gmail.com>, mamouton
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2949121#post2949121
