NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Power Button to End Calls
DESCRIPTION = Press the power button to end all phone calls.
CATEGORY = Phone
VERSIONS = 2.0.0-29 2.0.1-51 2.1.0-2 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = KeyToss, CRaiaSoftware
HOMEPAGE = http://forums.precentral.net/webos-patches/215031-patch-power-button-end-calls.html
