NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Hide RSSI Icons
DESCRIPTION = This patch will hide the signal strength icons in the Top Bar. They will only display when you have zero bars or are in Airplane Mode.
CATEGORY = Top Bar
VERSIONS = 1.4.5-109
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Garrett92C <Garrett92C@gmail.com>
HOMEPAGE = http://webos.choorp.com
