NAME = 
PATCH = ${NAME}.patch
TITLE = 
DESCRIPTION = 
CATEGORY = 
VERSION = 
ICON = 
SCREENSHOTS = 
META_VERSION = 
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
