#!/bin/sh
APP_DIR=
PATCH_NAME=
FILE_LIST=`/var/usr/bin/diffstat -p1 -l $APP_DIR/$PATCH_NAME`
IPKG_INFO_DIR=/usr/lib/ipkg/info
PATCH_CONTROL_DIR=/var/usr/lib/.webosinternals.patches

do_failure() {
  ipkg -o /var remove `basename $APP_DIR`
  exit 1
}

if [ "$APP_DIR" = "" ] || [ "$PATCH_NAME" = "" ]
then
  echo "ERROR: APP_DIR and PATCH_NAME both must be set in postinst"
  do_failure
fi

/var/usr/bin/patch -p1 -d / --dry-run < ${APP_DIR}/$PATCH_NAME || do_failure
if [ ! -d $PATCH_CONTROL_DIR ]
then
  rm -rf $PATCH_CONTROL_DIR
  mkdir $PATCH_CONTROL_DIR || do_failure
fi

if [ ! -e $PATCH_CONTROL_DIR/backups ]
then
  touch $PATCH_CONTROL_DIR/backups || do_failure
fi

if [ ! -e $PATCH_CONTROL_DIR/packages ]
then
  touch $PATCH_CONTROL_DIR/packages || do_failure
fi

rm -f $PATCH_CONTROL_DIR/tmp
touch $PATCH_CONTROL_DIR/tmp || do_failure

for i in $FILE_LIST
do
  file=/$i
  if [ `grep -l $file $IPKG_INFO_DIR/*.md5sums | wc -l` -gt 1 ]
  then
    echo "ERROR: File found in multiple packages: $file"
    do_failure
  fi
  
  in_list="no"
  for j in `cat $PATCH_CONTROL_DIR/backups`
  do
    if [ "$file" = "$j" ]
    then
      in_list="yes"
      break
    fi
  done

  if [ "$in_list" = "yes" ]
  then
    echo "VERIFY BACKUP"
  else
    expected=`grep -h $file $IPKG_INFO_DIR/*.md5sums | awk '{print $1}'`
    echo "file $file"
    if [ "$expected" != "" ]
    then
      calculated=`md5sum $file | awk '{print $1}'`
      if [ "$expected" != "$calculated" ]
      then
        echo "ERROR: MD5SUMS do not match"
        echo "       expected: $expected"
        echo "       calculated: $calculated"
        do_failure
      else
        echo "NOTE: Palm md5sum found: $expected $file"
      fi
    fi

    if [ -e $file.webosinternals.orig ]
    then
      orig_md5sum=`md5sum $file.webosinternals.orig | awk '{print $1}'`
      file_md5sum=`md5sum $file | awk '{print $1}'`
      if [ "$orig_md5sum" != "$file_md5sum" ]
      then
        echo "ERROR: Existing backup file not in list, but md5sums do not match"
        echo "       backup md5sum: $orig_md5sum"
        echo "       current md5sum: $file_md5sum"
        do_failure
      fi
    fi

    echo $file >> $PATCH_CONTROL_DIR/tmp
  fi
done

if [ -e $PATCH_CONTROL_DIR/$PATCH_NAME ]
then
  echo "ERROR: Patch already installed?"
  do_failure
fi

for i in `cat $PATCH_CONTROL_DIR/tmp`
do
  if [ ! -e $i ]
  then
    touch $i.webosinternals.orig
  else
    cp $i $i.webosinternals.orig
  fi

  echo $i >> $PATCH_CONTROL_DIR/backups
done

basename $APP_DIR >> $PATCH_CONTROL_DIR/packages

cp $APP_DIR/$PATCH_NAME $PATCH_CONTROL_DIR/$PATCH_NAME
/var/usr/bin/patch -d / -p1 < ${APP_DIR}/$PATCH_NAME || do_failure

echo "SUCCESS"

# Restart Luna
if [ -z "$IPKG_OFFLINE_ROOT" ]; then # Defined by recent installers that also support flags.
    /sbin/stop LunaSysMgr
    /sbin/start LunaSysMgr
fi

exit 0
