#!/bin/sh
APP_DIR=
PATCH_NAME=
FILE_LIST=`/var/usr/bin/diffstat -p1 -l $APP_DIR/$PATCH_NAME`
IPKG_INFO_DIR=/usr/lib/ipkg/info
PATCH_CONTROL_DIR=/var/usr/lib/.webosinternals.patches

do_failure() {
  ipkg -o /var remove `basename $APP_DIR`
  exit 1
}

if [ "$APP_DIR" = "" ] || [ "$PATCH_NAME" = "" ]
then
  echo "ERROR: APP_DIR and PATCH_NAME both must be set in postinst"
  do_failure
fi

/var/usr/bin/patch -p1 -d / --dry-run < ${APP_DIR}/$PATCH_NAME || do_failure
if [ ! -d $PATCH_CONTROL_DIR ]
then
  rm -rf $PATCH_CONTROL_DIR
  mkdir $PATCH_CONTROL_DIR || do_failure
fi

if [ ! -e $PATCH_CONTROL_DIR/backups ]
then
  touch $PATCH_CONTROL_DIR/backups || do_failure
fi

if [ ! -e $PATCH_CONTROL_DIR/packages ]
then
  touch $PATCH_CONTROL_DIR/packages || do_failure
fi

rm -f $PATCH_CONTROL_DIR/tmp
touch $PATCH_CONTROL_DIR/tmp || do_failure

if [ -e $PATCH_CONTROL_DIR/$PATCH_NAME ]
then
  echo "ERROR: Patch already installed?"
  do_failure
fi

for i in $FILE_LIST
do
  file=/$i

  if [ ! -e $file.webosinternals.orig ]
  then
    if [ ! -e $file ]
    then
      touch $file.webosinternals.orig
    else
      cp $file $file.webosinternals.orig
    fi
  fi

  tmpvar=`echo $file | tr '/' '.'`
  sed -i -e /$tmpvar/d $PATCH_CONTROL_DIR/backups
  echo $file >> $PATCH_CONTROL_DIR/backups
done

sed -i -e /`basename $APP_DIR`/d $PATCH_CONTROL_DIR/packages
basename $APP_DIR >> $PATCH_CONTROL_DIR/packages

cp $APP_DIR/$PATCH_NAME $PATCH_CONTROL_DIR/$PATCH_NAME
/var/usr/bin/patch -d / -p1 < ${APP_DIR}/$PATCH_NAME || do_failure

echo "SUCCESS"

# Restart Luna
if [ -z "$IPKG_OFFLINE_ROOT" ]; then # Defined by recent installers that also support flags.
    /sbin/stop LunaSysMgr
    /sbin/start LunaSysMgr
fi

exit 0
