#!/bin/sh
APP_DIR=
PATCH_NAME=
FILE_LIST=`/var/usr/bin/diffstat -p1 -l $APP_DIR/$PATCH_NAME`
PATCH_CONTROL_DIR=/var/usr/lib/.webosinternals.patches

do_failure() {
  exit 1
}

if [ "$APP_DIR" = "" ] || [ "$PATCH_NAME" = "" ]
then
  echo "ERROR: APP_DIR and PATCH_NAME both must be set in postinst"
  do_failure
fi

/var/usr/bin/patch -R -p1 -d / --dry-run < ${APP_DIR}/$PATCH_NAME || do_failure

/var/usr/bin/patch -R -p1 -d / < ${APP_DIR}/$PATCH_NAME

for i in $FILE_LIST
do
  file=/$i
  orig_md5sum=`md5sum $file.webosinternals.orig | awk '{print $1}'`
  file_md5sum=""

  if [ -e $file ]
  then
    file_md5sum=`md5sum $file | awk '{print $1}'`
  fi

  if [ ! -e $file ] && [ ! -s $file.webosinternals.orig ] || [ "$orig_md5sum" = "$file_md5sum" ]
  then
    tmpvar=`echo $file | tr '/' '.'`
    rm -f $file.webosinternals.orig
    sed -i -e /$tmpvar/d $PATCH_CONTROL_DIR/backups
  fi
done

rm -f $PATCH_CONTROL_DIR/$PATCH_NAME
sed -i -e /`basename $APP_DIR`/d $PATCH_CONTROL_DIR/packages
rm -rf ${APP_DIR}

if [ -e $APP_DIR/prerm_extra ]
then
  export APP_DIR
  /bin/sh $APP_DIR/prerm_extra
fi

echo "SUCCESS"

# Restart Luna
if [ -z "$IPKG_OFFLINE_ROOT" ]; then # Defined by recent installers that also support flags.
    /sbin/stop LunaSysMgr
    /sbin/start LunaSysMgr
fi

exit 0
