NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Auto Bcc
DESCRIPTION = Borrowed the email 'Account Name' field to store Bcc email address. Bcc address will be add to email’s “BCC” field upon create or reply.
CATEGORY = Email
VERSIONS = 1.4.3-36 1.4.5-46
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/c/cd/Email-auto-bcc-1.jpg\",\
\"http://www.webos-internals.org/images/b/b4/Email-auto-bcc-2.jpg\",\
\"http://www.webos-internals.org/images/8/84/Email-auto-bcc-3.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Eric <eric.hk.tsang@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2631915#post2631915