NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Auto Bcc
DESCRIPTION = Allow input bcc email address in email account profile. The bcc address will be automatically added to outgoing email.<br/>Should now work for *all* languages.<br/><br/>Note: The bcc address is only filled in of the account you start the e-mail from. If you change the account in header of the compose e-mail scene, the bcc address won't be changed.
CATEGORY = Email
VERSIONS = 1.4.5-61 2.0.0-35 2.0.1-62 2.1.0-16 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/c/cd/Email-auto-bcc-1.jpg\",\
\"http://www.webos-internals.org/images/7/75/Email-auto-bcc-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Eric <0188801@gmail.com>, pcworld
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2631915#post2631915
