NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Share Image Message Option
DESCRIPTION = Adds a menu option named Share Image Message to send an image through the Messaging app...The option named Share Image is also renamed to Share Image Email.
CATEGORY = Browser
VERSIONS = 1.4.1-7
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/f/fa/Browser-share-image-message-option-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2371220#post2371220