NAME = $(shell basename $(shell pwd))
PATCH = youtube/${NAME}.patch
TITLE = Share Videos Via Facebook
DESCRIPTION = Puts a link under the Share button in the Youtube app that allows sharing with the Facebook app. Done using the Facebook crossapp api, which posts shared items as a status.
CATEGORY = YouTube
VERSIONS = 1.4.5-124
ICON = http://www.webos-internals.org/images/8/8b/Icon_WebOSInternals_Patches_Youtube.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/4/42/Youtube-share-videos-via-facebook-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha (screwdestiny)
HOMEPAGE = http://forums.precentral.net/webos-patches/273455-share-youtube-links-facebook.html
