NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Phone No AutoClose
DESCRIPTION = Here's a requested patch that will keep the phone app from automatically closing after an incoming call is ended. You can still manually close it, but it will allow you to continue to use the phone app without having to open it again.
CATEGORY = Phone
VERSIONS = 1.4.5-1
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Elryon <elryon@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/237225-patch-keep-phone-app-open-after-incoming-call.html#post2317197
