NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = HP WebOS Carrier String
DESCRIPTION = Replaces the carrier string with 'HP WebOS' to match the behaviour of the Touchpad. Also replaces the 'Phone Offline' message.
CATEGORY = Top Bar
VERSIONS = 2.1.0-200 2.2.0-72 2.2.3-64
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ShiftyAxel <jpalmerwatkins@me.com>, Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/305673-patch-hp-webos-carrier-string-2-x.html