#!/bin/sh                                                                                       

# All the following code is simply to remove the obsolete C service
# This is only required for upgrades from 0.2.4 to 0.3.0

SID="org.webosinternals.wirc"

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

# Remove the wirc service executable
rm -f /var/usr/sbin/${SID}

# Remove the dbus service
rm -f /usr/share/dbus-1/system-services/${SID}.service /var/palm/system-services/${SID}.service

# Stop the service if running
/sbin/stop ${SID} || true
/usr/bin/killall -9 ${SID} || true

# Remove the upstart script
rm -f /etc/event.d/${SID} /var/palm/event.d/${SID}

exit 0
