NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Match State to Area Code
DESCRIPTION = This will cause the Phone application to display the State a call is coming from for numbers that do not match a Contact entry.
CATEGORY = Phone
VERSIONS = 1.2.1-0 1.3.1-0 1.3.5-2
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/1/13/State.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Ikyo <jody.r.owens@sprint.com>, dbsooner <webos@dbsooner.com>
