NAME     = simplyflipflops
APP_ID   = com.simplyflipflops
VERSION  = 0.9.99
HOMEPAGE = http://forums.precentral.net/homebrew-apps/188554-simplyflipflops-v0-9-99-nrr.html
SECTION  = System Utilities

SRC_IPKG = http://forums.precentral.net/attachments/homebrew-apps/20349d1245854061-simplyflipflops-v0-9-99-nrr-${APP_ID}_${VERSION}_${PLATFORM}.ipk
include ../../support/download.mk

include ../../support/application-copy.mk
