NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TITLE = Custom Low-Battery Notification Sounds
DESCRIPTION = Let's you specify custom low-battery notification sounds for the
CATEGORY = Notifications
VERSIONS = 1.4.5-30 2.0.1-45 2.1.0-3
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/257305-patch-custom-low-battery-notification-sounds.html#post2584823