NAME = $(shell basename $(shell pwd))
PATCH = google-maps/${NAME}.patch
TITLE = Start in Fullscreen
DESCRIPTION = Starts Google Maps in fullscreen mode which can later be toggled on and off with a tap-hold on the screen.
CATEGORY = Google Maps
VERSIONS = 1.3.5-22 1.4.0-28 1.4.1-1
ICON = http://www.webos-internals.org/images/c/c3/Icon_WebOSInternals_Patches_SprintNav.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/228309-patch-google-maps-fullscreen.html
