NAME = $(shell basename $(shell pwd))
PATCH = google-maps/${NAME}.patch
TITLE = Start in Fullscreen
DESCRIPTION = Starts Google Maps in fullscreen mode which can later be toggled on and off using the forward gesture.
CATEGORY = Google Maps
VERSIONS = 1.3.1-37 1.3.5-21 1.4.0-10
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/228309-patch-google-maps-fullscreen.html