NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = 20px Font
DESCRIPTION = Increase the font in the messaging app to 20px, For those of us that are visually challenged.
CATEGORY = Messaging
VERSIONS = 1.4.1-5 1.4.2-1 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = 2sslow <2sslow@gmail.com>
HOMEPAGE =
