NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Full IM Status
DESCRIPTION = This will show the full buddy list IM status instead of a truncated one.
CATEGORY = Messaging
VERSIONS = 1.2.1-0 1.3.1-0 1.3.5-1 1.4.0-1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = 
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = fritos1406
