NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TWEAKS =
TITLE = Extend Notification Tone Time Limit
DESCRIPTION = Changes default notification time limit from 5 seconds to a minute. Caution: Once the notification sound is activated, there is no way to stop the event. Ringer switch works in muting the sound. Not recommended to assign long length tones.
CATEGORY = Notifications
VERSIONS = 1.4.5-19 2.1.0-141
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Abyssul <Time4swim@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2509977#post2509977