NAME = $(shell basename $(shell pwd))
PATCH = clock/${NAME}.patch
TITLE = Enable Hidden Clock
DESCRIPTION = This will enable the hidden clock theme. It is an analog clock instead of the digital one. You can select it in the Clock application preferences.
CATEGORY = Clock
VERSIONS = 1.2.1-0 1.1.3-0 1.3.1-0
ICON = http://www.webos-internals.org/images/8/8d/Icon_WebOSInternals_Patches_Clock.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/8/8a/Hidden-clock-1.png\",\
\"http://www.webos-internals.org/images/0/01/Hidden-clock-2.png\"]
META_SUB_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk

MAINTAINER = frankos72
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Clock_Enabling_the_Hidden_Theme
