NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TWEAKS =
TITLE = Just Type Scrim Fix
DESCRIPTION = Fixes the 1px white bar at the bottom of the empty Just Type screen.
CATEGORY = App Launcher
VERSIONS = 2.2.0-103 2.2.3-97 2.2.4-12
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ShiftyAxel <jpalmerwatkins@me.com>
HOMEPAGE = http://forums.webosnation.com/webos-themes/308966-patch-pre3-fix-just-type-scrim.html