NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = AM-PM Indicator in Top Bar
DESCRIPTION = Adds an AM/PM indicator to the top bar's time display.
CATEGORY = Top Bar
VERSIONS = 2.1.0-3 2.2.0-19 2.2.3-19
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/231780-am-pm-indicator-top-bar.html