#!/bin/sh

DISTRO=ubuntu-natty

NAME=xapps-xchat-ubuntu-natty

APPID=org.webosinternals.${NAME}

APPS=/media/cryptofs/apps

CHROOT_NAME=ubuntu-natty-chroot

CHROOT_PATH=/media/ext3fs/${CHROOT_NAME}

XAPP_NAME=xchat

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

# Stop the service if running
/sbin/stop ${APPID} || true

# Remove the upstart script
rm -f /var/palm/event.d/${APPID}

# remove our application

cp /etc/resolv.conf ${CHROOT_PATH}/etc/resolv.conf

mount --bind /dev ${CHROOT_PATH}/dev
mount --bind /dev/pts ${CHROOT_PATH}/dev/pts
mount --bind /proc ${CHROOT_PATH}/proc
mount --bind /sys ${CHROOT_PATH}/sys
mount --bind /tmp ${CHROOT_PATH}/tmp

# remove our application
export PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin
chroot ${CHROOT_PATH} /usr/bin/apt-get remove --force-yes -y ${XAPP_NAME}

umount ${CHROOT_PATH}/tmp
umount ${CHROOT_PATH}/sys
umount ${CHROOT_PATH}/proc
umount ${CHROOT_PATH}/dev/pts
umount ${CHROOT_PATH}/dev

# We intentionally do not remove the chroot contents.

exit 0
