NAME = $(shell basename $(shell pwd))
PATCH = universal-search/${NAME}.patch
TWEAKS =
TITLE = Add Button to Clear Recent Searches
DESCRIPTION = This patch adds a button to Just Type that will clear your recent search history.
CATEGORY = Universal Search
VERSIONS = 3.0.0-2
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Garrett92C <Garrett92C@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/286853-patch-touchpad-add-clear-recent-searches-button-just-type.html