NAME = $(shell basename $(shell pwd))
PATCH = camera/${NAME}.patch
TITLE = Capture With All Keys
DESCRIPTION = Enables all keys to be used to take an image in the camera app.
CATEGORY = Camera
VERSIONS = 1.3.5-9 1.4.0-3
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/219294-patch-capture-photos-any-key.html
