NAME = $(shell basename $(shell pwd))
PATCH = universal-search/${NAME}.patch
TITLE = KeyToss Keyword Search
DESCRIPTION = This will install KeyToss keyword-powered search tool to Universal Search and to the browser URL search. Type '@help' for a list of keywords.
CATEGORY = Universal Search
VERSIONS = 1.3.5-36 1.4.0-37 1.4.1-6
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/d/db/Universal-search-keytoss-keyword-search-1.png\",\
\"http://www.webos-internals.org/images/2/2a/Universal-search-keytoss-keyword-search-2.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = dweigh <info@keytoss.com>, Sam Kim
HOMEPAGE = http://keytoss.com/pre