NAME = $(shell basename $(shell pwd))
PATCH = advanced/${NAME}.patch
FILES = advanced/${NAME}.tar.gz
TITLE = Advanced System Menus - Mode Menu (Veer)
DESCRIPTION = * Requires Advanced System Menus Framework patch to be installed to function properly!<br/><br/>Adds mode menu to the left corner of the top bar. This is only useful if you have Mode Switcher installed. This menu enables changing of modes manually through the menu.
CATEGORY = Advanced
VERSIONS = 2.1.0-155
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/a/a0/AdvancedSystemMenusModeMenu.png\",\"http://www.webos-internals.org/images/d/df/AdvancedSystemMenusModeMenuEdit.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = http://forums.precentral.net/enlightened-linux-solutions/269207-patch-advanced-system-menus-2-x.html
