NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Replies Forwards Multi Mod Black Font
DESCRIPTION = This will change the reply to a smaller, black Calibri font. Also changes the Reply to remove the 'John Smith wrote' text and replace it with the typical 'From: ... To: ...' language that Outlook displays.<br/><br/>This patch is currently not compatible with Replies/Forwards in Black Font. Must remove before you try to apply this patch.
CATEGORY = Email
VERSIONS = 1.3.5-21 1.4.0-30 1.4.1-1 1.4.2-1
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/4/4e/Email-replies-forwards-multi-mod-black-font-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mikePre, Jonolee
HOMEPAGE = http://forums.precentral.net/palm-pre-tips-information-resources/205741-how-change-font-size-email-8.html#post2173731
