#!/bin/sh

DISTRO=ubuntu-natty

NAME=${DISTRO}-chroot

APPID=org.webosinternals.${NAME}

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

# Stop the service if running
/sbin/stop ${APPID} || true

# Remove the upstart script
rm -f /var/palm/event.d/${APPID}

if [ ! -d /media/ext3fs ] ; then
    echo "This package requires a dedicated ext3fs partition created by the WebOS Internals Meta-Doctor"
    exit 1
fi

#Check to see that ext3fs is mounted
    mount_info =  mount | grep ext3fs
if [ -z ${MOUNT_INFO} ] ; then
    echo '/media/ext3fs not mounted, will not install on a device without this mounted'
    exit 1
else
fi

if [ -d /media/ext3fs/${NAME} ] ; then
    echo "Will not overwrite existing chroot directory at /media/ext3fs/${NAME}"
else
    mkdir -p /media/ext3fs/${NAME} || exit 1
    tar -C /media/ext3fs/${NAME} -z -x -f ${APPDIR}/${NAME}.tgz || exit 1
fi

#Add non-privleged user to chroot

chroot /usr/sbin/addgroup webos --GID 1002
chroot /usr/sbin/adduser webos --UID 1000 --GID 1002 --disabled-password --gecos 'webOS User,,,'

# Install the upstart script
mkdir -p /var/palm/event.d
cp ${APPDIR}/upstart/${APPID} /var/palm/event.d/${APPID}

exit 0
