NAME = update-bug-fix
PATCH = /email/${NAME}.patch
TITLE = Fix Bug in Email App
DESCRIPTION = Fixes bug in _updateAccountsInfo() method in Email app
CATEGORY = Email
VERSION = 0.3.5
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
