NAME = update-bug-fix
PATCH = /email/${NAME}.patch
TITLE = Fix Bug in Email App
DESCRIPTION = Fixes bug in _updateAccountsInfo() method in Email application that causes error when email app is loaded.  This method and error seem to add no functionality to the email app so this 'bug fix' is really just to get rid of an error reported to stdout.  No functionality should be changed.
CATEGORY = Email
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
