NAME = message-orientation
PATCH = /messaging/${NAME}.patch
TITLE = Enable Landscape Messaging
DESCRIPTION = This will enable landscape mode in the Messaging application. It uses accelerometer to detect orientation.
CATEGORY = Messaging
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
