NAME = message-orientation
PATCH = /messaging/${NAME}.patch
VERSION = 0.1.5
TITLE = Messaging in Landscape Orientation
DESCRIPTION = Adds ability for Landscape mode in messaging app
CATEGORY = Messaging
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
