NAME = message-orientation
PATCH = /messaging/${NAME}.patch
TITLE = Messaging in Landscape Orientation
DESCRIPTION = Adds ability for Landscape mode in messaging app
CATEGORY = Messaging
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
