NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Remove Clear Bookmarks Button
DESCRIPTION = Removes the Clear Bookmarks button from the preferences screen of the browser app
CATEGORY = Browser
VERSIONS = 3.0.2-3 3.0.4-5 3.0.5-9
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/288496-patch-request-touchpad-remove-clear-bookmarks-button-browser-preferences.html