NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = Arabization Fix for Messaging App
DESCRIPTION = Fixes the issue with the Messaging Application and the Arabization. Generally, it changes the application so that it can handle the Arabic text entry correctly.
CATEGORY = Messaging
VERSIONS = 3.0.2-52
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = CvvB
HOMEPAGE = http://forums.precentral.net/webos-development/288634-arabization-webos.html