NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Add One Minute Interval
DESCRIPTION = Changes the start and end time inputs from 5 minutes to 1 minute interval.
CATEGORY = Calendar
VERSIONS = 1.3.5-3 1.4.0-18 1.4.1-1
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/0/00/Calendar-add-one-minute-interval-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = aric <aaakins@gmail.com>
HOMEPAGE =
