NAME = $(shell basename $(shell pwd))
PATCH = /app-launcher/${NAME}.patch
TITLE = Unhide Dev Mode Icon
DESCRIPTION = This will show the Developer Mode Icon in the App Launcher.
CATEGORY = App Launcher
VERSION = 1.2.1-0
ICON = http://www.webos-internals.org/images/e/ec/Icon_WebOSInternals_Patches_Devmodelauncher.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/0/09/Enable-dev-mode-icon.png\"]
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
