NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Unhide Dev Mode Icon
DESCRIPTION = This will show the Developer Mode Icon in the App Launcher.
CATEGORY = App Launcher
VERSIONS = 1.3.5-3 1.4.0-3
ICON = http://www.webos-internals.org/images/e/ec/Icon_WebOSInternals_Patches_Devmodelauncher.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/0/09/Enable-dev-mode-icon.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Jauder Ho <jauderho+git@gmail.com>
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Launcher_Unhide_the_DeveloperMode_App
