#!/bin/sh
PACKAGE=org.webosinternals.virtual-keyboard

if [ "$IPKG_OFFLINE_ROOT" = "" ]
then
  echo "ERROR: IPKG_OFFLINE_ROOT must be supplied to the postinst"
  exit 1
fi

if [ "`ipkg -o $IPKG_OFFLINE_ROOT list_installed | awk '{print $1}' | grep ^org.webosinternals.patches.add-onscreen-keyboard$`" = "" ]
then
  rm -rf /media/internal/virtual-keyboard/.themes/remix_classic
  rm -rf /media/internal/virtual-keyboard/.themes/remix_glossy
  rm -rf /media/internal/virtual-keyboard/.themes/remix_ice
  rm -rf /media/internal/virtual-keyboard/.themes/LPC_DarkRounded_2e
  rm -f /media/internal/virtual-keyboard/.sounds/click1.wav
  rm -f /media/internal/virtual-keyboard/kb_config.json
fi

ipkg -o $IPKG_OFFLINE_ROOT remove $PACKAGE
exit 0
