NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Include Plain Text Alternate
DESCRIPTION = This patch will include a plain text 'text/plain' chunk for emails sent with the TouchPad. The plain text formatting should be similar to that which was present from WebOS 1.4.5 devices. It has been tested only through a squirrelmail IMAP server. Only use with caution! This patch was created out of personal need and it fulfills the author's requirements, but they cannot guarantee that it will work with all email servers or configurations.
CATEGORY = Email
VERSIONS = 3.0.5-39
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = bbito
HOMEPAGE =