NAME = battery-percent-and-icon
PATCH = /luna/${NAME}.patch
TITLE = Battery Percent and Icon
DESCRIPTION = Battery percent and icon in top bar with default percent
CATEGORY = Luna
VERSION = 0.3.1
ICON = 
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
