NAME = $(shell basename ${PWD})
PATCH = /luna/${NAME}.patch
TITLE = Battery Icon and Percent
DESCRIPTION = This will add a color-coded percent number with the battery icon in the top bar. Charging = Teal. 100%-70% = Green. 69%-45% = Yellow. = 44%-20% = Orange. 19%-0% = Red.
CATEGORY = Luna
VERSION = 0.5.0
ICON = 
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
