NAME = battery-percent-and-icon
PATCH = /luna/${NAME}.patch
TITLE = Battery Percent and Icon
DESCRIPTION = Battery percent and icon in top bar with default percent
CATEGORY = Luna
VERSION = 0.2.1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
