NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Add Roam Control to Prefs
DESCRIPTION = This will enable a roam only option in the Phone Preferences.
CATEGORY = Phone
VERSIONS = 1.2.1-1 1.3.1-1 1.3.5-1
ICON = http://www.webos-internals.org/images/c/c8/Icon_WebOSInternals_Patches_Phonepreferences.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/d/d2/Roam-control.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = w5mw
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_webOS_Roam_Control
