NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Add Roam Control to Prefs
DESCRIPTION = This will enable a roam only option in the Phone Preferences.
CATEGORY = Phone
VERSIONS = 1.2.1-0 1.3.1-0 1.3.5-12
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/6/66/Phone-add-roam-control-to-prefs-1.png\",\
\"http://www.webos-internals.org/images/d/d9/Phone-add-roam-control-to-prefs-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>, w5mw
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_webOS_Roam_Control
