NAME = show-actual-battery-percent
PATCH = /luna/${NAME}.patch
VERSION = 0.1.4
TITLE = Show Actual Battery Percent
DESCRIPTION = ???
CATEGORY = Luna
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
