NAME = show-actual-battery-percent
PATCH = /luna/${NAME}.patch
TITLE = Show Actual Battery Percent
DESCRIPTION = Shows the actual battery percent in the top bar rather than the gui percent mapping.  
CATEGORY = Luna
VERSION = 0.4.0
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
