NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = SMS Vibrate to Two Seconds
DESCRIPTION = Extends the vibrate time to two second whenever you alerted for a SMS message.
CATEGORY = Messaging
VERSIONS = 1.4.5-176 2.1.0-11 2.2.0-62 2.2.3-56
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Abyssul <Time4swim@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/225334-patch-sms-vibrate-two-seconds.html