NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Use default email addr  for you-AT-self-com
DESCRIPTION = Support for any patch or App  that sends an email, such as the patch send all contact via email. The patch replaces the pseudo email address you@self.com, to be used by the 'calling' App or patch, by the current email address of the default email account. The email then can be send immediately without the user having to to change or fill in the 'to' address.
CATEGORY = Email
VERSIONS = 2.1.0-171 2.2.0-30 2.2.3-30
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Dick99999
HOMEPAGE = http://forums.precentral.net/webos-patches/300185-patch-use-default-email-addr-you-self-com.html#post3167824