NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Use default email addr  for you-AT-self-com
DESCRIPTION = Support for patches that send an email such as send all contact via email. A symbolic address used in the patch (you@self.com) is replaced by the current email address of the default account.
CATEGORY = Email
VERSIONS = 2.1.0-170 2.2.0-29
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Dick99999
HOMEPAGE =