NAME     = prechess
APP_ID   = com.boatrights.${NAME}
VERSION  = 0.0.01
PLATFORM = all
HOMEPAGE = http://forums.precentral.net/homebrew-apps/193848-pre-chess-nrr.html

SRC_IPKG = http://forums.precentral.net/attachments/homebrew-apps/23012d1248157183-pre-chess-nrr-com.boatrights.prechess_0.0.01_all.ipk
include ../../support/download.mk

include ../../support/application-copy.mk
