NAME     = prechess
APP_ID   = com.boatrights.${NAME}
VERSION  = 0.0.04
PLATFORM = all
HOMEPAGE = http://www.precentral.net/homebrew-apps/homebrew-apps/pre-chess

SRC_IPKG = http://www.precentral.net/sites/precentral.net/files/webos-homebrew-apps/feeds/com.boatrights.prechess_0.0.04_all_0.ipk
include ../../support/download.mk

include ../../support/application-copy.mk
