NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Format app menu for adding date
DESCRIPTION = Shrinks the app menu to prevent overlap when using add date patches.  Works perfectly with 'Add date - MM/DD'.
CATEGORY = Top Bar
VERSIONS = 1.4.0-65 1.4.1-37 1.4.2-22 1.4.3-16 1.4.5-21
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = cwgtex
HOMEPAGE = http://forums.precentral.net/webos-patches/252052-patch-format-app-menu-adding-date.html