NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Find in Page
DESCRIPTION = Add the ability to search for text within a page in the Web Browser.  Access the find dialog from the app menu.Note: This is an early version, and has had little testing.  It also lacks a working 'previous' button currently.This will cause some weird behaviors.  The zoom level may change at random, and may scroll in odd ways.  If anyone can find a solution please let me know.
CATEGORY = Browser
VERSIONS = 3.0.2-46
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = minego (Micah N Gorrell) <patches@minego.net>
HOMEPAGE =