NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Edit Item as New
DESCRIPTION = This patch allows you to edit an existing calendar item as a new item and edit it. (i.e. copy it)
CATEGORY = Calendar
VERSIONS = 1.4.1-8
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/2/28/Calendar-edit-item-as-new-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = lexb <lex.brugman@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/241773-patch-edit-calendar-item-new.html