NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Edit Item as New
DESCRIPTION = This patch allows you to edit an existing calendar item as a new item and edit it. (i.e. copy it)
CATEGORY = Calendar
VERSIONS = 1.4.5-140 2.0.0-40 2.0.1-67 2.1.0-30 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = lexb <lex.brugman@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/241773-patch-edit-calendar-item-new.html
