NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TWEAKS =
TITLE = Max Blocker
DESCRIPTION = This is a superset to Ad Blocker. It blocks ads, tracking etc.If you find that this breaks an app for you, try uninstalling it and using Ad Blocker instead. WARNING: Only install Max Blocker OR Ad Blocker, not both. Failure to heed this will result in Santa putting you on the naughty list.
CATEGORY = Misc
VERSIONS = 3.0.5-4
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = webosinternals
HOMEPAGE =