NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = GPS Icon On Top Bar
DESCRIPTION = This patch adds an icon to the phone's top bar when the GPS is turned on.
CATEGORY = Top Bar
VERSIONS = 1.4.5-1 2.1.0-2 2.1.1-22 2.1.2-31 2.2.4-43
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/c/c9/Top-bar-gps-icon-on-top-bar-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = roto22, EdCates, Herrie
HOMEPAGE = http://forums.precentral.net/webos-patches/243684-patch-gps-top-bar.html