NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Bridge Call Dialer Calendar Launcher
DESCRIPTION = Create an item in the Calendar Event application menu that launches the 'Bridge Call Dialer' App.
CATEGORY = Calendar
VERSIONS = 1.4.5-78
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/c/ce/Calendar-bridge-call-dialer-calendar-launcher-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ahub-dev <support@ahub-dev.com>
HOMEPAGE = www.ahub-dev.com
