NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS = system/${NAME}.json
TITLE = Autostart Exhibition
DESCRIPTION = Autostart Exhibition mode from the Exhibition app which ordinarily launches into the Preferences screen
CATEGORY = System
VERSIONS = 2.1.0-159 2.2.0-19 2.2.3-19 3.0.2-53 3.0.4-3
ICON = http://www.webos-internals.org/images/f/f1/Icon_WebOSInternals_Patch_Plus.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = appsotutely <patches@appsotutely.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/280531-patch-request-exhibition.html