NAME = enable-landscape-email
PATCH = /email/${NAME}.patch
VERSION = 0.1.3
TITLE = Enable Landscape Email
DESCRIPTION = Enable landscape mode in email app
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
