NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Fixed Keyboard Brightness 50
DESCRIPTION = Keeps the keyboard brightness at a fixed value of 50.
CATEGORY = Misc
VERSIONS = 1.4.5-90
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = webOSdealer
HOMEPAGE = http://forums.precentral.net/webos-patches/266115-fixed-keyboard-brightness-patches.html