NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = No Airplane Mode
DESCRIPTION = Removes the airplane mode toggle from the device menu.
CATEGORY = Top Bar
VERSIONS = 1.4.5-1 2.0.1-45 2.1.0-3
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/213754-patch-request-remove-airplane-mode-drop-down-2.html#post2036132