NAME = hide-nfl-app
PATCH = /nfl/${NAME}.patch
TITLE = Hide NFL App
DESCRIPTION = Hides the NFL App in the Launcher
CATEGORY = NFL
VERSION = 0.1.16
ICON = http://www.webos-internals.org/images/8/80/Icon_WebOSInternals_Patches_Nfl.png

include ../common.mk
include ../modifications.mk
