NAME = hide-nfl-app
PATCH = /nfl/${NAME}.patch
TITLE = Hide NFL App
DESCRIPTION = This will hide the NFL application in the App Launcher.
CATEGORY = App Launcher
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/8/80/Icon_WebOSInternals_Patches_Nfl.png
SCREENSHOTS =
META_VERSION = 1

include ../common.mk
include ../modifications.mk
