NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Continue Sending Video in Skype when Minimize
DESCRIPTION = This patch allows the Phone app to continue sending video even when the card is minimized. This patch does not enable playing video when the card is minimized.
CATEGORY = Phone
VERSIONS = 3.0.5-46
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GMMan <yukaili.geek@gmail.com>
HOMEPAGE = http://forums.webosnation.com/webos-patches/319902-patch-continue-sending-video-skype-when-minimized.html