NAME = $(shell basename $(shell pwd))
PATCH = video-player/${NAME}.patch
TITLE = Add Delete Buttons
DESCRIPTION = Adds buttons for deleting a video while viewing the video details or watching the video.
CATEGORY = Video Player
VERSIONS = 1.4.1-8
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Videoplayer.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/e/ed/Video-player-add-delete-buttons-1.png\",\
\"http://www.webos-internals.org/images/a/a7/Video-player-add-delete-buttons-2.png\",\
\"http://www.webos-internals.org/images/d/d6/Video-player-add-delete-buttons-3.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/242017-patch-add-delete-buttons-videos.html#post2385309