NAME = state
PATCH = /phone/${NAME}.patch
VERSION = 0.1.1
TITLE = state patch
DESCRIPTION = ???
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
