NAME = state
PATCH = /phone/${NAME}.patch
VERSION = 0.1.4
TITLE = state patch
DESCRIPTION = ???
CATEGORY = Phone
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
