NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Launcher Page Selection Tabs
DESCRIPTION = This patch adds tabs to the top of the app launcher, giving quick access to any page without swiping.
CATEGORY = App Launcher
VERSIONS = 1.3.5-12
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = lmorchard
HOMEPAGE = http://forums.precentral.net/webos-patches/223410-patch-page-selection-tabs-app-launcher.html