NAME     = magic8ball
APP_ID   = com.orbsix.app.magic8ball
VERSION  = 0.1.0
PLATFORM = all
HOMEPAGE = http://forums.precentral.net/homebrew-apps/194675-magic-8-ball-v0-1-0-7-24-a.html

SRC_IPKG = http://forums.precentral.net/attachments/homebrew-apps/23516d1248466572-magic-8-ball-v0-1-0-7-24-com.orbsix.app.magic8ball_0.1.0_all.ipk
include ../../support/download.mk

include ../../support/application-copy.mk
