NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Enhanced Nav Buttons
DESCRIPTION = This patch lets you access the entire card history when holding down the 'back' and 'forward' buttons (might conflict with other browser patches).
CATEGORY = Browser
VERSIONS = 3.0.4-71 3.0.5-32
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Garret92C, isagar2004
HOMEPAGE =