NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Palm Dark System Devices
DESCRIPTION = Changes Programs to Palm Dark<br/>app store<br/>backup<br/>bluetooth<br/>browser<br/>calender<br/>certificate<br/>clock<br/>contacts<br/>date time<br/>dev mode<br/>device info<br/>docviewer<br/>email<br/>languagepicker<br/>location<br/>maps<br/>messaging<br/>musicplayer<br/>phone<br/>screen and lock<br/>sounds<br/><br/>20-12-01<br/>Removed:<br/>Messaging<br/>Email<br/><br/>Added<br/>Wifi<br/>Update <br/><br/><br/>NOTE: This patch modifies many different Palm packages, so it will likely not work for OTA updates.  Users may need to EPR to remove it and update it.
CATEGORY = Misc
VERSIONS = 1.4.5-111
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Warlord
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2780759&posted=1#post2780759
