NAME = $(shell basename $(shell pwd))
PATCH = advanced/${NAME}.patch
TITLE = Advanced System Prefs - System Prefs
DESCRIPTION = * Requires Advanced System Prefs Framework patch to function properly!<br/><br/>Adds additional preferences into some of the system preferences applications.
CATEGORY = Advanced
VERSIONS = 2.1.0-98 2.2.0-2
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/c/c7/AdvancedSystemPrefsSystem_1.jpg\",\"http://www.webos-internals.org/images/8/84/AdvancedSystemPrefsSystem_2.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = http://forums.precentral.net/enlightened-linux-solutions/269550-patch-advanced-system-prefs-2-x.html
