NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Hebrew layout for the physical keyboard
DESCRIPTION = Adds Hebrew support for the physical keyboard. Press the SYM button twice to switch between English/Hebrew layouts.
CATEGORY = Mojo
VERSIONS = 2.1.0-219 2.1.1-20 2.1.2-29 2.2.0-94 2.2.3-87
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = isagar2004
HOMEPAGE =