NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Hebrew layout for the physical keyboard
DESCRIPTION = Adds Hebrew support for the physical keyboard
CATEGORY = Mojo
VERSIONS = 2.1.0-181 2.2.0-46 2.2.3-39
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = isagar2004
HOMEPAGE =