NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Scrim Email
DESCRIPTION = This patch adds the ability to add a background scrim image to the email app. When you install this patch it will first change the email app to almost the Palm-Dark scheme (dark gray back ground with white fonts) if you like it you can stop there. For the user that wants to add their own back ground, there are many 320x480 png images to choose from. Choose an image, name it email-scrim.png and save it in the wallpapers folder (/media/internal/wallpapers/) on your Pre. There are some great scrim images and ideas here: <a href="http://forums.precentral.net/webos-patches/214624-patch-add-background-scrim-contacts-app.html">http://forums.precentral.net/webos-patches/214624-patch-add-background-scrim-contacts-app.html</a>
CATEGORY = Email
VERSIONS = 1.4.5-1
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/2/28/Email-scrim-email-1.jpg\",\
\"http://www.webos-internals.org/images/8/8e/Email-scrim-email-2.jpg\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = mracer29 <mracer29@yahoo.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/214891-patch-add-background-scrim-email-app.html?highlight=scrim
