NAME = $(shell basename $(shell pwd))
PATCH = camera/${NAME}.patch
TITLE = Improved PIXI Video Naming
DESCRIPTION = Will output videos from the camera in the format: PIXI_YYYY-MM-DD-hhmmss.mp4
CATEGORY = Camera
VERSIONS = 2.0.1-45
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE =