NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Audio/Video Attachments
DESCRIPTION = Adds ability to attach (send) audio and video files in the Messaging application.
CATEGORY = Messaging
VERSIONS = 1.2.1-0 1.1.3-0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/1/14/All-attachments-1.png\",\
\"http://www.webos-internals.org/images/5/5c/All-attachments-2.png\",\
\"http://www.webos-internals.org/images/f/f6/All-attachments-3.png\" ]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = fritos1406
