NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Increase Font Size 18
DESCRIPTION = Increases the font of the top bar to size 18 for the carrier string, date/time, battery icon percent (if you have the Battery Icon as Percent patch installed), and to size 16 for the app name when an app is open.  It makes the clock much easier to read and uses up more of the available space.<br/><br/>NOTE: To display properly, this patch should only be used with the Battery Icon AS Percent patch.
CATEGORY = Top Bar
VERSION = 1.3.1-20
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/0/06/Top-bar-increase-top-bar-font-size-1.jpg\",\
\"http://www.webos-internals.org/images/4/4a/Top-bar-increase-top-bar-font-size-2.jpg\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = jmartino2011 <jmartino2011@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2055028#post2055028
