NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = file URLs for Browser
DESCRIPTION = generally allow browsing local files
CATEGORY = Browser
VERSIONS = 3.0.5-4
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = chpwn <support@chpwn.com>
HOMEPAGE = http://chpwn.com/
