NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Hide VoiceMail Button
DESCRIPTION = Hides the VoiceMail button in the phone application, increases the size of the 2nd button on the right to be full width.
CATEGORY = Phone
VERSIONS = 1.4.5-90 2.0.0-35 2.0.1-62 2.1.0-16
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/f/f4/Phone-hide-voicemail-button-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Pulp, Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/266067-patch-hide-voicemail-button.html