NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Hide VoiceMail Button
DESCRIPTION = Hides the VoiceMail button/tab in the phone application
CATEGORY = Phone
VERSIONS = 1.4.5-90 2.1.0-16 2.2.0-19 3.0.2-3 3.0.4-5
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/f/f4/Phone-hide-voicemail-button-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/288394-patch-touchpad-hide-voicemail-button.html