NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Hebrew support for physical keyboard
DESCRIPTION = Hebrew support for physical keyboard. Double press Sym button to switch between English/Hebrew.
CATEGORY = Mojo
VERSIONS = 2.0.1-37
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/4/45/Mojo-hebrew-support-for-physical-keyboard-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Avner Arbel / palmpreacher <preacher@palmpreacher.com>
HOMEPAGE = www.palmpreacher.com