NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Hebrew support for physical keyboard
DESCRIPTION = Hebrew support for physical keyboard. Double press Sym button to switch between English/Hebrew.
CATEGORY = Mojo
VERSIONS = 2.0.0-40 2.0.1-67 2.1.0-30 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Avner Arbel / palmpreacher <preacher@palmpreacher.com>
HOMEPAGE = www.palmpreacher.com
