NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Delete Email and View Next - Older Message
DESCRIPTION = Normally when you hit delete within an email message. The message is deleted then you are back to the Message List. This patch will move you to the next message(Older) in the list instead. Which is the default sort.
CATEGORY = Email
VERSIONS = 1.4.0-84 1.4.1-69 1.4.2-56 1.4.3-51 1.4.5-78
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = theinnkeeper
HOMEPAGE = http://forums.precentral.net/webos-patches/257228-patch-email-delete-next.html#post2583966