NAME = roam-control
PATCH = /phoneprefs/${NAME}.patch
TITLE = Roam Control Patch
DESCRIPTION = Enable roam only option in phone preferences
CATEGORY = Phone Preferences
VERSION = 0.1.19
ICON = http://www.webos-internals.org/images/c/c8/Icon_WebOSInternals_Patches_Phonepreferences.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
