NAME = roam-control
PATCH = /phoneprefs/${NAME}.patch
TITLE = roam control patch
DESCRIPTION = ???
CATEGORY = Phone Preferences
VERSION = 0.1.16
ICON = http://www.webos-internals.org/images/c/c8/Icon_WebOSInternals_Patches_Phonepreferences.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
