NAME = roam-control
PATCH = /phoneprefs/${NAME}.patch
VERSION = 0.1.4
TITLE = roam control patch
DESCRIPTION = ???
CATEGORY = Phone Preferences
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
