#!/bin/sh
PACKAGE=org.webosinternals.emergency-patch-recovery
PATCH_CONTROL_DIR=/var/usr/lib/.webosinternals.patches
PATCH_LOG=/media/internal/webos-patches.log
IPKG_INFO_DIR=/usr/lib/ipkg/info

if [ ! -e $PATCH_LOG ]
then
  touch $PATCH_LOG
  echo "******* Patch Log Created by EPR $(date) ************" >> $PATCH_LOG
fi

echo "" >> $PATCH_LOG
echo "------------------------------------------------------" >> $PATCH_LOG
echo "Emergency Patch Recovery $(date)" >> $PATCH_LOG
echo "------------------------------------------------------" >> $PATCH_LOG

if [ "$IPKG_OFFLINE_ROOT" = "" ]
then
  echo "ERROR: IPKG_OFFLINE_ROOT must be supplied to the postinst" | tee -a $PATCH_LOG
  exit 1
fi

if [ ! -d $PATCH_CONTROL_DIR ]
then
  echo "NOTE: No patches found!" | tee -a $PATCH_LOG
  ipkg -o $IPKG_OFFLINE_ROOT remove $PACKAGE
  exit 1
fi

if [ -e $PATCH_CONTROL_DIR/packages ]
then
  for i in `cat $PATCH_CONTROL_DIR/packages`
  do
    package=`echo $i | awk '{print $1}'`
    version=`echo $i | awk '{print $2}'`

    if [ "$version" = "" ]
    then
      version=apt-1
    fi

    echo "" >> $PATCH_LOG
    echo "------------------------------------------------------" >> $PATCH_LOG
    echo "Removing package: $package" >> $PATCH_LOG
    echo "Patch technology: $version" >> $PATCH_LOG
    echo "------------------------------------------------------" >> $PATCH_LOG
		echo "Remove from /var..." >> $PATCH_LOG
    ipkg -o /var --force-depends remove $package
    echo "" >> $PATCH_LOG
		echo "Remove from /media/cryptofs/apps..." >> $PATCH_LOG
    ipkg -o /media/cryptofs/apps --force-depends remove $package
  done
fi

if [ -e $PATCH_CONTROL_DIR/backups ]
then
  for i in `cat $PATCH_CONTROL_DIR/backups`
  do
    file=`echo $i | awk '{print $1}'`
    version=`echo $i | awk '{print $2}'`
    palm_md5sum=`grep -h $file $IPKG_INFO_DIR/*md5sums | awk '{print $1}'`
    file_md5sum=`md5sum $file | awk '{print $1}'`

    if [ "$version" = "" ]
    then
      version=apt-1
    fi

    echo "File: $file" >> $PATCH_LOG
    echo "Patch technology: $version" >> $PATCH_LOG
    echo "  palm md5sum: $palm_md5sum" >> $PATCH_LOG
    echo "  file md5sum: $file_md5sum" >> $PATCH_LOG
    if [ "$palm_md5sum" = "$file_md5sum" ]
    then
      echo "Existing file matches Palm md5sum (maybe due to OTA update)" | tee -a $PATCH_LOG
      echo "Removing original file..." | tee -a $PATCH_LOG
      rm -f $file.webosinternals.orig
    else
      if [ ! -e $file.webosinternals.orig ]
      then
        echo "WARNING: Could not find backup for $file" | tee -a $PATCH_LOG
      elif [ ! -s $file.webosinternals.orig ]
      then
        echo "Removing created file $file" | tee -a $PATCH_LOG
        rm -f $file
        rm -f $file.webosinternals.orig
      else
        echo "Recovering original file $file..." | tee -a $PATCH_LOG
        mv $file.webosinternals.orig $file
      fi
    fi
  done
fi

echo "DONE" | tee -a $PATCH_LOG
rm -rf $PATCH_CONTROL_DIR

ipkg -o $IPKG_OFFLINE_ROOT remove $PACKAGE
exit 0
