#!/bin/sh
PACKAGE=org.webosinternals.emergency-patch-recovery
PATCH_CONTROL_DIR=/var/usr/lib/.webosinternals.patches
IPKG_INFO_DIR=/usr/lib/ipkg/info

if [ ! -d $PATCH_CONTROL_DIR ]
then
  echo "NOTE: No patches found!"
  ipkg -o $IPKG_OFFLINE_ROOT remove $PACKAGE
  exit 1
fi

if [ -e $PATCH_CONTROL_DIR/packages ]
then
  for i in `cat $PATCH_CONTROL_DIR/packages`
  do
    ipkg -o $IPKG_OFFLINE_ROOT remove $i
  done
fi

if [ -e $PATCH_CONTROL_DIR/backups ]
then
  for i in `cat $PATCH_CONTROL_DIR/backups`
  do
    palm_md5sum=`grep -h $i $IPKG_INFO_DIR/*md5sums | awk '{print $1}'`
    file_md5sum=`md5sum $i | awk '{print $1}'`
    #echo "palm: $palm_md5sum"
    #echo "file: $file_md5sum"
    if [ "$palm_md5sum" = "$file_md5sum" ]
    then
      echo "Existing file matches Palm md5sum (maybe due to OTA update)"
      echo "Removing original file..."
      rm -f $i.webosinternals.orig
    else
      if [ ! -e $i.webosinternals.orig ]
      then
        echo "WARNING: Could not find backup for $i"
      elif [ ! -s $i.webosinternals.orig ]
      then
        echo "Removing created file $i"
        rm -f $i
        rm -f $i.webosinternals.orig
      else
        echo "Recovering original file $i..."
        mv $i.webosinternals.orig $i
      fi
    fi
  done
fi

echo "DONE"
rm -rf $PATCH_CONTROL_DIR

ipkg -o $IPKG_OFFLINE_ROOT remove $PACKAGE
exit 0
