NAME = $(shell basename ${PWD})
PATCH = /messaging/${NAME}.patch
TITLE = Timestamp - Builtin
DESCRIPTION = This will cause the Messaging application use the builtin timestamps for all messages instead of just messages that show up late.
CATEGORY = Messaging
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
