NAME = timestamp-all-messages-builtin-method
PATCH = /messaging/${NAME}.patch
TITLE = Builting Timestamp Messaging always
DESCRIPTION = Always use builtin timestamps for messaging app that usually only are used for messages that show up late
CATEGORY = Messaging
VERSION = 0.2.1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
