NAME = timestamp-all-messages-builtin-method
PATCH = /messaging/${NAME}.patch
TITLE = Messaging Timestamp - Builtin
DESCRIPTION = This will cause the Messaging application use the builtin timestamps for all messages instead of just messages that show up late.
CATEGORY = Messaging
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/wiki/Image:Timestamp-all-messages-builtin-method.png\"]
META_VERSION = 1

include ../common.mk
include ../modifications.mk
