NAME = $(shell basename $(shell pwd))
PATCH = clock/${NAME}.patch
TWEAKS =
TITLE = Auto Set Clock Alarm to 95 Percent Volume
DESCRIPTION = This will Auto Set Clock Alarm volume to 95% volume always when the alarm goes off using the Default Clock App. This will automatically raise or lower you ringtone volume for the Alarm to 95% volume.
CATEGORY = Clock
VERSIONS = 2.1.0-255 2.1.1-60 2.1.2-70 2.2.4-61
ICON = http://www.webos-internals.org/images/8/8d/Icon_WebOSInternals_Patches_Clock.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Djgardn2
HOMEPAGE = forums.webosnation.com/webos-patches/315011-patch-auto-set-alarm-clock-volume.html