NAME = $(shell basename $(shell pwd))
PATCH = sounds-and-alerts/${NAME}.patch
TWEAKS =
TITLE = Charging Alert Vibrate Only
DESCRIPTION = This will change the charging alert sound to vibrate only.
CATEGORY = Sounds and Alerts
VERSIONS = 3.0.5-3
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Soundsandalerts.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = michote
HOMEPAGE =
