NAME = $(shell basename $(shell pwd))
PATCH = google-maps/${NAME}.patch
TWEAKS =
TITLE = Save Google Maps - while having HP Maps too
DESCRIPTION = Patch will let you keep Google Maps app from disappearing when installing HP's Maps app (powered by Microsoft's Bing Maps). Must install this patch first before installing HP Maps.
CATEGORY = Google Maps
VERSIONS = 1.4.5-174
ICON = http://www.webos-internals.org/images/c/c3/Icon_WebOSInternals_Patches_SprintNav.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = opacityzero
HOMEPAGE = http://forums.precentral.net/webos-patches/303811-patch-save-google-maps.html