NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Call Log Styling Mod
DESCRIPTION = Adds call type icons to all the first row calls & changes all the first row calls to boldface font, rather than only the missed calls.
CATEGORY = Phone
VERSIONS = 1.4.0-32
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/c/c7/Phone-call-log-styling-mod-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/236482-patch-call-log-styling-mod.html#post2309011