NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Call Block with Block Unknown or Blocked
DESCRIPTION = This is a version of the call block patch that will block not only those in your 'Do Not Answer' contact but also unknown and blocked numbers.
CATEGORY = Phone
VERSIONS = 1.4.0-38 1.4.1-7
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Elryon <elryon@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/211255-patch-call-block-ignore-14.html#post2373487