NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = No AutoDial from Contacts
DESCRIPTION = Makes sure that there will be no autodial from the contacts app when you press the phone number, it will prefill the dialer with the number instead.
CATEGORY = Phone
VERSIONS = 2.2.4-45
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Herrie <webos-internals.org@herrie.org>
HOMEPAGE = http://forums.webosnation.com/webos-patches/311509-patch-no-autodial-contacts.html