NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Text Messaging White Font
DESCRIPTION = Changes text in the messaging application to white.
CATEGORY = Messaging
VERSIONS = 1.4.1-42 1.4.2-28 1.4.3-22 1.4.5-28
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Demlor <trfuller7@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/257581-patch-text-messaging-white-font.html