NAME           = aufs
APP_ID         = org.webosinternals.modules.${NAME}
TITLE          = AUFS module
TYPE           = Modules
CATEGORY       = Kernel
VERSIONS       = 1.4.1-65
BLDFLAGS       = -p
DESCRIPTION    = This is the AUFS (Another Union FileSystem) kernel module.  AUFS is useful for mounting rw overlays on ro filesystems.  
CHANGELOG      = 
DEVICE         = pre
SRC_GIT = git://git.webos-internals.org/kernels/patches.git
#SRC_GIT = /source/webos-internals/kernels/patches
EXTRA_MODULES = aufs

include ../../support/modules.mk
