#!/bin/sh
THEME=autumn
KB_CONFIG=/media/internal/virtual-keyboard/kb_config.json

rm -rf /media/internal/virtual-keyboard/.themes/${THEME}
if [ -e ${KB_CONFIG} ]; then
  sed -i -e '/"value":"'${THEME}'"/d' ${KB_CONFIG}
fi
