NAME = $(shell basename ${PWD})
PATCH = /messaging/${NAME}.patch
TITLE = New Card per Convo
DESCRIPTION = This will create a new card per conversation in the Messaging application.
CATEGORY = Messaging
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOT = [\"http://www.webos-internals.org/images/c/c3/Messaging-new-card-per-convo.png\"]
META_VERSION = 1

include ../common.mk
include ../modifications.mk
