NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = New Card per Convo
DESCRIPTION = This will create a new card per conversation in the Messaging application.
CATEGORY = Messaging
VERSIONS = 1.2.1-2 1.1.3-2 1.3.1-2 1.3.5-4
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOT = [\"http://www.webos-internals.org/images/c/c3/Messaging-new-card-per-convo.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Mike dg, dBsooner <webos@dbsooner.com>
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Messaging_New_Cards_For_Each_Conversation
