NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = New Card per Convo
DESCRIPTION = This will create a new card per conversation in the Messaging application.
CATEGORY = Messaging
VERSIONS = 1.3.5-5 1.4.0-18 v1.4.1-1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = dBsooner, Mike dg
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Messaging_New_Cards_For_Each_Conversation
