NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Change EV icon to 3G
DESCRIPTION = Switches the EV icon set for the on-device 3G icon set.
CATEGORY = Top Bar
VERSIONS = 2.0.0-30 2.0.1-52 2.1.0-4 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/a/a9/Top-bar-change-ev-icon-to-3g-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha <dropdeadbabies@gmail.com>, xanthinealkaloid
HOMEPAGE = http://forums.precentral.net/webos-patches/235435-patch-change-evdo-icon-3g.html
