NAME = $(shell basename $(shell pwd))
PATCH = clock/${NAME}.patch
TITLE = Show hidden clocks
DESCRIPTION = Show 5 hidden clocks in 2.xx 0nly
CATEGORY = Clock
VERSIONS = 2.0.0-29 2.0.1-51 2.1.0-2
ICON = http://www.webos-internals.org/images/8/8d/Icon_WebOSInternals_Patches_Clock.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Warlord9159
HOMEPAGE = http://m.forums.precentral.net/2879434-post54.html