NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = Set Avatar in Messaging
DESCRIPTION = This adds a menu option to dynamically set avatar whenever you want. Requires FileMgr service.
CATEGORY = Messaging
VERSIONS = 1.4.5-30 2.1.0-36 2.2.0-19
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/257309-patch-set-avatar-messaging.html#post2611333