NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Swipe History Auto Confirm
DESCRIPTION = This will add the ability to swipe delete items in the browser history WITHOUT a confirmation dialog.
CATEGORY = Browser
VERSIONS = 1.3.5-3 1.4.0-26 1.4.1-1
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = dBsooner, Wtgreen
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Browser_Delete_Individual_History_Items
