NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Battery Percent as Icon Big with Color
DESCRIPTION = This will replace the battery icon in the top bar with a color-coded percent number.<br/>Charging = Teal.<br/>100%-70% = Green.<br/>69%-45% = Yellow.<br/>44%-20% = Orange.<br/>19%-0% = Red.
CATEGORY = Top Bar
VERSIONS = 2.0.0-29 2.0.1-51 2.1.0-2 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/6/60/Top-bar-battery-percent-as-icon-big-with-color-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = nesl247, Jason Robitaille, CRaiaSoftware
HOMEPAGE = http://forums.precentral.net/webos-patches/275560-patch-webos-2-0-bucket-o-patches-2.html#post2877211
