NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TWEAKS =
TITLE = Default to Week View
DESCRIPTION = This will set the default view of the Calendar application to Week view.
CATEGORY = Calendar
VERSIONS = 3.0.2-16 3.0.4-3 3.0.5-10
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 2

include ../common.mk

include ../modifications.mk

MAINTAINER = djgardn2, matthewn
HOMEPAGE = http://forums.precentral.net/webos-patches/291355-patch-touchpad-open-calendar-week-view.html