NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Default to Week View
DESCRIPTION = This will set the default view of the Calendar application to Week view.
CATEGORY = Calendar
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/2/27/Default-to-week-view.png\"]
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
