NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = Default to Week View
DESCRIPTION = This will set the default view of the Calendar application to Week view.
CATEGORY = Calendar
VERSIONS = 1.3.5-3 1.4.0-3 1.4.1-1 1.4.2-1
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/2/27/Default-to-week-view.png\"]
META_SUB_VERSION = 2

include ../common.mk
include ../modifications.mk

MAINTAINER = matthewn <webospatches@mahnamahna.net>
