NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Hide Nascar App
DESCRIPTION = This will hide the Nascar application in the App Launcher.
CATEGORY = App Launcher
VERSIONS = 1.3.5-34 1.4.0-52 1.4.1-24 1.4.2-1 1.4.5-8
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = dBsooner, noir, cryptk (Chris Jowett), v3ritas
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Launcher_Hide-Delete_The_NASCAR_App