NAME = $(shell basename $(shell pwd))
PATCH = /app-launcher/${NAME}.patch
TITLE = Hide Nascar App
DESCRIPTION = This will hide the Nascar application in the App Launcher.
CATEGORY = App Launcher
VERSION = 1.2.1-0
ICON = http://www.webos-internals.org/images/b/b8/Icon_WebOSInternals_Patches_Nascar.png
SCREENSHOTS =
META_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = noir
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Launcher_Hide-Delete_The_NASCAR_App
