#!/bin/sh
APP_DIR=/var/usr/palm/applications/org.webosinternals.virtual-keyboard
MEDIA_BASE=/media/internal/virtual-keyboard
THEMES="themes/remix_ice themes/remix_classic themes/remix_glossy"
SOUNDS=sounds/click1.wav

while read i
do
  file=/`echo $i | awk -F* '{print $2}'`
  expected=`echo $i | awk '{print $1}'`
  calculated=`md5sum $file | awk '{print $1}'`
  if [ "$expected" != "$calculated" ]
  then
    echo "ERROR: mismatch md5sums"
    exit 1
  fi
done < ${APP_DIR}/md5sums

cd / && /var/usr/bin/patch -p1 < ${APP_DIR}/patches/add-onscreen-keyboard.patch

# Default themes, sounds and config
if [ ! -d ${MEDIA_BASE} ]
then
  rm -rf ${MEDIA_BASE}
  mv ${APP_DIR}/virtual-keyboard ${MEDIA_BASE}
else
  if [ ! -d ${MEDIA_BASE}/themes ]
  then
    rm -rf ${MEDIA_BASE}/themes
    mv ${APP_DIR}/virtual-keyboard/themes ${MEDIA_BASE}/themes
  else
    for i in ${THEMES}
    do
      rm -rf ${MEDIA_BASE}/$i
      mv ${APP_DIR}/virtual-keyboard/$i ${MEDIA_BASE}/$i
    done
  fi

  if [ ! -d ${MEDIA_BASE}/sounds ]
  then
    rm -rf ${MEDIA_BASE}/sounds
    mv ${APP_DIR}/virtual-keyboard/sounds ${MEDIA_BASE}/sounds
  else
    for i in ${SOUNDS}
    do
      rm -rf ${MEDIA_BASE}/$i
      mv ${APP_DIR}/virtual-keyboard/$i ${MEDIA_BASE}/$i
    done
  fi

  if [ ! -e ${MEDIA_BASE}/kb_config.json ]
  then
    mv ${APP_DIR}/virtual-keyboard/kb_config.json ${MEDIA_BASE}/kb_config.json
  fi
fi

stop LunaSysMgr && start LunaSysMgr
exit 0
