NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = All-Day Events in Month View
DESCRIPTION = This will enable showing of all-day events while in the Month View of the Calendar application.
CATEGORY = Calendar
VERSIONS = 1.3.5-17 1.4.0-6 1.4.1-1 1.4.2-1 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/7/70/Calendar-all-day-events-month-view-1.jpg\",\
\"http://www.webos-internals.org/images/9/90/Calendar-all-day-events-month-view-2.jpg\",\
\"http://www.webos-internals.org/images/2/26/Calendar-all-day-events-month-view-3.jpg\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = daventx, d2globalinc, Hopspitfire
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Calendar_Show_All-Day_Events_in_Month_View
