NAME = $(shell basename $(shell pwd))
PATCH = /calendar/${NAME}.patch
TITLE = All-Day Events in Month View
DESCRIPTION = Does not work properly in 1.2.0+ at this time. -- This will enable showing of all-day events while in the Month View of the Calendar application.
CATEGORY = Calendar
WEBOS_VERSION = 1.2.1
IPKG_VERSION = 0
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Hopspitfire
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Calendar_Show_All-Day_Events_in_Month_View
