NAME = $(shell basename $(shell pwd))
PATCH = /calendar/${NAME}.patch
TITLE = All-Day Events in Month View
DESCRIPTION = Does not work properly in 1.2.0+ at this time. -- This will enable showing of all-day events while in the Month View of the Calendar application.
CATEGORY = Calendar
VERSION = 1.2.1-0
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS =
META_VERSION = 1

include ../common.mk
include ../modifications.mk
