NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Delete Email and View Next - Deluxe
DESCRIPTION = Allows you to decide if you want to go to the next email in your list after deletion.  Newer moves you up the list after deletion, older moves you down.  List is default functionality where you go back to your list of emails.
CATEGORY = Email
VERSIONS = 1.4.5-96
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/0/08/Email-delete-email-and-view-next---deluxe-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = theinnkeeper <rdiaz@centeraxis.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/257228-patch-email-delete-next.html
