NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Boom action time
DESCRIPTION = Changes 'Just type...' to 'Boom, action time!' in card view and the just type scene
CATEGORY = Mojo
VERSIONS = 2.0.0-5 2.0.1-5
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/d/d0/Mojo-boom-action-time-1.png\",\
\"http://www.webos-internals.org/images/5/51/Mojo-boom-action-time-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = oil <brandonvb@gmail.com>
HOMEPAGE =
