NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Enable Landscape Messaging
DESCRIPTION = This will enable landscape mode in the Messaging application. It uses accelerometer to detect orientation.
CATEGORY = Messaging
VERSIONS = 1.2.1-0 1.3.1-0 1.3.5-3 1.4.0-1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/7/72/Message-orientation.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = fritos1406, dBsooner <webos@dbsooner.com>
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Messaging_Landscape_Orientation
