NAME = $(shell basename $(shell pwd))
PATCH = /messaging/${NAME}.patch
TITLE = Enable Landscape Messaging
DESCRIPTION = This will enable landscape mode in the Messaging application. It uses accelerometer to detect orientation.
CATEGORY = Messaging
VERSION = 1.2.1-0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/7/72/Message-orientation.png\"]
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk

MAINTAINER = fritos1406
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Messaging_Landscape_Orientation
