NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Launch with Folder View Minimized
DESCRIPTION = When the Email app launches, it'll launch with the folder view minimized
CATEGORY = Email
VERSIONS = 3.0.2-3 3.0.4-5
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/288691-patch-reques-touchpad-default-email-all-inboxes.html#post3038958
