#!/bin/sh

APPID=mobi.optware.openvpn

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

/sbin/stop $APPID

rm -f /var/palm/event.d/${APPID}

# Remove files from /opt
cd ${APPDIR}/opt
find sbin -depth -type f -exec rm -f /opt/{} \;
find sbin -depth -type d -exec rmdir /opt/{} \;

exit 0
