NAME = $(shell basename $(shell pwd))
PATCH = photos/${NAME}.patch
TWEAKS = photos/${NAME}.json
TITLE = Show Filenames
DESCRIPTION = Out of the factory, only images are displayed in the Photos application. For some people, this feels wrong. This patch adds in display of filenames beneath the associated image.
CATEGORY = Photos
VERSIONS = 3.0.2-31
ICON = http://www.webos-internals.org/images/1/1c/Icon_WebOSInternals_Patches_Plus_Photos.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Havvoric <havvoric@gmail.com>
HOMEPAGE =