NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Device Menu Maxed Out Ultra
DESCRIPTION = Date and battery level Bright<br/>Adds temperature<br/>Adds screen brightness control<br/>Adds media volume control<br/>Adds system volume control<br/>Adds phone submenu (radio data roaming) toggles<br/>Adds GPS toggle<br/>Adds a flashlight led toggle<br/>Airplane mode toggle<br/>Bluetooth<br/>WIFI<br/><br/>To the Devicemenu
CATEGORY = Top Bar
VERSIONS = 1.4.5-79
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/7/7a/System-devicemenu-maxed-out-ultra-1.png\",\
\"http://www.webos-internals.org/images/d/de/System-devicemenu-maxed-out-ultra-2.png\",\
\"http://www.webos-internals.org/images/0/09/System-devicemenu-maxed-out-ultra-3.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Warlord
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2649380#post2649380
