NAME     = timer
APP_ID   = com.webonastick.${NAME}
VERSION  = 0.1.0
HOMEPAGE = http://webonastick.com/webos/timer/
DESCRIPTION = A simple timer application.
MAINTAINER = Darren Embry <dse@webonastick.com>
SECTION = Clocks and Timers

SRC_IPKG = http://webonastick.com/webos/packages/${APP_ID}_${VERSION}_all.ipk
include ../../support/download.mk

include ../../support/application-copy.mk
