NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Fully Transparent Launcher
DESCRIPTION = Makes Launcher fully transparent; no background, arrows, or fades.
CATEGORY = App Launcher
VERSIONS = 1.4.0-30 1.4.1-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/5/52/App-launcher-fully-transparent-launcher-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mhous33
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2302773#post2302773
