NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Ad Blocker
DESCRIPTION = Blocks out addresses of ad servers to provide an ad-free web experience
CATEGORY = Misc
VERSIONS = 1.4.5-106 2.0.0-8 2.0.1-10
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille, WebOS Internals
HOMEPAGE = http://forums.precentral.net/webos-patches/236358-patch-ad-blocker.html