NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Add Scrollbars to the Browser
DESCRIPTION = Adds (to the browser) horizontal and vertical scrollbars that looks like the iOS' scrollbars.
CATEGORY = Browser
VERSIONS = 2.1.0-219 2.1.1-20 2.1.2-29 2.2.0-94 2.2.3-87
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = isagar2004
HOMEPAGE = http://forums.precentral.net/webos-patches/307335-patch-browser-scrollbars-ios-like-style.html