NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Sign In As Invisible in IM
DESCRIPTION = Gives An Option To Sign In As Invisible Which Is Found In The Buddies Section. Doesnt Yet Support Google
CATEGORY = Messaging
VERSIONS = 1.3.1-26
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/3/3f/Messaging-sign-in-as-invisible-in-im-1.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/219308-patch-sign-invisible-im.html
