NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Mojo Flick Regulator
DESCRIPTION = Lowers the Flick Scrolling speed in all Mojo apps to match that of the browser, creating a more manageable/unified experience.
CATEGORY = Mojo
VERSIONS = 1.4.5-183 2.1.0-215 2.1.1-22 2.1.2-31 2.2.0-83 2.2.3-77 2.2.4-12 3.0.2-80
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ShiftyAxel <jpalmerwatkins@me.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/307282-patch-mojo-flick-regulator.html