#!/bin/sh
if [ -x /opt/bin/ez-ipupdate -a -e /opt/etc/ez-ipupdate.conf ] ; then
  /opt/bin/ez-ipupdate -i %WAN% -b /opt/var/run/ez-ipupdate.cache -c /opt/etc/ez-ipupdate.conf -q > /dev/null 2>&1 || /bin/true
fi
