NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TWEAKS =
TITLE = More Standby Times
DESCRIPTION = For Phone users (1.4.5, 2.1.0): This will add more standby times to the Screen & Lock application. New settings will be 15 seconds, 3 minutes, 5 minutes and never. For TouchPad (3.0.2, 3.0.4): This adds more standby time possibilities in the 'Screen & Lock' preferences: 15 seconds, 30 seconds, 30 minutes, 1 hour, 3 hours, 8 hours, 24 hours.For all devices: This will not change your standby time automatically. You will have to select the length you desire in 'Screen & Lock' in the 'Settings' tab.
CATEGORY = Screen Lock
VERSIONS = 1.4.5-170 2.1.0-160 2.1.1-22 2.1.2-31 3.0.2-53 3.0.4-3
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/4/4f/Longer-standby-times.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = appsotutely <patches@appsotutely.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/301134-patch-more-standby-times-hd.html
