NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TWEAKS =
TITLE = More Standby Times
DESCRIPTION = For TouchPad users looking for more standby time possibilities in the 'Screen & Lock' preferences. This adds: 15 seconds, 30 seconds, 30 minutes, 1 hour, 3 hours, 8 hours, 24 hours. This will not change your standby time automatically. You will have to select the length you desire in 'Screen & Lock' in the 'Settings' tab.
CATEGORY = Screen Lock
VERSIONS = 1.4.5-170 2.1.0-160 3.0.2-38
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/4/4f/Longer-standby-times.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = appsotutely <patches@appsotutely.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/301134-patch-more-standby-times-hd.html