NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = View Source of Webpage
DESCRIPTION = Adds a 'View Source' option to the web browser's application menu in the 'Page' submenu. (Note: requires Internalz 1.3 or greater)
CATEGORY = Browser
VERSIONS = 2.0.1-45 2.1.0-3 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE =
