#!/bin/sh

DISTRO=ubuntu-natty

NAME=${DISTRO}-chroot

APPID=org.webosinternals.${NAME}

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

# Stop the service if running
/sbin/stop ${APPID} || true

# Remove the upstart script
rm -f /var/palm/event.d/${APPID}

if [ -d /media/ext3fs/${NAME} ] ; then
    echo "Will not overwrite existing chroot directory at /media/ext3fs/${NAME}"
    exit 1
fi

if [ -d /media/ext3fs ] ; then
    mkdir -p /media/ext3fs/${NAME} || exit 1
    tar -C /media/ext3fs/${NAME} -z -x -f ${APPDIR}/${NAME}.tgz || exit 1

    # Install the upstart script
    mkdir -p /var/palm/event.d
    cp ${APPDIR}/upstart/${APPID} /var/palm/event.d/${APPID}
fi

exit 0
