NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Better Email Headers
DESCRIPTION = Better Email Headers aims to provide a more compact header section to email messages, giving a higher focus on the content of the message itself.
CATEGORY = Email
VERSIONS = 3.0.5-36
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = HaDAk <skipmeister123@gmail.com>
HOMEPAGE =