#!/bin/sh

APP_ID=org.webosinternals.avahi

APP_DIR=/media/cryptofs/apps/usr/palm/applications/${APP_ID}

[ -d ${APP_DIR} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Disable mdnsd upstart job
if ! grep "manual" /etc/event.d/mdnsd ; then
  echo manual >> /etc/event.d/mdnsd
fi

/sbin/stop mdnsd

# Create services directory
mkdir -p /var/palm/avahi

ln -s ${APP_DIR}/etc/avahi/services /var/palm/avahi

# Install the upstart configuration file
mkdir -p /var/palm/event.d

cp ${APP_DIR}/upstart/org.webosinternals.avahi-daemon /var/palm/event.d/

# Check that the upstart script was installed
[ -f /var/palm/event.d/org.webosinternals.avahi-daemon ] || exit 1

# Start the service
/sbin/start org.webosinternals.avahi-daemon

exit 0
