#!/bin/sh

# Stop the service if running
/sbin/stop org.webos-internals.avahi-daemon || true

/usr/bin/killall -9 avahi-daemon || true

# Remove the upstart script
rm -f /var/palm/event.d/org.webosinternals.avahi-daemon

rmdir /var/run/avahi-daemon

# Enable mdnsd upstart job
sed -i '/^manual$/d' /etc/event.d/mdnsd

/sbin/start mdnsd

exit 0

