NAME = $(shell basename $(shell pwd))
PATCH = contacts/${NAME}.patch
TITLE = Add Sync Now
DESCRIPTION = Adds a menu item to sync all contacts while in the main list of contacts.
CATEGORY = Contacts
VERSIONS = 1.4.0-42 1.4.1-12 1.4.2-1 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/c/ca/Icon_WebOSInternals_Patches_Contacts.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/1/18/Contacts-add-sync-now-1.png\",\
\"http://www.webos-internals.org/images/5/59/Contacts-add-sync-now-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2383665#post2383665
