NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Delete Email and View Next - Newer Message
DESCRIPTION = Normally when you hit delete within an email message the message is deleted then you are back to the Message List. This patch will move you to the next message(Newer) in the list instead.
CATEGORY = Email
VERSIONS = 1.4.5-80
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = theinnkeeper
HOMEPAGE = http://forums.precentral.net/webos-patches/257228-patch-email-delete-next.html#post2583966
