NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TWEAKS =
TITLE = Quick USB Dashboard
DESCRIPTION = This will skip the 'Charging battery' banner when connected to a computer via USB
CATEGORY = Notifications
VERSIONS = 2.1.0-3 2.2.0-19
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/237350-patch-quick-usb-dashboard.html