NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Hide ATT Navigator
DESCRIPTION = Hides the AT&T Navigator icon from the Launcher
CATEGORY = App Launcher
VERSIONS = 1.4.2-20 1.4.3-14
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Abyssul <Time4swim@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/249129-patch-request-remove-t-navigator-yellowpages.html