NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Youview from Phone
DESCRIPTION = This patch replaces the default voicemail button action in the Phone App by launching the Youview visual voicemail client instead
CATEGORY = Phone
VERSIONS = 1.4.5-151 2.1.0-79 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Inglorious Apps <ingloriousapps@gmail.com>
HOMEPAGE = www.IngloriousApps.com
