NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Show Wifi SSID
DESCRIPTION = Shows the wifi SSID instead of the cellular carrier string.
CATEGORY = Top Bar
VERSIONS = 1.4.5-1 2.0.0-35 2.0.1-62 2.1.0-16
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 2

include ../common.mk

include ../modifications.mk

MAINTAINER = Rod Whitby, zinge
HOMEPAGE =