NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Show Wifi SSID
DESCRIPTION = Shows the wifi SSID instead of the cellular carrier string.
CATEGORY = Top Bar
VERSION = 1.2.1-5
ICON = http://www.webos-internals.org/images/1/1f/Icon_WebOSInternals_Patches_Wifi.png
# SCREENSHOTS = [...]
META_SUB_VERSION = 2
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk

MAINTAINER = Rod Whitby <rod@whitby.id.au>
# HOMEPAGE = http://www.webos-internals.org/wiki/Patch_webOS_...
