#!/bin/sh

APPID=org.webosinternals.optware

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

# Stop the service if running
/sbin/stop ${APPID} || true

# Remove the upstart script
rm -f /etc/event.d/${APPID} /var/palm/event.d/${APPID}

# Remove the profile script
rm -f /etc/profile.d/optware /etc/profile.d/${APPID}

# Create the /media/ext3fs/opt directory if it does not already exist
if [ -e /media/ext3fs ] && [ ! -e /media/ext3fs/opt ] ; then
    /bin/mkdir -p /media/ext3fs/opt || \
	{ echo "ERROR: Cannot create /media/ext3fs/opt directory" ; exit 1 ; }
fi

# Create the /media/cryptofs/optware.ext3 filesystem if it does not already exist
if [ ! -e /media/ext3fs/opt ] && [ ! -e /media/cryptofs/optware.ext3 ] ; then
    /bin/mkdir -p /media/cryptofs || \
	{ echo "ERROR: Cannot create /media/cryptofs directory" ; exit 1 ; }
    echo "Creating 128MB optware filesystem ..."
    /bin/dd if=/dev/zero of=/media/cryptofs/optware.ext3 bs=4096 count=32768 || \
	{ echo "ERROR: Cannot initialise /media/cryptofs/optware.ext3 file" ; exit 1 ; }
    /sbin/mkfs.ext3 -F -L optware /media/cryptofs/optware.ext3 || \
	{ echo "ERROR: Cannot make /media/cryptofs/optware.ext3 filesystem" ; exit 1 ; }
fi

# Migrate legacy /var/opt installation directory to /media/ext3fs/opt
if [ -d /var/opt ] && [ -e /media/ext3fs/opt ] ; then
    /bin/cp -a /var/opt/* /media/ext3fs/opt/ || \
	{ echo "ERROR: Error migrating /var/opt to /media/ext3fs/opt" ; exit 1 ; }
    /bin/rm -rf /var/opt || \
	{ echo "ERROR: Error removing legacy /var/opt" ; exit 1 ; }
fi

# Remove an empty /var/opt directory first
/bin/rmdir /var/opt || true

# Migrate legacy /var/opt installation directory to /media/cryptosfs/optware.ext3
if [ -d /var/opt ] && [ -e /media/cryptofs/optware.ext3 ] ; then
    /bin/umount /opt || true
    /bin/mount /media/cryptofs/optware.ext3 /opt || \
	{ echo "ERROR: Unable to mount /opt for migration" ; exit 1 ; }
    /bin/cp -a /var/opt/* /opt/ || \
	{ echo "ERROR: Error migrating /var/opt to /opt" ; umount /opt ; exit 1 ; }
    /bin/rm -rf /var/opt || \
	{ echo "ERROR: Error removing legacy /var/opt" ; umount /opt ; exit 1 ; }
    /bin/umount /opt ||  \
	{ echo "ERROR: Error unmounting /opt" ; exit 1 ; }
fi

# Install the profile script
mkdir -p /etc/profile.d/
cp ${APPDIR}/profile/${APPID} /etc/profile.d/${APPID}

# Install the upstart script
mkdir -p /var/palm/event.d
cp ${APPDIR}/upstart/${APPID} /var/palm/event.d/${APPID}

# Start ${APPID}
/sbin/start -n ${APPID}

exit 0
