NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TITLE = No Auto-Off While Charging
DESCRIPTION = Adds an option to the Screen & Lock app to enable or disable auto-off while charging
CATEGORY = Screen Lock
VERSIONS = 1.3.1-39 1.3.5-23 1.4.0-12
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/d/d5/Misc-no-auto-off-while-charging-1.png\" ]
META_SUB_VERSION = 

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/217699-patch-no-auto-off-while-charging-3.html#post2166926