NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TWEAKS =
TITLE = No Auto-Off While Charging
DESCRIPTION = Prevents auto-off while charging
CATEGORY = Screen Lock
VERSIONS = 1.4.5-28 2.1.0-3 2.2.0-19 2.2.3-19
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/d/d5/Misc-no-auto-off-while-charging-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/217699-patch-no-auto-off-while-charging-3.html#post2166926