NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Close Slider to End Regular Phone Calls Only
DESCRIPTION = Allows you to end your phone calls by closing the slider on your Pre. Ignores slider when a headset (wired or bluetooth) is connected, or when using speakerphone.
CATEGORY = Phone
VERSIONS = 2.1.0-4 2.1.1-22 2.1.2-31 2.2.0-82 2.2.3-76
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = malpha, KeyToss, Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/209950-phone-slider-patch.html
