NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Show Flash Preferences on Legacy Devices
DESCRIPTION = Shows the flash preferences in the Browser's preferences screen on webOS 2.1.0 on legacy devices  (MIT license)
CATEGORY = Browser
VERSIONS = 2.1.0-18
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille, Leathal
HOMEPAGE =
