NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Make It So - DE
DESCRIPTION = Changes 'Einfach lostippen...' to 'Make it so...' for german Pre3.
CATEGORY = Mojo
VERSIONS = 3.0.5-3
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = DiplPhy <DiplPhy@gmail.com>
HOMEPAGE = http://forums.precentral.net/hp-touchpad-tips-information-resources/295014-replace-just-type-custom-message-6.html#post3176394