NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Battery Icon and Percent
DESCRIPTION = This will add a color-coded percent number with the battery icon in the top bar. Charging = Teal. 100%-70% = Green. 69%-45% = Yellow. = 44%-20% = Orange. 19%-0% = Red.
CATEGORY = Top Bar
VERSION = 1.2.1-0
ICON = http://www.webos-internals.org/images/a/a2/Icon_WebOSInternals_Patches_Percent.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/1/16/Battery-percent-and-icon.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = nesl247, Jason Robitaille <robitaille88@gmail.com>
HOMEPAGE = http://forums.precentral.net/web-os-development/194029-battery-place-icon-working-1-1-0-color.html
