NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Battery Percent and Icon
DESCRIPTION = This will add a color-coded percent number with the battery icon in the top bar.<br/>Charging = Teal.<br/>100%-70% = Green.<br/>69%-45% = Yellow.<br/>44%-20% = Orange.<br/>19%-0% = Red.
CATEGORY = Top Bar
VERSIONS = 1.4.5-1 2.1.0-4
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/e/eb/Top-bar-battery-percent-and-icon-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = nesl247 <0188801@gmail.com>, Jason Robitaille, pcworld
HOMEPAGE = http://forums.precentral.net/web-os-development/194029-battery-place-icon-working-1-1-0-color.html