#!/bin/sh

DISTRO=ubuntu-natty

NAME=${DISTRO}-chroot

APPID=org.webosinternals.${NAME}

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

# Stop the service if running
/sbin/stop ${APPID} || true

# Remove the upstart script
rm -f /var/palm/event.d/${APPID}

# We intentionally do not remove the chroot contents.

exit 0
