NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = Remove Untrusted SSL Certs
DESCRIPTION = This removes untrusted SSL certs from the system. Google for more info.<br/><br/>* DigiNotar
CATEGORY = System
VERSIONS = 2.0.0-65 2.0.1-94 2.1.0-151 3.0.0-38 3.0.2-18
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = webos internals
HOMEPAGE =