NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = Remove Untrusted SSL Certs
DESCRIPTION = This removes untrusted SSL certs from the system. Google for more info.* DigiNotar
CATEGORY = System
VERSIONS = 2.0.0-66 2.0.1-95 2.1.0-154 2.2.0-9 3.0.0-40 3.0.2-20
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = webos internals
HOMEPAGE =