NAME = quiet-powerd-messages
PATCH = /luna/${NAME}.patch
VERSION = 0.1.0
TITLE = Quiet powerd messages patch
DESCRIPTION = ???
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
