NAME = quiet-powerd-messages
PATCH = /luna/${NAME}.patch
TITLE = Quiet powerd messages patch
DESCRIPTION = ???
CATEGORY = Luna
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
