NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = BIG Fonts for Messaging App
DESCRIPTION = <br/><br/>This patch makes the font size in messaging app bigger.
CATEGORY = Messaging
VERSIONS = 2.1.0-180 2.1.1-22 2.1.2-31 2.2.0-48 2.2.3-43 2.2.4-31 3.0.2-44 3.0.4-4 3.0.5-5
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = 
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = 
