NAME = $(shell basename $(shell pwd))
PATCH = music-player/${NAME}.patch
TWEAKS =
TITLE = Default to List View in Stock Music App
DESCRIPTION = Opens to List View as default instead of Album View in Music App.
CATEGORY = Music Player
VERSIONS = 1.4.5-170 2.1.0-162 2.1.1-22 2.1.2-31 2.2.0-23 2.2.3-23
ICON = http://www.webos-internals.org/images/d/df/Icon_WebOSInternals_Patches_Musicplayer.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Djgardn2
HOMEPAGE = http://forums.precentral.net/webos-patches/297593-patch-default-list-view-stock-music-app.html
