NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Bad Kitty Super Mix
DESCRIPTION = Adds Shorten URL, Tweet via Bad Kitty, Add to Relego, Add to Spare Time, and Send via Neato! options in the app menu. Disables auto-refresh in the browser. <br/><br/>Adds shortcut keys for the following:<br/>New Card: Gesture+N;<br/>Add Bookmark: Gesture+M;<br/>Add To Launcher: Gesture+L;<br/>Bookmarks: Gesture+B;<br/>History: Gesture+H;<br/>Share Page: Gesture+S;<br/><br/>Based off patches by benuk, mamouton, and fritos1406.<br/><br/>*Send via Neato! requires Neato! version 0.9.5 or higher
CATEGORY = Browser
VERSIONS = 1.4.5-105
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/d/d2/Browser-bad-kitty-super-mix-1.png\",\
\"http://www.webos-internals.org/images/9/91/Browser-bad-kitty-super-mix-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ThomasCoe <thomascoe1@gmail.com>
HOMEPAGE =
