NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Vibrate to One Second
DESCRIPTION = Extends the current email vibrate function by one second for notifications.
CATEGORY = Email
VERSIONS = 1.3.5-18 1.4.0-26 1.4.1-1
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Abyssul <Time4swim@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2167814#post2167814
