NAME = longer-standby-times
PATCH = /screenlock/longer_standby_times.patch
TITLE = longer standby times patch
DESCRIPTION = ???
CATEGORY = Screen Lock
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
