NAME = longer-standby-times
PATCH = /screenlock/longer_standby_times.patch
VERSION = 0.1.3
TITLE = longer standby times patch
DESCRIPTION = ???
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
