NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = 21px Font
DESCRIPTION = Increase font size in messaging app to 21px for those of us who are visually challenged.
CATEGORY = Messaging
VERSIONS = 1.4.1-5
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = 2sslow <2sslow@gmail.com>
HOMEPAGE =