NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = Add Resend Option
DESCRIPTION = Adds a 'Resend' option to the context menu of a SMS/IM message in chat view. Mimics the 'Resend' option that was available in PalmOS Messaging app.
CATEGORY = Messaging
VERSIONS = 2.1.0-185 2.2.0-53 2.2.3-47
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sara.ramli
HOMEPAGE = http://forums.precentral.net/webos-patches/302696-patch-add-resend-option-messaging-app.html