#!/bin/sh

APPID=mobi.optware.pcre

# Symlink files into /opt
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find lib -type d -exec mkdir -p /opt/{} \;
find lib -type f -exec ln -sf $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt/{} /opt/{} \;
ln -sf libpcre.so.0.0.1 /opt/lib/libpcre.so.0
ln -sf libpcre.so.0.0.1 /opt/lib/libpcre.so
ln -sf libpcrecpp.so.0.0.0 /opt/lib/libpcrecpp.so.0
ln -sf libpcrecpp.so.0.0.0 /opt/lib/libpcrecpp.so
ln -sf libpcreposix.so.0.0.0 /opt/lib/libpcreposix.so.0
ln -sf libpcreposix.so.0.0.0 /opt/lib/libpcreposix.so

exit 0
