NAME = $(shell basename $(shell pwd))
PATCH = camera/$(shell basename ${NAME} -grey).patch
TITLE = Sound Toggle - Grey
DESCRIPTION = This will add a grey button in the Camera application that will allow you to turn the shutter sound On and Off.
CATEGORY = Camera
VERSIONS = 1.2.1-2 1.1.3-2 1.3.1-28 1.3.5-11
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/1/13/Shutter-sound-on-off-button.png\"]
META_SUB_VERSION = 1
include ../common.mk
include ../modifications.mk

MAINTAINER = Hopspitfire, dBsooner 
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Camera_Shutter_Sound_On-Off_Button
