NAME = messaging-timestamps
PATCH = /messaging/${NAME}.patch
VERSION = 0.1.2
TITLE = Messaging Timestamps
DESCRIPTION = Adds timestamps to messages in messaging app
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
