NAME = messaging-timestamps
PATCH = /messaging/${NAME}.patch
TITLE = Messaging Timestamps
DESCRIPTION = Adds timestamps to messages in messaging app
CATEGORY = Messaging
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
