NAME = messaging-timestamps
PATCH = /messaging/${NAME}.patch
VERSION = 0.1.5
TITLE = Messaging Timestamps
DESCRIPTION = Adds timestamps to messages in messaging app
CATEGORY = Messaging
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
