NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = Device Menu Megamix with Airplane Mode
DESCRIPTION = The standard Device Menu Megamix, but with the Airplane Mode toggle retained
CATEGORY = Top Bar
VERSIONS = 2.2.0-105 2.2.3-99 2.2.4-14
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE =