NAME = $(shell basename $(shell pwd))
PATCH = clock/${NAME}.patch
TITLE = Open to Alarm List
DESCRIPTION = This will cause the Clock app to open directly to the alarm list instead of the clock view.
CATEGORY = Clock
VERSIONS = 1.3.1-23 1.3.5-3 1.4.0-3
ICON = http://www.webos-internals.org/images/8/8d/Icon_WebOSInternals_Patches_Clock.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = akamil <akamil@gmail.com>
HOMEPAGE =
