NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Read/Delete All Email
DESCRIPTION = This will give you the ability to mark all messages as read or even delete all messages in the Email application. 
CATEGORY = Email
VERSIONS = 1.4.5-1
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/b/b4/Readalldelall-1.png\",\
\"http://www.webos-internals.org/images/7/7b/Readalldelall-2.png\",\
\"http://www.webos-internals.org/images/d/dd/Readalldelall-3.png\"]
META_SUB_VERSION = 2

include ../common.mk
include ../modifications.mk

MAINTAINER = lclarkjr
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2041573#post2041573
