NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Read/Delete All Email
DESCRIPTION = This will give you the ability to mark all messages as read or even delete all messages in the Email application. 
CATEGORY = Email
VERSION = 1.2.1-2
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/b/b4/Readalldelall-1.png\",\
\"http://www.webos-internals.org/images/7/7b/Readalldelall-2.png\",\
\"http://www.webos-internals.org/images/d/dd/Readalldelall-3.png\"]
META_SUB_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk

MAINTAINER = Lclarkjr
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Email_DeleteAll
