NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Search SMS in Google and Open Link in Browser
DESCRIPTION = Adds a 'Search in Google' option when tapping a message to instantly search your message at google.com. The second option added is 'Open Link in Browser' for when a url isn't click-able. The entire message should be a url for it to work.
CATEGORY = Messaging
VERSIONS = 1.4.5-122
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/9/9b/Messaging-search-sms-in-google-and-open-link-in-browser-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = opacityzero
HOMEPAGE = http://forums.precentral.net/webos-patches/273292-patch-search-sms-google-open-browser.html
