NAME = $(shell basename $(shell pwd))
PATCH = advanced/${NAME}.patch
TITLE = Advanced System Prefs - Calendar Prefs (Veer)
DESCRIPTION = * Requires Advanced System Prefs Framework patch to function properly!<br/><br/>Adds snooze settings and basic additional functionality for calendar app.
CATEGORY = Advanced
VERSIONS = 2.1.0-119
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/9/90/AdvancedSystemPrefsCalendar_1.jpg\",\"http://www.webos-internals.org/images/3/37/AdvancedSystemPrefsCalendar_2.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = http://forums.precentral.net/enlightened-linux-solutions/269550-patch-advanced-system-prefs-2-x.html
