NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Toggle 3G in Device Menu English Only
DESCRIPTION = Displays a submenu in device menu to switch network type between 2G, 3G or Auto. This is the patch for English only devices.
CATEGORY = Top Bar
VERSIONS = 1.4.1-15 1.4.2-1 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = MetaView <metaview@web.de>
HOMEPAGE = http://forums.precentral.net/webos-patches/225494-switch-between-2g-3g-auto-device-menu.html
