NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Streaming Media Download
DESCRIPTION = This patch gives you the option to stream or download streaming media from the web browser.
CATEGORY = Browser
VERSIONS = 2.0.0-27 2.0.1-42
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = pastorrich1
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2810585#post2810585
