NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TWEAKS =
TITLE = Calendar App Bug Fixes
DESCRIPTION = This patch provides bug fixes for the core, un-patched webOS 3.0.5 Calendar application.
CATEGORY = Calendar
VERSIONS = 3.0.5-53
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = iskitz (Mike Lee)
HOMEPAGE = https://github.com/iskitz/webOS/tree/master/calendar