NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Inverted Keyboard Brightness
DESCRIPTION = Inverts the keyboard brightness to be the opposite of the screen brightness with lower limit of 25 and upper limit of 85. 
CATEGORY = Misc
VERSIONS = 1.4.5-87
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = 
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = 
