NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = ImageView Hi-Res Zoom
DESCRIPTION = Lets you more fully zoom into large-size photos in any application that uses the Mojo ImageView widget, like slideshow apps Slide RSS and Slide Master.
CATEGORY = System
VERSIONS = 1.4.5-193 2.1.0-239 2.1.1-45 2.1.2-54 2.2.0-118 2.2.3-112 2.2.4-29 3.0.2-90 3.0.4-58
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = appsotutely <patches@appsotutely.com>
HOMEPAGE = http://forums.webosnation.com/webos-patches/309833-patch-mojo-imageview-hi-res-zoom-see-all-pixels-your-original-photo.html