NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Battery Percent and Icon White
DESCRIPTION = This is the same as the original Battery percent and Icon patch, except the font will be white instead of the multiple colored.<br/><br/>If you use one of my topbar font patches the numbers and % icon will match the font size and color.<br/><br/>This will not affect the Battery colors, your current Battery icons will be unaffected!<br/><br/>Thanks to nesl247 for the original!
CATEGORY = Top Bar
VERSIONS = 1.3.5-3 1.4.0-3 v1.4.1-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/5/50/Top-bar-battery-percent-and-icon-white-1.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = 2sslow
HOMEPAGE =
