NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Mojo Speedy Switch
DESCRIPTION = Eliminates the 500ms delay between entering/leaving an app and the App Menu in the top left changing. Stops apps reopening if you accidentally tap their App Menu after closing.
CATEGORY = Mojo
VERSIONS = 1.4.5-185 2.1.0-219 2.1.1-20 2.1.2-29 2.2.0-89 2.2.3-83
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ShiftyAxel <jpalmerwatkins@me.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/307789-patch-mojo-speedy-switch.html
