NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS = top-bar/${NAME}.json
TITLE = Custom Carrier String
DESCRIPTION = This patch lets you set your own carrier string by using the Tweaks app.
CATEGORY = Top Bar
VERSIONS = 2.1.0-260 2.1.1-65 2.1.2-76 2.2.4-68
ICON = http://www.webos-internals.org/images/f/f1/Icon_WebOSInternals_Patch_Plus.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Choorp Studios <Choorp@gmail.com>
HOMEPAGE = http://forums.webosnation.com/webos-patches/317586-patch-custom-carrier-string.html