NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Device Menu Alternate Mix
DESCRIPTION = This patch is similar to the other device menu patches out there. It undims the date, adds Brightness control, Device Temp, Flashlight and Phone details (data, roam, radio), and Removes VPN.
CATEGORY = Top Bar
VERSIONS = 1.4.5-62 2.0.0-29 2.0.1-51 2.1.0-2 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/7/7b/Top-bar-device-menu-alternate-mix-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille & Warlord9159 & CRaiaSoftware
HOMEPAGE = http://forums.precentral.net/webos-patches/276298-patch-device-menu-alternate-mix.html
