NAME = $(shell basename $(shell pwd))
PATCH = contacts/${NAME}.patch
TWEAKS =
TITLE = Company-Nick divider
DESCRIPTION = If you have a lot of contacts without company info but you want to use 'Company & First Name' or 'Company & Last Name' order. This patch is for you.Instead of a lot of contacts inside 1 single '- NONE ---' divider, you now get '- NONE-A ---', '- NONE-B ---' etc, while A/B/C... is the same as you sort it by 'First Name' or 'Last Name' order
CATEGORY = Contacts
VERSIONS = 2.1.0-210 2.1.1-22 2.1.2-31 2.2.4-4 3.0.2-74 3.0.4-73 3.0.5-37
ICON = http://www.webos-internals.org/images/c/ca/Icon_WebOSInternals_Patches_Contacts.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = moo <moo.tinys@gmail.com>
HOMEPAGE = http://www.treo8.com/bbs/thread-275013-1-1.html