NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Hide VZNav
DESCRIPTION = Hides VZNav icon
CATEGORY = App Launcher
VERSIONS = 1.3.5-24
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1 

include ../common.mk

include ../modifications.mk

MAINTAINER = mhous33 <mhous33@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/229971-patch-request-hide-vz-navigator.html