NAME = more-icons-per-row
PATCH = /luna/more_icons_per_row.patch
TITLE = App Launcher 5x4
DESCRIPTION = This will modify the App launcher to display 5x4 icons rather than 3x4.
CATEGORY = App Launcher
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/b/b0/More-icons-per-row.png\"]
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
