NAME = more-icons-per-row
PATCH = /luna/more_icons_per_row.patch
VERSION = 0.1.4
TITLE = More Icons Per Row
DESCRIPTION = ???
CATEGORY = Luna
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
