NAME = default-to-week-view
PATCH = calendar/${NAME}.patch
VERSION = 0.1.0
TITLE = Week View as default
DESCRIPTION = Set the calendar to default to week view
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
