NAME = default-to-week-view
PATCH = calendar/${NAME}.patch
TITLE = Week View as default
DESCRIPTION = Set the calendar to default to week view
CATEGORY = Calendar
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
