NAME = default-to-week-view
PATCH = calendar/${NAME}.patch
TITLE = Calendar Week View Default
DESCRIPTION = This will set the default view of the Calendar application to Week view.
CATEGORY = Calendar
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
