NAME = msg-avatar
PATCH = /messaging/${NAME}.patch
TITLE = Allow Avatar in Messaging
DESCRIPTION = Allows for avatars to be used in Messaging. For customization, upload your own avatar.png separately.
CATEGORY = Messaging
VERSION = 0.3.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
