NAME = msg-avatar
PATCH = /messaging/${NAME}.patch
TITLE = Add Avatar to Messaging
DESCRIPTION = This will enable your own avatar in the messaging application. To add your own personal avatar, name it my-avatar.png and place it in /usr/palm/applications/com.palm.app.messaging/images/
CATEGORY = Messaging
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/0/00/Msg-avatar.png\"]
META_VERSION = 1

include ../common.mk
include ../modifications.mk
