NAME = $(shell basename $(shell pwd))
PATCH = memos/${NAME}.patch
TWEAKS =
TITLE = More Spacing between Memo Rows
DESCRIPTION = This gives you more space in between each row when on the main viewing page of the Memos app.
CATEGORY = Memos
VERSIONS = 1.4.5-155 2.0.0-48 2.0.1-78 2.1.0-95
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/f/f7/Misc-more-spacing-between-memo-rows-1.png\",\
\"http://www.webos-internals.org/images/e/e1/Misc-more-spacing-between-memo-rows-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Djgardn2
HOMEPAGE =