NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Bigger Progress Bar and Color Options
DESCRIPTION = This Patch makes the Progress Bar a little more than double the size. You also can load different color choices other than default blue. You can Load still or animated progress bar images. Note:You must manually load two images in order for this to take effect. You Must Re-load the images again if you are updating the patch, if you did not have animated version installed. See HomePage Link Below for All Images.
CATEGORY = Browser
VERSIONS = 3.0.5-3
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Djgardn2
HOMEPAGE = http://forums.precentral.net/webos-patches/298774-patch-touchpad-bigger-progress-bar-color-options.html
