NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = qon neH
DESCRIPTION = Replaces 'Just Type...' with the Klingon translation 'qon neH'.
CATEGORY = Mojo
VERSIONS = 2.0.0-36 2.0.1-63 2.1.0-17 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/5/50/Mojo-qon-neh-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = roneyii <naHQun@gmail.com>
HOMEPAGE =
