NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = Battery Percent and Horizontal Icon
DESCRIPTION = Rotates the battery icon and adds percent text above it.
CATEGORY = Top Bar
VERSIONS = 2.1.0-249 2.1.1-54 2.1.2-64 2.2.4-47
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = isagar2004
HOMEPAGE = http://forums.webosnation.com/webos-patches/311455-battery-percent-horizontal-icon.html