NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Lite List Launcher
DESCRIPTION = Lite List Launcher is a new way of visualizing the App Launcher for WebOS. View photos for a better description.<br/><br/>* One important note: this patch alters the app launcher's css file, and will not work with some other launcher patches. you may have to remove them and restart luna before using the Lite List Launcher.<br/><br/>To rearrange, grab the app icon, not the app name.
CATEGORY = App Launcher
VERSIONS = 1.4.1-9
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/1/1c/App-launcher-lite-list-launcher-1.png\",\
\"http://www.webos-internals.org/images/9/9e/App-launcher-lite-list-launcher-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Owen Bickford <owen@thetimelinepost.org>
HOMEPAGE = http://forums.precentral.net/webos-patches/231538-plain-launcher-patch-looking-advice.html