NAME = $(shell basename $(shell pwd))
PATCH = calculator/${NAME}.patch
TITLE = Enable Vibration
DESCRIPTION = Adds haptic (vibration) feedback to screen presses and keyboard input in the Calculator application only.
CATEGORY = Calculator
VERSIONS = 1.3.5-3 1.4.0-20 1.4.1-1 1.4.2-1 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/2/20/Icon_WebOSInternals_Patches_Calculator.png
SCREENSHOTS =
META_SUB_VERSION = 2

include ../common.mk

include ../modifications.mk

MAINTAINER = dallashigh <karl@webosnerd.com>
HOMEPAGE = http://webosnerd.com
