NAME = $(shell basename $(shell pwd))
PATCH = calculator/${NAME}.patch
TITLE = Enable Vibration
DESCRIPTION = Adds haptic (vibration) feedback to screen presses and keyboard input.
CATEGORY = Calculator
VERSION = 1.2.1-13
ICON = http://www.webos-internals.org/images/2/20/Icon_WebOSInternals_Patches_Calculator.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = dallashigh <karl@webosnerd.com>
HOMEPAGE = http://webosnerd.com
