NAME = $(shell basename ${PWD})
PATCH = /messaging/${NAME}.patch
TITLE = Character Counter
DESCRIPTION = This will add a small dot in the top left corner of the text entry field in the Messaging application. It will keep track of how many characters have been entered. When nothing has been entered, the dot will not be visible.
CATEGORY = Messaging
VERSION = 0.5.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/c/c4/Messaging_CharacterCounter.jpg\"]
META_VERSION = 0.5.0
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
