NAME = charcounter
PATCH = /messaging/${NAME}.patch
TITLE = Character Counter
DESCRIPTION = Adds character counter to messaging app
CATEGORY = Messaging
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/c/c4/Messaging_CharacterCounter.jpg\"]
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
