NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TWEAKS =
TITLE = AgendaView as app
DESCRIPTION = * AgendaView as app in launcher<br/>* 14 day forecast<br/>* 'Just Type' support<br/>* black background fixed
CATEGORY = Calendar
VERSIONS = 2.1.0-101 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = MetaView <metaview@web.de>
HOMEPAGE = http://forums.precentral.net/webos-patches/283300-2-1-multiday-agenda-app-calendar-search.html
