NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = More Sync Times
DESCRIPTION = Allows you to sync email at any one-hour increment between 1 and 12. Original sync times are still available as well.
CATEGORY = Email
VERSIONS = 1.3.5-3 1.4.0-3 1.4.1-1 1.4.2-1 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/b/be/Email-more-sync-times-1.png\",\
\"http://www.webos-internals.org/images/6/61/Email-more-sync-times-2.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = dallashigh <karl@webosnerd.com>
HOMEPAGE = http://webosnerd.com
