NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Delete Email from Dashboard
DESCRIPTION = Adds trash icon to new email notification to enable deleting message without launching email app
CATEGORY = Email
VERSIONS = 2.1.0-145 2.1.1-22 2.1.2-31 2.2.0-74 2.2.3-68
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = kbywal (based on patch by ryanjduffy)
HOMEPAGE =
