NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Delete Email from Dashboard
DESCRIPTION = Adds trash icon to new email notification to enable deleting message without launching email app
CATEGORY = Email
VERSIONS = 2.1.0-224 2.1.1-31 2.1.2-39 2.2.0-101 2.2.3-95 2.2.4-9
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = kbywal (based on patch by ryanjduffy)
HOMEPAGE =