NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Fullscreen Mode Browser
DESCRIPTION = When scrolled to the top and Urlbar becomes visible will make it leave fullscreen mode, if scrolled away from the top and urlbar becomes hidden will then re-enable full screen mode
CATEGORY = Browser
VERSIONS = 1.3.5-16 1.4.0-5 1.4.1-1 1.4.2-1 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/6/64/Browser-fullscreen-mode-browser-1.png\",\
\"http://www.webos-internals.org/images/5/50/Browser-fullscreen-mode-browser-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/225374-patch-fullscreen-mode-browser.html
