NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TITLE = Muffle System Logging
DESCRIPTION = By default, webOS tends to log pretty much everything. This patch turns logging down so that it only logs errors or worse.<br/><br/>If you are on ATT, make sure you apply the Quieter PmLog Logging patch first.
CATEGORY = System
VERSIONS = 1.4.5-60
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = WebOS Internals, Canuck Software
HOMEPAGE =
