NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = Muffle System Logging
DESCRIPTION = By default, webOS tends to log pretty much everything. This patch turns logging down so that it only logs errors or worse.
CATEGORY = System
VERSIONS = 1.4.5-60 2.1.0-158 2.1.1-22 2.1.2-31 2.2.0-17 2.2.3-17 3.0.2-23 3.0.4-15
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = WebOS Internals, Canuck Software
HOMEPAGE =
