NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TITLE = Muffle System Logging
DESCRIPTION = By default, webOS tends to log pretty much everything. This patch turns logging down so that it only logs errors or worse.
CATEGORY = System
VERSIONS = 1.4.1-57 1.4.2-43 1.4.3-37 1.4.5-53
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = WebOS Internals
HOMEPAGE =