NAME = phonenoalert
PATCH = /phone/${NAME}.patch
TITLE = phone no alert patch
DESCRIPTION = ???
CATEGORY = Phone
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
