NAME = phonenoalert
PATCH = /phone/${NAME}.patch
VERSION = 0.1.0
TITLE = phone no alert patch
DESCRIPTION = ???
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
