NAME = $(shell basename $(shell pwd))
PATCH = universal-search/${NAME}.patch
TITLE = Hide Twitter Global Search
DESCRIPTION = This patch will hide the Twitter option from Global Search ( as per request ).
CATEGORY = Universal Search
VERSIONS = 1.4.0-32 1.4.1-1 1.4.2-1 1.4.5-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/8/83/Universal-search-hide-twitter-global-search-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = v3ritas <spm7654@optonline.net>
HOMEPAGE = http://forums.precentral.net/webos-patches/237852-patch-request-remove-twitter-synergy.html#post2326184
