NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = webOS Scrollbars
DESCRIPTION = Adds system-wide scrollbars to Mojo and Mojo2 apps on webOS for phones. Note that this patch is still in testing, so hope for the best but expect the worst. For some reason this does not work in the following Mojo2 apps: Accounts, Contacts, Email, Exhibition and Photos. This patch won't conflict with any other scrollbars patch you have installed.
CATEGORY = System
VERSIONS = 2.2.4-47
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Isaac Garzon (isagar2004)
HOMEPAGE = http://forums.webosnation.com/webos-patches/311755-patch-project-webos-scrollbars.html