NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = webOS Scrollbars
DESCRIPTION = Adds system-wide scrollbars to Mojo (and Mojo 2 in webOS 2.0+) apps on webOS for phones. Note that this patch is still in testing, so hope for the best but expect the worst. This patch won't conflict with any other scrollbars patch you have installed.
CATEGORY = System
VERSIONS = 1.4.5-208 2.1.0-272 2.1.2-110 2.2.4-58
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Isaac Garzon (isagar2004)
HOMEPAGE = http://forums.webosnation.com/webos-patches/311755-patch-project-webos-scrollbars.html