NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Animated Backgrounds
DESCRIPTION = Animated Back Grounds for WebOS!!!<br/>Messaging, Phone and Music player animated back grounds<br/><br/>Without over-clocking, your experience would be<br/>sluggish with the stock Kernel in place.<br/>WebOS Internals Uber-Kernel @ 800Mhz should run this just fine.<br/><br/>name your animated gif image (image size 320x480) to<br/><br/>animatedbg<br/><br/>put your animated gif in the wallpapers folder in pre internal memory.<br/>install patch.<br/><br/>You can find some animated gif's to get you started at Patch Homepage below.<br/>http://forums.precentral.net/2560231-post1.html
CATEGORY = Misc
VERSIONS = 1.4.1-39 1.4.2-24 1.4.3-18 1.4.5-23
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Warlord9159
HOMEPAGE = http://forums.precentral.net/2560231-post1.html