NAME = $(shell basename $(shell pwd))
PATCH = video-player/${NAME}.patch
TWEAKS =
TITLE = No video pause on minimize
DESCRIPTION = This patch allows video content to continue playing when the screen is minimized, dimmed or off.
CATEGORY = Video Player
VERSIONS = 3.0.0-31 3.0.2-3
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Videoplayer.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = peterlemonjello
HOMEPAGE =