NAME = camera-simple-shutter-sound-off
PATCH = camera/camera-simple-shutter-sound-off.patch
TITLE = Simple Shutter Sound Off
DESCRIPTION = This will permanently disable the shutter sound for the camera.
CATEGORY = Camera
VERSION = 1.2.1-8
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = jhoff80
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Camera_Easy_Shutter_Sound_Off
