NAME = $(shell basename $(shell pwd))
PATCH = camera/${NAME}.patch
TITLE = Simple Shutter Sound Off
DESCRIPTION = This will disable the shutter sound for the camera while it's actively being used.
CATEGORY = Camera
VERSIONS = 1.4.5-1
ICON = http://www.webos-internals.org/images/c/c5/Icon_WebOSInternals_Patches_Camera.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid, jhoff80
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2382133#post2382133
