NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Tweet URL and Title via Spaz
DESCRIPTION = This patch adds a 'Tweet Link' option to the Browser Menu under Page it will launch Spaz and compose a tweet containing the page title and URL.<br/><br/>Please note this patch is not currently compatible with the Send to Relego and Add to Spare Time patches. Please uninstall first<br/><br/>Thanks to the authors of the Add to Relego and Add to Spare Time patches for the inspiration for this patch and @funkatron the Spaz dev for creating a cross app API to plug into.<br/><br/>You need to be running Spaz version v1.5.2 or later for this to work which is currentley in the Palm beta feeds
CATEGORY = Browser
VERSIONS = 1.4.5-79
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/c/ca/Browser-tweet-url-and-title-via-spaz-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Ben Fysh
HOMEPAGE = http://forums.precentral.net/webos-patches/264956-patch-tweet-link-via-spaz-spare-time-relego-support.html
