NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TITLE = Device Profile Service Override
DESCRIPTION = Allows the Impostah application to override the values returned by the com.palm.deviceprofile service.
CATEGORY = System
VERSIONS = 3.0.5-3
ICON = http://www.webos-internals.org/images/a/aa/Tux_Imposter.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = WebOS Internals
HOMEPAGE =
