NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TWEAKS =
TITLE = Messaging Privacy for Pre3
DESCRIPTION = Sometimes your phone is laying around where others are passing by and you don't want them to see your text messages. Well, this patch will prevent casual looking at your private texts. It does this hiding the message on the Notification and Dashboard (including lock screen). It displays the phrase 'New Message' where the message used to appear under the sender.
CATEGORY = Messaging
VERSIONS = 2.2.4-57
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sara.ramli dallashigh peterlemonjello
HOMEPAGE = http://forums.webosnation.com/webos-patches/228141-patch-text-message-privacy-4.html#post3207808