NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = SMS Vibrate to One Second
DESCRIPTION = Extends the vibrate time to a second whenever you alerted for a SMS message.
CATEGORY = Messaging
VERSIONS = 1.3.1-31 1.3.5-14 1.4.0-3
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Abyssul <Time4swim@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2164165#post2164165