NAME = messaging-enter-newline
PATCH = /messaging/${NAME}.patch
VERSION = 0.1.2
TITLE = Messaging Enter Newline
DESCRIPTION = Inserts newline rather than submit when enter key is hit in messaging app
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
