NAME = messaging-enter-newline
PATCH = /messaging/${NAME}.patch
TITLE = Messaging Newline on Enter
DESCRIPTION = This will cause the enter button to insert a newline instead of sending the message in the Messaging application.
CATEGORY = Messaging
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
