NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = Fahrenheit Temperature with Battery in Device
DESCRIPTION = Will add a temperature value, in Fahrenheit, on the right side of the battery row of the device menu.
CATEGORY = Top Bar
VERSIONS = 2.1.0-3 2.2.0-19 2.2.3-19
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/238526-patch-fahrenheit-temperature-battery-device-menu.html