NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Remove Tap Locator
DESCRIPTION = Removes the tap locator (Reticle) when you touch your screen.
CATEGORY = Mojo
VERSIONS = 1.4.1-7
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Atlanta <apps@boaproso.com>
HOMEPAGE =