NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Remove Tap Locator
DESCRIPTION = Removes the tap locator (Reticle) when you touch your screen. (The ripple-effect that occurs when you touch your screen.)
CATEGORY = Mojo
VERSIONS = 1.4.5-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Atlanta
HOMEPAGE = http://forums.precentral.net/webos-patches/242378-patch-remove-tap-locator-reticle.html
