NAME = $(shell basename $(shell pwd))
PATCH = video-player/${NAME}.patch
TWEAKS =
TITLE = Improved Edited Video Filenames
DESCRIPTION = Will output edited videos in the format [filename]_[date/time].mp4.mp4
CATEGORY = Video Player
VERSIONS = 1.4.5-31 2.1.0-3 2.1.1-22 2.1.2-31 2.2.0-21 2.2.3-21 2.2.4-14
ICON = http://www.webos-internals.org/images/f/ff/Icon_WebOSInternals_Patches_Videoplayer.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/235046-patch-improved-edited-video-filenames.html