NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = Devicemenu Maxed Out Ultra
DESCRIPTION = Date and battery level Bright plus temperature value, adds screen brightness control, system & media volume control, <br/>adds phone submenu(radio data roaming)toggles, adds GPS toggle, Keeps airplane mode toggle, adds a flashlight led toggle
CATEGORY = Top Bar
VERSIONS = 1.4.5-67 2.0.0-62 2.0.1-91 2.1.0-141
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Warlord9159, mau
HOMEPAGE = http://forums.precentral.net/webos-patches/262052-patch-devicemenu-maxed-out.html