NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = Date and Lower-case AM-PM Indicator
DESCRIPTION = This is a lower case version of the 'Date with AM-PM Indicator' patch.Adds the date (without year) to the left of the time display as well as a lower case AM/PM indicator. If the time is in 24 hours format, there will just be the date without the AM/PM indicator.Date can be in DD/MM or MM/DD format, based on regional settings.
CATEGORY = Top Bar
VERSIONS = 2.1.0-233 2.1.1-39 2.1.2-48 2.2.0-112 2.2.3-106 2.2.4-22
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = isagar2004
HOMEPAGE =