NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TWEAKS =
TITLE = Bypass PIN
DESCRIPTION = This will allow you to bypass the PIN entry to unlock your device.
CATEGORY = Screen Lock
VERSIONS = 2.1.0-15 2.1.1-22 2.1.2-31 2.2.0-109 2.2.3-103 2.2.4-19 3.0.2-87 3.0.4-53
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = lingfish
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_WebOS_Bypassing_Lock_Screen