NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TITLE = BypassPINLock
DESCRIPTION = This will allow you to bypass the PIN entry to unlock your device.
CATEGORY = Screen Lock
VERSIONS = 1.2.1-26 1.3.1-11 1.3.5-2 1.4.0-2
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = dBsooner <webos@dbsooner.com>
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_WebOS_Bypassing_Lock_Screen
