NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Increase Minimum Font Size 16
DESCRIPTION = If you're like me, you may find the miniscule text size when viewing websites on the Pre 3 in portrait orientation to be an extreme annoyance.This patch slightly increases the minimum font size within the browser from 12 to 16. It's not a cure all but it helps. On some websites it may slightly break the layout, but it's minimal. Give it a try and see how it works for you. Visit the forum link for more information.
CATEGORY = Browser
VERSIONS = 2.2.0-78 2.2.3-72
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = nightburn
HOMEPAGE = http://forums.precentral.net/webos-patches/306527-patch-increase-browser-minimum-font-size-16-pre3.html