NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = No Multi Message Header
DESCRIPTION = Removes the (x of y) header Message in Messaging App.
CATEGORY = Messaging
VERSIONS = 1.3.5-24 1.4.0-13
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/d/d5/Messaging-no-multi-message-header-1.png\" ]
META_SUB_VERSION = 

include ../common.mk

include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE =