NAME = $(shell basename $(shell pwd))
PATCH = advanced/${NAME}.patch
TITLE = Advanced System Prefs - Phone Prefs
DESCRIPTION = * Requires Advanced System Prefs Framework patch to function properly!<br/><br/>Adds additional preferences for phone app. Also adds support for notification settings for phone calls received from unknown contacts and per contact notification configuration.
CATEGORY = Advanced
VERSIONS = 2.1.0-91 2.2.0-25
ICON = http://www.webos-internals.org/images/1/1b/Icon_WebOSInternals_Patches_Plus_Phone.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/8/8d/AdvancedSystemPrefsPhone_1.jpg\",\"http://www.webos-internals.org/images/8/80/AdvancedSystemPrefsPhone_2.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = http://forums.precentral.net/enlightened-linux-solutions/269550-patch-advanced-system-prefs-2-x.html
