NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Pixel Perfect Multipart Menus
DESCRIPTION = There's a one pixel issue on the Pre 3 where the segmented buttons that you see at the bottom of many Mojo apps are not aligned right: the leftmost button leaves a one pixel gap to the right of itself.This fixes that issue.
CATEGORY = Mojo
VERSIONS = 2.2.0-38 2.2.3-38
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Grant Paul (chpwn) <support@chpwn.com>
HOMEPAGE =
