#!/bin/sh

PACKAGE=org.webosinternals.emergency-service-enabler

for i in `ls $IPKG_OFFLINE_ROOT/usr/lib/ipkg/info/*.postinst | grep -v $PACKAGE`
do
  echo "Enabling `basename $i`"
  /bin/sh $i
done

echo "DONE"

ipkg -o $IPKG_OFFLINE_ROOT remove $PACKAGE
