#!/bin/sh

PACKAGE=org.webosinternals.emergency-service-enabler

FIRSTS="\
$IPKG_OFFLINE_ROOT/usr/lib/ipkg/info/org.webosinternals.optware.postinst \
$IPKG_OFFLINE_ROOT/usr/lib/ipkg/info/org.webosinternals.widk.postinst \
$IPKG_OFFLINE_ROOT/usr/lib/ipkg/info/org.webosinternals.patch.postinst \
$IPKG_OFFLINE_ROOT/usr/lib/ipkg/info/org.webosinternals.lsdiff.postinst \
"

for i in $FIRSTS `ls $IPKG_OFFLINE_ROOT/usr/lib/ipkg/info/*.postinst | grep -v $PACKAGE`
do
  if [ -e $i ] ; then
    echo "Enabling `basename $i`"
    /bin/sh $i
  fi
done

echo "DONE"

ipkg -o $IPKG_OFFLINE_ROOT remove $PACKAGE
