NAME = enable-led-notifications
PATCH = /screenlock/${NAME}.patch
TITLE = Enables LED Notifications
DESCRIPTION = Enable the LED behind the gesture button to light up when notifications are received
CATEGORY = Screen Lock
VERSION = 0.2.4
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS = [\"http://www.precentral.net/sites/precentral.net/files/articleimages/Dieter%20Bohn/2009/09/palm-pre-blink-notifications.png\"]

include ../common.mk
include ../modifications.mk
