NAME = enable-led-notifications
PATCH = /screenlock/${NAME}.patch
TITLE = Enables LED Notifications
DESCRIPTION = Enable the LED behind the gesture button to light up when notifications are received
CATEGORY = Screen Lock
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png

include ../common.mk
include ../modifications.mk
