NAME = enable-led-notifications
PATCH = /screenlock/${NAME}.patch
TITLE = Enable LED Notifications
DESCRIPTION = This will uncomment the code necessary for the gesture area to light up for notifications. You must still make sure LED Notifications is enabled in the Screen & Lock application.
CATEGORY = Screen Lock
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/8/86/Enable-led-notifications.png\"]
META_VERSION = 1

include ../common.mk
include ../modifications.mk
