NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TWEAKS =
TITLE = Reset Options on Power Button Hold
DESCRIPTION = On power button hold, it goes straight to the reset options, with airplaine mode added, and skips the swap-battery/shutdown prompt.
CATEGORY = Notifications
VERSIONS = 2.1.0-3 2.1.1-22 2.1.2-31 2.2.0-19 2.2.3-19
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/220366-patch-reset-options-power-button-hold.html
