NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TITLE = Reset Options on Power Button Hold
DESCRIPTION = On power button hold, it goes straight to the reset options, with airplaine mode added, and skips the swap-battery/shutdown prompt.
CATEGORY = Notifications
VERSIONS = 1.4.5-1 2.0.1-45 2.1.0-3
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/220366-patch-reset-options-power-button-hold.html