NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TITLE = Vibrate to Two Seconds
DESCRIPTION = Extends the current email vibrate function by two seconds for notifications.
CATEGORY = Email
VERSIONS = 1.3.1-34 1.3.5-17 1.4.0-6
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Abyssul <Time4swim@gmail.com>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2167814#post2167814
