NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Hide Quick Launch Bar
DESCRIPTION = Hides the quick launch bar (while still alowing the quick launch wave)
CATEGORY = App Launcher
VERSIONS = 1.3.1-13 1.3.5-1 1.4.0-1
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/214847-patch-hide-quick-launch-bar.html#post2038251
