NAME = new-task-details
PATCH = /tasks/${NAME}.patch
TITLE = new task details pach
DESCRIPTION = ???
CATEGORY = Tasks
VERSION = 0.1.16
ICON = http://www.webos-internals.org/images/8/83/Icon_WebOSInternals_Patches_Tasks.png
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
