NAME = new-task-details
PATCH = /tasks/${NAME}.patch
VERSION = 0.1.3
TITLE = new task details pach
DESCRIPTION = ???
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
