NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = Force Send Offline
DESCRIPTION = This will enable the force sending while offline in the Messaging application.
CATEGORY = Messaging
VERSIONS = 1.2.1-0 1.3.1-0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = 
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = fritos1406
