NAME = clean-timestamp
PATCH = /messaging/${NAME}.patch
TITLE = Clean Messaging Timestamp
DESCRIPTION = Add clean timestamps to messaging app
CATEGORY = Messaging
VERSION = 0.2.1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
