NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TITLE = Just Charge By Default
DESCRIPTION = On plugging in your device, it will automatically go into 'Just Charge' with notification at bottom if you want to change to a different mode.
CATEGORY = Notifications
VERSIONS = 2.0.0-29 2.0.1-51 2.1.0-2
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = dBsooner, Jason Robitaille, EdCates
HOMEPAGE = http://forums.precentral.net/webos-patches/212483-patch-request-media-sync-just-charge-usb-drive-minimized-default.html