NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TWEAKS =
TITLE = Just Charge By Default
DESCRIPTION = On plugging in your device, it will automatically go into 'Just Charge' mode with notification dashboard if you want to change to USB Mode.
CATEGORY = Notifications
VERSIONS = 2.1.0-3 2.2.0-19 2.2.3-19 3.0.2-3
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/288398-patch-touchpad-just-charge-default.html