NAME = $(shell basename $(shell pwd))
PATCH = clock/${NAME}.patch
TWEAKS =
TITLE = Alarm Daily Options
DESCRIPTION = This patch will add Sunday, Monday, Tuesday, Wednesday, etc. to the 'occurs' dropdown list. The alarm will ring on that day every week at the time you specify.
CATEGORY = Clock
VERSIONS = 2.0.0-62 2.0.1-91 2.1.0-141
ICON = http://www.webos-internals.org/images/8/8d/Icon_WebOSInternals_Patches_Clock.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/e/e1/Clock-alarm-daily-options-1.png\",\
\"http://www.webos-internals.org/images/2/23/Clock-alarm-daily-options-2.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = romanodog, mau
HOMEPAGE = http://forums.precentral.net/webos-patches/215970-patch-alarm-daily-options.html