NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Turn the dialpad tones off and vibrate
DESCRIPTION = When dialing a phone number, the dialpad tones are off and phone vibrates after pressing each digit.
CATEGORY = Phone
VERSIONS = 2.1.0-13 2.1.1-22 2.1.2-31 2.2.0-52
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = brennan7, sara.ramli
HOMEPAGE = http://forums.precentral.net/webos-patches/302377-patch-turnoff-phone-dialpad-tones.html
