NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Turn the dialpad tones off and vibrate
DESCRIPTION = When dialing a phone number, the dialpad tones are off and phone vibrates after pressing each digit.
CATEGORY = Phone
VERSIONS = 2.0.1-49
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = kbywal
HOMEPAGE =