NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Veer SIM RemoveButton fix
DESCRIPTION = This patch hides the following text from SIM account scene to allow access to the 'Remove account' button on HP Veer.'The data is still in your phone, but can't be edited. You can edit data and add new contacts after you re-insert the SIM.'
CATEGORY = Phone
VERSIONS = 2.1.1-58
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = MetaView <metaview@web.de>
HOMEPAGE =