NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Change Number of Bookmarks on Startpage
DESCRIPTION = Change the number of bookmarks that your browser start page shows - the browser is set to show the first 12 bookmarks in your list.  This patch changes the total number of bookmarks shown to 100.
CATEGORY = Browser
VERSIONS = 1.3.5-3 1.4.0-3 1.4.1-1 1.4.2-1 1.4.3-1 1.4.5-1
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = jmartino2011 <jmartino2011@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/215949-patch-change-number-bookmarks-browser.html
