NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Add Date as MM period DD
DESCRIPTION = Adds the date to the left of the time in the top bar in MM.DD format when your date format uses a '/' for the delimiter.<br/><br/>(Original work by dirtygeek & tk102)
CATEGORY = Top Bar
VERSIONS = 1.4.0-34 1.4.1-3 1.4.2-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/0/0e/Top-bar-add-date-as-mm-period-dd-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = xanthinealkaloid <hardfam1@gmail.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/236204-patch-add-date-mm-dd.html#post2303342
