NAME = $(shell basename $(shell pwd))
PATCH = contacts/${NAME}.patch
TWEAKS =
TITLE = Search Contacts in PinYin
DESCRIPTION = You can now search contacts in PinYin initial of each Chinese character. non-chinese is not affected and still searchable as it used to be.PinYin framework patch is required for this patch to work.
CATEGORY = Contacts
VERSIONS = 2.1.0-211 2.2.0-84 2.2.3-78 3.0.2-75 3.0.4-38
ICON = http://www.webos-internals.org/images/c/ca/Icon_WebOSInternals_Patches_Contacts.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = moo <moo.tinys@gmail.com>
HOMEPAGE =