NAME = $(shell basename $(shell pwd))
PATCH = contacts/${NAME}.patch
TWEAKS =
TITLE = Search Contacts in PinYin
DESCRIPTION = You can now search contacts in PinYin initial of each Chinese character. non-chinese is not affected and still searchable as it used to be. PinYin framework patch is required for this patch to work.You have to restart your device after installation and then open Accounts, disable your account contacts data, gesture back. Open Accounts again and enable your account contacts data. (Just let it re-sync your contacts)
CATEGORY = Contacts
VERSIONS = 2.1.0-213 2.1.1-22 2.1.2-31 2.2.0-88 2.2.3-82 3.0.2-79 3.0.4-43
ICON = http://www.webos-internals.org/images/c/ca/Icon_WebOSInternals_Patches_Contacts.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = moo <moo.tinys@gmail.com>
HOMEPAGE = http://www.treo8.com/bbs/thread-275013-1-1.html
