NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Simple Browser Gestures Inverted
DESCRIPTION = This patch is the inverted version of Garret92C's Simple Browser Gestures patch. This patch adds two new 'gestures' to the stock Browser app. Swipe your finger from the left bezel to go back. Swipe from the right to go forward.
CATEGORY = Browser
VERSIONS = 3.0.2-30
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Garret92C <nightburn@gmail.com>, nightburn
HOMEPAGE = http://forums.precentral.net/webos-patches/300156-patch-add-browser-back-forward-gesture.html