NAME = $(shell basename $(shell pwd))
PATCH = music-player/${NAME}.patch
TWEAKS =
TITLE = Default to Play Shuffle All when Opened
DESCRIPTION = When you first open the music app it will default to Playing the 'Shuffle All' from main menu. When the Music app is opened it will immediately start playing music.
CATEGORY = Music Player
VERSIONS = 1.4.5-171
ICON = http://www.webos-internals.org/images/d/df/Icon_WebOSInternals_Patches_Musicplayer.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Djgardn2
HOMEPAGE = http://forums.precentral.net/webos-patches/298407-patch-default-play-shuffle-all-when-first-opened-stock-music-app.html