NAME = more-icons-per-row-5x4-flare576
PATCH = /luna/more-icons-per-row-5x4-flare576.patch
TITLE = App Launcher 5x4 - Ver 2
DESCRIPTION = This will modify the App launcher to display 5x4 icons rather than 3x4. This is an alternate version made by flare576. It has different spacing and properly word wraps.
CATEGORY = App Launcher
VERSION = 0.4.5
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/9/93/5x4-icons.png\"]
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
