#!/bin/sh

APPID=mobi.optware.pwgen

# Symlink files into /opt
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find bin -type d -exec mkdir -p /opt/{} \;
find bin -type f -exec ln -sf $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt/{} /opt/{} \;

exit 0
