#!/bin/sh

APPID=mobi.optware.pwgen

# Remove files from /opt
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find bin -depth -type f -exec rm -f /opt/{} \;
find bin -depth -type d -exec rmdir /opt/{} \;

exit 0
