NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TITLE = Quieter PmLog Logging
DESCRIPTION = This patch is currently intended only for AT&T Pre and Pixis.<br/><br/>It turns out that the PmLog.conf file for AT&T phones for some reason log a lot more information. This patch brings it in line with phones from other carriers.
CATEGORY = System
VERSIONS = 1.4.2-48 1.4.3-43
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = WebOS Internals
HOMEPAGE =