NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = Fixed Keyboard Brightness 80
DESCRIPTION = Keeps the keyboard brightness in fixed value of 80. 
CATEGORY = Misc
VERSIONS = 1.4.5-87
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = 
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = sconix
HOMEPAGE = 
