NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Brightness in Device Menu - DE
DESCRIPTION = *DE only*<br/>Adds screen brightness control to the device menu.<br/><br/>(Translation of the orignal patch by Jason  Robitaille)
CATEGORY = Top Bar
VERSIONS = 2.0.0-31 2.0.1-53 2.1.0-5 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/d/df/Top-bar-brightness-in-device-menu---de-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = michote <reischuck.micha@googlemail.com>
HOMEPAGE =
