NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = No Autodial from Call Log
DESCRIPTION = Tapping any phone number in the call log simply inserts the number into the dialpad rather than automatically dialing the number. Originally, patch was created by xanthinealkaloid
CATEGORY = Phone
VERSIONS = 1.4.5-211 2.1.0-33 2.1.1-22 2.1.2-31 2.2.4-39
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = chalx
HOMEPAGE =