NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = No Autodial from Call Log
DESCRIPTION = Tapping any phone number in the call log simply inserts the number into the dialpad rather than automatically dialing the number.
CATEGORY = Phone
VERSIONS = 2.1.0-33 2.1.1-22 2.1.2-31 2.2.4-39
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Herrie <webos-internals.org@herrie.org>
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2402622#post2402622