NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TWEAKS =
TITLE = Remove-Reduce Launcher Bar
DESCRIPTION = Reduces the Launcher Bar to 1px at bottom of screen.
CATEGORY = App Launcher
VERSIONS = 3.0.2-62 3.0.4-23
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = pgregg <webos-patch@pgregg.com>
HOMEPAGE =