NAME = $(shell basename $(shell pwd))
PATCH = youtube/${NAME}.patch
TWEAKS =
TITLE = Upload to Youtube as Unlisted
DESCRIPTION = Upload all videos to Youtube as Unlisted.Reboot after applying.
CATEGORY = YouTube
VERSIONS = 2.1.0-228 2.1.1-35 2.1.2-43 2.2.0-106 2.2.3-100 2.2.4-16
ICON = http://www.webos-internals.org/images/8/8b/Icon_WebOSInternals_Patches_Youtube.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GuyFromNam <GuyFromNam@hotmail.com>
HOMEPAGE =