NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Georgian Layout for hardware keyboard
DESCRIPTION = Adds georgian-translit keyboard layout for the hardware keyboard. Double SYM to change ENGLISH/GEORGIAN layouts.
CATEGORY = Mojo
VERSIONS = 2.1.0-107
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = David Iverieli
HOMEPAGE =