NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = 15px Font
DESCRIPTION = Decreases the font size in the Messaging app to 15px. If you have the Left Avatar patch it would only decrease their font size and not yours (will not work with the iPhone Style patch).
CATEGORY = Messaging
VERSIONS = 2.0.0-42 2.0.1-70 2.1.0-39 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/e/e4/Messaging-15px-font-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = fritos1406 <dse@webonastick.com>, dsevil
HOMEPAGE = http://forums.precentral.net/webos-patches/216337-patch-smaller-font-size-messaging-app.html
