NAME = $(shell basename $(shell pwd))
PATCH = messaging/${NAME}.patch
TITLE = 15px Font
DESCRIPTION = Decreases the font size in the messaging app to 15px. If u have the left avatar patch it would only decrease their font size and not yours (wont work with the iphone style patch).
CATEGORY = Messaging
VERSIONS = 1.3.5-3 1.4.0-3
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/e/e4/Messaging-15px-font-1.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = fritos1406 <fritos1406@aim.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/216337-patch-smaller-font-size-messaging-app.html
