NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = D-Bus Access
DESCRIPTION = Allows all users to connect to D-Bus. Useful for 3rd party linux apps that rely on D-Bus to work properly.
CATEGORY = System
VERSIONS = 1.4.5-185
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Will Rea <will.rea@gmail.com>
HOMEPAGE =
