NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TWEAKS =
TITLE = No Launcher Button
DESCRIPTION = Removes launcher button from launcher bar. Allows launcher bar to hold 8 icons in landscape view.Note on removal: when uninstalling this patch remove excess icons first or you will have to remove an excess icon then do another luna restart to get launcher bar back to normal.
CATEGORY = App Launcher
VERSIONS = 3.0.2-55 3.0.4-9
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = kyle3om <kyle3om@yahoo.com>
HOMEPAGE = http://forums.precentral.net/hp-touchpad-homebrew/302053-patch-remove-launcher-button-icon.html#post3189484