NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = Hold Tap Context Menu
DESCRIPTION = Hold tap on a link or picture to pull up the context menu
CATEGORY = Browser
VERSIONS = 1.4.5-96
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = n1ce
HOMEPAGE = http://forums.precentral.net/webos-patches/265128-patch-browser-hold-tap-context-menu.html