NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = No Autolaunch Keyboard in Browser
DESCRIPTION = Makes the browser not put focus on the address bar when opening the browser, keeping the keyboard closed so that the bookmark list is more visible. This patch works well in conjunction with the 'Default to Show Bookmarks in Browser' patch.
CATEGORY = Browser
VERSIONS = 3.0.2-71 3.0.4-34
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = kyle3om <kyle3om@yahoo.com>
HOMEPAGE = http://forums.precentral.net/hp-touchpad-homebrew/306368-patch-no-keyboard-autolaunch-broswer-support-thread.html#post3238543