NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Enable GPS Dial Action on GSM
DESCRIPTION = This patch enables the \#*GPS\# dial action for GSM devices.
CATEGORY = Phone
VERSIONS = 1.3.1-27 1.3.5-11 1.4.0-4
ICON = http://www.webos-internals.org/images/c/c8/Icon_WebOSInternals_Patches_Phonepreferences.png
SCREENSHOTS = 
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Rod Whitby <rod@whitby.id.au>, dBsooner 
HOMEPAGE = 
