NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TITLE = BetterOfflineBrowser
DESCRIPTION = The browser will not tell you about the phone being offline, instead the URL is copied to the address bar, means you can just refresh after reconnecting.
CATEGORY = Browser
VERSIONS = 1.4.5-132
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = MetaView <metaview@web.de>
HOMEPAGE =
