NAME = $(shell basename $(shell pwd))
PATCH = calendar/${NAME}.patch
TITLE = More Reminder Alarm Times
DESCRIPTION = Adds 45, 90, and 120 minutes to reminder alarm time choices.
CATEGORY = Calendar
VERSIONS = 1.3.5-3 1.4.0-28 v1.4.1-1
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/e/e2/Calendar-more-reminder-alarm-times-1.jpg\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = dBsooner, wtgreen
HOMEPAGE =
