NAME = calendar-more-reminder-alarm-times
PATCH = calendar/calendar-more-reminder-alarm-times.patch
TITLE = More Reminder Alarm Times
DESCRIPTION = Adds 45, 90, amd 120 minutes to reminder alarm time choices.
CATEGORY = Calendar
VERSION = 1.2.1-7
ICON = http://www.webos-internals.org/images/d/d4/Icon_WebOSInternals_Patches_Calendar.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/e/e2/Calendar-more-reminder-alarm-times-1.jpg\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = wtgreen
HOMEPAGE =
