NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TWEAKS =
TITLE = Enable Dialpad Vibration with Audio
DESCRIPTION = Enables Heptic Feedback for the Dialpad while maintaining audible functionality.
CATEGORY = Phone
VERSIONS = 2.2.4-43
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = aramova, sara.ramli, Herrie
HOMEPAGE = http://forums.precentral.net/webos-patches/302377-patch-turnoff-phone-dialpad-tones.html