NAME = $(shell basename $(shell pwd))
PATCH = phone/${NAME}.patch
TITLE = Enable Dialpad Vibration with Audio
DESCRIPTION = Enables Heptic Feedback for the Dialpad while maintaining audible functionality.
CATEGORY = Phone
VERSIONS = 1.4.1-7
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = aramova <aramova@gmail.com>
HOMEPAGE =