NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = NoAds patch GERMAN
DESCRIPTION = This patch will block ads on the most popular german mobile sites like m.spiegel.de m.focus.de kicker.mobi heise.mobi and so on.
CATEGORY = Browser
VERSIONS = 2.1.0-182
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = michel
HOMEPAGE =