NAME = $(shell basename $(shell pwd))
PATCH = screen-lock/${NAME}.patch
TWEAKS =
TITLE = Lower Minimum Brightness
DESCRIPTION = This allows you to dim the screen brightness even further using the usual slider in the Screen & Lock preferences.
CATEGORY = Screen Lock
VERSIONS = 2.2.0-19
ICON = http://www.webos-internals.org/images/f/fa/Icon_WebOSInternals_Patches_Screenlock.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = errade
HOMEPAGE =