NAME = $(shell basename $(shell pwd))
PATCH = misc/${NAME}.patch
TITLE = No Auto-Off While Charging
DESCRIPTION = Prevents the screen from turning off while the device is charging.
CATEGORY = Misc
VERSIONS = 1.3.1-25 1.3.5-6 1.4.0-1
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = Sakasune, Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/217699-patch-no-auto-off-while-charging.html

