NAME = $(shell basename $(shell pwd))
PATCH = /messaging/${NAME}.patch
TITLE = Enable Forwarding
DESCRIPTION = This will add the ability to forward messages in the Messaging application. Touch a message to use this feature.
CATEGORY = Messaging
VERSION = 1.2.1-0
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/5/5c/Message-forwarding-1.png\",\
\"http://www.webos-internals.org/images/9/97/Message-forwarding-2.png\"]
META_VERSION = 1
#POSTINSTALLFLAGS = RestartLuna
#POSTREMOVEFLAGS = RestartLuna

include ../common.mk
include ../modifications.mk
