NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Make It So - DE
DESCRIPTION = Changes 'Einfach lostippen...' to 'Make it so...' for german Pre3.
CATEGORY = Mojo
VERSIONS = 2.2.0-38
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = DiplPhy
HOMEPAGE =