NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Make It So - DE
DESCRIPTION = Changes 'Einfach lostippen...' to 'Make it so...' for german TouchPad.
CATEGORY = Mojo
VERSIONS = 2.2.0-38 2.2.3-38 3.0.2-35 3.0.4-3
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = DiplPhy
HOMEPAGE = http://forums.precentral.net/hp-touchpad-tips-information-resources/295014-replace-just-type-custom-message-6.html#post3176394