NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Fix No Bookmarks Displayed Bug
DESCRIPTION = Fixes a bug in the bookmark list display -not the opening tiles - that inhibits displaying the bookmarks and sorting and deleting them. Most times happens after a profile restore.
CATEGORY = Browser
VERSIONS = 2.1.0-170 2.1.1-22 2.1.2-31 2.2.0-29 2.2.3-29
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Dick99999
HOMEPAGE = http://forums.precentral.net/webos-patches/276011-patch-browser-fix-no-bookmarks-displayed-bug-2-0-1-a.html#post2873649
