NAME = $(shell basename $(shell pwd))
PATCH = music-player/${NAME}.patch
TITLE = Vibrate on Headset Track Advance
DESCRIPTION = This patch will add a long vibration (750ms) when you use your headset button to advance the track. If your headset has a button, you can quickly double-press it to advance the track in the music player. 
There will be a long vibration (750ms) when you advance the track this way.
CATEGORY = Music Player
VERSION = 1.2.1-13
ICON = http://www.webos-internals.org/images/d/df/Icon_WebOSInternals_Patches_Musicplayer.png
SCREENSHOTS =
META_SUB_VERSION = 4

include ../common.mk
include ../modifications.mk

MAINTAINER = jhoff80
HOMEPAGE = http://forums.precentral.net/webos-patches/211631-musicplayer-vibrate-headset-button-track-advance.html
