NAME = $(shell basename $(shell pwd))
PATCH = universal-search/${NAME}.patch
TWEAKS =
TITLE = Just Type to Petite et accipietis
DESCRIPTION = Petite et accipietis is latin for 'ask and you will recieve'
CATEGORY = Universal Search
VERSIONS = 2.1.0-184 2.1.1-22 2.1.2-31 2.2.0-49 2.2.3-44 3.0.2-49
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = drewksparks <drewksparks@gmail.com>
HOMEPAGE =
