NAME = $(shell basename $(shell pwd))
PATCH = google-maps/${NAME}.patch
TITLE = Sprint Nav Google Maps Navigation Megamix
DESCRIPTION = Starts Google Maps in fullscreen and turns GPS on when Sprint Nav and Google maps are launched and back off when turned off
CATEGORY = Google Maps
VERSIONS = 1.4.5-145
ICON = http://www.webos-internals.org/images/c/c3/Icon_WebOSInternals_Patches_SprintNav.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = mamouton <marion.mouton@gmail.com>, ahsrig
HOMEPAGE =
