NAME = $(shell basename $(shell pwd))
PATCH = app-catalog/${NAME}.patch
TWEAKS =
TITLE = Larger Back Button in AppCatalog for TouchPad
DESCRIPTION = Enlarges the 'Back' button in HP's App Catalog for the TouchPad when viewing an app's detail page at the lower-left allowing for a quicker finger-friendlier navigation.
CATEGORY = App Catalog
VERSIONS = 3.0.4-35
ICON = http://www.webos-internals.org/images/0/03/Icon_WebOSInternals_Patches_Findapps.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = opacityzero
HOMEPAGE = http://forums.precentral.net/webos-patches/306972-patch-touchpad-larger-back-button-hp-app-catalog.html