NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Greek accented layout for hardware keyboard
DESCRIPTION = Adds Greek to hardware keyboard. Double press SYM to change language to Greek. This patch adds support for accents over Greek lowercase letters and also diaeresis. For accents use q+vowel and for diaeresis Q+i/y. Credits to shura for making the original keyboard and to A24 for making the first Greek keyboard.
CATEGORY = Mojo
VERSIONS = 2.1.0-228 2.1.1-35 2.1.2-43 2.2.0-106 2.2.3-100 2.2.4-16
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [\
\"http://www.webos-internals.org\",\
\"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Loiter
HOMEPAGE = http://forums.precentral.net/webos-patches/280001-patch-greek-keyboard-layout.html