#!/bin/sh

APPID=mobi.optware.openssh

# Symlink files into /opt
cd $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt
find * -type d -exec mkdir -p /opt/{} \;
find * -type f -exec ln -sf $IPKG_OFFLINE_ROOT/usr/palm/applications/$APPID/opt/{} /opt/{} \;

# Disable any legacy openssh server that was installed manually
if [ -f /etc/event.d/optware-openssh ]; then
    /sbin/stop optware-openssh
    rm -f /etc/event.d/optware-openssh
fi

/opt/bin/update-alternatives --install /opt/bin/scp scp /opt/bin/openssh-scp 80
/opt/bin/update-alternatives --install /opt/bin/ssh ssh /opt/bin/openssh-ssh 80

mkdir -p /opt/etc/openssh

# Check for the SSH1 RSA key
if [ ! -f /opt/etc/openssh/ssh_host_key ]; then
    echo Generating RSA Key...
    /opt/bin/ssh-keygen -t rsa1 -f /opt/etc/openssh/ssh_host_key -C '' -N ''
fi

# Check for the SSH2 RSA key
if [ ! -f /opt/etc/openssh/ssh_host_rsa_key ]; then
    echo Generating RSA Key...
    /opt/bin/ssh-keygen -t rsa -f /opt/etc/openssh/ssh_host_rsa_key -C '' -N ''
fi

# Check for the SSH2 DSA key
if [ ! -f /opt/etc/openssh/ssh_host_dsa_key ]; then
    echo Generating DSA Key...
    /opt/bin/ssh-keygen -t dsa -f /opt/etc/openssh/ssh_host_dsa_key -C '' -N ''
fi

# Install the profile script
rm -f /etc/profile.d/${APPID}
mkdir -p /etc/profile.d/
cp $IPKG_OFFLINE_ROOT/etc/profile.d/${APPID} /etc/profile.d/${APPID}

# The emulator already has an ssh server running, so no need to start another.
if [ "`uname -m`" != "i686" ]; then
    rm -f /etc/event.d/${APPID}
    mkdir -p /etc/event.d/
    cp $IPKG_OFFLINE_ROOT/etc/event.d/${APPID} /etc/event.d/${APPID}
    /sbin/start ${APPID}
fi

exit 0
