#!/bin/sh

# Disable any legacy openssh server that was installed manually
if [ -f /etc/event.d/optware-openssh ]; then
    /sbin/stop optware-openssh
    rm -f /etc/event.d/optware-openssh
fi

update-alternatives --install /opt/bin/scp scp /opt/bin/openssh-scp 80
update-alternatives --install /opt/bin/ssh ssh /opt/bin/openssh-ssh 80

mkdir -p /opt/etc/openssh

# Check for the SSH1 RSA key
if [ ! -f /opt/etc/openssh/ssh_host_key ]; then
    echo Generating RSA Key...
    /opt/bin/ssh-keygen -t rsa1 -f /opt/etc/openssh/ssh_host_key -C '' -N ''
fi

# Check for the SSH2 RSA key
if [ ! -f /opt/etc/openssh/ssh_host_rsa_key ]; then
    echo Generating RSA Key...
    /opt/bin/ssh-keygen -t rsa -f /opt/etc/openssh/ssh_host_rsa_key -C '' -N ''
fi

# Check for the SSH2 DSA key
if [ ! -f /opt/etc/openssh/ssh_host_dsa_key ]; then
    echo Generating DSA Key...
    /opt/bin/ssh-keygen -t dsa -f /opt/etc/openssh/ssh_host_dsa_key -C '' -N ''
fi

# The emulator already has an ssh server running, so no need to start another.
if [ "`uname -m`" != "i686" ]; then
    rm -f /etc/event.d/mobi.optware.openssh
    mkdir -p /etc/event.d/
    cp $IPKG_OFFLINE_ROOT/etc/event.d/mobi.optware.openssh /etc/event.d/mobi.optware.openssh
    /sbin/start mobi.optware.openssh
fi

exit 0
