#!/bin/sh

# The emulator already has an ssh server running, so no need to start another.
if [ "`uname -m`" != "i686" ]; then
    /sbin/stop mobi.optware.openssh
    rm -f /etc/event.d/mobi.optware.openssh
fi

update-alternatives --remove scp /opt/bin/openssh-scp
update-alternatives --remove ssh /opt/bin/openssh-ssh

# We intentionally do not remove the host keys.

exit 0
