#!/bin/sh

APPID=mobi.optware.openssh

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

APPDIR=${APPS}/usr/palm/applications/${APPID}

# The emulator already has an ssh server running, so we didn't start our own.
if [ "`uname -m`" != "i686" ]; then
    /sbin/stop ${APPID}
fi

rm -f /var/palm/event.d/${APPID}

/opt/bin/update-alternatives --remove scp /opt/bin/openssh-scp
/opt/bin/update-alternatives --remove ssh /opt/bin/openssh-ssh

# Remove files from /opt
cd ${APPDIR}/opt
find bin etc libexec sbin var -depth -type f -exec rm -f /opt/{} \;
find bin etc libexec sbin var -depth -type d -exec rmdir /opt/{} \;

# We intentionally do not remove the host keys.

exit 0
