NAME = $(shell basename $(shell pwd))
PATCH = youtube/${NAME}.patch
TWEAKS =
TITLE = Change default Youtube cat to People-Blogs
DESCRIPTION = Change default Youtube category to People & Blogs.Reboot after applying.
CATEGORY = YouTube
VERSIONS = 3.0.5-3
ICON = http://www.webos-internals.org/images/8/8b/Icon_WebOSInternals_Patches_Youtube.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = GuyFromNam <GuyFromNam@hotmail.com>
HOMEPAGE =