NAME = all-attachments
PATCH = /messaging/${NAME}.patch
TITLE = Messaging Attachments
DESCRIPTION = Adds ability to attach audio and video files to messaging app
CATEGORY = Messaging
VERSION = 0.3.2
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
