NAME = all-attachments
PATCH = /messaging/${NAME}.patch
TITLE = Audio/Video Messaging Attaches
DESCRIPTION = Adds ability to attach (send) audio and video files in the Messaging application.
CATEGORY = Messaging
VERSION = 0.4.1
ICON = http://www.webos-internals.org/images/2/24/Icon_WebOSInternals_Patches_Messaging.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/1/14/All-attachments-1.png\",\
\"http://www.webos-internals.org/images/5/5c/All-attachments-2.png\",\
\"http://www.webos-internals.org/images/f/f6/All-attachments-3.png\" ]

include ../common.mk
include ../modifications.mk
