NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TWEAKS =
TITLE = Mojo Flick Regulator
DESCRIPTION = Lowers the Flick Scrolling speed in all Mojo apps to match that of the browser, creating a more manageable/unified experience.
CATEGORY = Mojo
VERSIONS = 3.0.5-4
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = ShiftyAxel <jpalmerwatkins@me.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/307282-patch-mojo-flick-regulator.html