NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = Launcher Auto-Popup
DESCRIPTION = Will bring up launcher on system boot. Also, upon turning the screen on, if no cards are in focus, the launcher will pop up.
CATEGORY = App Launcher
VERSIONS = 1.3.5-24 1.4.0-13
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS =
META_SUB_VERSION = 1 

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/221023-patch-launcher-auto-popup.html