NAME = $(shell basename $(shell pwd))
PATCH = mojo/${NAME}.patch
TITLE = Disable Banners and Keep Sound Alerts
DESCRIPTION = Disables the display of ALL banner notifications while still allowing any accompanying sound alerts to still be heard.
CATEGORY = Mojo
VERSIONS = 1.4.5-119 2.0.1-39 2.1.0-18 2.1.1-22 2.1.2-31
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = appsotutely <patches@appsotutely.com>
HOMEPAGE = http://forums.precentral.net/webos-patches/270853-there-patch-disable-banner-update-yes.html#post2803079
