NAME = $(shell basename $(shell pwd))
PATCH = notifications/${NAME}.patch
TITLE = No Charging Banner On AC
DESCRIPTION = Disables the charging banner notification when plugged into an AC wall charger.
CATEGORY = Notifications
VERSIONS = 1.4.5-98
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Speebs
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2735082#post2727981
