NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = No Clear History
DESCRIPTION = This Removes the Clear History button so you aren't ever able to clear or delete your history.
CATEGORY = Browser
VERSIONS = 1.4.5-153 2.0.0-47 2.0.1-77 2.1.0-89
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/f/f5/Browser-no-clear-history-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Djgardn2
HOMEPAGE =