NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = No Clear History
DESCRIPTION = This Removes the Clear History button so you aren't ever able to clear or delete your history.
CATEGORY = Browser
VERSIONS = 1.4.5-154 2.1.0-89 2.1.1-22 2.1.2-31 2.2.0-115 2.2.3-109 2.2.4-25 3.0.2-26 3.0.4-3
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Djgardn2
HOMEPAGE = http://forums.precentral.net/webos-patches/287118-touchpad-no-clear-history.html