NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Phone Radio Toggle
DESCRIPTION = This will add the ability to turn the Phone Radio On and Off in the Device Menu. This will only turn off the Phone Radio.
CATEGORY = Top Bar
VERSIONS = 1.2.1-1 1.1.3-1 1.3.1-1 1.3.5-2 1.4.0-2
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/4/4b/Radiopower.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = pEEf
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_webOS_Radio_Power_Switch
