NAME = enable-dialpad-vibration
PATCH = /phone/${NAME}.patch
TITLE = Enable Dialpad Vibration
DESCRIPTION = This will enable haptic feedback and silence the dialpad in the phone application.
CATEGORY = Phone
VERSION = 0.4.0
ICON = http://www.webos-internals.org/images/2/2c/Icon_WebOSInternals_Patches_Phone.png
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
