NAME = enable-dialpad-vibration
PATCH = /phone/${NAME}.patch
TITLE = Enable Dialpad Vibration
DESCRIPTION = Enables haptic feedback for dialpad in phone app
CATEGORY = Phone
VERSION = 0.2.6
ICON = 
SCREENSHOTS = 

include ../common.mk
include ../modifications.mk
