NAME = $(shell basename $(shell pwd))
PATCH = email/${NAME}.patch
TWEAKS =
TITLE = Always Show Previous and Next Buttons
DESCRIPTION = The previous and next email buttons will be displayed always
CATEGORY = Email
VERSIONS = 3.0.2-3 3.0.4-5
ICON = http://www.webos-internals.org/images/2/29/Icon_WebOSInternals_Patches_Email.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Jason Robitaille
HOMEPAGE = http://forums.precentral.net/webos-patches/289071-patch-touchpad-always-show-previous-next-email-buttons.html
