NAME = $(shell basename $(shell pwd))
PATCH = browser/${NAME}.patch
TWEAKS =
TITLE = Add Scrollbars to Browser
DESCRIPTION = This patch adds scrollbars to the Browser. This is an updated and modified version of TI Wizard's original patch.
CATEGORY = Browser
VERSIONS = 2.2.0-49 2.2.3-44
ICON = http://www.webos-internals.org/images/4/4a/Icon_WebOSInternals_Patches_Browser.png
SCREENSHOTS = [ \"http://www.webos-internals.org\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Garrett92C <Garrett92C@gmail.com>
HOMEPAGE = http://forum.webosroundup.com/index.php?threads/pre3-add-scrollbars-to-browser.1058/