NAME = $(shell basename $(shell pwd))
PATCH = system/${NAME}.patch
TWEAKS =
TITLE = Chinese PinYin Framework - Veer
DESCRIPTION = Provide Chinese character to PinYin lookup. This is a framework require by other patch or modules, you don't get anything directly.A device restart is required (instead of just luna restart)
CATEGORY = System
VERSIONS = 2.1.0-213
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS =
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = moo <moo.tinys@gmail.com>
HOMEPAGE = http://www.treo8.com/bbs/thread-275013-1-1.html