NAME = $(shell basename $(shell pwd))
PATCH = app-launcher/${NAME}.patch
TITLE = 4x4 Icons v3
DESCRIPTION = This will modify the App launcher to display 4x4 icons rather than 3x4. This version has larger icons and closer spacing. It is a very slick version of the 4x4 patch.
CATEGORY = App Launcher
VERSIONS = 1.2.1-5 1.3.1-2 1.3.5-3 1.4.0-3
ICON = http://www.webos-internals.org/images/b/b1/Icon_WebOSInternals_Patches_Applauncher.png
SCREENSHOTS = [\
\"http://www.webos-internals.org/images/5/5c/App-launcher-4x4-icons-v3-1.png\",\
\"http://www.webos-internals.org/images/0/00/App-launcher-4x4-icons-v3-2.png\",\
\"http://www.webos-internals.org/images/c/c1/App-launcher-4x4-icons-v3-3.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = onlinespending
HOMEPAGE = http://forums.precentral.net/webos-patches/209069-alternative-4x4-launcher-larger-icons-text.html
