NAME = clock-add-space-between-snooze-and-dismiss
PATCH = clock/${NAME}.patch
TITLE = Add Space Between Snooze and Dismiss
DESCRIPTION = This will add space between the snooze and dismiss buttons during Clock alarms.
CATEGORY = Clock
VERSIONS = 1.2.1-4 1.3.1-13
ICON = http://www.webos-internals.org/images/8/8d/Icon_WebOSInternals_Patches_Clock.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/1/18/ClockAddSpaceBetweenSnoozeAndDismiss.png\"]
META_SUB_VERSION = 1

include ../common.mk
include ../modifications.mk

MAINTAINER = lclarkjr
HOMEPAGE = http://www.webos-internals.org/wiki/Patch_Clock_Add_space_between_Snooze_and_Dismiss_buttons
