NAME = $(shell basename $(shell pwd))
PATCH = clock/${NAME}.patch
TITLE = Add Space Between Snooze and Dismiss
DESCRIPTION = This will add space between the snooze and dismiss buttons during Clock alarms.
CATEGORY = Clock
VERSIONS = 1.3.5-3 1.4.0-8 1.4.1-1
ICON = http://www.webos-internals.org/images/8/8d/Icon_WebOSInternals_Patches_Clock.png
SCREENSHOTS = [\"http://www.webos-internals.org/images/1/18/ClockAddSpaceBetweenSnoozeAndDismiss.png\"]
META_SUB_VERSION = 2

include ../common.mk

include ../modifications.mk

MAINTAINER = lclarkjr <lclarkjr@gmail.com>, dBsooner
HOMEPAGE = http://forums.precentral.net/showthread.php?p=2041500#post2041500
