NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TITLE = Ringer Switch Icon
DESCRIPTION = Adds a mute icon to the top bar when the ringer switch is set to silent.
CATEGORY = Top Bar
VERSIONS = 1.3.1-32 1.3.5-15 1.4.0-4
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/d/d3/Top-bar-ringer-switch-icon-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Franz Rühmland <frause@stealthberry.org>
HOMEPAGE = http://forums.precentral.net/webos-patches/225094-patch-ringer-switch-icon-top-bar.html