NAME = $(shell basename $(shell pwd))
PATCH = top-bar/${NAME}.patch
TWEAKS =
TITLE = Ringer Switch Icon
DESCRIPTION = Adds a mute icon to the top bar when the ringer switch is set to silent.
CATEGORY = Top Bar
VERSIONS = 1.4.5-112 2.1.0-2 2.2.0-82 2.2.3-76
ICON = http://www.webos-internals.org/images/f/f9/Icon_WebOSInternals_Patch.png
SCREENSHOTS = [ \"http://www.webos-internals.org/images/d/d3/Top-bar-ringer-switch-icon-1.png\" ]
META_SUB_VERSION = 1

include ../common.mk

include ../modifications.mk

MAINTAINER = Franz Rühmland
HOMEPAGE = http://m.forums.precentral.net/webos-patches/225094-patch-ringer-switch-icon-top-bar.html